import { ArrowPathIcon } from "@heroicons/react/24/solid";
import { ReloadIcon } from "@radix-ui/react-icons";
import { RiLoader4Line } from "@remixicon/react";
import {
  Loader2Icon,
  AlertCircleIcon,
  AlertTriangleIcon,
  CheckCircle2Icon,
  InfoIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  SearchIcon,
  HelpCircleIcon,
  CalendarIcon,
  XIcon,
  AsteriskIcon,
  CheckIcon,
  MinusIcon,
  PlusIcon,
  WalletIcon,
  GlobeIcon,
  User2Icon,
  ShieldIcon,
  ChevronRightSquareIcon,
  HomeIcon,
  LogInIcon,
  UploadIcon,
  PaletteIcon,
  UsersIcon,
  PlaneIcon,
  CameraIcon,
  ExternalLinkIcon,
  MenuIcon,
  CopyIcon,
  PlusSquareIcon,
  SquarePenIcon,
  RotateCwIcon,
  XCircleIcon,
  BoldIcon,
  ItalicIcon,
  TimerIcon,
  PinIcon,
  ALargeSmallIcon,
} from "lucide-react";
import { Loader } from "react-feather";

const icons = {
  LoaderIcon: {
    lucide: { name: "Loader2Icon", icon: Loader2Icon },
    remix: { name: "RiLoader4Line", icon: RiLoader4Line },
    radix: { name: "Reload", icon: ReloadIcon },
    heroicons: { name: "ArrowPath", icon: ArrowPathIcon },
    feather: { name: "Loader", icon: Loader },
  },
  DangerIcon: {
    lucide: { name: "AlertCircleIcon", icon: AlertCircleIcon },
    remix: { name: "AlertCircleIcon", icon: AlertCircleIcon },
    radix: { name: "AlertCircleIcon", icon: AlertCircleIcon },
    heroicons: { name: "AlertCircleIcon", icon: AlertCircleIcon },
    feather: { name: "AlertCircleIcon", icon: AlertCircleIcon },
  },
  WarningIcon: {
    lucide: { name: "AlertTriangleIcon", icon: AlertTriangleIcon },
    remix: { name: "AlertTriangleIcon", icon: AlertTriangleIcon },
    radix: { name: "AlertTriangleIcon", icon: AlertTriangleIcon },
    heroicons: { name: "AlertTriangleIcon", icon: AlertTriangleIcon },
    feather: { name: "AlertTriangleIcon", icon: AlertTriangleIcon },
  },
  SuccessIcon: {
    lucide: { name: "CheckCircle2Icon", icon: CheckCircle2Icon },
    remix: { name: "CheckCircle2Icon", icon: CheckCircle2Icon },
    radix: { name: "CheckCircle2Icon", icon: CheckCircle2Icon },
    heroicons: { name: "CheckCircle2Icon", icon: CheckCircle2Icon },
    feather: { name: "CheckCircle2Icon", icon: CheckCircle2Icon },
  },
  InfoIcon: {
    lucide: { name: "InfoIcon", icon: InfoIcon },
    remix: { name: "InfoIcon", icon: InfoIcon },
    radix: { name: "InfoIcon", icon: InfoIcon },
    heroicons: { name: "InfoIcon", icon: InfoIcon },
    feather: { name: "InfoIcon", icon: InfoIcon },
  },
  ChevronRightIcon: {
    lucide: { name: "ChevronRightIcon", icon: ChevronRightIcon },
    remix: { name: "ChevronRightIcon", icon: ChevronRightIcon },
    radix: { name: "ChevronRightIcon", icon: ChevronRightIcon },
    heroicons: { name: "ChevronRightIcon", icon: ChevronRightIcon },
    feather: { name: "ChevronRightIcon", icon: ChevronRightIcon },
  },
  ChevronLeftIcon: {
    lucide: { name: "ChevronLeftIcon", icon: ChevronLeftIcon },
    remix: { name: "ChevronLeftIcon", icon: ChevronLeftIcon },
    radix: { name: "ChevronLeftIcon", icon: ChevronLeftIcon },
    heroicons: { name: "ChevronLeftIcon", icon: ChevronLeftIcon },
    feather: { name: "ChevronLeftIcon", icon: ChevronLeftIcon },
  },
  ChevronDownIcon: {
    lucide: { name: "ChevronDownIcon", icon: ChevronDownIcon },
    remix: { name: "ChevronDownIcon", icon: ChevronDownIcon },
    radix: { name: "ChevronDownIcon", icon: ChevronDownIcon },
    heroicons: { name: "ChevronDownIcon", icon: ChevronDownIcon },
    feather: { name: "ChevronDownIcon", icon: ChevronDownIcon },
  },
  ChevronUpIcon: {
    lucide: { name: "ChevronUpIcon", icon: ChevronUpIcon },
    remix: { name: "ChevronUpIcon", icon: ChevronUpIcon },
    radix: { name: "ChevronUpIcon", icon: ChevronUpIcon },
    heroicons: { name: "ChevronUpIcon", icon: ChevronUpIcon },
    feather: { name: "ChevronUpIcon", icon: ChevronUpIcon },
  },
  SearchIcon: {
    lucide: { name: "SearchIcon", icon: SearchIcon },
    remix: { name: "SearchIcon", icon: SearchIcon },
    radix: { name: "SearchIcon", icon: SearchIcon },
    heroicons: { name: "SearchIcon", icon: SearchIcon },
    feather: { name: "SearchIcon", icon: SearchIcon },
  },
  HelpIcon: {
    lucide: { name: "HelpCircleIcon", icon: HelpCircleIcon },
    remix: { name: "HelpCircleIcon", icon: HelpCircleIcon },
    radix: { name: "HelpCircleIcon", icon: HelpCircleIcon },
    heroicons: { name: "HelpCircleIcon", icon: HelpCircleIcon },
    feather: { name: "HelpCircleIcon", icon: HelpCircleIcon },
  },
  CalendarIcon: {
    lucide: { name: "CalendarIcon", icon: CalendarIcon },
    remix: { name: "CalendarIcon", icon: CalendarIcon },
    radix: { name: "CalendarIcon", icon: CalendarIcon },
    heroicons: { name: "CalendarIcon", icon: CalendarIcon },
    feather: { name: "CalendarIcon", icon: CalendarIcon },
  },
  XIcon: {
    lucide: { name: "XIcon", icon: XIcon },
    remix: { name: "XIcon", icon: XIcon },
    radix: { name: "XIcon", icon: XIcon },
    heroicons: { name: "XIcon", icon: XIcon },
    feather: { name: "XIcon", icon: XIcon },
  },
  AsteriskIcon: {
    lucide: { name: "AsteriskIcon", icon: AsteriskIcon },
    remix: { name: "AsteriskIcon", icon: AsteriskIcon },
    radix: { name: "AsteriskIcon", icon: AsteriskIcon },
    heroicons: { name: "AsteriskIcon", icon: AsteriskIcon },
    feather: { name: "AsteriskIcon", icon: AsteriskIcon },
  },
  CheckIcon: {
    lucide: { name: "CheckIcon", icon: CheckIcon },
    remix: { name: "CheckIcon", icon: CheckIcon },
    radix: { name: "CheckIcon", icon: CheckIcon },
    heroicons: { name: "CheckIcon", icon: CheckIcon },
    feather: { name: "CheckIcon", icon: CheckIcon },
  },
  MinusIcon: {
    lucide: { name: "MinusIcon", icon: MinusIcon },
    remix: { name: "MinusIcon", icon: MinusIcon },
    radix: { name: "MinusIcon", icon: MinusIcon },
    heroicons: { name: "MinusIcon", icon: MinusIcon },
    feather: { name: "MinusIcon", icon: MinusIcon },
  },
  PlusIcon: {
    lucide: { name: "PlusIcon", icon: PlusIcon },
    remix: { name: "PlusIcon", icon: PlusIcon },
    radix: { name: "PlusIcon", icon: PlusIcon },
    heroicons: { name: "PlusIcon", icon: PlusIcon },
    feather: { name: "PlusIcon", icon: PlusIcon },
  },
  WalletIcon: {
    lucide: { name: "WalletIcon", icon: WalletIcon },
    remix: { name: "WalletIcon", icon: WalletIcon },
    radix: { name: "WalletIcon", icon: WalletIcon },
    heroicons: { name: "WalletIcon", icon: WalletIcon },
    feather: { name: "WalletIcon", icon: WalletIcon },
  },
  GlobeIcon: {
    lucide: { name: "GlobeIcon", icon: GlobeIcon },
    remix: { name: "GlobeIcon", icon: GlobeIcon },
    radix: { name: "GlobeIcon", icon: GlobeIcon },
    heroicons: { name: "GlobeIcon", icon: GlobeIcon },
    feather: { name: "GlobeIcon", icon: GlobeIcon },
  },
  UserIcon: {
    lucide: { name: "User2Icon", icon: User2Icon },
    remix: { name: "User2Icon", icon: User2Icon },
    radix: { name: "User2Icon", icon: User2Icon },
    heroicons: { name: "User2Icon", icon: User2Icon },
    feather: { name: "User2Icon", icon: User2Icon },
  },
  ShieldIcon: {
    lucide: { name: "ShieldIcon", icon: ShieldIcon },
    remix: { name: "ShieldIcon", icon: ShieldIcon },
    radix: { name: "ShieldIcon", icon: ShieldIcon },
    heroicons: { name: "ShieldIcon", icon: ShieldIcon },
    feather: { name: "ShieldIcon", icon: ShieldIcon },
  },
  ChevronRightSquareIcon: {
    lucide: { name: "ChevronRightSquareIcon", icon: ChevronRightSquareIcon },
    remix: { name: "ChevronRightSquareIcon", icon: ChevronRightSquareIcon },
    radix: { name: "ChevronRightSquareIcon", icon: ChevronRightSquareIcon },
    heroicons: { name: "ChevronRightSquareIcon", icon: ChevronRightSquareIcon },
    feather: { name: "ChevronRightSquareIcon", icon: ChevronRightSquareIcon },
  },
  HomeIcon: {
    lucide: { name: "HomeIcon", icon: HomeIcon },
    remix: { name: "HomeIcon", icon: HomeIcon },
    radix: { name: "HomeIcon", icon: HomeIcon },
    heroicons: { name: "HomeIcon", icon: HomeIcon },
    feather: { name: "HomeIcon", icon: HomeIcon },
  },
  LogInIcon: {
    lucide: { name: "LogInIcon", icon: LogInIcon },
    remix: { name: "LogInIcon", icon: LogInIcon },
    radix: { name: "LogInIcon", icon: LogInIcon },
    heroicons: { name: "LogInIcon", icon: LogInIcon },
    feather: { name: "LogInIcon", icon: LogInIcon },
  },
  UploadIcon: {
    lucide: { name: "UploadIcon", icon: UploadIcon },
    remix: { name: "UploadIcon", icon: UploadIcon },
    radix: { name: "UploadIcon", icon: UploadIcon },
    heroicons: { name: "UploadIcon", icon: UploadIcon },
    feather: { name: "UploadIcon", icon: UploadIcon },
  },
  PaletteIcon: {
    lucide: { name: "PaletteIcon", icon: PaletteIcon },
    remix: { name: "PaletteIcon", icon: PaletteIcon },
    radix: { name: "PaletteIcon", icon: PaletteIcon },
    heroicons: { name: "PaletteIcon", icon: PaletteIcon },
    feather: { name: "PaletteIcon", icon: PaletteIcon },
  },
  UsersIcon: {
    lucide: { name: "UsersIcon", icon: UsersIcon },
    remix: { name: "UsersIcon", icon: UsersIcon },
    radix: { name: "UsersIcon", icon: UsersIcon },
    heroicons: { name: "UsersIcon", icon: UsersIcon },
    feather: { name: "UsersIcon", icon: UsersIcon },
  },
  PlaneIcon: {
    lucide: { name: "PlaneIcon", icon: PlaneIcon },
    remix: { name: "PlaneIcon", icon: PlaneIcon },
    radix: { name: "PlaneIcon", icon: PlaneIcon },
    heroicons: { name: "PlaneIcon", icon: PlaneIcon },
    feather: { name: "PlaneIcon", icon: PlaneIcon },
  },
  CameraIcon: {
    lucide: { name: "CameraIcon", icon: CameraIcon },
    remix: { name: "CameraIcon", icon: CameraIcon },
    radix: { name: "CameraIcon", icon: CameraIcon },
    heroicons: { name: "CameraIcon", icon: CameraIcon },
    feather: { name: "CameraIcon", icon: CameraIcon },
  },
  ExternalLinkIcon: {
    lucide: { name: "ExternalLinkIcon", icon: ExternalLinkIcon },
    remix: { name: "ExternalLinkIcon", icon: ExternalLinkIcon },
    radix: { name: "ExternalLinkIcon", icon: ExternalLinkIcon },
    heroicons: { name: "ExternalLinkIcon", icon: ExternalLinkIcon },
    feather: { name: "ExternalLinkIcon", icon: ExternalLinkIcon },
  },
  MenuIcon: {
    lucide: { name: "MenuIcon", icon: MenuIcon },
    remix: { name: "MenuIcon", icon: MenuIcon },
    radix: { name: "MenuIcon", icon: MenuIcon },
    heroicons: { name: "MenuIcon", icon: MenuIcon },
    feather: { name: "MenuIcon", icon: MenuIcon },
  },
  CopyIcon: {
    lucide: { name: "CopyIcon", icon: CopyIcon },
    remix: { name: "CopyIcon", icon: CopyIcon },
    radix: { name: "CopyIcon", icon: CopyIcon },
    heroicons: { name: "CopyIcon", icon: CopyIcon },
    feather: { name: "CopyIcon", icon: CopyIcon },
  },
  PlusSquareIcon: {
    lucide: { name: "PlusSquareIcon", icon: PlusSquareIcon },
    remix: { name: "PlusSquareIcon", icon: PlusSquareIcon },
    radix: { name: "PlusSquareIcon", icon: PlusSquareIcon },
    heroicons: { name: "PlusSquareIcon", icon: PlusSquareIcon },
    feather: { name: "PlusSquareIcon", icon: PlusSquareIcon },
  },
  SquarePenIcon: {
    lucide: { name: "SquarePenIcon", icon: SquarePenIcon },
    remix: { name: "SquarePenIcon", icon: SquarePenIcon },
    radix: { name: "SquarePenIcon", icon: SquarePenIcon },
    heroicons: { name: "SquarePenIcon", icon: SquarePenIcon },
    feather: { name: "SquarePenIcon", icon: SquarePenIcon },
  },
  RotateCwIcon: {
    lucide: { name: "RotateCwIcon", icon: RotateCwIcon },
    remix: { name: "RotateCwIcon", icon: RotateCwIcon },
    radix: { name: "RotateCwIcon", icon: RotateCwIcon },
    heroicons: { name: "RotateCwIcon", icon: RotateCwIcon },
    feather: { name: "RotateCwIcon", icon: RotateCwIcon },
  },
  XCircleIcon: {
    lucide: { name: "XCircleIcon", icon: XCircleIcon },
    remix: { name: "XCircleIcon", icon: XCircleIcon },
    radix: { name: "XCircleIcon", icon: XCircleIcon },
    heroicons: { name: "XCircleIcon", icon: XCircleIcon },
    feather: { name: "XCircleIcon", icon: XCircleIcon },
  },
  BoldIcon: {
    lucide: { name: "BoldIcon", icon: BoldIcon },
    remix: { name: "BoldIcon", icon: BoldIcon },
    radix: { name: "BoldIcon", icon: BoldIcon },
    heroicons: { name: "BoldIcon", icon: BoldIcon },
    feather: { name: "BoldIcon", icon: BoldIcon },
  },
  ItalicIcon: {
    lucide: { name: "ItalicIcon", icon: ItalicIcon },
    remix: { name: "ItalicIcon", icon: ItalicIcon },
    radix: { name: "ItalicIcon", icon: ItalicIcon },
    heroicons: { name: "ItalicIcon", icon: ItalicIcon },
    feather: { name: "ItalicIcon", icon: ItalicIcon },
  },
  TimerIcon: {
    lucide: { name: "TimerIcon", icon: TimerIcon },
    remix: { name: "TimerIcon", icon: TimerIcon },
    radix: { name: "TimerIcon", icon: TimerIcon },
    heroicons: { name: "TimerIcon", icon: TimerIcon },
    feather: { name: "TimerIcon", icon: TimerIcon },
  },
  PinIcon: {
    lucide: { name: "PinIcon", icon: PinIcon },
    remix: { name: "PinIcon", icon: PinIcon },
    radix: { name: "PinIcon", icon: PinIcon },
    heroicons: { name: "PinIcon", icon: PinIcon },
    feather: { name: "PinIcon", icon: PinIcon },
  },
  ALargeSmallIcon: {
    lucide: { name: "ALargeSmallIcon", icon: ALargeSmallIcon },
    remix: { name: "ALargeSmallIcon", icon: ALargeSmallIcon },
    radix: { name: "ALargeSmallIcon", icon: ALargeSmallIcon },
    heroicons: { name: "ALargeSmallIcon", icon: ALargeSmallIcon },
    feather: { name: "ALargeSmallIcon", icon: ALargeSmallIcon },
  },
};

export { icons };
