import type { PropGroups } from "./types";

export const DEFAULT_PROP_GROUPS: PropGroups = {
  Content: [
    "children",
    "items",
    "defaultItems",
    "columns",
    "loadingState",
    "onLoadMore",
    "renderEmptyState",
    "dependencies",
  ],
  Selection: [
    "selectionMode",
    "selectionBehavior",
    "selectedKeys",
    "defaultSelectedKeys",
    "selectedKey",
    "defaultSelectedKey",
    "onSelectionChange",
    "disabledKeys",
    "disabledBehavior",
    "disallowEmptySelection",
    "shouldSelectOnPressUp",
    "shouldFocusWrap",
    "shouldFocusOnHover",
    "escapeKeyBehavior",
  ],
  Value: [
    "value",
    "defaultValue",
    "onChange",
    "onChangeEnd",
    "inputValue",
    "defaultInputValue",
    "onInputChange",
    "formatOptions",
  ],
  Labeling: ["label", "labelPosition", "labelAlign", "contextualHelp"],
  Validation: [
    "minValue",
    "maxValue",
    "step",
    "minLength",
    "maxLength",
    "pattern",
    "isRequired",
    "isInvalid",
    "validate",
    "validationBehavior",
    "validationErrors",
    "necessityIndicator",
    "description",
    "errorMessage",
  ],
  Overlay: [
    "isOpen",
    "defaultOpen",
    "onOpenChange",
    "shouldCloseOnSelect",
    "placement",
    "direction",
    "align",
    "shouldFlip",
    "offset",
    "crossOffset",
    "containerPadding",
    "menuWidth",
  ],
  Events: [/^on[A-Z]/],
  Links: [
    "href",
    "hrefLang",
    "target",
    "rel",
    "download",
    "ping",
    "referrerPolicy",
    "routerOptions",
  ],
  Styling: ["style", "className"],
  Forms: [
    "name",
    "startName",
    "endName",
    "value",
    "formValue",
    "type",
    "autoComplete",
    "form",
    "formTarget",
    "formNoValidate",
    "formMethod",
    "formEncType",
    "formAction",
  ],
  Accessibility: [
    "autoFocus",
    "role",
    "id",
    "tabIndex",
    "excludeFromTabOrder",
    "preventFocusOnPress",
    /^aria-/,
  ],
  Advanced: ["UNSAFE_className", "UNSAFE_style", "slot"],
};

export const DEFAULT_EXPANDED_GROUPS = new Set([
  "Content",
  "Selection",
  "Value",
]);

