packages:
  - www
  - packages/*
  - config/*

catalog:
  eslint: ^9.28.0
  prettier: ^3.5.3
  typescript: ^5.8.3
  tailwindcss: ^4.1.8
  '@tailwindcss/postcss': ^4.1.8
  postcss: ^8.4.31
  zod: ^4.0.5
  '@tanstack/react-query': ^5.80.2
  '@trpc/client': ^11.2.0
  '@trpc/tanstack-react-query': ^11.2.0
  '@trpc/server': ^11.2.0
  tsx: ^4.19.2
  shadcn: ^3.2.1
  '@types/node': ^22.15.3

catalogs:
  react:
    react: ^19.1.1
    react-dom: ^19.1.1
    '@types/react': ^19.1.10
    '@types/react-dom': ^19.1.7
  next:
    next: ^15.6.0-canary.26
  ui:
    react-aria-components: ^1.12.2
    tailwind-variants: ^1.0.0
    clsx: ^2.1.0
    tailwind-merge: ^3.0.2
    '@hookform/resolvers': ^5.1.1
    '@internationalized/date': ^3.9.0
    '@react-aria/utils': ^3.30.1
    '@react-stately/utils': ^3.10.8
    '@remixicon/react': ^4.2.0
    '@tanstack/react-form': ^1.23.4
    lucide-react: ^0.469.0
    motion: ^11.16.4
    react-aria: ^3.43.2
    react-hook-form: ^7.54.2
    react-stately: ^3.41.0

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - bufferutil
  - core-js-pure
  - esbuild
  - msw
  - puppeteer
  - sharp
