packages:
  - www
  - packages/*
  - config/*

catalog:
  eslint: ^9.25.1
  prettier: ^3.5.3
  tailwindcss: ^4.0.0
  typescript: ^5.8.3
  zod: ^3.24.3

catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    '@types/react': ^19.1.6
    '@types/react-dom': ^19.1.5

onlyBuiltDependencies:
  - core-js-pure
  - esbuild
  - msw
  - sharp
