packages:
  - www
  - packages/*
  - config/*

catalog:
  eslint: ^9.28.0
  prettier: ^3.5.3
  typescript: ^5.8.3
  zod: ^3.25.0
  "@tanstack/react-query": ^5.80.2
  "@trpc/client": ^11.2.0
  "@trpc/tanstack-react-query": ^11.2.0
  "@trpc/server": ^11.2.0

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.1.6
    "@types/react-dom": ^19.1.5

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - bufferutil
  - core-js-pure
  - esbuild
  - msw
  - sharp
