packages:
  - www
  - packages/*
  - config/*

catalog:
  '@tanstack/react-router': ^1.170.1
  '@tanstack/react-start': ^1.168.2
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.1
  react: ^19.2.1
  react-dom: ^19.2.1
  tailwindcss: ^4.3.0
  typescript: ^6.0.3

allowBuilds:
  '@tailwindcss/oxide': true
  bufferutil: true
  core-js-pure: true
  esbuild: true
  msw: true
  puppeteer: true
  sharp: true

overrides:
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.1

patchedDependencies:
  tailwindcss-react-aria-components@2.1.1: patches/tailwindcss-react-aria-components@2.1.1.patch
