/**
 * The typography axis' shared font infrastructure: the curated catalog the
 * builder offers, and the helpers that turn a family name into a CSS stack,
 * a Google Fonts stylesheet URL, and an idempotent <link> injection.
 *
 * Fonts are stored in the design system as plain global tokens (full CSS
 * font-family stacks) so they ride the existing codec → provider → publisher
 * pipeline unchanged:
 *   --font-sans     body font (Tailwind's `font-sans`, applied on <body>)
 *   --font-heading  heading font (defaults to var(--font-sans) in the theme)
 *   --font-mono     monospace font (`font-mono`)
 *
 * Pure JS — no React. Safe to import from the publisher.
 */

export const FONT_SANS_VAR = '--font-sans'
export const FONT_HEADING_VAR = '--font-heading'
export const FONT_MONO_VAR = '--font-mono'

export const FONT_TOKEN_VARS = [
  FONT_SANS_VAR,
  FONT_HEADING_VAR,
  FONT_MONO_VAR,
] as const

/** Families the app self-hosts (fontsource) — the no-token defaults. */
export const DEFAULT_BODY_FAMILY = 'Geist'
export const DEFAULT_MONO_FAMILY = 'Geist Mono'

export type FontCategory =
  | 'sans-serif'
  | 'serif'
  | 'display'
  | 'handwriting'
  | 'mono'

export interface FontOption {
  family: string
  category: FontCategory
}

/**
 * Every Google Fonts *variable* family (has a weight axis), categorized by
 * Google's own classification. Variable = one file covers the whole 400–700
 * range the builder requests. Generated from fonts.google.com metadata; the
 * most-used families are floated to the top of each category, the rest A–Z.
 */
export const FONT_CATALOG: FontOption[] = [
  // Sans serif (285)
  { family: 'Geist', category: 'sans-serif' },
  { family: 'Inter', category: 'sans-serif' },
  { family: 'Roboto', category: 'sans-serif' },
  { family: 'Open Sans', category: 'sans-serif' },
  { family: 'Montserrat', category: 'sans-serif' },
  { family: 'Nunito', category: 'sans-serif' },
  { family: 'Nunito Sans', category: 'sans-serif' },
  { family: 'Work Sans', category: 'sans-serif' },
  { family: 'DM Sans', category: 'sans-serif' },
  { family: 'Manrope', category: 'sans-serif' },
  { family: 'Rubik', category: 'sans-serif' },
  { family: 'Mulish', category: 'sans-serif' },
  { family: 'Figtree', category: 'sans-serif' },
  { family: 'Outfit', category: 'sans-serif' },
  { family: 'Sora', category: 'sans-serif' },
  { family: 'Space Grotesk', category: 'sans-serif' },
  { family: 'Plus Jakarta Sans', category: 'sans-serif' },
  { family: 'Urbanist', category: 'sans-serif' },
  { family: 'Lexend', category: 'sans-serif' },
  { family: 'Public Sans', category: 'sans-serif' },
  { family: 'Source Sans 3', category: 'sans-serif' },
  { family: 'IBM Plex Sans', category: 'sans-serif' },
  { family: 'Raleway', category: 'sans-serif' },
  { family: 'Karla', category: 'sans-serif' },
  { family: 'Mona Sans', category: 'sans-serif' },
  { family: 'Onest', category: 'sans-serif' },
  { family: 'Hanken Grotesk', category: 'sans-serif' },
  { family: 'Instrument Sans', category: 'sans-serif' },
  { family: 'Albert Sans', category: 'sans-serif' },
  { family: 'Jost', category: 'sans-serif' },
  { family: 'Archivo', category: 'sans-serif' },
  { family: 'Josefin Sans', category: 'sans-serif' },
  { family: 'Quicksand', category: 'sans-serif' },
  { family: 'Oswald', category: 'sans-serif' },
  { family: 'Bricolage Grotesque', category: 'sans-serif' },
  { family: 'Unbounded', category: 'sans-serif' },
  { family: 'Syne', category: 'sans-serif' },
  { family: 'Advent Pro', category: 'sans-serif' },
  { family: 'Afacad', category: 'sans-serif' },
  { family: 'Afacad Flux', category: 'sans-serif' },
  { family: 'Akshar', category: 'sans-serif' },
  { family: 'Akt', category: 'sans-serif' },
  { family: 'Alan Sans', category: 'sans-serif' },
  { family: 'Alexandria', category: 'sans-serif' },
  { family: 'Alumni Sans', category: 'sans-serif' },
  { family: 'Alumni Sans SC', category: 'sans-serif' },
  { family: 'Amarna', category: 'sans-serif' },
  { family: 'Anaheim', category: 'sans-serif' },
  { family: 'Ancizar Sans', category: 'sans-serif' },
  { family: 'Anek Bangla', category: 'sans-serif' },
  { family: 'Anek Devanagari', category: 'sans-serif' },
  { family: 'Anek Gujarati', category: 'sans-serif' },
  { family: 'Anek Gurmukhi', category: 'sans-serif' },
  { family: 'Anek Kannada', category: 'sans-serif' },
  { family: 'Anek Latin', category: 'sans-serif' },
  { family: 'Anek Malayalam', category: 'sans-serif' },
  { family: 'Anek Odia', category: 'sans-serif' },
  { family: 'Anek Tamil', category: 'sans-serif' },
  { family: 'Anek Telugu', category: 'sans-serif' },
  { family: 'Antonio', category: 'sans-serif' },
  { family: 'Anuphan', category: 'sans-serif' },
  { family: 'AR One Sans', category: 'sans-serif' },
  { family: 'Archivo Narrow', category: 'sans-serif' },
  { family: 'Arimo', category: 'sans-serif' },
  { family: 'Asap', category: 'sans-serif' },
  { family: 'Assistant', category: 'sans-serif' },
  { family: 'Asta Sans', category: 'sans-serif' },
  { family: 'Atkinson Hyperlegible Mono', category: 'sans-serif' },
  { family: 'Atkinson Hyperlegible Next', category: 'sans-serif' },
  { family: 'Beiruti', category: 'sans-serif' },
  { family: 'Cabin', category: 'sans-serif' },
  { family: 'Cairo', category: 'sans-serif' },
  { family: 'Cairo Play', category: 'sans-serif' },
  { family: 'Cascadia Code', category: 'sans-serif' },
  { family: 'Cascadia Mono', category: 'sans-serif' },
  { family: 'Catamaran', category: 'sans-serif' },
  { family: 'Changa', category: 'sans-serif' },
  { family: 'Chiron GoRound TC', category: 'sans-serif' },
  { family: 'Chiron Hei HK', category: 'sans-serif' },
  { family: 'Chivo', category: 'sans-serif' },
  { family: 'Comme', category: 'sans-serif' },
  { family: 'Commissioner', category: 'sans-serif' },
  { family: 'Cuprum', category: 'sans-serif' },
  { family: 'Darker Grotesque', category: 'sans-serif' },
  { family: 'Dosis', category: 'sans-serif' },
  { family: 'Doto', category: 'sans-serif' },
  { family: 'El Messiri', category: 'sans-serif' },
  { family: 'Elms Sans', category: 'sans-serif' },
  { family: 'Encode Sans', category: 'sans-serif' },
  { family: 'Encode Sans SC', category: 'sans-serif' },
  { family: 'Epilogue', category: 'sans-serif' },
  { family: 'Epunda Sans', category: 'sans-serif' },
  { family: 'Estedad', category: 'sans-serif' },
  { family: 'Exo', category: 'sans-serif' },
  { family: 'Exo 2', category: 'sans-serif' },
  { family: 'Familjen Grotesk', category: 'sans-serif' },
  { family: 'Finlandica Headline', category: 'sans-serif' },
  { family: 'Finlandica Text', category: 'sans-serif' },
  { family: 'Fredoka', category: 'sans-serif' },
  { family: 'Funnel Sans', category: 'sans-serif' },
  { family: 'Fustat', category: 'sans-serif' },
  { family: 'Gantari', category: 'sans-serif' },
  { family: 'Gemunu Libre', category: 'sans-serif' },
  { family: 'Genos', category: 'sans-serif' },
  { family: 'Geologica', category: 'sans-serif' },
  { family: 'Geom', category: 'sans-serif' },
  { family: 'Geomini', category: 'sans-serif' },
  { family: 'Georama', category: 'sans-serif' },
  { family: 'Glory', category: 'sans-serif' },
  { family: 'Golos Text', category: 'sans-serif' },
  { family: 'Google Sans', category: 'sans-serif' },
  { family: 'Google Sans Flex', category: 'sans-serif' },
  { family: 'Heebo', category: 'sans-serif' },
  { family: 'Host Grotesk', category: 'sans-serif' },
  { family: 'Hubot Sans', category: 'sans-serif' },
  { family: 'Inclusive Sans', category: 'sans-serif' },
  { family: 'Inter Tight', category: 'sans-serif' },
  { family: 'Jura', category: 'sans-serif' },
  { family: 'Kantumruy Pro', category: 'sans-serif' },
  { family: 'Kufam', category: 'sans-serif' },
  { family: 'Kumbh Sans', category: 'sans-serif' },
  { family: 'League Spartan', category: 'sans-serif' },
  { family: 'Lexend Deca', category: 'sans-serif' },
  { family: 'Lexend Exa', category: 'sans-serif' },
  { family: 'Lexend Giga', category: 'sans-serif' },
  { family: 'Lexend Mega', category: 'sans-serif' },
  { family: 'Lexend Peta', category: 'sans-serif' },
  { family: 'Lexend Tera', category: 'sans-serif' },
  { family: 'Lexend Zetta', category: 'sans-serif' },
  { family: 'Libre Franklin', category: 'sans-serif' },
  { family: 'M PLUS 1', category: 'sans-serif' },
  { family: 'M PLUS 2', category: 'sans-serif' },
  { family: 'M PLUS Code Latin', category: 'sans-serif' },
  { family: 'M PLUS U', category: 'sans-serif' },
  { family: 'Mada', category: 'sans-serif' },
  { family: 'Matangi', category: 'sans-serif' },
  { family: 'Maven Pro', category: 'sans-serif' },
  { family: 'Menbere', category: 'sans-serif' },
  { family: 'Merriweather Sans', category: 'sans-serif' },
  { family: 'Miranda Sans', category: 'sans-serif' },
  { family: 'Miriam Libre', category: 'sans-serif' },
  { family: 'Moderustic', category: 'sans-serif' },
  { family: 'Mohave', category: 'sans-serif' },
  { family: 'Momo Trust Sans', category: 'sans-serif' },
  { family: 'Monda', category: 'sans-serif' },
  { family: 'Montserrat Underline', category: 'sans-serif' },
  { family: 'Mozilla Headline', category: 'sans-serif' },
  { family: 'Mozilla Text', category: 'sans-serif' },
  { family: 'Murecho', category: 'sans-serif' },
  { family: 'Nata Sans', category: 'sans-serif' },
  { family: 'National Park', category: 'sans-serif' },
  { family: 'Nokora', category: 'sans-serif' },
  { family: 'Noto Emoji', category: 'sans-serif' },
  { family: 'Noto Kufi Arabic', category: 'sans-serif' },
  { family: 'Noto Sans', category: 'sans-serif' },
  { family: 'Noto Sans Adlam', category: 'sans-serif' },
  { family: 'Noto Sans Adlam Unjoined', category: 'sans-serif' },
  { family: 'Noto Sans Arabic', category: 'sans-serif' },
  { family: 'Noto Sans Armenian', category: 'sans-serif' },
  { family: 'Noto Sans Balinese', category: 'sans-serif' },
  { family: 'Noto Sans Bamum', category: 'sans-serif' },
  { family: 'Noto Sans Bassa Vah', category: 'sans-serif' },
  { family: 'Noto Sans Bengali', category: 'sans-serif' },
  { family: 'Noto Sans Canadian Aboriginal', category: 'sans-serif' },
  { family: 'Noto Sans Cham', category: 'sans-serif' },
  { family: 'Noto Sans Cherokee', category: 'sans-serif' },
  { family: 'Noto Sans Devanagari', category: 'sans-serif' },
  { family: 'Noto Sans Display', category: 'sans-serif' },
  { family: 'Noto Sans Ethiopic', category: 'sans-serif' },
  { family: 'Noto Sans Georgian', category: 'sans-serif' },
  { family: 'Noto Sans Gujarati', category: 'sans-serif' },
  { family: 'Noto Sans Gunjala Gondi', category: 'sans-serif' },
  { family: 'Noto Sans Gurmukhi', category: 'sans-serif' },
  { family: 'Noto Sans Hanifi Rohingya', category: 'sans-serif' },
  { family: 'Noto Sans Hebrew', category: 'sans-serif' },
  { family: 'Noto Sans HK', category: 'sans-serif' },
  { family: 'Noto Sans Javanese', category: 'sans-serif' },
  { family: 'Noto Sans JP', category: 'sans-serif' },
  { family: 'Noto Sans Kannada', category: 'sans-serif' },
  { family: 'Noto Sans Kawi', category: 'sans-serif' },
  { family: 'Noto Sans Kayah Li', category: 'sans-serif' },
  { family: 'Noto Sans Khmer', category: 'sans-serif' },
  { family: 'Noto Sans KR', category: 'sans-serif' },
  { family: 'Noto Sans Lao', category: 'sans-serif' },
  { family: 'Noto Sans Lao Looped', category: 'sans-serif' },
  { family: 'Noto Sans Lisu', category: 'sans-serif' },
  { family: 'Noto Sans Malayalam', category: 'sans-serif' },
  { family: 'Noto Sans Medefaidrin', category: 'sans-serif' },
  { family: 'Noto Sans Meetei Mayek', category: 'sans-serif' },
  { family: 'Noto Sans Mono', category: 'sans-serif' },
  { family: 'Noto Sans Myanmar', category: 'sans-serif' },
  { family: 'Noto Sans Nag Mundari', category: 'sans-serif' },
  { family: 'Noto Sans New Tai Lue', category: 'sans-serif' },
  { family: 'Noto Sans NKo Unjoined', category: 'sans-serif' },
  { family: 'Noto Sans Ol Chiki', category: 'sans-serif' },
  { family: 'Noto Sans Oriya', category: 'sans-serif' },
  { family: 'Noto Sans SC', category: 'sans-serif' },
  { family: 'Noto Sans Sinhala', category: 'sans-serif' },
  { family: 'Noto Sans Sora Sompeng', category: 'sans-serif' },
  { family: 'Noto Sans Sundanese', category: 'sans-serif' },
  { family: 'Noto Sans Symbols', category: 'sans-serif' },
  { family: 'Noto Sans Syriac', category: 'sans-serif' },
  { family: 'Noto Sans Syriac Eastern', category: 'sans-serif' },
  { family: 'Noto Sans Syriac Western', category: 'sans-serif' },
  { family: 'Noto Sans Tai Tham', category: 'sans-serif' },
  { family: 'Noto Sans Tamil', category: 'sans-serif' },
  { family: 'Noto Sans Tangsa', category: 'sans-serif' },
  { family: 'Noto Sans TC', category: 'sans-serif' },
  { family: 'Noto Sans Telugu', category: 'sans-serif' },
  { family: 'Noto Sans Thaana', category: 'sans-serif' },
  { family: 'Noto Sans Thai', category: 'sans-serif' },
  { family: 'Noto Sans Thai Looped', category: 'sans-serif' },
  { family: 'Noto Sans Vithkuqi', category: 'sans-serif' },
  { family: 'Noto Traditional Nushu', category: 'sans-serif' },
  { family: 'Ojuju', category: 'sans-serif' },
  { family: 'Orbitron', category: 'sans-serif' },
  { family: 'Overpass', category: 'sans-serif' },
  { family: 'Parkinsans', category: 'sans-serif' },
  { family: 'Pathway Extreme', category: 'sans-serif' },
  { family: 'Pliant', category: 'sans-serif' },
  { family: 'Pontano Sans', category: 'sans-serif' },
  { family: 'Radio Canada', category: 'sans-serif' },
  { family: 'Radio Canada Big', category: 'sans-serif' },
  { family: 'Readex Pro', category: 'sans-serif' },
  { family: 'Recursive', category: 'sans-serif' },
  { family: 'Red Hat Display', category: 'sans-serif' },
  { family: 'Red Hat Text', category: 'sans-serif' },
  { family: 'Reddit Sans', category: 'sans-serif' },
  { family: 'Reddit Sans Condensed', category: 'sans-serif' },
  { family: 'Reem Kufi', category: 'sans-serif' },
  { family: 'Reem Kufi Fun', category: 'sans-serif' },
  { family: 'REM', category: 'sans-serif' },
  { family: 'Rethink Sans', category: 'sans-serif' },
  { family: 'Roboto Condensed', category: 'sans-serif' },
  { family: 'Roboto Flex', category: 'sans-serif' },
  { family: 'Rosario', category: 'sans-serif' },
  { family: 'Ruda', category: 'sans-serif' },
  { family: 'Saira', category: 'sans-serif' },
  { family: 'Savate', category: 'sans-serif' },
  { family: 'Schibsted Grotesk', category: 'sans-serif' },
  { family: 'Science Gothic', category: 'sans-serif' },
  { family: 'Sen', category: 'sans-serif' },
  { family: 'Signika', category: 'sans-serif' },
  { family: 'Signika Negative', category: 'sans-serif' },
  { family: 'Smooch Sans', category: 'sans-serif' },
  { family: 'SN Pro', category: 'sans-serif' },
  { family: 'Sofia Sans', category: 'sans-serif' },
  { family: 'Sofia Sans Condensed', category: 'sans-serif' },
  { family: 'Sofia Sans Extra Condensed', category: 'sans-serif' },
  { family: 'Sofia Sans Semi Condensed', category: 'sans-serif' },
  { family: 'Sono', category: 'sans-serif' },
  { family: 'Sour Gummy', category: 'sans-serif' },
  { family: 'Special Gothic', category: 'sans-serif' },
  { family: 'Spline Sans', category: 'sans-serif' },
  { family: 'Stack Sans Headline', category: 'sans-serif' },
  { family: 'Stack Sans Notch', category: 'sans-serif' },
  { family: 'Stack Sans Text', category: 'sans-serif' },
  { family: 'Stick No Bills', category: 'sans-serif' },
  { family: 'Strichpunkt Sans', category: 'sans-serif' },
  { family: 'SUSE', category: 'sans-serif' },
  { family: 'SUSE Mono', category: 'sans-serif' },
  { family: 'TASA Explorer', category: 'sans-serif' },
  { family: 'TASA Orbiter', category: 'sans-serif' },
  { family: 'Teachers', category: 'sans-serif' },
  { family: 'Teko', category: 'sans-serif' },
  { family: 'TikTok Sans', category: 'sans-serif' },
  { family: 'Trispace', category: 'sans-serif' },
  { family: 'Truculenta', category: 'sans-serif' },
  { family: 'Ubuntu Sans', category: 'sans-serif' },
  { family: 'Varta', category: 'sans-serif' },
  { family: 'Vazirmatn', category: 'sans-serif' },
  { family: 'Vend Sans', category: 'sans-serif' },
  { family: 'Winky Rough', category: 'sans-serif' },
  { family: 'Winky Sans', category: 'sans-serif' },
  { family: 'Wix Madefor Display', category: 'sans-serif' },
  { family: 'Wix Madefor Text', category: 'sans-serif' },
  { family: 'Yaldevi', category: 'sans-serif' },
  { family: 'Yanone Kaffeesatz', category: 'sans-serif' },
  { family: 'Ysabeau', category: 'sans-serif' },
  { family: 'Ysabeau Infant', category: 'sans-serif' },
  { family: 'Ysabeau Office', category: 'sans-serif' },
  { family: 'Ysabeau SC', category: 'sans-serif' },
  { family: 'Zalando Sans', category: 'sans-serif' },
  { family: 'Zalando Sans Expanded', category: 'sans-serif' },
  { family: 'Zalando Sans SemiExpanded', category: 'sans-serif' },

  // Serif (100)
  { family: 'Playfair Display', category: 'serif' },
  { family: 'Lora', category: 'serif' },
  { family: 'Merriweather', category: 'serif' },
  { family: 'Source Serif 4', category: 'serif' },
  { family: 'Libre Baskerville', category: 'serif' },
  { family: 'EB Garamond', category: 'serif' },
  { family: 'Cormorant Garamond', category: 'serif' },
  { family: 'Crimson Pro', category: 'serif' },
  { family: 'Fraunces', category: 'serif' },
  { family: 'Newsreader', category: 'serif' },
  { family: 'Literata', category: 'serif' },
  { family: 'Bitter', category: 'serif' },
  { family: 'Roboto Slab', category: 'serif' },
  { family: 'Domine', category: 'serif' },
  { family: 'Frank Ruhl Libre', category: 'serif' },
  { family: 'Alegreya', category: 'serif' },
  { family: 'Aleo', category: 'serif' },
  { family: 'Alyamama', category: 'serif' },
  { family: 'Ancizar Serif', category: 'serif' },
  { family: 'Andada Pro', category: 'serif' },
  { family: 'Baskervville', category: 'serif' },
  { family: 'Baskervville SC', category: 'serif' },
  { family: 'Besley', category: 'serif' },
  { family: 'BioRhyme', category: 'serif' },
  { family: 'Bodoni Moda', category: 'serif' },
  { family: 'Bodoni Moda SC', category: 'serif' },
  { family: 'Brygada 1918', category: 'serif' },
  { family: 'Buenard', category: 'serif' },
  { family: 'Chiron Sung HK', category: 'serif' },
  { family: 'Cinzel', category: 'serif' },
  { family: 'Cormorant', category: 'serif' },
  { family: 'Cormorant Infant', category: 'serif' },
  { family: 'Eczar', category: 'serif' },
  { family: 'Epunda Slab', category: 'serif' },
  { family: 'Faustina', category: 'serif' },
  { family: 'Gelasio', category: 'serif' },
  { family: 'Grenze', category: 'serif' },
  { family: 'Hahmlet', category: 'serif' },
  { family: 'Hanuman', category: 'serif' },
  { family: 'Hepta Slab', category: 'serif' },
  { family: 'Ibarra Real Nova', category: 'serif' },
  { family: 'Imbue', category: 'serif' },
  { family: 'Josefin Slab', category: 'serif' },
  { family: 'Kalnia', category: 'serif' },
  { family: 'Kameron', category: 'serif' },
  { family: 'Kreon', category: 'serif' },
  { family: 'Labrada', category: 'serif' },
  { family: 'Libre Bodoni', category: 'serif' },
  { family: 'Manuale', category: 'serif' },
  { family: 'Markazi Text', category: 'serif' },
  { family: 'Montagu Slab', category: 'serif' },
  { family: 'Noto Naskh Arabic', category: 'serif' },
  { family: 'Noto Nastaliq Urdu', category: 'serif' },
  { family: 'Noto Rashi Hebrew', category: 'serif' },
  { family: 'Noto Serif', category: 'serif' },
  { family: 'Noto Serif Armenian', category: 'serif' },
  { family: 'Noto Serif Bengali', category: 'serif' },
  { family: 'Noto Serif Devanagari', category: 'serif' },
  { family: 'Noto Serif Display', category: 'serif' },
  { family: 'Noto Serif Ethiopic', category: 'serif' },
  { family: 'Noto Serif Georgian', category: 'serif' },
  { family: 'Noto Serif Gujarati', category: 'serif' },
  { family: 'Noto Serif Gurmukhi', category: 'serif' },
  { family: 'Noto Serif Hebrew', category: 'serif' },
  { family: 'Noto Serif Hentaigana', category: 'serif' },
  { family: 'Noto Serif HK', category: 'serif' },
  { family: 'Noto Serif JP', category: 'serif' },
  { family: 'Noto Serif Kannada', category: 'serif' },
  { family: 'Noto Serif Khmer', category: 'serif' },
  { family: 'Noto Serif Khojki', category: 'serif' },
  { family: 'Noto Serif KR', category: 'serif' },
  { family: 'Noto Serif Lao', category: 'serif' },
  { family: 'Noto Serif Malayalam', category: 'serif' },
  { family: 'Noto Serif NP Hmong', category: 'serif' },
  { family: 'Noto Serif Oriya', category: 'serif' },
  { family: 'Noto Serif SC', category: 'serif' },
  { family: 'Noto Serif Sinhala', category: 'serif' },
  { family: 'Noto Serif Tamil', category: 'serif' },
  { family: 'Noto Serif TC', category: 'serif' },
  { family: 'Noto Serif Telugu', category: 'serif' },
  { family: 'Noto Serif Thai', category: 'serif' },
  { family: 'Noto Serif Tibetan', category: 'serif' },
  { family: 'Noto Serif Toto', category: 'serif' },
  { family: 'Noto Serif Vithkuqi', category: 'serif' },
  { family: 'Noto Serif Yezidi', category: 'serif' },
  { family: 'Parastoo', category: 'serif' },
  { family: 'Petrona', category: 'serif' },
  { family: 'Piazzolla', category: 'serif' },
  { family: 'Platypi', category: 'serif' },
  { family: 'Playfair', category: 'serif' },
  { family: 'Podkova', category: 'serif' },
  { family: 'Poltawski Nowy', category: 'serif' },
  { family: 'Rasa', category: 'serif' },
  { family: 'Roboto Serif', category: 'serif' },
  { family: 'Rokkitt', category: 'serif' },
  { family: 'STIX Two Text', category: 'serif' },
  { family: 'Texturina', category: 'serif' },
  { family: 'Vollkorn', category: 'serif' },
  { family: 'Wittgenstein', category: 'serif' },
  { family: 'Yrsa', category: 'serif' },

  // Display (53)
  { family: 'Alkatra', category: 'display' },
  { family: 'Anybody', category: 'display' },
  { family: 'Arima', category: 'display' },
  { family: 'Baloo 2', category: 'display' },
  { family: 'Baloo Bhai 2', category: 'display' },
  { family: 'Baloo Bhaijaan 2', category: 'display' },
  { family: 'Baloo Bhaina 2', category: 'display' },
  { family: 'Baloo Chettan 2', category: 'display' },
  { family: 'Baloo Da 2', category: 'display' },
  { family: 'Baloo Paaji 2', category: 'display' },
  { family: 'Baloo Tamma 2', category: 'display' },
  { family: 'Baloo Tammudu 2', category: 'display' },
  { family: 'Baloo Thambi 2', category: 'display' },
  { family: 'Big Shoulders', category: 'display' },
  { family: 'Big Shoulders Inline', category: 'display' },
  { family: 'Big Shoulders Stencil', category: 'display' },
  { family: 'Bitcount', category: 'display' },
  { family: 'Bitcount Grid Double', category: 'display' },
  { family: 'Bitcount Grid Double Ink', category: 'display' },
  { family: 'Bitcount Grid Single', category: 'display' },
  { family: 'Bitcount Grid Single Ink', category: 'display' },
  { family: 'Bitcount Ink', category: 'display' },
  { family: 'Bitcount Prop Double', category: 'display' },
  { family: 'Bitcount Prop Double Ink', category: 'display' },
  { family: 'Bitcount Prop Single', category: 'display' },
  { family: 'Bitcount Prop Single Ink', category: 'display' },
  { family: 'Bitcount Single', category: 'display' },
  { family: 'Bitcount Single Ink', category: 'display' },
  { family: 'Comfortaa', category: 'display' },
  { family: 'DynaPuff', category: 'display' },
  { family: 'Expletus Sans', category: 'display' },
  { family: 'Foldit', category: 'display' },
  { family: 'Funnel Display', category: 'display' },
  { family: 'Gabarito', category: 'display' },
  { family: 'Gluten', category: 'display' },
  { family: 'Grandstander', category: 'display' },
  { family: 'Grenze Gotisch', category: 'display' },
  { family: 'Handjet', category: 'display' },
  { family: 'Kalnia Glaze', category: 'display' },
  { family: 'Lemonada', category: 'display' },
  { family: 'Linefont', category: 'display' },
  { family: 'Marhey', category: 'display' },
  { family: 'MuseoModerno', category: 'display' },
  { family: 'Oxanium', category: 'display' },
  { family: 'Phudu', category: 'display' },
  { family: 'Pixelify Sans', category: 'display' },
  { family: 'Red Rose', category: 'display' },
  { family: 'Saira Stencil', category: 'display' },
  { family: 'Sansita Swashed', category: 'display' },
  { family: 'Shantell Sans', category: 'display' },
  { family: 'Tektur', category: 'display' },
  { family: 'Tourney', category: 'display' },
  { family: 'Wavefont', category: 'display' },

  // Monospace (22)
  { family: 'Geist Mono', category: 'mono' },
  { family: 'JetBrains Mono', category: 'mono' },
  { family: 'Fira Code', category: 'mono' },
  { family: 'Source Code Pro', category: 'mono' },
  { family: 'Roboto Mono', category: 'mono' },
  { family: 'Inconsolata', category: 'mono' },
  { family: 'Red Hat Mono', category: 'mono' },
  { family: 'Martian Mono', category: 'mono' },
  { family: 'Ubuntu Sans Mono', category: 'mono' },
  { family: 'Azeret Mono', category: 'mono' },
  { family: 'Chivo Mono', category: 'mono' },
  { family: 'Datatype', category: 'mono' },
  { family: 'Google Sans Code', category: 'mono' },
  { family: 'Intel One Mono', category: 'mono' },
  { family: 'Kode Mono', category: 'mono' },
  { family: 'Lilex', category: 'mono' },
  { family: 'M PLUS 1 Code', category: 'mono' },
  { family: 'Overpass Mono', category: 'mono' },
  { family: 'Reddit Mono', category: 'mono' },
  { family: 'Sometype Mono', category: 'mono' },
  { family: 'Spline Sans Mono', category: 'mono' },
  { family: 'Victor Mono', category: 'mono' },

  // Handwriting (78)
  { family: 'Caveat', category: 'handwriting' },
  { family: 'Dancing Script', category: 'handwriting' },
  { family: 'Cause', category: 'handwriting' },
  { family: 'Edu AU VIC WA NT Arrows', category: 'handwriting' },
  { family: 'Edu AU VIC WA NT Dots', category: 'handwriting' },
  { family: 'Edu AU VIC WA NT Guides', category: 'handwriting' },
  { family: 'Edu AU VIC WA NT Hand', category: 'handwriting' },
  { family: 'Edu AU VIC WA NT Pre', category: 'handwriting' },
  { family: 'Edu NSW ACT Cursive', category: 'handwriting' },
  { family: 'Edu NSW ACT Foundation', category: 'handwriting' },
  { family: 'Edu NSW ACT Hand Pre', category: 'handwriting' },
  { family: 'Edu QLD Beginner', category: 'handwriting' },
  { family: 'Edu QLD Hand', category: 'handwriting' },
  { family: 'Edu SA Beginner', category: 'handwriting' },
  { family: 'Edu SA Hand', category: 'handwriting' },
  { family: 'Edu TAS Beginner', category: 'handwriting' },
  { family: 'Edu VIC WA NT Beginner', category: 'handwriting' },
  { family: 'Edu VIC WA NT Hand', category: 'handwriting' },
  { family: 'Edu VIC WA NT Hand Pre', category: 'handwriting' },
  { family: 'Kapakana', category: 'handwriting' },
  { family: 'Merienda', category: 'handwriting' },
  { family: 'Playpen Sans', category: 'handwriting' },
  { family: 'Playpen Sans Arabic', category: 'handwriting' },
  { family: 'Playpen Sans Deva', category: 'handwriting' },
  { family: 'Playpen Sans Hebrew', category: 'handwriting' },
  { family: 'Playpen Sans Thai', category: 'handwriting' },
  { family: 'Playwrite AR', category: 'handwriting' },
  { family: 'Playwrite AT', category: 'handwriting' },
  { family: 'Playwrite AU NSW', category: 'handwriting' },
  { family: 'Playwrite AU QLD', category: 'handwriting' },
  { family: 'Playwrite AU SA', category: 'handwriting' },
  { family: 'Playwrite AU TAS', category: 'handwriting' },
  { family: 'Playwrite AU VIC', category: 'handwriting' },
  { family: 'Playwrite BE VLG', category: 'handwriting' },
  { family: 'Playwrite BE WAL', category: 'handwriting' },
  { family: 'Playwrite BR', category: 'handwriting' },
  { family: 'Playwrite CA', category: 'handwriting' },
  { family: 'Playwrite CL', category: 'handwriting' },
  { family: 'Playwrite CO', category: 'handwriting' },
  { family: 'Playwrite CU', category: 'handwriting' },
  { family: 'Playwrite CZ', category: 'handwriting' },
  { family: 'Playwrite DE Grund', category: 'handwriting' },
  { family: 'Playwrite DE LA', category: 'handwriting' },
  { family: 'Playwrite DE SAS', category: 'handwriting' },
  { family: 'Playwrite DE VA', category: 'handwriting' },
  { family: 'Playwrite DK Loopet', category: 'handwriting' },
  { family: 'Playwrite DK Uloopet', category: 'handwriting' },
  { family: 'Playwrite ES', category: 'handwriting' },
  { family: 'Playwrite ES Deco', category: 'handwriting' },
  { family: 'Playwrite FR Moderne', category: 'handwriting' },
  { family: 'Playwrite FR Trad', category: 'handwriting' },
  { family: 'Playwrite GB J', category: 'handwriting' },
  { family: 'Playwrite GB S', category: 'handwriting' },
  { family: 'Playwrite HR', category: 'handwriting' },
  { family: 'Playwrite HR Lijeva', category: 'handwriting' },
  { family: 'Playwrite HU', category: 'handwriting' },
  { family: 'Playwrite ID', category: 'handwriting' },
  { family: 'Playwrite IE', category: 'handwriting' },
  { family: 'Playwrite IN', category: 'handwriting' },
  { family: 'Playwrite IS', category: 'handwriting' },
  { family: 'Playwrite IT Moderna', category: 'handwriting' },
  { family: 'Playwrite IT Trad', category: 'handwriting' },
  { family: 'Playwrite MX', category: 'handwriting' },
  { family: 'Playwrite NG Modern', category: 'handwriting' },
  { family: 'Playwrite NL', category: 'handwriting' },
  { family: 'Playwrite NO', category: 'handwriting' },
  { family: 'Playwrite NZ', category: 'handwriting' },
  { family: 'Playwrite NZ Basic', category: 'handwriting' },
  { family: 'Playwrite PE', category: 'handwriting' },
  { family: 'Playwrite PL', category: 'handwriting' },
  { family: 'Playwrite PT', category: 'handwriting' },
  { family: 'Playwrite RO', category: 'handwriting' },
  { family: 'Playwrite SK', category: 'handwriting' },
  { family: 'Playwrite TZ', category: 'handwriting' },
  { family: 'Playwrite US Modern', category: 'handwriting' },
  { family: 'Playwrite US Trad', category: 'handwriting' },
  { family: 'Playwrite VN', category: 'handwriting' },
  { family: 'Playwrite ZA', category: 'handwriting' },
]

const CATEGORY_BY_FAMILY = new Map(
  FONT_CATALOG.map((font) => [font.family, font.category]),
)

const FALLBACK_STACKS: Record<FontCategory, string> = {
  'sans-serif': 'ui-sans-serif, system-ui, sans-serif',
  serif: 'ui-serif, Georgia, serif',
  display: 'system-ui, sans-serif',
  handwriting: 'cursive',
  mono: "ui-monospace, 'SF Mono', monospace",
}

/** `'Inter', ui-sans-serif, system-ui, sans-serif` — the token value. */
export function fontStack(family: string): string {
  const category = CATEGORY_BY_FAMILY.get(family) ?? 'sans-serif'
  return `'${family}', ${FALLBACK_STACKS[category]}`
}

/** First family of a stack, unquoted — the display name / load target. */
export function familyFromStack(stack: string): string {
  const first = stack.split(',')[0] ?? stack
  return first.trim().replace(/^['"]|['"]$/g, '')
}

/** Google-hosted families referenced by a token record, load order stable. */
export function fontFamiliesFromTokens(
  tokens: Record<string, string>,
): string[] {
  const families: string[] = []
  for (const varName of FONT_TOKEN_VARS) {
    const stack = tokens[varName]
    if (!stack) continue
    const family = familyFromStack(stack)
    if (family && !families.includes(family)) families.push(family)
  }
  return families
}

/**
 * One css2 stylesheet URL for the given families. The shared 400–700 weight
 * request covers UI text; css2 drops weights a family doesn't ship rather
 * than erroring (verified against the live endpoint).
 */
export function googleFontsUrl(
  families: string[],
  opts: { text?: string; weights?: string } = {},
): string {
  const weights = opts.weights ?? '400;500;600;700'
  const params = families
    .map((family) => `family=${family.replaceAll(' ', '+')}:wght@${weights}`)
    .join('&')
  const text = opts.text ? `&text=${encodeURIComponent(opts.text)}` : ''
  return `https://fonts.googleapis.com/css2?${params}&display=swap${text}`
}

/**
 * Load one family's preview face, subset (`text=`) to just its own name glyphs
 * — a couple of KB, enough to render that row's label in itself. Idempotent;
 * the picker calls this per row as it scrolls into view, so a ~500-font list
 * fetches only the handful actually seen instead of every face up front.
 */
export function loadFontPreview(doc: Document, family: string): void {
  const id = `dotui-font-preview-${family.replaceAll(' ', '-').toLowerCase()}`
  if (doc.getElementById(id)) return
  const text = [...new Set([...family])].join('')
  const link = doc.createElement('link')
  link.id = id
  link.rel = 'stylesheet'
  link.href = googleFontsUrl([family], { text, weights: '400' })
  doc.head.append(link)
}

/**
 * Idempotently inject one stylesheet <link> per family into `doc`. Per-family
 * links (not one combined) so switching fonts never re-fetches already-loaded
 * ones. Links are never removed — a font once loaded stays usable.
 */
export function ensureFontStylesheets(doc: Document, families: string[]): void {
  for (const family of families) {
    const id = `dotui-font-${family.replaceAll(' ', '-').toLowerCase()}`
    if (doc.getElementById(id)) continue
    const link = doc.createElement('link')
    link.id = id
    link.rel = 'stylesheet'
    link.href = googleFontsUrl([family])
    doc.head.append(link)
  }
}
