// Produce the DS compile-entry CSS for design-sync (deterministic, committed
// script; its OUTPUT is a gitignored build artifact under www/.ds-sync-build/).
//
// We mirror the app's real Tailwind entry (www/src/styles.css) so the compiled
// stylesheet is byte-for-byte the look the app ships — same base layer, same
// committed default-preset OKLCH ramps (registry/base/colors.css), same
// per-component styles.css closure, and the tailwindcss-autocontrast plugin
// still runs (its cssfile './src/styles.css' resolves with cwd=www) to bake the
// `--on-*` contrast foregrounds.
//
// Two deltas from src/styles.css:
//   - drop the `@fontsource*` @imports: their @font-face url()s are relative to
//     node_modules and wouldn't resolve from the shipped stylesheet. Fonts ride
//     instead via cfg.extraFonts, which the converter copies + rewrites.
//   - drop the marketing-only Josefin Sans family (components never use it).
//
// `@tailwindcss/cli` then compiles this entry into www/.ds-sync-build/bundle.css,
// which cfg.cssEntry points the converter at.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const WWW = resolve('www')
const BUILD = join(WWW, '.ds-sync-build')
mkdirSync(BUILD, { recursive: true })

let css = readFileSync(join(WWW, 'src/styles.css'), 'utf8')

// Drop font @imports (fonts ship via cfg.extraFonts).
css = css.replace(/^@import\s+['"]@fontsource[^'"]+['"];?\s*$/gm, '')
// Drop the Josefin Sans metric-fallback @font-face + its @theme line.
css = css.replace(/@font-face\s*\{[^}]*Josefin Sans[^}]*\}\s*/g, '')
css = css.replace(/^\s*--font-josefin:[\s\S]*?;\s*$/m, '')

// The compile entry lives in www/.ds-sync-build/, so the registry @import and
// @source globs (written relative to src/ in the original) need one more `../`.
css = css.replace(/(['"])\.\/registry\//g, '$1../src/registry/')
css = css.replace(/@source\s+(['"])\.\/registry\//g, '@source $1../src/registry/')

// Also scan the authored preview cards so any Tailwind utility used in a
// preview wrapper is compiled into the shipped CSS (previews mostly use inline
// styles, but this is the belt-and-suspenders for ones that don't).
css = css.replace(
  /@source '\.\.\/src\/registry\/\*\*\/\*\.\{ts,tsx\}';/,
  `$&\n@source '../../.design-sync/previews/**/*.{ts,tsx}';`,
)

const header = `/* AUTO-GENERATED by .design-sync/gen-css.mjs — do not edit. */\n/* DS compile entry: mirrors www/src/styles.css minus fontsource imports. */\n`
writeFileSync(join(BUILD, 'compile.css'), header + css)
console.error('✓ wrote www/.ds-sync-build/compile.css')
