/**
 * Auto-generated by packages/registry/scripts/build.ts
 * DO NOT EDIT MANUALLY
 */

export const VARIANTS = {
	accordion: {
		options: ["base"] as const,
		default: "base",
		group: "data-display",
	},
	alert: {
		options: ["base"] as const,
		default: "base",
		group: "feedback",
	},
	avatar: {
		options: ["base"] as const,
		default: "base",
		group: "data-display",
	},
	badge: {
		options: ["base"] as const,
		default: "base",
		group: "data-display",
	},
	breadcrumbs: {
		options: ["base"] as const,
		default: "base",
		group: "navigation",
	},
	button: {
		options: ["base"] as const,
		default: "base",
		group: "buttons",
	},
	calendar: {
		options: ["base"] as const,
		default: "base",
		group: "date-time",
	},
	card: {
		options: ["base"] as const,
		default: "base",
		group: "data-display",
	},
	checkbox: {
		options: ["base"] as const,
		default: "base",
		group: "selections",
	},
	"checkbox-group": {
		options: ["base"] as const,
		default: "base",
		group: "selections",
	},
	"color-area": {
		options: ["base"] as const,
		default: "base",
		group: "color",
	},
	"color-editor": {
		options: ["base"] as const,
		default: "base",
		group: "color",
	},
	"color-field": {
		options: ["base"] as const,
		default: "base",
		group: "inputs",
	},
	"color-picker": {
		options: ["base"] as const,
		default: "base",
		group: "color",
	},
	"color-slider": {
		options: ["base"] as const,
		default: "base",
		group: "color",
	},
	"color-swatch": {
		options: ["base"] as const,
		default: "base",
		group: "color",
	},
	"color-swatch-picker": {
		options: ["base"] as const,
		default: "base",
		group: "color",
	},
	"color-thumb": {
		options: ["base"] as const,
		default: "base",
		group: "color",
	},
	combobox: {
		options: ["base"] as const,
		default: "base",
		group: "selections",
	},
	command: {
		options: ["base"] as const,
		default: "base",
		group: "overlays",
	},
	"date-field": {
		options: ["base"] as const,
		default: "base",
		group: "inputs",
	},
	"date-picker": {
		options: ["base"] as const,
		default: "base",
		group: "date-time",
	},
	dialog: {
		options: ["base"] as const,
		default: "base",
		group: "overlays",
	},
	disclosure: {
		options: ["base"] as const,
		default: "base",
		group: "data-display",
	},
	drawer: {
		options: ["base"] as const,
		default: "base",
		group: "overlays",
	},
	"drop-zone": {
		options: ["base"] as const,
		default: "base",
		group: "forms",
	},
	empty: {
		options: ["base"] as const,
		default: "base",
		group: "feedback",
	},
	field: {
		options: ["base"] as const,
		default: "base",
		group: "forms",
	},
	"file-trigger": {
		options: ["base"] as const,
		default: "base",
		group: "buttons",
	},
	form: {
		options: ["base", "react-hook-form"] as const,
		default: "base",
		group: "forms",
	},
	group: {
		options: ["base"] as const,
		default: "base",
		group: "forms",
	},
	input: {
		options: ["base"] as const,
		default: "base",
		group: "inputs",
	},
	kbd: {
		options: ["base"] as const,
		default: "base",
		group: "data-display",
	},
	link: {
		options: ["base"] as const,
		default: "base",
		group: "buttons",
	},
	"list-box": {
		options: ["base"] as const,
		default: "base",
		group: "selections",
	},
	loader: {
		options: ["base"] as const,
		default: "base",
		group: "feedback",
	},
	menu: {
		options: ["base"] as const,
		default: "base",
		group: "overlays",
	},
	modal: {
		options: ["base"] as const,
		default: "base",
		group: "overlays",
	},
	"number-field": {
		options: ["base"] as const,
		default: "base",
		group: "inputs",
	},
	overlay: {
		options: ["base"] as const,
		default: "base",
		group: "overlays",
	},
	popover: {
		options: ["base"] as const,
		default: "base",
		group: "overlays",
	},
	"progress-bar": {
		options: ["base"] as const,
		default: "base",
		group: "feedback",
	},
	"radio-group": {
		options: ["base"] as const,
		default: "base",
		group: "selections",
	},
	"search-field": {
		options: ["base"] as const,
		default: "base",
		group: "inputs",
	},
	select: {
		options: ["base"] as const,
		default: "base",
		group: "selections",
	},
	separator: {
		options: ["base"] as const,
		default: "base",
		group: "layout",
	},
	skeleton: {
		options: ["base"] as const,
		default: "base",
		group: "feedback",
	},
	slider: {
		options: ["base"] as const,
		default: "base",
		group: "inputs",
	},
	switch: {
		options: ["base"] as const,
		default: "base",
		group: "selections",
	},
	table: {
		options: ["base"] as const,
		default: "base",
		group: "data-display",
	},
	tabs: {
		options: ["base"] as const,
		default: "base",
		group: "navigation",
	},
	"tag-group": {
		options: ["base"] as const,
		default: "base",
		group: "selections",
	},
	text: {
		options: ["base"] as const,
		default: "base",
		group: "data-display",
	},
	"text-field": {
		options: ["base"] as const,
		default: "base",
		group: "inputs",
	},
	"time-field": {
		options: ["base"] as const,
		default: "base",
		group: "inputs",
	},
	toast: {
		options: ["base"] as const,
		default: "base",
		group: "feedback",
	},
	"toggle-button": {
		options: ["base"] as const,
		default: "base",
		group: "buttons",
	},
	"toggle-button-group": {
		options: ["base"] as const,
		default: "base",
		group: "buttons",
	},
	tooltip: {
		options: ["base"] as const,
		default: "base",
		group: "overlays",
	},
} as const;

/** Component groups for style editor UI */
export const VARIANT_GROUPS = {
	buttons: ["button", "file-trigger", "link", "toggle-button", "toggle-button-group"],
	color: [
		"color-area",
		"color-editor",
		"color-picker",
		"color-slider",
		"color-swatch",
		"color-swatch-picker",
		"color-thumb",
	],
	"data-display": ["accordion", "avatar", "badge", "card", "disclosure", "kbd", "table", "text"],
	"date-time": ["calendar", "date-picker"],
	feedback: ["alert", "empty", "loader", "progress-bar", "skeleton", "toast"],
	forms: ["drop-zone", "field", "form", "group"],
	inputs: ["color-field", "date-field", "input", "number-field", "search-field", "slider", "text-field", "time-field"],
	layout: ["separator"],
	navigation: ["breadcrumbs", "tabs"],
	overlays: ["command", "dialog", "drawer", "menu", "modal", "overlay", "popover", "tooltip"],
	selections: ["checkbox", "checkbox-group", "combobox", "list-box", "radio-group", "select", "switch", "tag-group"],
} as const;

export type VariantKey = keyof typeof VARIANTS;
export type VariantGroupKey = keyof typeof VARIANT_GROUPS;
