import { Registry } from "@/registry/schema";

export const core: Registry = [
  {
    name: "alert",
    type: "registry:core",
    files: ["core/alert/alert.tsx"],
  },
  {
    name: "aspect-ratio",
    type: "registry:core",
    dependencies: ["@radix-ui/react-aspect-ratio"],
    files: ["core/aspect-ratio/aspect-ratio.tsx"],
  },
  {
    name: "avatar",
    type: "registry:core",
    files: ["core/avatar/avatar.tsx"],
  },
  {
    name: "badge",
    type: "registry:core",
    files: ["core/badge/badge.tsx"],
  },
  {
    name: "breadcrumbs",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    files: ["core/breadcrumbs/breadcrumbs.tsx"],
  },
  {
    name: "button",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    files: ["core/button/button.tsx"],
  },
  {
    name: "calendar",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["button", "heading", "text"],
    files: ["core/calendar/calendar.tsx"],
  },
  {
    name: "checkbox",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    files: ["core/checkbox/checkbox.tsx"],
  },
  {
    name: "checkbox-group",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["checkbox"],
    files: ["core/checkbox-group/checkbox-group.tsx"],
  },
  {
    name: "color-area",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["color-thumb"],
    files: ["core/color-area/color-area.tsx"],
  },
  {
    name: "color-field",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["field", "input"],
    files: ["core/color-field/color-field.tsx"],
  },
  {
    name: "color-picker",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: [
      "button",
      "color-area",
      "color-field",
      "color-slider",
      "color-swatch",
      "dialog",
      "list-box",
      "select",
    ],
    files: ["core/color-picker/color-picker.tsx"],
  },
  {
    name: "color-slider",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["color-thumb", "field"],
    files: ["core/color-slider/color-slider.tsx"],
  },
  {
    name: "color-swatch",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    files: ["core/color-swatch/color-swatch.tsx"],
  },
  {
    name: "color-thumb",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    files: ["core/color-thumb/color-thumb.tsx"],
  },
  {
    name: "combobox",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["button", "field", "input", "list-box", "overlay"],
    files: ["core/combobox/combobox.tsx"],
  },
  {
    name: "date-field",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["date-input", "field", "input"],
    files: ["core/date-field/date-field.tsx"],
  },
  {
    name: "date-input",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    files: ["core/date-input/date-input.tsx"],
  },
  {
    name: "date-picker",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: [
      "button",
      "calendar",
      "dialog",
      "date-input",
      "field",
      "input",
    ],
    files: ["core/date-picker/date-picker.tsx"],
  },
  {
    name: "date-range-picker",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: [
      "button",
      "range-calendar",
      "dialog",
      "date-input",
      "field",
      "input",
    ],
    files: ["core/date-range-picker/date-range-picker.tsx"],
  },
  {
    name: "dialog",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["overlay", "heading", "text"],
    files: ["core/dialog/dialog.tsx"],
  },
  {
    name: "drop-zone",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    files: ["core/drop-zone/drop-zone.tsx"],
  },
  {
    name: "field",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    files: ["core/field/field.tsx"],
  },
  {
    name: "file-trigger",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    files: ["core/file-trigger/file-trigger.tsx"],
  },
  {
    name: "group",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    files: ["core/group/group.tsx"],
  },
  {
    name: "heading",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    files: ["core/heading/heading.tsx"],
  },
  {
    name: "input",
    type: "registry:core",
    dependencies: [
      "react-aria-components",
      "@react-aria/utils",
      "@react-stately/utils",
    ],
    files: ["core/input/input.tsx"],
  },
  {
    name: "kbd",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    files: ["core/kbd/kbd.tsx"],
  },
  {
    name: "link",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    files: ["core/link/link.tsx"],
  },
  {
    name: "list-box",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["text"],
    files: ["core/list-box/list-box.tsx"],
  },
  {
    name: "menu",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["overlay", "kbd", "text"],
    files: ["core/menu/menu.tsx"],
  },
  // TODO: add useMediaQuery
  {
    name: "number-field",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["input", "field", "button"],
    files: ["core/number-field/number-field.tsx"],
  },
  // TODO: add useMediaQuery
  {
    name: "overlay",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["button"],
    files: ["core/overlay/overlay.tsx", "core/overlay/use-motion-drawer.tsx"],
  },
  {
    name: "progress",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["field"],
    files: ["core/progress/progress.tsx"],
  },
  {
    name: "radio-group",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["field"],
    files: ["core/radio-group/radio-group.tsx"],
  },
  {
    name: "range-calendar",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["button", "calendar", "heading", "text"],
    files: ["core/range-calendar/range-calendar.tsx"],
  },
  {
    name: "scroll-area",
    type: "registry:core",
    dependencies: ["@radix-ui/react-scroll-area"],
    files: ["core/scroll-area/scroll-area.tsx"],
  },
  {
    name: "search-field",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["button", "field", "input"],
    files: ["core/search-field/search-field.tsx"],
  },
  {
    name: "section",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    files: ["core/section/section.tsx"],
  },
  {
    name: "select",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["button", "field", "list-box", "overlay"],
    files: ["core/select/select.tsx"],
  },
  {
    name: "separator",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    files: ["core/separator/separator.tsx"],
  },
  {
    name: "skeleton",
    type: "registry:core",
    files: ["core/separator/separator.tsx"],
  },
  {
    name: "slider",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["field"],
    files: ["core/slider/slider.tsx"],
  },
  {
    name: "switch",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    files: ["core/switch/switch.tsx"],
  },
  {
    name: "tabs",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    files: ["core/tabs/tabs.tsx"],
  },
  {
    name: "text",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    files: ["core/text/text.tsx"],
  },
  {
    name: "text-area",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["field", "input", "text-field"],
    files: ["core/text-area/text-area.tsx"],
  },
  {
    name: "text-field",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["field", "input"],
    files: ["core/text-field/text-field.tsx"],
  },
  {
    name: "time-field",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["field", "input", "date-input"],
    files: ["core/time-field/time-field.tsx"],
  },
  {
    name: "toggle-button",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    files: ["core/toggle-button/toggle-button.tsx"],
  },
  {
    name: "tooltip",
    type: "registry:core",
    dependencies: ["react-aria-components"],
    registryDependencies: ["overlay", "text"],
    files: ["core/tooltip/tooltip.tsx"],
  },
];
