export const iconLibraries: { name: string; dependency: string }[] = [
  {
    name: "lucide",
    dependency: "lucide-react",
  },
  {
    name: "remix",
    dependency: "@remixicon/react",
  },
  {
    name: "radix",
    dependency: "@radix-ui/react-icons",
  },
  {
    name: "heroicons",
    dependency: "@heroicons/react",
  },
  {
    name: "feather",
    dependency: "react-feather",
  },
] as const;

type Icons = {
  [key: string]: {
    lucide: string;
    remix: string;
    radix: string;
    heroicons: string;
    feather: string;
  };
};

export const icons: Icons = {
  LoaderIcon: {
    lucide: "Loader2Icon",
    remix: "RiLoader4Line",
    radix: "Reload",
    heroicons: "ArrowPath",
    feather: "Loader",
  },
  DangerIcon: {
    lucide: "AlertCircleIcon",
    remix: "AlertCircleIcon",
    radix: "AlertCircleIcon",
    heroicons: "AlertCircleIcon",
    feather: "AlertCircleIcon",
  },
  WarningIcon: {
    lucide: "AlertTriangleIcon",
    remix: "AlertTriangleIcon",
    radix: "AlertTriangleIcon",
    heroicons: "AlertTriangleIcon",
    feather: "AlertTriangleIcon",
  },
  SuccessIcon: {
    lucide: "CheckCircle2Icon",
    remix: "CheckCircle2Icon",
    radix: "CheckCircle2Icon",
    heroicons: "CheckCircle2Icon",
    feather: "CheckCircle2Icon",
  },
  InfoIcon: {
    lucide: "InfoIcon",
    remix: "InfoIcon",
    radix: "InfoIcon",
    heroicons: "InfoIcon",
    feather: "InfoIcon",
  },
  ChevronRightIcon: {
    lucide: "ChevronRightIcon",
    remix: "ChevronRightIcon",
    radix: "ChevronRightIcon",
    heroicons: "ChevronRightIcon",
    feather: "ChevronRightIcon",
  },
  ChevronLeftIcon: {
    lucide: "ChevronLeftIcon",
    remix: "ChevronLeftIcon",
    radix: "ChevronLeftIcon",
    heroicons: "ChevronLeftIcon",
    feather: "ChevronLeftIcon",
  },
  ChevronDownIcon: {
    lucide: "ChevronDownIcon",
    remix: "ChevronDownIcon",
    radix: "ChevronDownIcon",
    heroicons: "ChevronDownIcon",
    feather: "ChevronDownIcon",
  },
  ChevronUpIcon: {
    lucide: "ChevronUpIcon",
    remix: "ChevronUpIcon",
    radix: "ChevronUpIcon",
    heroicons: "ChevronUpIcon",
    feather: "ChevronUpIcon",
  },
  SearchIcon: {
    lucide: "SearchIcon",
    remix: "SearchIcon",
    radix: "SearchIcon",
    heroicons: "SearchIcon",
    feather: "SearchIcon",
  },
  HelpIcon: {
    lucide: "HelpCircleIcon",
    remix: "HelpCircleIcon",
    radix: "HelpCircleIcon",
    heroicons: "HelpCircleIcon",
    feather: "HelpCircleIcon",
  },
  CalendarIcon: {
    lucide: "CalendarIcon",
    remix: "CalendarIcon",
    radix: "CalendarIcon",
    heroicons: "CalendarIcon",
    feather: "CalendarIcon",
  },
  XIcon: {
    lucide: "XIcon",
    remix: "XIcon",
    radix: "XIcon",
    heroicons: "XIcon",
    feather: "XIcon",
  },
  AsteriskIcon: {
    lucide: "AsteriskIcon",
    remix: "AsteriskIcon",
    radix: "AsteriskIcon",
    heroicons: "AsteriskIcon",
    feather: "AsteriskIcon",
  },
  CheckIcon: {
    lucide: "CheckIcon",
    remix: "CheckIcon",
    radix: "CheckIcon",
    heroicons: "CheckIcon",
    feather: "CheckIcon",
  },
  MinusIcon: {
    lucide: "MinusIcon",
    remix: "MinusIcon",
    radix: "MinusIcon",
    heroicons: "MinusIcon",
    feather: "MinusIcon",
  },
  PlusIcon: {
    lucide: "PlusIcon",
    remix: "PlusIcon",
    radix: "PlusIcon",
    heroicons: "PlusIcon",
    feather: "PlusIcon",
  },
  WalletIcon: {
    lucide: "WalletIcon",
    remix: "WalletIcon",
    radix: "WalletIcon",
    heroicons: "WalletIcon",
    feather: "WalletIcon",
  },
  GlobeIcon: {
    lucide: "GlobeIcon",
    remix: "GlobeIcon",
    radix: "GlobeIcon",
    heroicons: "GlobeIcon",
    feather: "GlobeIcon",
  },
  UserIcon: {
    lucide: "User2Icon",
    remix: "User2Icon",
    radix: "User2Icon",
    heroicons: "User2Icon",
    feather: "User2Icon",
  },
  ShieldIcon: {
    lucide: "ShieldIcon",
    remix: "ShieldIcon",
    radix: "ShieldIcon",
    heroicons: "ShieldIcon",
    feather: "ShieldIcon",
  },
  ChevronRightSquareIcon: {
    lucide: "ChevronRightSquareIcon",
    remix: "ChevronRightSquareIcon",
    radix: "ChevronRightSquareIcon",
    heroicons: "ChevronRightSquareIcon",
    feather: "ChevronRightSquareIcon",
  },
  HomeIcon: {
    lucide: "HomeIcon",
    remix: "HomeIcon",
    radix: "HomeIcon",
    heroicons: "HomeIcon",
    feather: "HomeIcon",
  },
  LogInIcon: {
    lucide: "LogInIcon",
    remix: "LogInIcon",
    radix: "LogInIcon",
    heroicons: "LogInIcon",
    feather: "LogInIcon",
  },
  UploadIcon: {
    lucide: "UploadIcon",
    remix: "UploadIcon",
    radix: "UploadIcon",
    heroicons: "UploadIcon",
    feather: "UploadIcon",
  },
  PaletteIcon: {
    lucide: "PaletteIcon",
    remix: "PaletteIcon",
    radix: "PaletteIcon",
    heroicons: "PaletteIcon",
    feather: "PaletteIcon",
  },
  UsersIcon: {
    lucide: "UsersIcon",
    remix: "UsersIcon",
    radix: "UsersIcon",
    heroicons: "UsersIcon",
    feather: "UsersIcon",
  },
  PlaneIcon: {
    lucide: "PlaneIcon",
    remix: "PlaneIcon",
    radix: "PlaneIcon",
    heroicons: "PlaneIcon",
    feather: "PlaneIcon",
  },
  CameraIcon: {
    lucide: "CameraIcon",
    remix: "CameraIcon",
    radix: "CameraIcon",
    heroicons: "CameraIcon",
    feather: "CameraIcon",
  },
  ExternalLinkIcon: {
    lucide: "ExternalLinkIcon",
    remix: "ExternalLinkIcon",
    radix: "ExternalLinkIcon",
    heroicons: "ExternalLinkIcon",
    feather: "ExternalLinkIcon",
  },
  MenuIcon: {
    lucide: "MenuIcon",
    remix: "MenuIcon",
    radix: "MenuIcon",
    heroicons: "MenuIcon",
    feather: "MenuIcon",
  },
  CopyIcon: {
    lucide: "CopyIcon",
    remix: "CopyIcon",
    radix: "CopyIcon",
    heroicons: "CopyIcon",
    feather: "CopyIcon",
  },
  PlusSquareIcon: {
    lucide: "PlusSquareIcon",
    remix: "PlusSquareIcon",
    radix: "PlusSquareIcon",
    heroicons: "PlusSquareIcon",
    feather: "PlusSquareIcon",
  },
  SquarePenIcon: {
    lucide: "SquarePenIcon",
    remix: "SquarePenIcon",
    radix: "SquarePenIcon",
    heroicons: "SquarePenIcon",
    feather: "SquarePenIcon",
  },
  RotateCwIcon: {
    lucide: "RotateCwIcon",
    remix: "RotateCwIcon",
    radix: "RotateCwIcon",
    heroicons: "RotateCwIcon",
    feather: "RotateCwIcon",
  },
  XCircleIcon: {
    lucide: "XCircleIcon",
    remix: "XCircleIcon",
    radix: "XCircleIcon",
    heroicons: "XCircleIcon",
    feather: "XCircleIcon",
  },
  BoldIcon: {
    lucide: "BoldIcon",
    remix: "BoldIcon",
    radix: "BoldIcon",
    heroicons: "BoldIcon",
    feather: "BoldIcon",
  },
  ItalicIcon: {
    lucide: "ItalicIcon",
    remix: "ItalicIcon",
    radix: "ItalicIcon",
    heroicons: "ItalicIcon",
    feather: "ItalicIcon",
  },
  TimerIcon: {
    lucide: "TimerIcon",
    remix: "TimerIcon",
    radix: "TimerIcon",
    heroicons: "TimerIcon",
    feather: "TimerIcon",
  },
  PinIcon: {
    lucide: "PinIcon",
    remix: "PinIcon",
    radix: "PinIcon",
    heroicons: "PinIcon",
    feather: "PinIcon",
  },
  ALargeSmallIcon: {
    lucide: "ALargeSmallIcon",
    remix: "ALargeSmallIcon",
    radix: "ALargeSmallIcon",
    heroicons: "ALargeSmallIcon",
    feather: "ALargeSmallIcon",
  },
  Volume1Icon: {
    lucide: "Volume1Icon",
    remix: "Volume1Icon",
    radix: "Volume1Icon",
    heroicons: "Volume1Icon",
    feather: "Volume1Icon",
  },
  Volume2Icon: {
    lucide: "Volume2Icon",
    remix: "Volume2Icon",
    radix: "Volume2Icon",
    heroicons: "Volume2Icon",
    feather: "Volume2Icon",
  },
  ChevronsUpDownIcon: {
    lucide: "ChevronsUpDownIcon",
    remix: "ChevronsUpDownIcon",
    radix: "ChevronsUpDownIcon",
    heroicons: "ChevronsUpDownIcon",
    feather: "ChevronsUpDownIcon",
  },
};
