import { promises as fs } from "fs";
import { existsSync } from "node:fs";
import path from "path";
import { rimraf } from "rimraf";

import { registryBlocks } from "@dotui/ui/registry/registry-blocks";

const REGISTRY_DIR = path.join(process.cwd(), "src/__registry__");

async function setup() {
  await rimraf(REGISTRY_DIR);
  await fs.mkdir(REGISTRY_DIR, { recursive: true });
}

async function buildBlocks() {
  const TARGET_PATH = path.join(REGISTRY_DIR, "blocks.tsx");

  let index = `// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<
  string,
  {
    files: string[];
    component: React.LazyExoticComponent<React.ComponentType<object>>;
  }
> = {
`;

  for (const block of registryBlocks) {
    const blockFiles =
      block.files?.map((file) => {
        const filePath = typeof file === "string" ? file : file.path;
        return `registry/${filePath}`;
      }) || [];

    let componentPath = `@dotui/ui/registry/blocks/${block.name}`;

    if (block.files && block.files.length > 0) {
      const files = block.files.map((file) =>
        typeof file === "string" ? { type: "registry:page", path: file } : file,
      );
      if (files?.length && files[0]) {
        const firstFilePath = files[0].path.replace(/\.tsx?$/, "");
        componentPath = `@dotui/ui/registry/${firstFilePath}`;
      }
    }

    index += `
  "${block.name}": {
    files: ${JSON.stringify(blockFiles)},
    component: React.lazy(() => import("${componentPath}")),
  },`;
  }

  index += `
}
`;

  const outputDir = path.dirname(TARGET_PATH);
  await fs.mkdir(outputDir, { recursive: true });

  await fs.writeFile(TARGET_PATH, index, "utf8");
}

async function processDirectory(
  dirPath: string,
  relativePath: string,
  index: string[],
): Promise<void> {
  const entries = await fs.readdir(dirPath, { withFileTypes: true });

  for (const entry of entries) {
    if (entry.isFile() && entry.name.endsWith(".tsx")) {
      const cleanRelativePath = relativePath
        .replace("/demos/", "/")
        .replace("/demos", "");
      const demoName = `${cleanRelativePath}/${entry.name.replace(".tsx", "")}`;
      const demoPath = `@dotui/ui/registry/components/${relativePath}/${entry.name.replace(".tsx", "")}`;
      const filePath = `registry/components/${relativePath}/${entry.name}`;

      index.push(`
  "${demoName}": {
    files: ["${filePath}"],
    component: React.lazy(() => import("${demoPath}")),
  },`);
    } else if (entry.isDirectory()) {
      const subDirPath = path.join(dirPath, entry.name);
      const subRelativePath = `${relativePath}/${entry.name}`;
      await processDirectory(subDirPath, subRelativePath, index);
    }
  }
}

async function buildDemos() {
  const targetPath = path.join(REGISTRY_DIR, "demos.tsx");

  let index = `// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<
  string,
  {
    files: string[];
    component: React.LazyExoticComponent<React.ComponentType<object>>;
  }
> = {
`;

  const sourcePath = path.join(process.cwd(), "src/registry/components");
  const componentFolders = await fs.readdir(sourcePath);

  const indexEntries: string[] = [];

  for (const componentFolder of componentFolders) {
    const componentPath = path.join(sourcePath, componentFolder);
    const stats = await fs.stat(componentPath);

    if (!stats.isDirectory()) continue;

    const demosPath = path.join(componentPath, "demos");

    if (!existsSync(demosPath)) continue;

    await processDirectory(demosPath, `${componentFolder}/demos`, indexEntries);
  }

  index += indexEntries.join("");

  index += `
}
`;

  const outputDir = path.dirname(targetPath);
  await fs.mkdir(outputDir, { recursive: true });

  await fs.writeFile(targetPath, index, "utf8");
}

async function main() {
  console.log("🔨 Building registry...");

  try {
    await setup();
    await buildBlocks();
    await buildDemos();
    console.log("✅ Registry built successfully!");
  } catch (error) {
    console.error("❌ Error building registry:", error);
    process.exit(1);
  }
}

main();
