// This file is synced from @dotui/registry
// Do not edit this file directly - it will be overwritten

"use client";

import type { FormProps as AriaFormProps } from "react-aria-components";
import { Form as AriaForm } from "react-aria-components";

export type FormProps = AriaFormProps;
export { AriaForm as Form };
