// This file is autogenerated by scripts/build-preview-imports.ts
// Do not edit this file directly.
import React from "react";

export const previews = {
  "components/sparkle-button/demo": {
    component: React.lazy<React.FC>(() => import("@/lib/components/sparkle-button/demo")),
    code: [
      {
        title: "demo.tsx",
        code: 'import { Button } from "@/lib/components/sparkle-button";\r\n\r\nexport default function SparkleButton() {\r\n  return <Button variant="sparkle">Get started</Button>;\r\n}\r\n',
      },
    ],
  },
  "components/hero-section": {
    component: React.lazy<React.FC>(() => import("@/lib/components/hero-section")),
    code: [
      {
        title: "hero-section.tsx",
        code: 'import React from "react";\r\nimport Link from "next/link";\r\nimport { ArrowRightIcon, SearchIcon, SparklesIcon } from "lucide-react";\r\nimport { badgeVariants } from "@/components/ui/badge";\r\nimport { Button } from "@/components/ui/button";\r\nimport { cn } from "@/utils/classes";\r\n\r\nexport default function Demo() {\r\n  return (\r\n    <section>\r\n      <Link\r\n        href="https://github.com/mehdibha/rcopy"\r\n        target="_blank"\r\n        className={cn(\r\n          badgeVariants({ variant: "outline", size: "md" }),\r\n          "cursor-pointer space-x-2 font-mono delay-75 duration-200 hover:bg-secondary"\r\n        )}\r\n      >\r\n        <SparklesIcon size={18} />\r\n        <span>Star us on GitHub</span> <ArrowRightIcon size={15} />\r\n      </Link>\r\n      <h1 className="mt-4 max-w-2xl font-display text-5xl font-bold leading-tight">\r\n        Copy and paste components for you React App\r\n      </h1>\r\n      <h2 className="text-md mt-6 text-muted-foreground md:text-lg lg:text-xl">\r\n        Copy the code, paste it, customize it, own it. Done.\r\n      </h2>\r\n      <div className="mt-10 flex space-x-4">\r\n        <Button size="lg" variant="default">\r\n          Explore components\r\n        </Button>\r\n        <Button size="lg" variant="outline">\r\n          <SearchIcon size={20} className="mr-2" />\r\n          Quick search\r\n        </Button>\r\n      </div>\r\n    </section>\r\n  );\r\n}\r\n',
      },
    ],
  },
  "hooks/use-battery/demo": {
    component: React.lazy<React.FC>(() => import("@/lib/hooks/use-battery/demo")),
    code: [
      {
        title: "demo.tsx",
        code: '"use client";\r\n\r\nimport {\r\n  BatteryChargingIcon,\r\n  BatteryFullIcon,\r\n  BatteryLowIcon,\r\n  BatteryMediumIcon,\r\n  BatteryWarning,\r\n  Loader2Icon,\r\n} from "lucide-react";\r\nimport { useBattery } from "@/lib/hooks/use-battery";\r\n\r\nexport default function Demo() {\r\n  const { isLoading, isSupported, isCharging, level } = useBattery();\r\n\r\n  const size = 120;\r\n\r\n  return (\r\n    <div className="text-center">\r\n      <h2 className="text-xl font-semibold">Battery status</h2>\r\n      <div className="mt-4 flex items-center justify-center space-x-4">\r\n        {isLoading ? (\r\n          <Loader2Icon className="animate-spin" />\r\n        ) : !isSupported ? (\r\n          <p className="text-muted-foreground">\r\n            Battery status API is not supported in your browser.\r\n          </p>\r\n        ) : (\r\n          <>\r\n            <span className="text-5xl font-bold">{level * 100}%</span>\r\n            {isCharging ? (\r\n              <BatteryChargingIcon size={size} />\r\n            ) : level === 1 ? (\r\n              <BatteryFullIcon size={size} />\r\n            ) : level > 0.5 ? (\r\n              <BatteryMediumIcon size={size} />\r\n            ) : level > 0.2 ? (\r\n              <BatteryLowIcon size={size} />\r\n            ) : (\r\n              <BatteryWarning size={size} />\r\n            )}\r\n          </>\r\n        )}\r\n      </div>\r\n    </div>\r\n  );\r\n}\r\n',
      },
    ],
  },
  "hooks/use-debounce/demo": {
    component: React.lazy<React.FC>(() => import("@/lib/hooks/use-debounce/demo")),
    code: [
      {
        title: "demo.tsx",
        code: '"use client";\r\n\r\nimport * as React from "react";\r\nimport { SearchIcon } from "lucide-react";\r\nimport { Input } from "@/components/ui/input";\r\nimport { useDebounce } from "@/lib/hooks/use-debounce";\r\n\r\nexport default function Demo() {\r\n  const [searchInput, setSearchInput] = React.useState("");\r\n  const debouncedValue = useDebounce(searchInput, 1000);\r\n\r\n  return (\r\n    <div className="w-full max-w-sm">\r\n      <div className="relative">\r\n        <SearchIcon\r\n          size={18}\r\n          className="pointer-events-none absolute left-2 top-1/2 -translate-y-1/2 transform text-muted-foreground"\r\n        />\r\n        <Input\r\n          value={searchInput}\r\n          onChange={(e) => {\r\n            setSearchInput(e.target.value);\r\n          }}\r\n          placeholder="Search"\r\n          className="full-w pl-8"\r\n        />\r\n      </div>\r\n      <div className="mt-10 text-center">\r\n        {debouncedValue ? (\r\n          <p>Results for &quot;{debouncedValue}&quot;</p>\r\n        ) : (\r\n          <p className="text-muted-foreground">Start searching</p>\r\n        )}\r\n      </div>\r\n    </div>\r\n  );\r\n}\r\n',
      },
    ],
  },
  "pages/pricing": {
    component: React.lazy<React.FC>(() => import("@/lib/pages/pricing")),
    code: [
      {
        title: "pricing.tsx",
        code: 'import { PricingPlan } from "./pricing-plan";\r\n\r\nexport default function Pricing() {\r\n  return (\r\n    <div className="min-h-screen">\r\n      <h1>Pricing</h1>\r\n      <p>\r\n        This is a simple example of a Next.js app with a custom routing solution that uses\r\n        the file system to define routes.\r\n      </p>\r\n      <PricingPlan />\r\n    </div>\r\n  );\r\n}\r\n',
      },
      {
        title: "pricing-plan.tsx",
        code: "export const PricingPlan = () => {\r\n  return <div>pricing plan</div>;\r\n};\r\n",
      },
    ],
  },
};
