
// This file is autogenerated by scripts/build-preview-imports.ts
// Do not edit this file directly.
import React from "react";

export const previews = {
  "components/animations/sparkle-button": {
    component: React.lazy<React.FC>(() => import("~/content/components/animations/sparkle-button")),
    code : `import { Button } from "@/modules/components/sparkle-button";

export default function SparkleButton() {
  return <Button variant="sparkle">Get started</Button>;
}
`
  },
  "components/marketing/hero-section": {
    component: React.lazy<React.FC>(() => import("~/content/components/marketing/hero-section")),
    code : `import React from "react";
import Link from "next/link";
import { ArrowRightIcon, SearchIcon, SparklesIcon } from "lucide-react";
import { badgeVariants } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { cn } from "@/utils/classes";

export default function Demo() {
  return (
    <section>
      <Link
        href="https://github.com/mehdibha/rcopy"
        target="_blank"
        className={cn(
          badgeVariants({ variant: "outline", size: "md" }),
          "cursor-pointer space-x-2 font-mono delay-75 duration-200 hover:bg-secondary"
        )}
      >
        <SparklesIcon size={18} />
        <span>Star us on GitHub</span> <ArrowRightIcon size={15} />
      </Link>
      <h1 className="mt-4 max-w-2xl font-display text-5xl font-bold leading-tight">
        Copy and paste components for you React App
      </h1>
      <h2 className="text-md mt-6 text-muted-foreground md:text-lg lg:text-xl">
        Copy the code, paste it, customize it, own it. Done.
      </h2>
      <div className="mt-10 flex space-x-4">
        <Button size="lg" variant="default">
          Explore components
        </Button>
        <Button size="lg" variant="outline">
          <SearchIcon size={20} className="mr-2" />
          Quick search
        </Button>
      </div>
    </section>
  );
}
`
  },
  "pages/about": {
    component: React.lazy<React.FC>(() => import("~/content/pages/about")),
    code : `export default function About() {
  return (
    <div className="min-h-screen">
      <h1>About</h1>
      <p>
        This is a simple example of a Next.js app with a custom routing solution that uses
        the file system to define routes.
      </p>
    </div>
  );
}
`
  },
  "pages/account": {
    component: React.lazy<React.FC>(() => import("~/content/pages/account")),
    code : `export default function Account() {
  return (
    <div className="min-h-screen">
      <h1>Account</h1>
      <p>
        This is a simple example of a Next.js app with a custom routing solution that uses
        the file system to define routes.
      </p>
    </div>
  );
}
`
  },
  "pages/landing": {
    component: React.lazy<React.FC>(() => import("~/content/pages/landing")),
    code : `export default function Landing() {
  return (
    <div className="min-h-screen">
      <h1>Landing</h1>
      <p>
        This is a simple example of a Next.js app with a custom routing solution that uses
        the file system to define routes.
      </p>
    </div>
  );
}
`
  },
  "pages/login": {
    component: React.lazy<React.FC>(() => import("~/content/pages/login")),
    code : `export default function Login() {
  return (
    <div className="min-h-screen">
      <h1>Login</h1>
      <p>
        This is a simple example of a Next.js app with a custom routing solution that uses
        the file system to define routes.
      </p>
    </div>
  );
}
`
  },
  "pages/pricing": {
    component: React.lazy<React.FC>(() => import("~/content/pages/pricing")),
    code : `export default function Pricing() {
  return (
    <div className="min-h-screen">
      <h1>Pricing</h1>
      <p>
        This is a simple example of a Next.js app with a custom routing solution that uses
        the file system to define routes.
      </p>
    </div>
  );
}
`
  },
  "pages/register": {
    component: React.lazy<React.FC>(() => import("~/content/pages/register")),
    code : `export default function Register() {
  return (
    <div className="min-h-screen">
      <h1>Register</h1>
      <p>
        This is a simple example of a Next.js app with a custom routing solution that uses
        the file system to define routes.
      </p>
    </div>
  );
}
`
  }
}