// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<
  string,
  {
    files: string[];
    component: React.LazyExoticComponent<React.ComponentType<object>>;
  }
> = {
  "login-01": {
    files: [
      "registry/blocks/auth/login-01/page.tsx",
      "registry/blocks/auth/login-01/components/login-form.tsx",
    ],
    component: React.lazy(
      () => import("@dotui/ui/registry/blocks/auth/login-01/page"),
    ),
  },
  "register-01": {
    files: [
      "registry/blocks/auth/register-01/page.tsx",
      "registry/blocks/auth/register-01/components/register-form.tsx",
    ],
    component: React.lazy(
      () => import("@dotui/ui/registry/blocks/auth/register-01/page"),
    ),
  },
  "overview-01": {
    files: ["registry/blocks/overview/overview-01/page.tsx"],
    component: React.lazy(
      () => import("@dotui/ui/registry/blocks/overview/overview-01/page"),
    ),
  },
  backlog: {
    files: ["registry/blocks/tables/backlog/page.tsx"],
    component: React.lazy(
      () => import("@dotui/ui/registry/blocks/tables/backlog/page"),
    ),
  },
  "invite-members": {
    files: ["registry/blocks/invite-members/page.tsx"],
    component: React.lazy(
      () => import("@dotui/ui/registry/blocks/invite-members/page"),
    ),
  },
};
