/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<
  string,
  {
    files: string[];
    component: React.LazyExoticComponent<React.ComponentType<object>>;
  }
> = {
  login: {
    files: [
      "registry/blocks/auth/login/page.tsx",
      "registry/blocks/auth/login/components/login-form.tsx",
    ],
    component: React.lazy(async () => {
      const mod = await import("@dotui/ui/registry/blocks/auth/login/page");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  backlog: {
    files: ["registry/blocks/tables/backlog/components/backlog.tsx"],
    component: React.lazy(async () => {
      const mod = await import(
        "@dotui/ui/registry/blocks/tables/backlog/components/backlog"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "invite-members": {
    files: [
      "registry/blocks/application/invite-members/components/invite-members.tsx",
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@dotui/ui/registry/blocks/application/invite-members/components/invite-members"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "team-name": {
    files: ["registry/blocks/application/team-name/components/team-name.tsx"],
    component: React.lazy(async () => {
      const mod = await import(
        "@dotui/ui/registry/blocks/application/team-name/components/team-name"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "color-editor": {
    files: [
      "registry/blocks/application/color-editor/components/accent-color-editor.tsx",
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@dotui/ui/registry/blocks/application/color-editor/components/accent-color-editor"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "account-menu": {
    files: [
      "registry/blocks/application/account-menu/components/account-menu.tsx",
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@dotui/ui/registry/blocks/application/account-menu/components/account-menu"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  notifications: {
    files: [
      "registry/blocks/application/notifications/components/notifications.tsx",
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@dotui/ui/registry/blocks/application/notifications/components/notifications"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  booking: {
    files: ["registry/blocks/calendars/booking/components/booking.tsx"],
    component: React.lazy(async () => {
      const mod = await import(
        "@dotui/ui/registry/blocks/calendars/booking/components/booking"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "blocks-showcase": {
    files: [
      "registry/blocks/showcase/blocks-showcase/page.tsx",
      "registry/blocks/showcase/blocks-showcase/components/blocks-showcase.tsx",
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@dotui/ui/registry/blocks/showcase/blocks-showcase/page"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
};
