// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<
  string,
  {
    files: string[];
    component: React.LazyExoticComponent<React.ComponentType<object>>;
  }
> = {
  "login-01": {
    files: [
      "registry/blocks/login-01/page.tsx",
      "registry/blocks/login-01/components/login-form.tsx",
    ],
    component: React.lazy(
      () => import("@dotui/ui/registry/blocks/login-01/page"),
    ),
  },
  "calendar-01": {
    files: ["registry/blocks/calendar-01.tsx"],
    component: React.lazy(
      () => import("@dotui/ui/registry/blocks/calendar-01"),
    ),
  },
};
