// AUTO-GENERATED - DO NOT EDIT
// Only exports the 182 icons the registry uses (not the entire library)
export {
	PulseIcon as ActivityIcon,
	AlertIcon as AlertCircleIcon,
	AlertIcon as AlertTriangleIcon,
	BrowserIcon as AppWindowIcon,
	ArchiveIcon,
	ArrowDownIcon,
	ArrowLeftIcon as ArrowLeftCircleIcon,
	ArrowLeftIcon,
	ArrowRightIcon as ArrowRightCircleIcon,
	ArrowRightIcon,
	ArrowUpIcon,
	ArrowUpRightIcon,
	UnmuteIcon as AudioLinesIcon,
	VerifiedIcon as BadgeCheck,
	VerifiedIcon as BadgeCheckIcon,
	BellIcon,
	CreditCardIcon as BitcoinIcon,
	AppsIcon as BlocksIcon,
	BroadcastIcon as BluetoothIcon,
	BoldIcon,
	BookIcon,
	BookmarkIcon,
	BookIcon as BookOpen,
	BookIcon as BookOpenIcon,
	HubotIcon as BotIcon,
	PackageIcon as BoxesIcon,
	PackageIcon as BoxIcon,
	OrganizationIcon as Building2Icon,
	NumberIcon as CalculatorIcon,
	CalendarIcon,
	CalendarIcon as CalendarPlusIcon,
	DeviceCameraIcon as CameraIcon,
	TypographyIcon as CaptionsIcon,
	GraphBarVerticalIcon as ChartBarIcon,
	GraphIcon as ChartLineIcon,
	MeterIcon as ChartPieIcon,
	CheckCircleIcon as CheckCircle2Icon,
	CheckIcon,
	ChevronDownIcon,
	ChevronLeftIcon,
	ChevronRightIcon,
	UnfoldIcon as ChevronsUpDownIcon,
	ChevronUpIcon,
	AlertIcon as CircleAlertIcon,
	CheckCircleIcon as CircleCheckIcon,
	IssueDraftIcon as CircleDashedIcon,
	CreditCardIcon as CircleDollarSignIcon,
	IssueOpenedIcon as CircleDotIcon,
	CircleIcon,
	PasteIcon as ClipboardPasteIcon,
	ClockIcon as Clock2Icon,
	ClockIcon,
	CloudIcon as CloudCogIcon,
	CodeIcon,
	ContainerIcon,
	MoonIcon as ContrastIcon,
	CopyIcon,
	CreditCardIcon,
	DownloadIcon,
	LinkExternalIcon as ExternalLinkIcon,
	EyeIcon,
	EyeClosedIcon as EyeOffIcon,
	FileCodeIcon,
	FileIcon,
	FileIcon as FileTextIcon,
	MirrorIcon as FlipHorizontalIcon,
	MirrorIcon as FlipVerticalIcon,
	FileDirectoryIcon as FolderIcon,
	FileDirectoryIcon as FolderOpenIcon,
	FileDirectoryIcon as FolderPlusIcon,
	FileDirectoryIcon as FolderSearchIcon,
	HashIcon as FrameIcon,
	GitBranchIcon,
	GlobeIcon,
	GrabberIcon as GripVerticalIcon,
	BlockedIcon as HandIcon,
	HeartIcon,
	QuestionIcon as HelpCircleIcon,
	HomeIcon,
	ImageIcon,
	ImageIcon as ImageUpIcon,
	InboxIcon,
	InfoIcon,
	ItalicIcon,
	CommandPaletteIcon as KeyboardIcon,
	GlobeIcon as LanguagesIcon,
	StackIcon as LayersIcon,
	AppsIcon as LayoutGridIcon,
	ColumnsIcon as LayoutIcon,
	QuestionIcon as LifeBuoy,
	LightBulbIcon as LightbulbIcon,
	LinkIcon,
	FilterIcon as ListFilterIcon,
	ListUnorderedIcon as ListIcon,
	SyncIcon as Loader2Icon,
	SyncIcon as LoaderCircleIcon,
	SignInIcon as LogInIcon,
	SignOutIcon as LogOutIcon,
	ReadIcon as MailCheckIcon,
	MailIcon,
	LocationIcon as MapIcon,
	ScreenFullIcon as MaximizeIcon,
	ThreeBarsIcon as MenuIcon,
	CommentIcon as MessageSquareIcon,
	UnmuteIcon as MicIcon,
	ScreenNormalIcon as MinimizeIcon,
	DashIcon as MinusIcon,
	DeviceDesktopIcon as MonitorIcon,
	MoonIcon,
	MoonIcon as MoonStarIcon,
	KebabHorizontalIcon as MoreHorizontalIcon,
	KebabHorizontalIcon as MoreVerticalIcon,
	CursorIcon as MousePointer2Icon,
	CursorIcon as MousePointerIcon,
	StopIcon as OctagonXIcon,
	PaintbrushIcon as PaletteIcon,
	SidebarExpandIcon as PanelLeftIcon,
	PaperclipIcon,
	PencilIcon,
	PencilIcon as PenSquareIcon,
	PencilIcon as PenToolIcon,
	MeterIcon as PieChartIcon,
	PinIcon,
	PlugIcon,
	PlusCircleIcon,
	PlusIcon,
	DiffAddedIcon as PlusSquareIcon,
	BroadcastIcon as RadioIcon,
	SyncIcon as RefreshCwIcon,
	RedoIcon as RotateCwIcon,
	SpacingMediumIcon as RulerIcon,
	DownloadIcon as SaveIcon,
	UnlinkIcon as ScissorsIcon,
	SearchIcon as Search,
	SearchIcon,
	PaperAirplaneIcon as Send,
	PaperAirplaneIcon as SendIcon,
	ServerIcon,
	SlidersIcon as Settings2Icon,
	GearIcon as SettingsIcon,
	SquareCircleIcon as ShapesIcon,
	ShareIcon,
	ShieldCheckIcon,
	ShieldIcon,
	PackageIcon as ShoppingBagIcon,
	PackageIcon as ShoppingCartIcon,
	GraphBarVerticalIcon as SignalHighIcon,
	CommandPaletteIcon as SlashSquareIcon,
	SmileyIcon as SmileIcon,
	SparkleIcon as SparklesIcon,
	PencilIcon as SquarePenIcon,
	StarIcon,
	SunIcon,
	TableIcon,
	TagIcon,
	TelescopeIcon,
	TerminalIcon,
	TerminalIcon as TerminalSquareIcon,
	StopwatchIcon as TimerIcon,
	TrashIcon as Trash2Icon,
	TrashIcon,
	GraphIcon as TrendingDownIcon,
	GraphIcon as TrendingUpIcon,
	AlertIcon as TriangleAlertIcon,
	TypographyIcon as TypeIcon,
	TypographyIcon as UnderlineIcon,
	UploadIcon,
	PersonIcon as User2Icon,
	PersonIcon as UserIcon,
	PersonIcon as UserRoundXIcon,
	PeopleIcon as Users2Icon,
	UnmuteIcon as Volume1Icon,
	UnmuteIcon as Volume2Icon,
	MuteIcon as VolumeOffIcon,
	MuteIcon as VolumeX,
	CreditCardIcon as WalletIcon,
	SparkleIcon as WandIcon,
	XCircleIcon,
	XIcon,
	ZapIcon,
	ZoomInIcon,
	ZoomOutIcon,
} from "@primer/octicons-react";
