// AUTO-GENERATED - DO NOT EDIT
// Only exports the 182 icons the registry uses (not the entire library)
export {
	PulseIcon as ActivityIcon,
	WarningCircleIcon as AlertCircleIcon,
	WarningIcon as AlertTriangleIcon,
	AppWindowIcon,
	ArchiveIcon,
	ArrowDownIcon,
	ArrowCircleLeftIcon as ArrowLeftCircleIcon,
	ArrowLeftIcon,
	ArrowCircleRightIcon as ArrowRightCircleIcon,
	ArrowRightIcon,
	ArrowUpIcon,
	ArrowUpRightIcon,
	WaveformIcon as AudioLinesIcon,
	SealCheckIcon as BadgeCheck,
	SealCheckIcon as BadgeCheckIcon,
	BellIcon,
	CurrencyBtcIcon as BitcoinIcon,
	SquaresFourIcon as BlocksIcon,
	BluetoothIcon,
	TextBIcon as BoldIcon,
	BookIcon,
	BookmarkIcon,
	BookOpenIcon as BookOpen,
	BookOpenIcon,
	RobotIcon as BotIcon,
	PackageIcon as BoxesIcon,
	CubeIcon as BoxIcon,
	BuildingsIcon as Building2Icon,
	CalculatorIcon,
	CalendarIcon,
	CalendarPlusIcon,
	CameraIcon,
	ClosedCaptioningIcon as CaptionsIcon,
	ChartBarIcon,
	ChartLineIcon,
	ChartPieIcon,
	CheckCircleIcon as CheckCircle2Icon,
	CheckIcon,
	CaretDownIcon as ChevronDownIcon,
	CaretLeftIcon as ChevronLeftIcon,
	CaretRightIcon as ChevronRightIcon,
	CaretUpDownIcon as ChevronsUpDownIcon,
	CaretUpIcon as ChevronUpIcon,
	WarningCircleIcon as CircleAlertIcon,
	CheckCircleIcon as CircleCheckIcon,
	CircleDashedIcon,
	CurrencyCircleDollarIcon as CircleDollarSignIcon,
	RadioButtonIcon as CircleDotIcon,
	CircleIcon,
	ClipboardIcon as ClipboardPasteIcon,
	ClockIcon as Clock2Icon,
	ClockIcon,
	CloudIcon as CloudCogIcon,
	CodeIcon,
	CubeIcon as ContainerIcon,
	CircleHalfIcon as ContrastIcon,
	CopyIcon,
	CreditCardIcon,
	DownloadSimpleIcon as DownloadIcon,
	ArrowSquareOutIcon as ExternalLinkIcon,
	EyeIcon,
	EyeSlashIcon as EyeOffIcon,
	FileCodeIcon,
	FileIcon,
	FileTextIcon,
	FlipHorizontalIcon,
	FlipVerticalIcon,
	FolderIcon,
	FolderOpenIcon,
	FolderPlusIcon,
	FolderOpenIcon as FolderSearchIcon,
	FrameCornersIcon as FrameIcon,
	GitBranchIcon,
	GlobeIcon,
	DotsSixVerticalIcon as GripVerticalIcon,
	HandIcon,
	HeartIcon,
	QuestionIcon as HelpCircleIcon,
	HouseIcon as HomeIcon,
	ImageIcon,
	ImageIcon as ImageUpIcon,
	TrayIcon as InboxIcon,
	InfoIcon,
	TextItalicIcon as ItalicIcon,
	KeyboardIcon,
	TranslateIcon as LanguagesIcon,
	StackIcon as LayersIcon,
	SquaresFourIcon as LayoutGridIcon,
	LayoutIcon,
	LifebuoyIcon as LifeBuoy,
	LightbulbIcon,
	LinkIcon,
	FunnelIcon as ListFilterIcon,
	ListIcon,
	CircleNotchIcon as Loader2Icon,
	CircleNotchIcon as LoaderCircleIcon,
	SignInIcon as LogInIcon,
	SignOutIcon as LogOutIcon,
	EnvelopeOpenIcon as MailCheckIcon,
	EnvelopeIcon as MailIcon,
	MapTrifoldIcon as MapIcon,
	ArrowsOutSimpleIcon as MaximizeIcon,
	ListIcon as MenuIcon,
	ChatIcon as MessageSquareIcon,
	MicrophoneIcon as MicIcon,
	ArrowsInSimpleIcon as MinimizeIcon,
	MinusIcon,
	MonitorIcon,
	MoonIcon,
	MoonStarsIcon as MoonStarIcon,
	DotsThreeIcon as MoreHorizontalIcon,
	DotsThreeVerticalIcon as MoreVerticalIcon,
	CursorIcon as MousePointer2Icon,
	CursorIcon as MousePointerIcon,
	WarningOctagonIcon as OctagonXIcon,
	PaletteIcon,
	SidebarSimpleIcon as PanelLeftIcon,
	PaperclipIcon,
	PencilSimpleIcon as PencilIcon,
	NotePencilIcon as PenSquareIcon,
	PenNibIcon as PenToolIcon,
	ChartPieSliceIcon as PieChartIcon,
	PushPinIcon as PinIcon,
	PlugIcon,
	PlusCircleIcon,
	PlusIcon,
	PlusSquareIcon,
	RadioIcon,
	ArrowsClockwiseIcon as RefreshCwIcon,
	ArrowClockwiseIcon as RotateCwIcon,
	RulerIcon,
	FloppyDiskIcon as SaveIcon,
	ScissorsIcon,
	MagnifyingGlassIcon as Search,
	MagnifyingGlassIcon as SearchIcon,
	PaperPlaneTiltIcon as Send,
	PaperPlaneRightIcon as SendIcon,
	HardDrivesIcon as ServerIcon,
	SlidersHorizontalIcon as Settings2Icon,
	GearIcon as SettingsIcon,
	ShapesIcon,
	ShareIcon,
	ShieldCheckIcon,
	ShieldIcon,
	ShoppingBagIcon,
	ShoppingCartIcon,
	CellSignalHighIcon as SignalHighIcon,
	CommandIcon as SlashSquareIcon,
	SmileyIcon as SmileIcon,
	SparkleIcon as SparklesIcon,
	NotePencilIcon as SquarePenIcon,
	StarIcon,
	SunIcon,
	TableIcon,
	TagIcon,
	BinocularsIcon as TelescopeIcon,
	TerminalIcon,
	TerminalWindowIcon as TerminalSquareIcon,
	TimerIcon,
	TrashSimpleIcon as Trash2Icon,
	TrashIcon,
	TrendDownIcon as TrendingDownIcon,
	TrendUpIcon as TrendingUpIcon,
	WarningIcon as TriangleAlertIcon,
	TextTIcon as TypeIcon,
	TextUnderlineIcon as UnderlineIcon,
	UploadSimpleIcon as UploadIcon,
	UserIcon as User2Icon,
	UserIcon,
	UserMinusIcon as UserRoundXIcon,
	UsersIcon as Users2Icon,
	SpeakerLowIcon as Volume1Icon,
	SpeakerHighIcon as Volume2Icon,
	SpeakerXIcon as VolumeOffIcon,
	SpeakerXIcon as VolumeX,
	WalletIcon,
	MagicWandIcon as WandIcon,
	XCircleIcon,
	XIcon,
	LightningIcon as ZapIcon,
	MagnifyingGlassPlusIcon as ZoomInIcon,
	MagnifyingGlassMinusIcon as ZoomOutIcon,
} from "@phosphor-icons/react";
