// AUTO-GENERATED - DO NOT EDIT
// Run "tsx scripts/registry-build.ts" to regenerate

export const ExamplesIndex: Record<string, () => Promise<{ default: React.ComponentType }>> = {
	accordion: () => import("@/registry/ui/accordion/examples"),
	alert: () => import("@/registry/ui/alert/examples"),
	avatar: () => import("@/registry/ui/avatar/examples"),
	badge: () => import("@/registry/ui/badge/examples"),
	breadcrumbs: () => import("@/registry/ui/breadcrumbs/examples"),
	button: () => import("@/registry/ui/button/examples"),
	calendar: () => import("@/registry/ui/calendar/examples"),
	card: () => import("@/registry/ui/card/examples"),
	checkbox: () => import("@/registry/ui/checkbox/examples"),
	"checkbox-group": () => import("@/registry/ui/checkbox-group/examples"),
	"color-area": () => import("@/registry/ui/color-area/examples"),
	"color-editor": () => import("@/registry/ui/color-editor/examples"),
	"color-field": () => import("@/registry/ui/color-field/examples"),
	"color-picker": () => import("@/registry/ui/color-picker/examples"),
	"color-slider": () => import("@/registry/ui/color-slider/examples"),
	"color-swatch": () => import("@/registry/ui/color-swatch/examples"),
	"color-swatch-picker": () => import("@/registry/ui/color-swatch-picker/examples"),
	combobox: () => import("@/registry/ui/combobox/examples"),
	command: () => import("@/registry/ui/command/examples"),
	"context-menu": () => import("@/registry/ui/context-menu/examples"),
	"date-field": () => import("@/registry/ui/date-field/examples"),
	"date-picker": () => import("@/registry/ui/date-picker/examples"),
	dialog: () => import("@/registry/ui/dialog/examples"),
	disclosure: () => import("@/registry/ui/disclosure/examples"),
	drawer: () => import("@/registry/ui/drawer/examples"),
	"drop-zone": () => import("@/registry/ui/drop-zone/examples"),
	empty: () => import("@/registry/ui/empty/examples"),
	field: () => import("@/registry/ui/field/examples"),
	"file-trigger": () => import("@/registry/ui/file-trigger/examples"),
	form: () => import("@/registry/ui/form/examples"),
	group: () => import("@/registry/ui/group/examples"),
	input: () => import("@/registry/ui/input/examples"),
	"input-group": () => import("@/registry/ui/input-group/examples"),
	kbd: () => import("@/registry/ui/kbd/examples"),
	"list-box": () => import("@/registry/ui/list-box/examples"),
	loader: () => import("@/registry/ui/loader/examples"),
	menu: () => import("@/registry/ui/menu/examples"),
	modal: () => import("@/registry/ui/modal/examples"),
	"number-field": () => import("@/registry/ui/number-field/examples"),
	overlay: () => import("@/registry/ui/overlay/examples"),
	popover: () => import("@/registry/ui/popover/examples"),
	"progress-bar": () => import("@/registry/ui/progress-bar/examples"),
	"radio-group": () => import("@/registry/ui/radio-group/examples"),
	"react-hook-form": () => import("@/registry/ui/react-hook-form/examples"),
	"scroll-fade": () => import("@/registry/ui/scroll-fade/examples"),
	"search-field": () => import("@/registry/ui/search-field/examples"),
	select: () => import("@/registry/ui/select/examples"),
	separator: () => import("@/registry/ui/separator/examples"),
	skeleton: () => import("@/registry/ui/skeleton/examples"),
	slider: () => import("@/registry/ui/slider/examples"),
	switch: () => import("@/registry/ui/switch/examples"),
	table: () => import("@/registry/ui/table/examples"),
	tabs: () => import("@/registry/ui/tabs/examples"),
	"tag-group": () => import("@/registry/ui/tag-group/examples"),
	"text-area": () => import("@/registry/ui/text-area/examples"),
	"text-field": () => import("@/registry/ui/text-field/examples"),
	"time-field": () => import("@/registry/ui/time-field/examples"),
	toast: () => import("@/registry/ui/toast/examples"),
	"toggle-button": () => import("@/registry/ui/toggle-button/examples"),
	"toggle-button-group": () => import("@/registry/ui/toggle-button-group/examples"),
	tooltip: () => import("@/registry/ui/tooltip/examples"),
};

export const GroupExamplesIndex: Record<string, () => Promise<{ default: React.ComponentType }>> = {
	buttons: () => import("@/registry/examples/buttons"),
	calendar: () => import("@/registry/examples/calendar"),
	"color-swatches": () => import("@/registry/examples/color-swatches"),
	containers: () => import("@/registry/examples/containers"),
	disclosure: () => import("@/registry/examples/disclosure"),
	"drop-zone": () => import("@/registry/examples/drop-zone"),
	feedback: () => import("@/registry/examples/feedback"),
	inputs: () => import("@/registry/examples/inputs"),
	"menus-lists": () => import("@/registry/examples/menus-lists"),
	navigation: () => import("@/registry/examples/navigation"),
	overlays: () => import("@/registry/examples/overlays"),
	pickers: () => import("@/registry/examples/pickers"),
	progress: () => import("@/registry/examples/progress"),
	"selection-controls": () => import("@/registry/examples/selection-controls"),
	sliders: () => import("@/registry/examples/sliders"),
	tags: () => import("@/registry/examples/tags"),
	typography: () => import("@/registry/examples/typography"),
};
