// AUTO-GENERATED — do not edit. Run `pnpm build:registry`.
// Every component styles.css `:root` default, aggregated for the
// publisher's class rewriter (see resolve-classes.ts).

export const STYLE_VAR_DEFAULTS: Record<string, string> = {
	"--alert-radius": "var(--radius-surface)",
	"--avatar-radius": "calc(infinity * 1px)",
	"--badge-radius": "var(--radius-full)",
	"--btn-font-weight": "var(--font-weight-medium)",
	"--btn-radius": "var(--radius-control)",
	"--calendar-cell-radius": "var(--radius-md)",
	"--calendar-cell-size": "--spacing(8)",
	"--calendar-range-radius": "var(--radius-xs)",
	"--card-radius": "var(--radius-panel)",
	"--chat-input-radius": "var(--radius-panel)",
	"--chat-message-radius": "var(--radius-surface)",
	"--checkbox-card-radius": "var(--radius-surface)",
	"--checkbox-radius": "var(--radius-sm)",
	"--color-area-radius": "var(--radius-md)",
	"--color-swatch-picker-item-radius": "var(--radius-item)",
	"--input-radius": "var(--radius-control)",
	"--kbd-radius": "var(--radius-sm)",
	"--list-box-item-radius": "var(--radius-item)",
	"--menu-item-radius": "var(--radius-item)",
	"--modal-backdrop-blur": "var(--blur-sm)",
	"--modal-backdrop-opacity": "40%",
	"--modal-background": "var(--color-popover)",
	"--modal-radius": "var(--radius-panel)",
	"--popover-radius": "var(--radius-surface)",
	"--radio-card-radius": "var(--radius-surface)",
	"--radio-radius": "var(--radius-full)",
	"--radius-control": "var(--radius-md)",
	"--radius-item": "var(--radius-md)",
	"--radius-panel": "var(--radius-xl)",
	"--radius-surface": "var(--radius-lg)",
	"--slider-cursor": "var(--cursor-interactive)",
	"--slider-dragging-cursor": "var(--cursor-interactive)",
	"--slider-fill-color": "var(--color-primary)",
	"--slider-size": "calc(var(--spacing) * 1)",
	"--slider-thumb-radius": "var(--radius-full)",
	"--slider-thumb-shadow": "none",
	"--slider-thumb-size": "calc(var(--spacing) * 3)",
	"--slider-track-radius": "var(--radius-full)",
	"--switch-card-radius": "var(--radius-surface)",
	"--switch-radius": "var(--radius-full)",
	"--tag-radius": "var(--radius-control)",
	"--tooltip-radius": "var(--radius-item)",
	"--tree-item-radius": "var(--radius-item)",
};
