// AUTO-GENERATED — do not edit. Run `pnpm build:registry`.
// Every studio-var default (roles.css + component styles.css), aggregated
// for the publisher (see resolve-classes.ts).

export const STYLE_VAR_DEFAULTS: Record<string, string> = {
	"--studio-accordion-radius": "var(--studio-radius-panel)",
	"--studio-accordion-trigger-radius": "var(--studio-radius-item)",
	"--studio-alert-radius": "var(--studio-radius-surface)",
	"--studio-attachment-radius": "var(--studio-radius-surface)",
	"--studio-avatar-radius": "var(--radius-full)",
	"--studio-badge-radius": "var(--studio-radius-pill)",
	"--studio-btn-font-weight": "var(--font-weight-medium)",
	"--studio-btn-radius": "var(--studio-radius-control)",
	"--studio-bubble-radius": "var(--studio-radius-surface)",
	"--studio-calendar-cell-radius": "var(--radius-md)",
	"--studio-calendar-range-radius": "var(--radius-xs)",
	"--studio-card-radius": "var(--studio-radius-panel)",
	"--studio-checkbox-card-radius": "var(--studio-radius-surface)",
	"--studio-checkbox-radius": "var(--studio-radius-detail)",
	"--studio-color-area-radius": "var(--studio-radius-control)",
	"--studio-color-editor-radius": "var(--studio-radius-surface)",
	"--studio-color-slider-radius": "var(--studio-radius-control)",
	"--studio-color-swatch-picker-item-radius": "var(--studio-radius-item)",
	"--studio-color-swatch-radius": "var(--studio-radius-detail)",
	"--studio-drawer-handle-radius": "var(--studio-radius-pill)",
	"--studio-drawer-radius": "var(--studio-radius-panel)",
	"--studio-drop-zone-radius": "var(--studio-radius-control)",
	"--studio-empty-media-radius": "var(--studio-radius-control)",
	"--studio-empty-radius": "var(--studio-radius-panel)",
	"--studio-group-radius": "var(--studio-radius-control)",
	"--studio-input-radius": "var(--studio-radius-control)",
	"--studio-kbd-radius": "var(--studio-radius-detail)",
	"--studio-list-box-item-radius": "var(--studio-radius-item)",
	"--studio-menu-item-radius": "var(--studio-radius-item)",
	"--studio-modal-background": "var(--color-popover)",
	"--studio-modal-radius": "var(--studio-radius-panel)",
	"--studio-popover-radius": "var(--studio-radius-surface)",
	"--studio-progress-radius": "var(--studio-radius-pill)",
	"--studio-questionnaire-choice-radius": "var(--studio-radius-control)",
	"--studio-questionnaire-indicator-radius": "var(--studio-radius-detail)",
	"--studio-questionnaire-input-radius": "var(--studio-radius-control)",
	"--studio-radio-card-radius": "var(--studio-radius-surface)",
	"--studio-radio-radius": "var(--radius-full)",
	"--studio-radius-control": "var(--radius-md)",
	"--studio-radius-control-sm": "var(--radius-sm)",
	"--studio-radius-detail": "var(--radius-sm)",
	"--studio-radius-item": "var(--radius-md)",
	"--studio-radius-panel": "var(--radius-xl)",
	"--studio-radius-pill": "var(--radius-full)",
	"--studio-radius-surface": "var(--radius-lg)",
	"--studio-segmented-control-item-radius": "var(--studio-radius-item)",
	"--studio-segmented-control-radius": "var(--studio-radius-surface)",
	"--studio-sidebar-inset-radius": "var(--studio-radius-panel)",
	"--studio-sidebar-item-radius": "var(--studio-radius-item)",
	"--studio-sidebar-radius": "var(--studio-radius-surface)",
	"--studio-skeleton-block-radius": "var(--studio-radius-control)",
	"--studio-skeleton-radius": "var(--studio-radius-detail)",
	"--studio-slider-cursor": "var(--cursor-drag)",
	"--studio-slider-dragging-cursor": "var(--cursor-dragging)",
	"--studio-slider-fill-color": "var(--color-primary)",
	"--studio-slider-thumb-radius": "var(--studio-radius-pill)",
	"--studio-slider-thumb-shadow": "0 0 #0000",
	"--studio-slider-track-radius": "var(--studio-radius-pill)",
	"--studio-switch-card-radius": "var(--studio-radius-surface)",
	"--studio-switch-radius": "var(--radius-full)",
	"--studio-tabs-list-radius": "var(--studio-radius-surface)",
	"--studio-tabs-radius": "var(--studio-radius-surface)",
	"--studio-tabs-tab-radius": "var(--studio-radius-item)",
	"--studio-tag-radius": "var(--studio-radius-control)",
	"--studio-time-picker-item-radius": "var(--studio-radius-item)",
	"--studio-toast-action-radius": "var(--studio-radius-control)",
	"--studio-toast-radius": "var(--studio-radius-surface)",
	"--studio-tooltip-radius": "var(--studio-radius-item)",
	"--studio-tree-item-radius": "var(--studio-radius-item)",
};
