import { DEFAULT_MOTION, definePreset } from "./preset"

export const origin = definePreset({
  id: "origin",
  name: "Origin",
  description: "dotUI blue, the starting point.",
  swatch: "#0070f1",
  state: {
    // Color
    // Geist's blue, a step darker so white labels clear AA; it drives every
    // solid role, selection included.
    brand: "#0070f1",
    buttonColor: "accent",
    selectionColor: "accent",
    neutralHue: null,
    successSeed: "",
    warningSeed: "",
    dangerSeed: "",
    selectionSeed: "",
    vividness: 1,
    neutralTint: 1,
    preserveSeed: false,
    lightBg: 99,
    darkBg: 2,

    // Typography
    headingFont: "",
    bodyFont: "Geist",
    monoFont: "Geist Mono",

    // Icons
    iconLibrary: "lucide",
    iconStroke: 2,
    iconWeight: "regular",

    // Shape
    radiusPx: 10,
    roleControl: "md",
    roleItem: "auto",
    roleSurface: "lg",
    rolePanel: "xl",
    roleCard: "auto",

    // Space
    density: "default",
    spacingUnit: 4,

    // Surfaces
    surfaceLayers: "same",
    surfaceEdge: "line",
    surfaceShadow: "flat",
    surfaceGlass: false,

    // Browser
    cursorControls: "pointer",
    cursorPending: "default",
    cursorDragging: "inherit",
    cursorDisabled: "not-allowed",
    selectionUiText: "none",
    selectionHighlight: "accent",

    // States
    focusColor: "accent",
    focusStyle: "ring",
    focusWidth: 2,
    focusOffset: "gap",
    focusGap: 2,
    focusHaloStrength: 45,
    focusInputStyle: "halo",
    focusInputWidth: 2,
    focusInputStrength: 30,
    focusInputBorderWidth: 1,
    disabledTreatment: "solid",
    inputError: "border",

    // Motion
    ...DEFAULT_MOTION,

    // Mobile
    mobilePickers: "sheet",
    mobileDialogs: "center",

    // Components
    chartPalette: "mono",
    chartGrid: "solid",
    linkUnderline: "never",
    linkColor: "accent",
    skeletonAnimation: "shimmer",
    spinnerStyle: "ring",
    progressTrack: "thin",
    progressIndeterminate: "slide",
    progressGap: false,
    buttonStyle: "flat",
    buttonRadius: "auto",
    groupSeparator: "auto",
    toggleSelected: "fill",
    segmentedSelected: "flat",
    segmentedTrack: "filled",
    switchColor: "accent",
    checkboxColor: "accent",
    checkCorner: "rounded",
    radioColor: "accent",
    cardSelected: "tint",
    cardControl: "start",
    inputStyle: "outline",
    inputHover: "none",
    addonLayout: "inside",
    addonDivider: "hairline",
    numberLayout: "right",
    otpStyle: "group",
    pickerCaret: "chevron",
    calendarDayShape: "rounded",
    calendarToday: "none",
    calendarWeekdays: "single",
    sliderThumb: "circle",
    sliderTrack: "thin",
    sliderColor: "accent",
    menuIndicator: "check-end",
    menuHighlight: "neutral",
    menuInset: "inset",
    menuLabels: "sentence",
    menuSearch: "field",
    menuScale: "default",
    dialogBackdrop: "dim",
    dialogPosition: "center",
    popoverTip: "none",
    popoverHeader: "title",
    tooltipStyle: "inverted",
    tabStyle: "segmented",
    tabsColor: "neutral",
    accordionContainer: "divided",
    accordionMarker: "chevron",
    accordionMarkerPosition: "trailing",
    breadcrumbSeparator: "chevron",
    breadcrumbTone: "muted",
    paginationCurrent: "outline",
    badgeStyle: "solid",
    badgeShape: "pill",
    kbdTreatment: "chip",
    avatarShape: "circle",
    avatarFallback: "neutral",
    tableSeparation: "lines",
    tableHeader: "plain",
  },
})
