import { definePreset } from "./preset"

export const stripe = definePreset({
  id: "stripe",
  name: "Stripe",
  description: "Blurple fills, cool slate hairlines.",
  swatch: "#675dff",
  inspiredBy: "Stripe",
  state: {
    // Color
    brand: "#533afd",
    buttonColor: "accent",
    selectionColor: "accent",
    neutralHue: 260,
    successSeed: "#228403",
    warningSeed: "",
    dangerSeed: "#df1b41",
    selectionSeed: "",
    vividness: 1,
    neutralTint: 2,
    preserveSeed: false,

    // Typography
    headingFont: "",
    // Söhne is proprietary; Inter is the closest free grotesque.
    bodyFont: "Inter",
    monoFont: "Source Code Pro",

    // Icons
    iconLibrary: "lucide",
    iconStroke: 2,
    iconWeight: "regular",

    // Shape
    radiusPx: 8,
    roleControl: "lg",
    roleItem: "sm",
    roleSurface: "lg",
    rolePanel: "xl",

    // Space
    density: "default",
    spacingUnit: 4,

    // Surfaces
    surfaceStrategy: "hairline",
    surfaceDepth: "raised",
    surfaceCanvas: "same",
    surfaceMaterial: "solid",
    lightBg: 100,
    darkBg: 2,

    // Browser
    cursorControls: "pointer",
    cursorPending: "default",
    cursorDragging: "inherit",
    cursorDisabled: "not-allowed",
    selectionUiText: "none",
    selectionHighlight: "accent",
    scrollbarStyle: "native",

    // States
    focusColor: "accent",
    // Stripe's flush halo fails on blurple fills; duo keeps the ring readable.
    focusStyle: "duo",
    focusWidth: 2,
    focusOffset: "gap",
    focusGap: 2,
    focusHaloStrength: 45,
    focusInputStyle: "halo",
    focusInputWidth: 4,
    focusInputStrength: 35,
    focusInputBorderWidth: 1,
    disabledTreatment: "solid",
    inputError: "border",

    // Motion
    motionCharacter: "standard",
    motionSpeed: 1,
    motionOverlay: "scale",
    motionState: "smooth",

    // Mobile
    mobilePickers: "drawer",
    mobileDialogs: "center",

    // Components
    chartPalette: "mono",
    chartGrid: "solid",
    linkUnderline: "never",
    linkColor: "accent",
    skeletonAnimation: "shimmer",
    spinnerStyle: "ring",
    progressTrack: "thin",
    progressIndeterminate: "slide",
    progressGap: false,
    buttonStyle: "flat",
    buttonRadius: "auto",
    buttonHover: "dim",
    buttonPress: "dim",
    groupSeparator: "auto",
    toggleSelected: "fill",
    segmentedSelected: "flat",
    segmentedTrack: "filled",
    switchColor: "accent",
    checkboxColor: "accent",
    checkCorner: "rounded",
    radioColor: "accent",
    cardSelected: "tint",
    cardControl: "start",
    inputStyle: "outline",
    inputHover: "none",
    addonLayout: "inside",
    addonDivider: "hairline",
    numberLayout: "right",
    otpStyle: "group",
    pickerCaret: "double",
    calendarDayShape: "rounded",
    calendarToday: "none",
    calendarWeekdays: "single",
    sliderThumb: "circle",
    sliderTrack: "thin",
    sliderColor: "accent",
    menuIndicator: "check-end",
    menuHighlight: "neutral",
    menuInset: "inset",
    menuLabels: "sentence",
    menuSearch: "field",
    menuScale: "default",
    dialogBackdrop: "dim",
    dialogPosition: "center",
    popoverTip: "none",
    popoverHeader: "title",
    tooltipStyle: "inverted",
    tabStyle: "line",
    tabsColor: "accent",
    accordionContainer: "divided",
    accordionMarker: "chevron",
    accordionMarkerPosition: "trailing",
    breadcrumbSeparator: "chevron",
    breadcrumbTone: "muted",
    paginationCurrent: "outline",
    badgeStyle: "soft-outline",
    badgeShape: "rounded",
    kbdTreatment: "chip",
    avatarShape: "circle",
    avatarFallback: "neutral",
    tableSeparation: "lines",
    tableHeader: "plain",
  },
})
