import { definePreset } from "./preset"

export const supabase = definePreset({
  id: "supabase",
  name: "Supabase",
  description: "Emerald on neutral graphite.",
  swatch: "#34b27b",
  inspiredBy: "Supabase",
  state: {
    // Color
    brand: "#3ecf8e",
    buttonColor: "accent",
    selectionColor: "neutral",
    neutralHue: 160,
    successSeed: "",
    warningSeed: "",
    dangerSeed: "",
    selectionSeed: "",
    vividness: 1,
    neutralTint: 0.3,
    // Primary is exactly #3ecf8e, as live.
    preserveSeed: true,

    // Typography
    headingFont: "Manrope",
    bodyFont: "Inter",
    monoFont: "Source Code Pro",

    // Icons
    iconLibrary: "lucide",
    iconStroke: 2,
    iconWeight: "regular",

    // Shape
    radiusPx: 10.5,
    roleControl: "md",
    roleItem: "xs",
    roleSurface: "md",
    rolePanel: "lg",

    // Space
    density: "default",
    spacingUnit: 4,

    // Surfaces
    surfaceStrategy: "hairline",
    surfaceDepth: "subtle",
    surfaceCanvas: "same",
    surfaceMaterial: "solid",
    lightBg: 99,
    darkBg: 6,

    // Browser
    cursorControls: "pointer",
    cursorPending: "default",
    cursorDragging: "inherit",
    cursorDisabled: "not-allowed",
    selectionUiText: "none",
    selectionHighlight: "accent",
    scrollbarStyle: "native",

    // States
    focusColor: "accent",
    // A halo of the bright seed is ~1.4:1 on white.
    focusStyle: "ring",
    focusWidth: 2,
    focusOffset: "gap",
    focusGap: 2,
    focusHaloStrength: 45,
    focusInputStyle: "ring",
    focusInputWidth: 2,
    focusInputStrength: 30,
    focusInputBorderWidth: 1,
    disabledTreatment: "fade",
    inputError: "border",

    // Motion
    motionCharacter: "standard",
    motionSpeed: 1,
    motionOverlay: "scale",
    motionState: "smooth",

    // Mobile
    mobilePickers: "drawer",
    mobileDialogs: "center",

    // Components
    chartPalette: "mono",
    chartGrid: "solid",
    linkUnderline: "always",
    linkColor: "neutral",
    skeletonAnimation: "pulse",
    spinnerStyle: "ring",
    progressTrack: "thin",
    progressIndeterminate: "slide",
    progressGap: false,
    buttonStyle: "outline",
    buttonRadius: "auto",
    buttonHover: "dim",
    buttonPress: "scale",
    groupSeparator: "auto",
    toggleSelected: "fill",
    segmentedSelected: "flat",
    segmentedTrack: "filled",
    switchColor: "accent",
    checkboxColor: "neutral",
    checkCorner: "rounded",
    radioColor: "accent",
    cardSelected: "tint",
    cardControl: "start",
    inputStyle: "outline",
    inputHover: "border",
    addonLayout: "inside",
    addonDivider: "hairline",
    numberLayout: "right",
    otpStyle: "group",
    pickerCaret: "chevron",
    calendarDayShape: "rounded",
    calendarToday: "none",
    calendarWeekdays: "single",
    sliderThumb: "circle",
    sliderTrack: "thin",
    sliderColor: "neutral",
    menuIndicator: "check-start",
    menuHighlight: "neutral",
    menuInset: "inset",
    menuLabels: "caps",
    menuSearch: "bar",
    menuScale: "large",
    dialogBackdrop: "blur",
    dialogPosition: "center",
    popoverTip: "none",
    popoverHeader: "title",
    tooltipStyle: "surface",
    tabStyle: "line",
    tabsColor: "neutral",
    accordionContainer: "divided",
    accordionMarker: "chevron",
    accordionMarkerPosition: "trailing",
    breadcrumbSeparator: "chevron",
    breadcrumbTone: "muted",
    paginationCurrent: "outline",
    badgeStyle: "soft-outline",
    badgeShape: "pill",
    kbdTreatment: "chip",
    avatarShape: "circle",
    avatarFallback: "neutral",
    tableSeparation: "lines",
    tableHeader: "filled",
  },
})
