// AUTO-GENERATED - DO NOT EDIT
// Run "tsx scripts/registry-build.ts" to regenerate
import type { PresetSummary } from "../catalog";

export const PRESET_CATALOG: PresetSummary[] = [
	{
		id: "origin",
		name: "Origin",
		description: "dotUI blue, the starting point.",
		swatch: "#0072f5",
		rev: 1,
		designSystem: {
			componentParams: {
				accordion: { container: "divided", marker: "chevron", markerPosition: "trailing" },
				avatar: { fallback: "neutral" },
				badge: { style: "solid" },
				breadcrumbs: { separator: "chevron", tone: "muted" },
				button: { style: "flat", hover: "dim", press: "dim" },
				calendar: { dayShape: "rounded", today: "none", weekdays: "single" },
				card: { style: "default" },
				chart: { grid: "solid" },
				checkbox: { "card-selected": "tint", "card-control": "start" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { header: "title" },
				drawer: { backdrop: "dim" },
				field: { error: "border" },
				group: { separator: "auto" },
				input: { style: "outline", hover: "none", addon: "inside" },
				kbd: { treatment: "chip" },
				link: { underline: "never", color: "accent" },
				"list-box": { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				modal: { backdrop: "dim", position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right" },
				"otp-field": { cells: "group" },
				pagination: { current: "outline" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", indeterminate: "slide", gap: "none" },
				"qr-code": { style: "squares" },
				"radio-group": { "card-selected": "tint", "card-control": "start" },
				"segmented-control": { selected: "flat", track: "filled" },
				select: { caret: "chevron" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "circle", track: "thin" },
				switch: { "card-selected": "tint" },
				table: { separation: "lines", header: "plain" },
				tabs: { style: "segmented", color: "neutral" },
				"tag-group": { style: "solid" },
				"toggle-button": { style: "flat", hover: "dim", press: "dim", selected: "fill" },
				"toggle-button-group": { separator: "auto" },
				tooltip: { style: "inverted", motion: "scale" },
			},
			tokens: {},
			density: "default",
		},
	},
	{
		id: "claude",
		name: "Claude",
		description: "Warm coral on sand.",
		swatch: "#e0916f",
		inspiredBy: "Claude",
		rev: 1,
		designSystem: {
			componentParams: {
				accordion: { container: "divided", marker: "chevron", markerPosition: "trailing" },
				avatar: { fallback: "neutral" },
				badge: { style: "solid" },
				breadcrumbs: { separator: "chevron", tone: "muted" },
				button: { style: "flat", hover: "dim", press: "dim" },
				calendar: { dayShape: "rounded", today: "none", weekdays: "single" },
				card: { style: "default" },
				chart: { grid: "solid" },
				checkbox: { "card-selected": "tint", "card-control": "start" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { header: "title" },
				drawer: { backdrop: "dim" },
				field: { error: "border" },
				group: { separator: "auto" },
				input: { style: "outline", hover: "none", addon: "inside" },
				kbd: { treatment: "chip" },
				link: { underline: "never", color: "accent" },
				"list-box": { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				modal: { backdrop: "dim", position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right" },
				"otp-field": { cells: "group" },
				pagination: { current: "outline" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", indeterminate: "slide", gap: "none" },
				"qr-code": { style: "squares" },
				"radio-group": { "card-selected": "tint", "card-control": "start" },
				"segmented-control": { selected: "flat", track: "filled" },
				select: { caret: "chevron" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "circle", track: "thin" },
				switch: { "card-selected": "tint" },
				table: { separation: "lines", header: "plain" },
				tabs: { style: "segmented", color: "neutral" },
				"tag-group": { style: "solid" },
				"toggle-button": { style: "flat", hover: "dim", press: "dim", selected: "fill" },
				"toggle-button-group": { separator: "auto" },
				tooltip: { style: "inverted", motion: "scale" },
			},
			tokens: {
				"--font-sans": "'Inter', ui-sans-serif, system-ui, sans-serif",
				"--font-heading": "'Source Serif 4', ui-serif, Georgia, serif",
				"--radius": "0.75rem",
			},
			density: "default",
			color: {
				v: 2,
				seeds: { accent: "#d97757" },
				background: { light: 98, dark: 2 },
				neutralHue: 96,
				primary: "accent",
			},
		},
	},
	{
		id: "supabase",
		name: "Supabase",
		description: "Emerald on cool gray.",
		swatch: "#3ecf8e",
		inspiredBy: "Supabase",
		rev: 1,
		designSystem: {
			componentParams: {
				accordion: { container: "divided", marker: "chevron", markerPosition: "trailing" },
				avatar: { fallback: "neutral" },
				badge: { style: "solid" },
				breadcrumbs: { separator: "chevron", tone: "muted" },
				button: { style: "flat", hover: "dim", press: "dim" },
				calendar: { dayShape: "rounded", today: "none", weekdays: "single" },
				card: { style: "default" },
				chart: { grid: "solid" },
				checkbox: { "card-selected": "tint", "card-control": "start" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { header: "title" },
				drawer: { backdrop: "dim" },
				field: { error: "border" },
				group: { separator: "auto" },
				input: { style: "outline", hover: "none", addon: "inside" },
				kbd: { treatment: "chip" },
				link: { underline: "never", color: "accent" },
				"list-box": { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				modal: { backdrop: "dim", position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right" },
				"otp-field": { cells: "group" },
				pagination: { current: "outline" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", indeterminate: "slide", gap: "none" },
				"qr-code": { style: "squares" },
				"radio-group": { "card-selected": "tint", "card-control": "start" },
				"segmented-control": { selected: "flat", track: "filled" },
				select: { caret: "chevron" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "circle", track: "thin" },
				switch: { "card-selected": "tint" },
				table: { separation: "lines", header: "plain" },
				tabs: { style: "segmented", color: "neutral" },
				"tag-group": { style: "solid" },
				"toggle-button": { style: "flat", hover: "dim", press: "dim", selected: "fill" },
				"toggle-button-group": { separator: "auto" },
				tooltip: { style: "inverted", motion: "scale" },
			},
			tokens: { "--font-sans": "'Inter', ui-sans-serif, system-ui, sans-serif" },
			density: "default",
			color: { v: 2, seeds: { accent: "#3ecf8e" }, background: { dark: 2 }, neutralHue: 160, primary: "accent" },
		},
	},
	{
		id: "stripe",
		name: "Stripe",
		description: "Blurple on cool slate.",
		swatch: "#7a73ff",
		inspiredBy: "Stripe",
		rev: 1,
		designSystem: {
			componentParams: {
				accordion: { container: "divided", marker: "chevron", markerPosition: "trailing" },
				avatar: { fallback: "neutral" },
				badge: { style: "solid" },
				breadcrumbs: { separator: "chevron", tone: "muted" },
				button: { style: "outline", hover: "dim", press: "dim" },
				calendar: { dayShape: "rounded", today: "none", weekdays: "single" },
				card: { style: "default" },
				chart: { grid: "solid" },
				checkbox: { "card-selected": "tint", "card-control": "start" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { header: "title" },
				drawer: { backdrop: "dim" },
				field: { error: "border" },
				group: { separator: "auto" },
				input: { style: "outline", hover: "none", addon: "inside" },
				kbd: { treatment: "chip" },
				link: { underline: "never", color: "accent" },
				"list-box": { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				modal: { backdrop: "dim", position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right" },
				"otp-field": { cells: "group" },
				pagination: { current: "outline" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", indeterminate: "slide", gap: "none" },
				"qr-code": { style: "squares" },
				"radio-group": { "card-selected": "tint", "card-control": "start" },
				"segmented-control": { selected: "flat", track: "filled" },
				select: { caret: "chevron" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "circle", track: "thin" },
				switch: { "card-selected": "tint" },
				table: { separation: "lines", header: "plain" },
				tabs: { style: "segmented", color: "neutral" },
				"tag-group": { style: "solid" },
				"toggle-button": { style: "outline", hover: "dim", press: "dim", selected: "fill" },
				"toggle-button-group": { separator: "auto" },
				tooltip: { style: "inverted", motion: "scale" },
			},
			tokens: { "--font-sans": "'Inter', ui-sans-serif, system-ui, sans-serif", "--radius": "0.665rem" },
			density: "default",
			color: { v: 2, seeds: { accent: "#635bff" }, background: { dark: 2 }, neutralHue: 260, primary: "accent" },
		},
	},
	{
		id: "linear",
		name: "Linear",
		description: "Indigo, crisp hairlines.",
		swatch: "#818cf8",
		inspiredBy: "Linear",
		rev: 1,
		designSystem: {
			componentParams: {
				accordion: { container: "divided", marker: "chevron", markerPosition: "trailing" },
				avatar: { fallback: "neutral" },
				badge: { style: "solid" },
				breadcrumbs: { separator: "chevron", tone: "muted" },
				button: { style: "flat", hover: "lighten", press: "dim" },
				calendar: { dayShape: "rounded", today: "none", weekdays: "single" },
				card: { style: "default" },
				chart: { grid: "solid" },
				checkbox: { "card-selected": "tint", "card-control": "start" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { header: "title" },
				drawer: { backdrop: "dim" },
				field: { error: "border" },
				group: { separator: "auto" },
				input: { style: "outline", hover: "none", addon: "inside" },
				kbd: { treatment: "chip" },
				link: { underline: "never", color: "accent" },
				"list-box": { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				modal: { backdrop: "dim", position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right" },
				"otp-field": { cells: "group" },
				pagination: { current: "outline" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", indeterminate: "slide", gap: "none" },
				"qr-code": { style: "squares" },
				"radio-group": { "card-selected": "tint", "card-control": "start" },
				"segmented-control": { selected: "flat", track: "filled" },
				select: { caret: "chevron" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "circle", track: "thin" },
				switch: { "card-selected": "tint" },
				table: { separation: "lines", header: "plain" },
				tabs: { style: "segmented", color: "neutral" },
				"tag-group": { style: "solid" },
				"toggle-button": { style: "flat", hover: "lighten", press: "dim", selected: "fill" },
				"toggle-button-group": { separator: "auto" },
				tooltip: { style: "inverted", motion: "scale" },
			},
			tokens: {
				"--font-sans": "'Inter', ui-sans-serif, system-ui, sans-serif",
				"--card-border": "light-dark(var(--neutral-300), var(--neutral-200))",
				"--overlay-border": "light-dark(var(--neutral-300), var(--neutral-200))",
				"--shadow-card": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
				"--shadow-popover": "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
				"--shadow-modal": "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
				"--color-popover": "light-dark(var(--neutral-50), var(--neutral-100))",
			},
			density: "default",
			color: { v: 2, seeds: { accent: "#5e6ad2" }, background: { dark: 2 }, neutralHue: 262, primary: "accent" },
		},
	},
	{
		id: "vercel",
		name: "Vercel",
		description: "Monochrome, hairline borders.",
		swatch: "#cbd5e1",
		inspiredBy: "Vercel",
		rev: 1,
		designSystem: {
			componentParams: {
				accordion: { container: "divided", marker: "chevron", markerPosition: "trailing" },
				avatar: { fallback: "neutral" },
				badge: { style: "solid" },
				breadcrumbs: { separator: "chevron", tone: "muted" },
				button: { style: "flat", hover: "dim", press: "dim" },
				calendar: { dayShape: "rounded", today: "none", weekdays: "single" },
				card: { style: "default" },
				chart: { grid: "solid" },
				checkbox: { "card-selected": "tint", "card-control": "start" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { header: "title" },
				drawer: { backdrop: "dim" },
				field: { error: "border" },
				group: { separator: "auto" },
				input: { style: "outline", hover: "none", addon: "inside" },
				kbd: { treatment: "chip" },
				link: { underline: "never", color: "accent" },
				"list-box": { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				modal: { backdrop: "dim", position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right" },
				"otp-field": { cells: "group" },
				pagination: { current: "outline" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", indeterminate: "slide", gap: "none" },
				"qr-code": { style: "squares" },
				"radio-group": { "card-selected": "tint", "card-control": "start" },
				"segmented-control": { selected: "flat", track: "filled" },
				select: { caret: "chevron" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "circle", track: "thin" },
				switch: { "card-selected": "tint" },
				table: { separation: "lines", header: "plain" },
				tabs: { style: "segmented", color: "neutral" },
				"tag-group": { style: "solid" },
				"toggle-button": { style: "flat", hover: "dim", press: "dim", selected: "fill" },
				"toggle-button-group": { separator: "auto" },
				tooltip: { style: "inverted", motion: "scale" },
			},
			tokens: {
				"--color-bg": "light-dark(color-mix(in oklab, var(--neutral-50) 50%, var(--neutral-100)), var(--neutral-25))",
				"--color-card": "light-dark(var(--neutral-25), var(--neutral-100))",
				"--color-popover": "light-dark(var(--neutral-25), var(--neutral-100))",
			},
			density: "default",
			color: { v: 2, seeds: { accent: "#171717", selection: "#0072f5" }, background: { dark: "oled" }, neutralTint: 0 },
		},
	},
	{
		id: "airbnb",
		name: "Airbnb",
		description: "Rausch accents, ink actions.",
		swatch: "#ff5c7c",
		inspiredBy: "Airbnb",
		rev: 1,
		designSystem: {
			componentParams: {
				accordion: { container: "divided", marker: "chevron", markerPosition: "trailing" },
				avatar: { fallback: "neutral" },
				badge: { style: "solid" },
				breadcrumbs: { separator: "chevron", tone: "muted" },
				button: { style: "flat", hover: "dim", press: "dim" },
				calendar: { dayShape: "rounded", today: "none", weekdays: "single" },
				card: { style: "default" },
				chart: { grid: "solid" },
				checkbox: { "card-selected": "tint", "card-control": "start" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { header: "title" },
				drawer: { backdrop: "dim" },
				field: { error: "border" },
				group: { separator: "auto" },
				input: { style: "outline", hover: "none", addon: "inside" },
				kbd: { treatment: "chip" },
				link: { underline: "never", color: "accent" },
				"list-box": { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				modal: { backdrop: "dim", position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right" },
				"otp-field": { cells: "group" },
				pagination: { current: "outline" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", indeterminate: "slide", gap: "none" },
				"qr-code": { style: "squares" },
				"radio-group": { "card-selected": "tint", "card-control": "start" },
				"segmented-control": { selected: "flat", track: "filled" },
				select: { caret: "chevron" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "circle", track: "thin" },
				switch: { "card-selected": "tint" },
				table: { separation: "lines", header: "plain" },
				tabs: { style: "segmented", color: "neutral" },
				"tag-group": { style: "solid" },
				"toggle-button": { style: "flat", hover: "dim", press: "dim", selected: "fill" },
				"toggle-button-group": { separator: "auto" },
				tooltip: { style: "inverted", motion: "scale" },
			},
			tokens: { "--font-sans": "'Plus Jakarta Sans', ui-sans-serif, system-ui, sans-serif", "--radius": "0.665rem" },
			density: "comfortable",
			color: { v: 2, seeds: { accent: "#ff385c" }, background: { dark: 2 }, neutralTint: 0 },
		},
	},
	{
		id: "github",
		name: "GitHub",
		description: "Primer blue, sober gray.",
		swatch: "#54aeff",
		inspiredBy: "GitHub",
		rev: 1,
		designSystem: {
			componentParams: {
				accordion: { container: "divided", marker: "chevron", markerPosition: "trailing" },
				avatar: { fallback: "neutral" },
				badge: { style: "solid" },
				breadcrumbs: { separator: "chevron", tone: "muted" },
				button: { style: "flat", hover: "dim", press: "dim" },
				calendar: { dayShape: "rounded", today: "none", weekdays: "single" },
				card: { style: "default" },
				chart: { grid: "solid" },
				checkbox: { "card-selected": "tint", "card-control": "start" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { header: "title" },
				drawer: { backdrop: "dim" },
				field: { error: "border" },
				group: { separator: "auto" },
				input: { style: "outline", hover: "none", addon: "inside" },
				kbd: { treatment: "chip" },
				link: { underline: "never", color: "accent" },
				"list-box": { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				modal: { backdrop: "dim", position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right" },
				"otp-field": { cells: "group" },
				pagination: { current: "outline" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", indeterminate: "slide", gap: "none" },
				"qr-code": { style: "squares" },
				"radio-group": { "card-selected": "tint", "card-control": "start" },
				"segmented-control": { selected: "flat", track: "filled" },
				select: { caret: "chevron" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "circle", track: "thin" },
				switch: { "card-selected": "tint" },
				table: { separation: "lines", header: "plain" },
				tabs: { style: "segmented", color: "neutral" },
				"tag-group": { style: "solid" },
				"toggle-button": { style: "flat", hover: "dim", press: "dim", selected: "fill" },
				"toggle-button-group": { separator: "auto" },
				tooltip: { style: "inverted", motion: "scale" },
			},
			tokens: { "--font-sans": "'Mona Sans', ui-sans-serif, system-ui, sans-serif" },
			density: "default",
			color: { v: 2, seeds: { accent: "#0969da" }, background: { dark: 4.5 }, neutralHue: 251, primary: "accent" },
		},
	},
	{
		id: "notion",
		name: "Notion",
		description: "Warm ink, quiet blue.",
		swatch: "#d4cec2",
		inspiredBy: "Notion",
		rev: 1,
		designSystem: {
			componentParams: {
				accordion: { container: "divided", marker: "chevron", markerPosition: "trailing" },
				avatar: { fallback: "neutral" },
				badge: { style: "solid" },
				breadcrumbs: { separator: "chevron", tone: "muted" },
				button: { style: "flat", hover: "dim", press: "dim" },
				calendar: { dayShape: "rounded", today: "none", weekdays: "single" },
				card: { style: "default" },
				chart: { grid: "solid" },
				checkbox: { "card-selected": "tint", "card-control": "start" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { header: "title" },
				drawer: { backdrop: "dim" },
				field: { error: "border" },
				group: { separator: "auto" },
				input: { style: "outline", hover: "none", addon: "inside" },
				kbd: { treatment: "chip" },
				link: { underline: "never", color: "accent" },
				"list-box": { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				modal: { backdrop: "dim", position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right" },
				"otp-field": { cells: "group" },
				pagination: { current: "outline" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", indeterminate: "slide", gap: "none" },
				"qr-code": { style: "squares" },
				"radio-group": { "card-selected": "tint", "card-control": "start" },
				"segmented-control": { selected: "flat", track: "filled" },
				select: { caret: "chevron" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "circle", track: "thin" },
				switch: { "card-selected": "tint" },
				table: { separation: "lines", header: "plain" },
				tabs: { style: "segmented", color: "neutral" },
				"tag-group": { style: "solid" },
				"toggle-button": { style: "flat", hover: "dim", press: "dim", selected: "fill" },
				"toggle-button-group": { separator: "auto" },
				tooltip: { style: "inverted", motion: "scale" },
			},
			tokens: { "--font-sans": "'Inter', ui-sans-serif, system-ui, sans-serif", "--radius": "0.375rem" },
			density: "default",
			color: { v: 2, seeds: { accent: "#0075de" }, background: { dark: 2 }, neutralHue: 91, primary: "accent" },
		},
	},
	{
		id: "spotify",
		name: "Spotify",
		description: "Vivid green, pill-shaped.",
		swatch: "#1ed760",
		inspiredBy: "Spotify",
		rev: 1,
		designSystem: {
			componentParams: {
				accordion: { container: "divided", marker: "chevron", markerPosition: "trailing" },
				avatar: { fallback: "neutral" },
				badge: { style: "solid" },
				breadcrumbs: { separator: "chevron", tone: "muted" },
				button: { style: "flat", hover: "dim", press: "dim" },
				calendar: { dayShape: "rounded", today: "none", weekdays: "single" },
				card: { style: "default" },
				chart: { grid: "solid" },
				checkbox: { "card-selected": "tint", "card-control": "start" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { header: "title" },
				drawer: { backdrop: "dim" },
				field: { error: "border" },
				group: { separator: "auto" },
				input: { style: "filled", hover: "none", addon: "inside" },
				kbd: { treatment: "chip" },
				link: { underline: "never", color: "accent" },
				"list-box": { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				modal: { backdrop: "dim", position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right" },
				"otp-field": { cells: "group" },
				pagination: { current: "outline" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", indeterminate: "slide", gap: "none" },
				"qr-code": { style: "squares" },
				"radio-group": { "card-selected": "tint", "card-control": "start" },
				"segmented-control": { selected: "flat", track: "filled" },
				select: { caret: "chevron" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "circle", track: "thin" },
				switch: { "card-selected": "tint" },
				table: { separation: "lines", header: "plain" },
				tabs: { style: "segmented", color: "neutral" },
				"tag-group": { style: "solid" },
				"toggle-button": { style: "flat", hover: "dim", press: "dim", selected: "fill" },
				"toggle-button-group": { separator: "auto" },
				tooltip: { style: "inverted", motion: "scale" },
			},
			tokens: {
				"--font-sans": "'Figtree', ui-sans-serif, system-ui, sans-serif",
				"--radius": "1rem",
				"--studio-btn-radius": "var(--radius-full)",
			},
			density: "default",
			color: { v: 2, seeds: { accent: "#1ed760" }, background: { dark: 2 }, neutralTint: 0, primary: "accent" },
		},
	},
];
