// AUTO-GENERATED - DO NOT EDIT
// Run "tsx scripts/registry-build.ts" to regenerate
import type { PresetMeta } from "../preset";
import type { DesignSystem } from "@/modules/studio/preset/types";

export const PRESET_CATALOG: Array<PresetMeta & { designSystem: DesignSystem }> = [
	{
		id: "origin",
		name: "Origin",
		description: "dotUI blue, the starting point.",
		swatch: "#0070f1",
		designSystem: {
			componentParams: {
				accordion: { motion: "expand", layout: "divided", marker: "trailing-chevron" },
				alert: { style: "neutral" },
				avatar: { shape: "circle", fallback: "neutral" },
				badge: { style: "solid", case: "sentence" },
				breadcrumbs: { separator: "chevron", ancestors: "muted" },
				button: {
					style: "flat",
					secondary: "flat",
					press: "as-style",
					case: "sentence",
					current: "none",
					linkUnderline: "never",
					linkColor: "accent",
				},
				calendar: { dayShape: "same", today: "fill", weekdays: "single" },
				card: { footer: "none", titles: "quiet" },
				chart: { grid: "solid", motion: "spring" },
				checkbox: { "card-selected": "tint" },
				collapsible: { motion: "expand" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { sections: "open", footer: "end", close: "quiet", titles: "quiet" },
				drawer: { edge: "docked" },
				empty: { titles: "quiet" },
				field: { error: "plain", label: "regular" },
				group: { segments: "attached", separator: "shared-edge" },
				input: { style: "outline", hover: "none", height: "controls", errorIcon: "none" },
				kbd: { style: "chip" },
				link: { underline: "never", color: "accent" },
				"list-box": {
					indicator: "check-end",
					highlight: "neutral",
					inset: "inset",
					selected: "none",
					labels: "sentence",
				},
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", selected: "none", labels: "sentence" },
				modal: { position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right-cells" },
				"otp-field": { cells: "attached" },
				pagination: { current: "secondary" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", trackStyle: "plain" },
				"qr-code": { style: "squares" },
				questionnaire: { titles: "quiet" },
				"radio-group": { mark: "dot", "card-selected": "tint" },
				"segmented-control": { selected: "tone", track: "filled", weight: "medium" },
				select: { trigger: "button", caret: "chevron" },
				sidebar: { labels: "sentence", shell: "subtle", marker: "fill", weight: "regular-medium" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "knob", track: "thin" },
				switch: { style: "inset", "card-selected": "tint" },
				table: { header: "plain", headerLabel: "muted" },
				tabs: { style: "segmented", color: "neutral", chip: "tone", track: "filled", pill: "tone", weight: "medium" },
				"tag-group": { style: "solid" },
				toast: { motion: "slide", surface: "surface", status: "icon" },
				"toggle-button": {
					style: "flat",
					secondary: "flat",
					press: "as-style",
					case: "sentence",
					selected: "tone",
					linkUnderline: "never",
					linkColor: "accent",
				},
				"toggle-button-group": { segments: "attached", separator: "shared-edge" },
				tooltip: { style: "inverted", tip: "tip", motion: "scale" },
			},
			tokens: {},
			density: "default",
			color: { v: 2, seeds: { accent: "#0070f1" }, background: { dark: 2 }, primary: "accent" },
		},
	},
	{
		id: "claude",
		name: "Claude",
		description: "Ink actions, clay highlights.",
		swatch: "#d97757",
		inspiredBy: "Claude",
		designSystem: {
			componentParams: {
				accordion: { motion: "expand", layout: "divided", marker: "trailing-chevron" },
				alert: { style: "neutral" },
				avatar: { shape: "circle", fallback: "neutral" },
				badge: { style: "soft", case: "sentence" },
				breadcrumbs: { separator: "chevron", ancestors: "muted" },
				button: {
					style: "flat",
					secondary: "flat",
					press: "as-style",
					case: "sentence",
					current: "none",
					linkUnderline: "always",
					linkColor: "neutral",
				},
				calendar: { dayShape: "same", today: "fill", weekdays: "single" },
				card: { footer: "none", titles: "quiet" },
				chart: { grid: "solid", motion: "spring" },
				checkbox: { "card-selected": "tint" },
				collapsible: { motion: "expand" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { sections: "open", footer: "end", close: "quiet", titles: "quiet" },
				drawer: { edge: "docked" },
				empty: { titles: "quiet" },
				field: { error: "plain", label: "regular" },
				group: { segments: "attached", separator: "shared-edge" },
				input: { style: "outline", hover: "none", height: "controls", errorIcon: "none" },
				kbd: { style: "chip" },
				link: { underline: "always", color: "neutral" },
				"list-box": {
					indicator: "check-end",
					highlight: "neutral",
					inset: "inset",
					selected: "none",
					labels: "sentence",
				},
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", selected: "none", labels: "sentence" },
				modal: { position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right-cells" },
				"otp-field": { cells: "attached" },
				pagination: { current: "secondary" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", trackStyle: "plain" },
				"qr-code": { style: "squares" },
				questionnaire: { titles: "quiet" },
				"radio-group": { mark: "dot", "card-selected": "tint" },
				"segmented-control": { selected: "tone", track: "filled", weight: "medium" },
				select: { trigger: "button", caret: "chevron" },
				sidebar: { labels: "sentence", shell: "subtle", marker: "fill-accent", weight: "regular-medium" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "knob", track: "thin" },
				switch: { style: "inset", "card-selected": "tint" },
				table: { header: "plain", headerLabel: "muted" },
				tabs: { style: "line", color: "accent", chip: "tone", track: "filled", pill: "tone", weight: "medium" },
				"tag-group": { style: "soft" },
				toast: { motion: "slide", surface: "surface", status: "icon" },
				"toggle-button": {
					style: "flat",
					secondary: "flat",
					press: "as-style",
					case: "sentence",
					selected: "tone",
					linkUnderline: "always",
					linkColor: "neutral",
				},
				"toggle-button-group": { segments: "attached", separator: "shared-edge" },
				tooltip: { style: "inverted", tip: "tip", motion: "scale" },
			},
			tokens: {
				"--font-sans": "'Inter', ui-sans-serif, system-ui, sans-serif",
				"--font-heading": "'Source Serif 4', ui-serif, Georgia, serif",
				"--radius": "0.666875rem",
				"--studio-radius-card": "var(--radius-xl)",
				"--shadow-card": "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
				"--focus-ring-width": "1px",
				"--focus-ring-inset": "inset",
				"--focus-ring-offset": "0px",
				"--focus-ring-inner": "calc(var(--focus-ring-width) + 1px)",
				"--focus-input-width": "var(--focus-ring-width)",
				"--focus-input-offset": "var(--focus-ring-offset)",
				"--focus-input-color": "var(--focus-ring-color)",
				"--focus-input-inset": "inset",
			},
			density: "default",
			color: {
				v: 2,
				seeds: { accent: "#d97757", warning: "#fab219", danger: "#d03b3b", selection: "#2a78d6" },
				background: { dark: 7 },
				neutralHue: 96,
				scopes: { slider: "neutral" },
			},
			icons: "phosphor",
		},
	},
	{
		id: "supabase",
		name: "Supabase",
		description: "Emerald on neutral graphite.",
		swatch: "#34b27b",
		inspiredBy: "Supabase",
		designSystem: {
			componentParams: {
				accordion: { motion: "expand", layout: "divided", marker: "trailing-chevron" },
				alert: { style: "neutral" },
				avatar: { shape: "circle", fallback: "neutral" },
				badge: { style: "soft-outline", case: "sentence" },
				breadcrumbs: { separator: "chevron", ancestors: "muted" },
				button: {
					style: "hairline",
					secondary: "hairline",
					press: "as-style",
					case: "sentence",
					current: "none",
					linkUnderline: "always",
					linkColor: "neutral",
				},
				calendar: { dayShape: "same", today: "fill", weekdays: "single" },
				card: { footer: "none", titles: "quiet" },
				chart: { grid: "solid", motion: "spring" },
				checkbox: { "card-selected": "tint" },
				collapsible: { motion: "expand" },
				"color-editor": { style: "default" },
				command: { search: "bar", inset: "inset", scale: "large" },
				dialog: { sections: "open", footer: "end", close: "quiet", titles: "quiet" },
				drawer: { edge: "docked" },
				empty: { titles: "quiet" },
				field: { error: "plain", label: "regular" },
				group: { segments: "attached", separator: "shared-edge" },
				input: { style: "inset", hover: "edge", height: "controls", errorIcon: "none" },
				kbd: { style: "chip" },
				link: { underline: "always", color: "neutral" },
				"list-box": {
					indicator: "check-start",
					highlight: "neutral",
					inset: "inset",
					selected: "none",
					labels: "caps",
				},
				loader: { style: "ring" },
				menu: { indicator: "check-start", highlight: "neutral", inset: "inset", selected: "none", labels: "caps" },
				modal: { position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right-cells" },
				"otp-field": { cells: "attached" },
				pagination: { current: "secondary" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", trackStyle: "plain" },
				"qr-code": { style: "squares" },
				questionnaire: { titles: "quiet" },
				"radio-group": { mark: "dot", "card-selected": "tint" },
				"segmented-control": { selected: "tone", track: "filled", weight: "medium" },
				select: { trigger: "button", caret: "chevron" },
				sidebar: { labels: "caps", shell: "subtle", marker: "fill", weight: "regular-medium" },
				skeleton: { animation: "pulse" },
				slider: { thumb: "knob", track: "thin" },
				switch: { style: "inset", "card-selected": "tint" },
				table: { header: "filled", headerLabel: "muted" },
				tabs: { style: "line", color: "neutral", chip: "tone", track: "filled", pill: "tone", weight: "medium" },
				"tag-group": { style: "soft-outline" },
				toast: { motion: "slide", surface: "surface", status: "icon" },
				"toggle-button": {
					style: "hairline",
					secondary: "hairline",
					press: "as-style",
					case: "sentence",
					selected: "tone",
					linkUnderline: "always",
					linkColor: "neutral",
				},
				"toggle-button-group": { segments: "attached", separator: "shared-edge" },
				tooltip: { style: "surface", tip: "tip", motion: "scale" },
			},
			tokens: {
				"--font-sans": "'Inter', ui-sans-serif, system-ui, sans-serif",
				"--font-heading": "'Manrope', ui-sans-serif, system-ui, sans-serif",
				"--font-mono": "'Source Code Pro', ui-monospace, 'SF Mono', monospace",
				"--radius": "0.65625rem",
				"--studio-radius-panel": "var(--radius-lg)",
				"--studio-radius-surface": "var(--radius-md)",
				"--studio-radius-item": "var(--radius-xs)",
				"--studio-radius-inline-item": "var(--radius-sm)",
				"--focus-input-width": "var(--focus-ring-width)",
				"--focus-input-offset": "var(--focus-ring-offset)",
				"--focus-input-color": "var(--focus-ring-color)",
				"--disabled-bg": "initial",
				"--disabled-fg": "initial",
				"--disabled-border": "initial",
				"--disabled-selected-bg": "initial",
				"--disabled-selected-fg": "initial",
				"--disabled-unselected-bg": "initial",
				"--color-primary-disabled": "initial",
				"--disabled-opacity": "0.5",
				"--color-scrim": "color-mix(in oklab, var(--color-overlay) 10%, transparent)",
			},
			density: "default",
			color: {
				v: 2,
				seeds: { accent: "#3ecf8e" },
				background: { dark: 6 },
				neutralTint: 0.3,
				neutralHue: 160,
				preserveSeed: true,
				primary: "accent",
				selection: "neutral",
				scopes: { switch: "accent", radio: "accent" },
			},
		},
	},
	{
		id: "stripe",
		name: "Stripe",
		description: "Blurple fills, cool slate hairlines.",
		swatch: "#675dff",
		inspiredBy: "Stripe",
		designSystem: {
			componentParams: {
				accordion: { motion: "expand", layout: "divided", marker: "trailing-chevron" },
				alert: { style: "neutral" },
				avatar: { shape: "circle", fallback: "neutral" },
				badge: { style: "soft-outline", case: "sentence" },
				breadcrumbs: { separator: "chevron", ancestors: "muted" },
				button: {
					style: "flat",
					secondary: "flat",
					press: "as-style",
					case: "sentence",
					current: "none",
					linkUnderline: "never",
					linkColor: "accent",
				},
				calendar: { dayShape: "same", today: "fill", weekdays: "single" },
				card: { footer: "none", titles: "quiet" },
				chart: { grid: "solid", motion: "spring" },
				checkbox: { "card-selected": "tint" },
				collapsible: { motion: "expand" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { sections: "open", footer: "end", close: "quiet", titles: "quiet" },
				drawer: { edge: "docked" },
				empty: { titles: "quiet" },
				field: { error: "plain", label: "regular" },
				group: { segments: "attached", separator: "shared-edge" },
				input: { style: "outline", hover: "none", height: "controls", errorIcon: "none" },
				kbd: { style: "chip" },
				link: { underline: "never", color: "accent" },
				"list-box": {
					indicator: "check-end",
					highlight: "neutral",
					inset: "inset",
					selected: "none",
					labels: "sentence",
				},
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", selected: "none", labels: "sentence" },
				modal: { position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right-cells" },
				"otp-field": { cells: "attached" },
				pagination: { current: "secondary" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", trackStyle: "plain" },
				"qr-code": { style: "squares" },
				questionnaire: { titles: "quiet" },
				"radio-group": { mark: "dot", "card-selected": "tint" },
				"segmented-control": { selected: "tone", track: "filled", weight: "medium" },
				select: { trigger: "button", caret: "double" },
				sidebar: { labels: "sentence", shell: "subtle", marker: "fill-accent", weight: "regular-medium" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "knob", track: "thin" },
				switch: { style: "inset", "card-selected": "tint" },
				table: { header: "plain", headerLabel: "muted" },
				tabs: { style: "line", color: "accent", chip: "tone", track: "filled", pill: "tone", weight: "medium" },
				"tag-group": { style: "soft-outline" },
				toast: { motion: "slide", surface: "surface", status: "icon" },
				"toggle-button": {
					style: "flat",
					secondary: "flat",
					press: "as-style",
					case: "sentence",
					selected: "tone",
					linkUnderline: "never",
					linkColor: "accent",
				},
				"toggle-button-group": { segments: "attached", separator: "shared-edge" },
				tooltip: { style: "inverted", tip: "tip", motion: "scale" },
			},
			tokens: {
				"--font-sans": "'Inter', ui-sans-serif, system-ui, sans-serif",
				"--font-mono": "'Source Code Pro', ui-monospace, 'SF Mono', monospace",
				"--radius": "0.5rem",
				"--studio-radius-card": "var(--radius-xl)",
				"--studio-radius-control": "var(--radius-lg)",
				"--studio-radius-item": "var(--radius-sm)",
				"--studio-radius-control-sm": "var(--radius-md)",
				"--studio-radius-field": "var(--radius-lg)",
				"--shadow-card": "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
				"--focus-ring-inset": "inset",
				"--focus-ring-offset": "0px",
				"--focus-ring-inner": "calc(var(--focus-ring-width) + 1px)",
				"--focus-input-width": "4px",
				"--studio-badge-radius": "var(--studio-radius-detail)",
			},
			density: "default",
			color: {
				v: 2,
				seeds: { accent: "#533afd", success: "#228403", danger: "#df1b41" },
				background: { light: 100, dark: 2 },
				neutralTint: 2,
				neutralHue: 260,
				primary: "accent",
			},
		},
	},
	{
		id: "linear",
		name: "Linear",
		description: "Indigo on near-black, pill actions.",
		swatch: "#828fff",
		inspiredBy: "Linear",
		designSystem: {
			componentParams: {
				accordion: { motion: "expand", layout: "divided", marker: "trailing-chevron" },
				alert: { style: "neutral" },
				avatar: { shape: "circle", fallback: "neutral" },
				badge: { style: "outline", case: "sentence" },
				breadcrumbs: { separator: "chevron", ancestors: "muted" },
				button: {
					style: "flat",
					secondary: "flat",
					press: "as-style",
					case: "sentence",
					current: "none",
					linkUnderline: "never",
					linkColor: "accent",
				},
				calendar: { dayShape: "same", today: "fill", weekdays: "single" },
				card: { footer: "none", titles: "quiet" },
				chart: { grid: "solid", motion: "spring" },
				checkbox: { "card-selected": "tint" },
				collapsible: { motion: "expand" },
				"color-editor": { style: "default" },
				command: { search: "prompt", inset: "inset", scale: "default" },
				dialog: { sections: "open", footer: "end", close: "quiet", titles: "quiet" },
				drawer: { edge: "docked" },
				empty: { titles: "quiet" },
				field: { error: "plain", label: "regular" },
				group: { segments: "attached", separator: "shared-edge" },
				input: { style: "outline", hover: "edge", height: "controls", errorIcon: "none" },
				kbd: { style: "chip" },
				link: { underline: "never", color: "accent" },
				"list-box": {
					indicator: "check-end",
					highlight: "neutral",
					inset: "inset",
					selected: "none",
					labels: "sentence",
				},
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", selected: "none", labels: "sentence" },
				modal: { position: "top", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right-cells" },
				"otp-field": { cells: "attached" },
				pagination: { current: "secondary" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", trackStyle: "plain" },
				"qr-code": { style: "squares" },
				questionnaire: { titles: "quiet" },
				"radio-group": { mark: "dot", "card-selected": "tint" },
				"segmented-control": { selected: "tone", track: "filled", weight: "medium" },
				select: { trigger: "button", caret: "chevron" },
				sidebar: { labels: "sentence", shell: "recessed", marker: "fill", weight: "regular-medium" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "knob", track: "thin" },
				switch: { style: "inset", "card-selected": "tint" },
				table: { header: "plain", headerLabel: "muted" },
				tabs: { style: "pill", color: "neutral", chip: "tone", track: "filled", pill: "tone", weight: "medium" },
				"tag-group": { style: "outline" },
				toast: { motion: "slide", surface: "surface", status: "icon" },
				"toggle-button": {
					style: "flat",
					secondary: "flat",
					press: "as-style",
					case: "sentence",
					selected: "tone",
					linkUnderline: "never",
					linkColor: "accent",
				},
				"toggle-button-group": { segments: "attached", separator: "shared-edge" },
				tooltip: { style: "surface", tip: "tip", motion: "scale" },
			},
			tokens: {
				"--color-selected": "var(--accent-100)",
				"--color-selected-hover": "var(--accent-200)",
				"--color-selected-active": "var(--accent-300)",
				"--color-fg-on-selected": "var(--color-fg-accent)",
				"--font-sans": "'Inter', ui-sans-serif, system-ui, sans-serif",
				"--radius": "0.5rem",
				"--studio-radius-card": "var(--radius-xl)",
				"--shadow-card": "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
				"--color-sidebar":
					"light-dark(color-mix(in oklab, var(--neutral-50) 50%, var(--neutral-100)), color-mix(in oklab, var(--neutral-25) 70%, oklch(0 0 0)))",
				"--focus-ring-width": "1px",
				"--focus-input-width": "0px",
				"--focus-input-color": "var(--color-border-focus)",
				"--focus-invalid-color": "var(--color-border-danger)",
				"--focus-input-edge": "0px",
				"--disabled-bg": "initial",
				"--disabled-fg": "initial",
				"--disabled-border": "initial",
				"--disabled-selected-bg": "initial",
				"--disabled-selected-fg": "initial",
				"--disabled-unselected-bg": "initial",
				"--color-primary-disabled": "initial",
				"--disabled-opacity": "0.5",
				"--cursor-interactive": "default",
				"--cursor-disabled": "default",
				"--studio-btn-radius": "var(--radius-full)",
				"--studio-btn-xs-radius": "var(--radius-full)",
			},
			density: "default",
			color: {
				v: 2,
				seeds: { accent: "#5e6ad2", success: "#27a644", danger: "#eb5757" },
				background: { dark: 2 },
				neutralHue: 262,
				primary: "accent",
			},
		},
	},
	{
		id: "vercel",
		name: "Vercel",
		description: "Monochrome ink, Geist blue accents.",
		swatch: "#8f8f8f",
		inspiredBy: "Vercel",
		designSystem: {
			componentParams: {
				accordion: { motion: "expand", layout: "divided", marker: "trailing-chevron" },
				alert: { style: "neutral" },
				avatar: { shape: "circle", fallback: "neutral" },
				badge: { style: "solid", case: "sentence" },
				breadcrumbs: { separator: "chevron", ancestors: "muted" },
				button: {
					style: "flat",
					secondary: "flat",
					press: "as-style",
					case: "sentence",
					current: "none",
					linkUnderline: "never",
					linkColor: "accent",
				},
				calendar: { dayShape: "same", today: "fill", weekdays: "single" },
				card: { footer: "none", titles: "quiet" },
				chart: { grid: "solid", motion: "spring" },
				checkbox: { "card-selected": "outline-tint" },
				collapsible: { motion: "expand" },
				"color-editor": { style: "default" },
				command: { search: "prompt", inset: "inset", scale: "default" },
				dialog: { sections: "open", footer: "end", close: "quiet", titles: "quiet" },
				drawer: { edge: "docked" },
				empty: { titles: "quiet" },
				field: { error: "plain", label: "regular" },
				group: { segments: "attached", separator: "shared-edge" },
				input: { style: "outline", hover: "edge", height: "controls", errorIcon: "none" },
				kbd: { style: "chip" },
				link: { underline: "never", color: "accent" },
				"list-box": {
					indicator: "check-end",
					highlight: "neutral",
					inset: "inset",
					selected: "none",
					labels: "sentence",
				},
				loader: { style: "blades" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", selected: "none", labels: "sentence" },
				modal: { position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right-cells" },
				"otp-field": { cells: "attached" },
				pagination: { current: "secondary" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", trackStyle: "plain" },
				"qr-code": { style: "squares" },
				questionnaire: { titles: "quiet" },
				"radio-group": { mark: "dot", "card-selected": "outline-tint" },
				"segmented-control": { selected: "tone", track: "outline", weight: "medium" },
				select: { trigger: "button", caret: "chevron" },
				sidebar: { labels: "sentence", shell: "subtle", marker: "fill", weight: "regular-medium" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "knob", track: "thin" },
				switch: { style: "inset", "card-selected": "outline-tint" },
				table: { header: "plain", headerLabel: "muted" },
				tabs: { style: "line", color: "neutral", chip: "tone", track: "outline", pill: "tone", weight: "medium" },
				"tag-group": { style: "solid" },
				toast: { motion: "slide", surface: "surface", status: "icon" },
				"toggle-button": {
					style: "flat",
					secondary: "flat",
					press: "as-style",
					case: "sentence",
					selected: "tone",
					linkUnderline: "never",
					linkColor: "accent",
				},
				"toggle-button-group": { segments: "attached", separator: "shared-edge" },
				tooltip: { style: "inverted", tip: "tip", motion: "scale" },
			},
			tokens: {
				"--icon-stroke-width": "2.25",
				"--radius": "0.5rem",
				"--studio-radius-card": "var(--radius-xl)",
				"--studio-radius-surface": "var(--radius-xl)",
				"--studio-radius-container": "var(--radius-xl)",
				"--focus-input-width": "4px",
			},
			density: "comfortable",
			color: {
				v: 2,
				seeds: { accent: "#0072f5", success: "#45a557", warning: "#ffb224", danger: "#e5484d" },
				background: { light: 100, dark: "oled" },
				neutralTint: 0,
				scopes: { switch: "accent" },
			},
		},
	},
	{
		id: "airbnb",
		name: "Airbnb",
		description: "Rausch accents, ink actions.",
		swatch: "#ff385c",
		inspiredBy: "Airbnb",
		designSystem: {
			componentParams: {
				accordion: { motion: "expand", layout: "divided", marker: "trailing-chevron" },
				alert: { style: "neutral" },
				avatar: { shape: "circle", fallback: "neutral" },
				badge: { style: "soft", case: "sentence" },
				breadcrumbs: { separator: "chevron", ancestors: "muted" },
				button: {
					style: "flat",
					secondary: "flat",
					press: "as-style",
					case: "sentence",
					current: "none",
					linkUnderline: "always",
					linkColor: "neutral",
				},
				calendar: { dayShape: "circle", today: "fill", weekdays: "double" },
				card: { footer: "none", titles: "quiet" },
				chart: { grid: "solid", motion: "spring" },
				checkbox: { "card-selected": "outline-tint" },
				collapsible: { motion: "expand" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "full-bleed", scale: "default" },
				dialog: { sections: "open", footer: "end", close: "quiet", titles: "quiet" },
				drawer: { edge: "docked" },
				empty: { titles: "quiet" },
				field: { error: "plain", label: "regular" },
				group: { segments: "attached", separator: "shared-edge" },
				input: { style: "outline", hover: "edge", height: "controls", errorIcon: "none" },
				kbd: { style: "chip" },
				link: { underline: "always", color: "neutral" },
				"list-box": {
					indicator: "check-end",
					highlight: "neutral",
					inset: "full-bleed",
					selected: "none",
					labels: "sentence",
				},
				loader: { style: "dots" },
				menu: {
					indicator: "check-end",
					highlight: "neutral",
					inset: "full-bleed",
					selected: "none",
					labels: "sentence",
				},
				modal: { position: "center", motion: "rise", mobile: "sheet" },
				"number-field": { steppers: "split" },
				"otp-field": { cells: "attached" },
				pagination: { current: "primary" },
				popover: { motion: "slide", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", trackStyle: "plain" },
				"qr-code": { style: "squares" },
				questionnaire: { titles: "quiet" },
				"radio-group": { mark: "dot", "card-selected": "outline-tint" },
				"segmented-control": { selected: "raised", track: "outline", weight: "medium" },
				select: { trigger: "button", caret: "chevron" },
				sidebar: { labels: "sentence", shell: "subtle", marker: "fill", weight: "regular-medium" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "knob", track: "thin" },
				switch: { style: "inset", "card-selected": "outline-tint" },
				table: { header: "plain", headerLabel: "muted" },
				tabs: { style: "line", color: "neutral", chip: "raised", track: "outline", pill: "tone", weight: "medium" },
				"tag-group": { style: "soft" },
				toast: { motion: "slide", surface: "surface", status: "icon" },
				"toggle-button": {
					style: "flat",
					secondary: "flat",
					press: "as-style",
					case: "sentence",
					selected: "tone",
					linkUnderline: "always",
					linkColor: "neutral",
				},
				"toggle-button-group": { segments: "attached", separator: "shared-edge" },
				tooltip: { style: "inverted", tip: "tip", motion: "slide" },
			},
			tokens: {
				"--font-sans": "'Plus Jakarta Sans', ui-sans-serif, system-ui, sans-serif",
				"--radius": "1rem",
				"--studio-radius-card": "var(--radius-xl)",
				"--studio-radius-surface": "var(--radius-md)",
				"--studio-radius-item": "var(--radius-sm)",
				"--card-border": "transparent",
				"--overlay-border": "light-dark(transparent, var(--color-border))",
				"--shadow-card":
					"0 0 2px 0 light-dark(rgb(0 0 0 / 0.12), rgb(0 0 0 / 0.24)), 0 1px 3px 0 light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2)), 0 1px 2px -1px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2))",
				"--shadow-popover":
					"0 0 2px 0 light-dark(rgb(0 0 0 / 0.12), rgb(0 0 0 / 0.24)), 0 4px 6px -1px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2)), 0 2px 4px -2px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2))",
				"--shadow-modal":
					"0 0 2px 0 light-dark(rgb(0 0 0 / 0.12), rgb(0 0 0 / 0.24)), 0 10px 15px -3px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2)), 0 4px 6px -4px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2))",
				"--color-card": "light-dark(var(--neutral-25), color-mix(in oklab, var(--neutral-50) 75%, var(--neutral-100)))",
				"--focus-input-width": "0px",
				"--focus-input-color": "var(--color-border-focus)",
				"--focus-invalid-color": "var(--color-border-danger)",
				"--focus-input-edge": "1px",
				"--color-text-selection": "Highlight",
				"--color-fg-on-text-selection": "HighlightText",
				"--studio-checkbox-radius": "2px",
				"--studio-badge-radius": "var(--studio-radius-detail)",
			},
			density: "comfortable",
			color: {
				v: 2,
				seeds: { accent: "#ff385c", success: "#038026", warning: "#eb6100", danger: "#d7251c" },
				background: { light: 100, dark: 5 },
				neutralTint: 0,
				preserveSeed: true,
				overrides: {
					"color-border-focus": { palette: "neutral", job: "solid" },
					"color-border-focus-muted": { palette: "neutral", job: "ui-active" },
				},
			},
		},
	},
	{
		id: "github",
		name: "GitHub",
		description: "Green actions, blue selection.",
		swatch: "#1f883d",
		inspiredBy: "GitHub",
		designSystem: {
			componentParams: {
				accordion: { motion: "expand", layout: "divided", marker: "trailing-chevron" },
				alert: { style: "neutral" },
				avatar: { shape: "circle", fallback: "neutral" },
				badge: { style: "outline", case: "sentence" },
				breadcrumbs: { separator: "slash", ancestors: "muted" },
				button: {
					style: "hairline",
					secondary: "hairline",
					press: "as-style",
					case: "sentence",
					current: "none",
					linkUnderline: "always",
					linkColor: "neutral",
				},
				calendar: { dayShape: "same", today: "fill", weekdays: "single" },
				card: { footer: "none", titles: "quiet" },
				chart: { grid: "solid", motion: "spring" },
				checkbox: { "card-selected": "tint" },
				collapsible: { motion: "expand" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { sections: "open", footer: "end", close: "quiet", titles: "quiet" },
				drawer: { edge: "docked" },
				empty: { titles: "quiet" },
				field: { error: "plain", label: "regular" },
				group: { segments: "attached", separator: "shared-edge" },
				input: { style: "inset", hover: "none", height: "controls", errorIcon: "none" },
				kbd: { style: "keycap" },
				link: { underline: "always", color: "neutral" },
				"list-box": {
					indicator: "check-start",
					highlight: "neutral",
					inset: "inset",
					selected: "none",
					labels: "sentence",
				},
				loader: { style: "ring" },
				menu: { indicator: "check-start", highlight: "neutral", inset: "inset", selected: "none", labels: "sentence" },
				modal: { position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right-cells" },
				"otp-field": { cells: "attached" },
				pagination: { current: "secondary" },
				popover: { motion: "fade", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thick", trackStyle: "plain" },
				"qr-code": { style: "squares" },
				questionnaire: { titles: "quiet" },
				"radio-group": { mark: "dot", "card-selected": "tint" },
				"segmented-control": { selected: "raised", track: "filled", weight: "medium" },
				select: { trigger: "button", caret: "double" },
				sidebar: { labels: "sentence", shell: "subtle", marker: "fill", weight: "regular-medium" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "knob", track: "thin" },
				switch: { style: "inset", "card-selected": "tint" },
				table: { header: "filled", headerLabel: "muted" },
				tabs: { style: "line", color: "neutral", chip: "raised", track: "filled", pill: "tone", weight: "medium" },
				"tag-group": { style: "outline" },
				toast: { motion: "slide", surface: "surface", status: "icon" },
				"toggle-button": {
					style: "hairline",
					secondary: "hairline",
					press: "as-style",
					case: "sentence",
					selected: "tone",
					linkUnderline: "always",
					linkColor: "neutral",
				},
				"toggle-button-group": { segments: "attached", separator: "shared-edge" },
				tooltip: { style: "inverted", tip: "tip", motion: "fade" },
			},
			tokens: {
				"--font-sans": "'Mona Sans', ui-sans-serif, system-ui, sans-serif",
				"--radius": "0.5rem",
				"--studio-radius-card": "var(--radius-xl)",
				"--studio-radius-surface": "var(--radius-xl)",
				"--studio-radius-container": "var(--radius-xl)",
				"--focus-ring-inset": "inset",
				"--focus-ring-offset": "0px",
				"--focus-ring-inner": "calc(var(--focus-ring-width) + 1px)",
				"--focus-input-width": "0px",
				"--focus-input-color": "var(--color-border-focus)",
				"--focus-invalid-color": "var(--color-border-danger)",
				"--focus-input-edge": "1px",
				"--color-text-selection": "Highlight",
				"--color-fg-on-text-selection": "HighlightText",
			},
			density: "default",
			color: {
				v: 2,
				seeds: { accent: "#1f883d", success: "#1f883d", warning: "#9a6700", danger: "#cf222e", selection: "#0969da" },
				background: { light: 100, dark: 5 },
				neutralTint: 1.4,
				neutralHue: 251,
				preserveSeed: true,
				primary: "accent",
				scopes: { slider: "accent" },
			},
		},
	},
	{
		id: "notion",
		name: "Notion",
		description: "Warm ink, quiet blue.",
		swatch: "#8e8b86",
		inspiredBy: "Notion",
		designSystem: {
			componentParams: {
				accordion: { motion: "expand", layout: "divided", marker: "leading-caret" },
				alert: { style: "neutral" },
				avatar: { shape: "circle", fallback: "neutral" },
				badge: { style: "soft", case: "sentence" },
				breadcrumbs: { separator: "slash", ancestors: "muted" },
				button: {
					style: "flat",
					secondary: "flat",
					press: "as-style",
					case: "sentence",
					current: "none",
					linkUnderline: "always",
					linkColor: "neutral",
				},
				calendar: { dayShape: "same", today: "fill", weekdays: "single" },
				card: { footer: "none", titles: "quiet" },
				chart: { grid: "solid", motion: "spring" },
				checkbox: { "card-selected": "tint" },
				collapsible: { motion: "expand" },
				"color-editor": { style: "default" },
				command: { search: "bar", inset: "inset", scale: "default" },
				dialog: { sections: "open", footer: "end", close: "quiet", titles: "quiet" },
				drawer: { edge: "docked" },
				empty: { titles: "quiet" },
				field: { error: "plain", label: "regular" },
				group: { segments: "attached", separator: "shared-edge" },
				input: { style: "outline", hover: "none", height: "controls", errorIcon: "none" },
				kbd: { style: "chip" },
				link: { underline: "always", color: "neutral" },
				"list-box": {
					indicator: "check-end",
					highlight: "neutral",
					inset: "inset",
					selected: "none",
					labels: "sentence",
				},
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", selected: "none", labels: "sentence" },
				modal: { position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right-cells" },
				"otp-field": { cells: "attached" },
				pagination: { current: "secondary" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", trackStyle: "plain" },
				"qr-code": { style: "squares" },
				questionnaire: { titles: "quiet" },
				"radio-group": { mark: "dot", "card-selected": "tint" },
				"segmented-control": { selected: "tone", track: "filled", weight: "medium" },
				select: { trigger: "button", caret: "chevron" },
				sidebar: { labels: "sentence", shell: "subtle", marker: "fill", weight: "regular-medium" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "knob", track: "thin" },
				switch: { style: "inset", "card-selected": "tint" },
				table: { header: "plain", headerLabel: "muted" },
				tabs: { style: "pill", color: "neutral", chip: "tone", track: "filled", pill: "tone", weight: "medium" },
				"tag-group": { style: "soft" },
				toast: { motion: "slide", surface: "surface", status: "icon" },
				"toggle-button": {
					style: "flat",
					secondary: "flat",
					press: "as-style",
					case: "sentence",
					selected: "tone",
					linkUnderline: "always",
					linkColor: "neutral",
				},
				"toggle-button-group": { segments: "attached", separator: "shared-edge" },
				tooltip: { style: "inverted", tip: "tip", motion: "scale" },
			},
			tokens: {
				"--color-selected": "var(--accent-100)",
				"--color-selected-hover": "var(--accent-200)",
				"--color-selected-active": "var(--accent-300)",
				"--color-fg-on-selected": "var(--color-fg-accent)",
				"--font-sans": "'Inter', ui-sans-serif, system-ui, sans-serif",
				"--text-xs": "0.8125rem",
				"--text-xs--line-height": "calc(16 / 13)",
				"--radius": "0.5rem",
				"--studio-radius-card": "var(--radius-xl)",
				"--focus-input-width": "0px",
				"--focus-input-color": "var(--color-border-focus)",
				"--focus-invalid-color": "var(--color-border-danger)",
				"--focus-input-edge": "1px",
				"--disabled-bg": "initial",
				"--disabled-fg": "initial",
				"--disabled-border": "initial",
				"--disabled-selected-bg": "initial",
				"--disabled-selected-fg": "initial",
				"--disabled-unselected-bg": "initial",
				"--color-primary-disabled": "initial",
				"--disabled-opacity": "0.5",
				"--cursor-disabled": "default",
				"--studio-badge-radius": "var(--studio-radius-detail)",
			},
			density: "compact",
			color: {
				v: 2,
				seeds: { accent: "#2783de" },
				background: { light: 100, dark: 8.8 },
				neutralTint: 0.5,
				neutralHue: 81,
				primary: "accent",
			},
		},
	},
	{
		id: "spotify",
		name: "Spotify",
		description: "Vivid green on near-black.",
		swatch: "#1ed760",
		inspiredBy: "Spotify",
		designSystem: {
			componentParams: {
				accordion: { motion: "expand", layout: "divided", marker: "trailing-chevron" },
				alert: { style: "neutral" },
				avatar: { shape: "circle", fallback: "neutral" },
				badge: { style: "soft", case: "sentence" },
				breadcrumbs: { separator: "chevron", ancestors: "muted" },
				button: {
					style: "flat",
					secondary: "flat",
					press: "as-style",
					case: "sentence",
					current: "none",
					linkUnderline: "hover",
					linkColor: "neutral",
				},
				calendar: { dayShape: "same", today: "fill", weekdays: "single" },
				card: { footer: "none", titles: "quiet" },
				chart: { grid: "solid", motion: "spring" },
				checkbox: { "card-selected": "tint" },
				collapsible: { motion: "expand" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { sections: "open", footer: "end", close: "quiet", titles: "quiet" },
				drawer: { edge: "docked" },
				empty: { titles: "quiet" },
				field: { error: "plain", label: "regular" },
				group: { segments: "attached", separator: "shared-edge" },
				input: { style: "filled", hover: "tint", height: "controls", errorIcon: "none" },
				kbd: { style: "chip" },
				link: { underline: "hover", color: "neutral" },
				"list-box": {
					indicator: "check-end",
					highlight: "neutral",
					inset: "inset",
					selected: "none",
					labels: "sentence",
				},
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", selected: "none", labels: "sentence" },
				modal: { position: "center", motion: "rise", mobile: "center" },
				"number-field": { steppers: "right-cells" },
				"otp-field": { cells: "attached" },
				pagination: { current: "secondary" },
				popover: { motion: "slide", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", trackStyle: "plain" },
				"qr-code": { style: "squares" },
				questionnaire: { titles: "quiet" },
				"radio-group": { mark: "dot", "card-selected": "tint" },
				"segmented-control": { selected: "tone", track: "filled", weight: "medium" },
				select: { trigger: "button", caret: "chevron" },
				sidebar: { labels: "sentence", shell: "recessed", marker: "fill", weight: "regular-medium" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "knob", track: "thin" },
				switch: { style: "inset", "card-selected": "tint" },
				table: { header: "plain", headerLabel: "muted" },
				tabs: { style: "line", color: "neutral", chip: "tone", track: "filled", pill: "inverse", weight: "medium" },
				"tag-group": { style: "soft" },
				toast: { motion: "slide", surface: "surface", status: "icon" },
				"toggle-button": {
					style: "flat",
					secondary: "flat",
					press: "as-style",
					case: "sentence",
					selected: "inverse",
					linkUnderline: "hover",
					linkColor: "neutral",
				},
				"toggle-button-group": { segments: "attached", separator: "shared-edge" },
				tooltip: { style: "surface", tip: "tip", motion: "slide" },
			},
			tokens: {
				"--color-border-control": "var(--neutral-700)",
				"--color-border-control-hover": "var(--neutral-800)",
				"--font-sans": "'Figtree', ui-sans-serif, system-ui, sans-serif",
				"--radius": "0.5rem",
				"--studio-radius-panel": "var(--radius-lg)",
				"--studio-radius-control": "var(--radius-full)",
				"--studio-radius-control-sm": "var(--radius-full)",
				"--studio-radius-field": "var(--radius-lg)",
				"--card-border": "transparent",
				"--overlay-border": "light-dark(transparent, var(--color-border))",
				"--shadow-popover":
					"0 0 2px 0 light-dark(rgb(0 0 0 / 0.12), rgb(0 0 0 / 0.24)), 0 4px 6px -1px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2)), 0 2px 4px -2px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2))",
				"--shadow-modal":
					"0 0 2px 0 light-dark(rgb(0 0 0 / 0.12), rgb(0 0 0 / 0.24)), 0 10px 15px -3px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2)), 0 4px 6px -4px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2))",
				"--color-card":
					"light-dark(color-mix(in oklab, var(--neutral-50) 50%, var(--neutral-100)), color-mix(in oklab, var(--neutral-50) 75%, var(--neutral-100)))",
				"--color-popover":
					"light-dark(var(--neutral-50), color-mix(in oklab, var(--neutral-50) 50%, var(--neutral-100)))",
				"--color-sidebar":
					"light-dark(color-mix(in oklab, var(--neutral-50) 50%, var(--neutral-100)), color-mix(in oklab, var(--neutral-25) 70%, oklch(0 0 0)))",
				"--focus-ring-inset": "inset",
				"--focus-ring-offset": "0px",
				"--focus-ring-inner": "calc(var(--focus-ring-width) + 1px)",
				"--focus-input-width": "var(--focus-ring-width)",
				"--focus-input-offset": "var(--focus-ring-offset)",
				"--focus-input-color": "var(--focus-ring-color)",
				"--focus-input-inset": "inset",
				"--disabled-bg": "initial",
				"--disabled-fg": "initial",
				"--disabled-border": "initial",
				"--disabled-selected-bg": "initial",
				"--disabled-selected-fg": "initial",
				"--disabled-unselected-bg": "initial",
				"--color-primary-disabled": "initial",
				"--disabled-opacity": "0.5",
				"--color-text-selection": "Highlight",
				"--color-fg-on-text-selection": "HighlightText",
				"--studio-btn-radius": "var(--radius-full)",
				"--studio-btn-xs-radius": "var(--radius-full)",
				"--studio-badge-radius": "var(--studio-radius-detail)",
			},
			density: "comfortable",
			color: {
				v: 2,
				seeds: { accent: "#1ed760", success: "#1ed760", warning: "#ffa42b", danger: "#e91429" },
				background: { light: 100, dark: 5.5 },
				neutralTint: 0,
				preserveSeed: true,
				primary: "accent",
				overrides: {
					"color-border-focus": { palette: "neutral", job: "solid" },
					"color-border-focus-muted": { palette: "neutral", job: "ui-active" },
				},
				scopes: { slider: "neutral" },
			},
		},
	},
	{
		id: "duolingo",
		name: "Duolingo",
		description: "Feather green on ledges, chunky and uppercase.",
		swatch: "#58cc02",
		inspiredBy: "Duolingo",
		designSystem: {
			componentParams: {
				accordion: { motion: "expand", layout: "divided", marker: "trailing-chevron" },
				alert: { style: "neutral" },
				avatar: { shape: "circle", fallback: "neutral" },
				badge: { style: "soft", case: "uppercase" },
				breadcrumbs: { separator: "chevron", ancestors: "muted" },
				button: {
					style: "ledge",
					secondary: "ledge",
					press: "as-style",
					case: "uppercase",
					current: "none",
					linkUnderline: "never",
					linkColor: "accent",
				},
				calendar: { dayShape: "circle", today: "fill", weekdays: "single" },
				card: { footer: "none", titles: "bold" },
				chart: { grid: "solid", motion: "spring" },
				checkbox: { "card-selected": "outline-tint" },
				collapsible: { motion: "expand" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { sections: "open", footer: "stack", close: "filled", titles: "bold" },
				drawer: { edge: "docked" },
				empty: { titles: "bold" },
				field: { error: "plain", label: "regular" },
				group: { segments: "gapped", separator: "shared-edge" },
				input: { style: "well", hover: "none", height: "controls", errorIcon: "none" },
				kbd: { style: "outline" },
				link: { underline: "never", color: "accent" },
				"list-box": { indicator: "none", highlight: "neutral", inset: "inset", selected: "tint", labels: "caps" },
				loader: { style: "dots" },
				menu: { indicator: "none", highlight: "neutral", inset: "inset", selected: "tint", labels: "caps" },
				modal: { position: "center", motion: "scale", mobile: "fullscreen" },
				"number-field": { steppers: "right-cells" },
				"otp-field": { cells: "attached" },
				pagination: { current: "secondary" },
				popover: { motion: "scale", mobile: "drawer", tip: "tip" },
				"progress-bar": { track: "x-heavy", trackStyle: "plain" },
				"qr-code": { style: "squares" },
				questionnaire: { titles: "bold" },
				"radio-group": { mark: "dot", "card-selected": "outline-tint" },
				"segmented-control": { selected: "tone", track: "filled", weight: "bold" },
				select: { trigger: "button", caret: "chevron" },
				sidebar: { labels: "caps", shell: "page", marker: "outline-accent", weight: "bold" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "knob", track: "thin" },
				switch: { style: "slab", "card-selected": "outline-tint" },
				table: { header: "plain", headerLabel: "muted" },
				tabs: { style: "line", color: "accent", chip: "tone", track: "filled", pill: "tint", weight: "bold" },
				"tag-group": { style: "soft" },
				toast: { motion: "slide", surface: "surface", status: "icon" },
				"toggle-button": {
					style: "ledge",
					secondary: "ledge",
					press: "as-style",
					case: "uppercase",
					selected: "tint",
					linkUnderline: "never",
					linkColor: "accent",
				},
				"toggle-button-group": { segments: "gapped", separator: "shared-edge" },
				tooltip: { style: "inverted", tip: "tip", motion: "scale" },
			},
			tokens: {
				"--color-border-control": "var(--color-border)",
				"--color-border-control-hover": "var(--neutral-400)",
				"--font-sans": "'Nunito', ui-sans-serif, system-ui, sans-serif",
				"--font-weight-heading": "var(--font-weight-bold)",
				"--studio-font-weight-label": "var(--font-weight-bold)",
				"--icon-stroke-width": "2.5",
				"--radius": "1rem",
				"--studio-radius-item": "var(--radius-xs)",
				"--studio-radius-inline-item": "var(--radius-sm)",
				"--studio-control-stroke": "2px",
				"--color-sidebar": "var(--color-bg)",
				"--focus-input-width": "0px",
				"--focus-input-color": "var(--color-border-focus)",
				"--focus-invalid-color": "var(--color-border-danger)",
				"--focus-input-edge": "0px",
				"--cursor-disabled": "default",
				"--studio-checkbox-radius": "2px",
				"--studio-scrim-blur": "0",
				"--studio-badge-radius": "var(--studio-radius-detail)",
			},
			density: "comfortable",
			color: {
				v: 2,
				seeds: { accent: "#58cc02", success: "#58cc02", warning: "#ffc800", danger: "#ff4b4b", selection: "#1cb0f6" },
				background: { light: 100, dark: 2 },
				neutralTint: 0,
				preserveSeed: true,
				primary: "accent",
				scopes: { slider: "accent" },
			},
		},
	},
	{
		id: "polaris",
		name: "Polaris",
		description: "Charcoal bevels on grouped gray, dense and blue-linked.",
		swatch: "#303030",
		inspiredBy: "Shopify Polaris",
		designSystem: {
			componentParams: {
				accordion: { motion: "expand", layout: "divided", marker: "trailing-chevron" },
				alert: { style: "neutral" },
				avatar: { shape: "rounded", fallback: "neutral" },
				badge: { style: "soft", case: "sentence" },
				breadcrumbs: { separator: "chevron", ancestors: "muted" },
				button: {
					style: "bevel",
					secondary: "bevel",
					press: "as-style",
					case: "sentence",
					current: "none",
					linkUnderline: "always",
					linkColor: "accent",
				},
				calendar: { dayShape: "same", today: "numeral", weekdays: "double" },
				card: { footer: "none", titles: "compact" },
				chart: { grid: "solid", motion: "spring" },
				checkbox: { "card-selected": "tint" },
				collapsible: { motion: "expand" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { sections: "header-band", footer: "end-rule", close: "quiet", titles: "compact" },
				drawer: { edge: "docked" },
				empty: { titles: "compact" },
				field: { error: "icon-message", label: "regular" },
				group: { segments: "attached", separator: "shared-edge" },
				input: { style: "outline", hover: "edge-tint", height: "step", errorIcon: "none" },
				kbd: { style: "chip" },
				link: { underline: "always", color: "accent" },
				"list-box": {
					indicator: "check-end",
					highlight: "neutral",
					inset: "inset",
					selected: "tint",
					labels: "sentence",
				},
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", selected: "tint", labels: "sentence" },
				modal: { position: "center", motion: "rise", mobile: "sheet" },
				"number-field": { steppers: "stacked-inset" },
				"otp-field": { cells: "attached" },
				pagination: { current: "secondary" },
				popover: { motion: "slide", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "x-heavy", trackStyle: "plain" },
				"qr-code": { style: "squares" },
				questionnaire: { titles: "compact" },
				"radio-group": { mark: "dot", "card-selected": "tint" },
				"segmented-control": { selected: "raised", track: "filled", weight: "medium-semibold" },
				select: { trigger: "field", caret: "double" },
				sidebar: { labels: "sentence", shell: "recessed", marker: "surface", weight: "medium-semibold" },
				skeleton: { animation: "none" },
				slider: { thumb: "solid", track: "thin" },
				switch: { style: "outlined", "card-selected": "tint" },
				table: { header: "filled", headerLabel: "muted" },
				tabs: {
					style: "pill",
					color: "neutral",
					chip: "raised",
					track: "filled",
					pill: "tone",
					weight: "medium-semibold",
				},
				"tag-group": { style: "soft" },
				toast: { motion: "slide", surface: "inverse", status: "bold" },
				"toggle-button": {
					style: "bevel",
					secondary: "bevel",
					press: "as-style",
					case: "sentence",
					selected: "tone",
					linkUnderline: "always",
					linkColor: "accent",
				},
				"toggle-button-group": { segments: "attached", separator: "shared-edge" },
				tooltip: { style: "surface", tip: "tip", motion: "slide" },
			},
			tokens: {
				"--color-border-control": "var(--neutral-700)",
				"--color-border-control-hover": "var(--neutral-800)",
				"--font-sans": "'Inter', ui-sans-serif, system-ui, sans-serif",
				"--font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace",
				"--font-weight-heading": "var(--font-weight-semibold)",
				"--text-xs": "0.8125rem",
				"--text-xs--line-height": "calc(16 / 13)",
				"--icon-stroke-width": "1.75",
				"--radius": "0.5rem",
				"--studio-radius-panel": "var(--radius-2xl)",
				"--studio-radius-card": "var(--radius-xl)",
				"--studio-radius-surface": "var(--radius-xl)",
				"--studio-radius-control": "var(--radius-lg)",
				"--studio-radius-item": "var(--radius-lg)",
				"--studio-radius-control-sm": "var(--radius-md)",
				"--studio-radius-field": "var(--radius-lg)",
				"--studio-radius-container": "var(--radius-xl)",
				"--studio-radius-inline-item": "var(--radius-lg)",
				"--card-border": "transparent",
				"--overlay-border": "light-dark(transparent, var(--color-border))",
				"--shadow-card":
					"0 0 2px 0 light-dark(rgb(0 0 0 / 0.12), rgb(0 0 0 / 0.24)), 0 1px 3px 0 light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2)), 0 1px 2px -1px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2))",
				"--shadow-popover":
					"0 0 2px 0 light-dark(rgb(0 0 0 / 0.12), rgb(0 0 0 / 0.24)), 0 4px 6px -1px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2)), 0 2px 4px -2px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2))",
				"--shadow-modal":
					"0 0 2px 0 light-dark(rgb(0 0 0 / 0.12), rgb(0 0 0 / 0.24)), 0 10px 15px -3px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2)), 0 4px 6px -4px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2))",
				"--color-card": "light-dark(oklch(1 0 0), color-mix(in oklab, var(--neutral-50) 75%, var(--neutral-100)))",
				"--color-popover": "light-dark(oklch(1 0 0), color-mix(in oklab, var(--neutral-50) 50%, var(--neutral-100)))",
				"--color-sidebar":
					"light-dark(color-mix(in oklab, var(--neutral-50) 50%, var(--neutral-100)), color-mix(in oklab, var(--neutral-25) 70%, oklch(0 0 0)))",
				"--focus-input-width": "var(--focus-ring-width)",
				"--focus-input-offset": "var(--focus-ring-offset)",
				"--focus-input-color": "var(--focus-ring-color)",
				"--cursor-disabled": "default",
				"--studio-scrim-blur": "0",
				"--studio-badge-radius": "var(--studio-radius-detail)",
			},
			density: "compact",
			color: {
				v: 2,
				seeds: { accent: "#005bd3", success: "#047b5d", warning: "#ffb800", danger: "#c70a24" },
				background: { light: 96, dark: 2 },
				neutralTint: 0,
				preserveSeed: true,
				selection: "accent",
				scopes: {
					switch: "neutral",
					checkbox: "neutral",
					radio: "neutral",
					calendar: "neutral",
					"range-calendar": "neutral",
					"time-picker-columns": "neutral",
					slider: "neutral",
				},
			},
		},
	},
	{
		id: "material3",
		name: "Material 3",
		description: "Purple on tonal lavender, pill actions and filled fields.",
		swatch: "#6750a4",
		inspiredBy: "Material 3",
		designSystem: {
			componentParams: {
				accordion: { motion: "expand", layout: "divided", marker: "trailing-chevron" },
				alert: { style: "neutral" },
				avatar: { shape: "circle", fallback: "neutral" },
				badge: { style: "outline", case: "sentence" },
				breadcrumbs: { separator: "chevron", ancestors: "muted" },
				button: {
					style: "flat",
					secondary: "tonal",
					press: "as-style",
					case: "sentence",
					current: "none",
					linkUnderline: "never",
					linkColor: "accent",
				},
				calendar: { dayShape: "circle", today: "ring-selection", weekdays: "single" },
				card: { footer: "none", titles: "display" },
				chart: { grid: "solid", motion: "spring" },
				checkbox: { "card-selected": "tint" },
				collapsible: { motion: "expand" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "full-bleed", scale: "default" },
				dialog: { sections: "on-scroll", footer: "end", close: "quiet", titles: "display" },
				drawer: { edge: "docked" },
				empty: { titles: "display" },
				field: { error: "plain", label: "regular" },
				group: { segments: "attached", separator: "divider" },
				input: { style: "indicator", hover: "tint", height: "tall", errorIcon: "inside" },
				kbd: { style: "chip" },
				link: { underline: "never", color: "accent" },
				"list-box": {
					indicator: "none",
					highlight: "neutral",
					inset: "full-bleed",
					selected: "tint",
					labels: "sentence",
				},
				loader: { style: "ring" },
				menu: { indicator: "none", highlight: "neutral", inset: "full-bleed", selected: "tint", labels: "sentence" },
				modal: { position: "center", motion: "drop", mobile: "center" },
				"number-field": { steppers: "right-cells" },
				"otp-field": { cells: "separate" },
				pagination: { current: "secondary" },
				popover: { motion: "slide", mobile: "anchored", tip: "none" },
				"progress-bar": { track: "thin", trackStyle: "gap" },
				"qr-code": { style: "squares" },
				questionnaire: { titles: "display" },
				"radio-group": { mark: "ring", "card-selected": "tint" },
				"segmented-control": { selected: "tone", track: "outline", weight: "medium" },
				select: { trigger: "field", caret: "chevron" },
				sidebar: { labels: "sentence", shell: "subtle", marker: "fill-accent", weight: "regular-medium" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "handle", track: "thick" },
				switch: { style: "outlined", "card-selected": "tint" },
				table: { header: "plain", headerLabel: "muted" },
				tabs: { style: "line", color: "accent", chip: "tone", track: "outline", pill: "solid", weight: "medium" },
				"tag-group": { style: "outline" },
				toast: { motion: "slide", surface: "inverse", status: "solid-icon" },
				"toggle-button": {
					style: "flat",
					secondary: "tonal",
					press: "as-style",
					case: "sentence",
					selected: "solid",
					linkUnderline: "never",
					linkColor: "accent",
				},
				"toggle-button-group": { segments: "attached", separator: "divider" },
				tooltip: { style: "inverted", tip: "none", motion: "slide" },
			},
			tokens: {
				"--color-selected": "var(--accent-100)",
				"--color-selected-hover": "var(--accent-200)",
				"--color-selected-active": "var(--accent-300)",
				"--color-fg-on-selected": "var(--color-fg-accent)",
				"--font-sans": "'Roboto', ui-sans-serif, system-ui, sans-serif",
				"--font-mono": "'Roboto Mono', ui-monospace, 'SF Mono', monospace",
				"--font-weight-heading": "var(--font-weight-normal)",
				"--radius": "0.5rem",
				"--studio-radius-panel": "var(--radius-3xl)",
				"--studio-radius-card": "var(--radius-xl)",
				"--studio-radius-surface": "var(--radius-sm)",
				"--studio-radius-control": "var(--radius-sm)",
				"--studio-radius-item": "0",
				"--studio-radius-control-sm": "var(--radius-xs)",
				"--studio-radius-detail": "var(--radius-xs)",
				"--studio-radius-field": "var(--radius-sm)",
				"--studio-radius-container": "var(--radius-md)",
				"--studio-radius-inline-item": "0",
				"--card-border": "transparent",
				"--overlay-border": "light-dark(transparent, var(--color-border))",
				"--shadow-card":
					"0 0 2px 0 light-dark(rgb(0 0 0 / 0.12), rgb(0 0 0 / 0.24)), 0 1px 3px 0 light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2)), 0 1px 2px -1px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2))",
				"--shadow-popover":
					"0 0 2px 0 light-dark(rgb(0 0 0 / 0.12), rgb(0 0 0 / 0.24)), 0 4px 6px -1px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2)), 0 2px 4px -2px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2))",
				"--shadow-modal":
					"0 0 2px 0 light-dark(rgb(0 0 0 / 0.12), rgb(0 0 0 / 0.24)), 0 10px 15px -3px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2)), 0 4px 6px -4px light-dark(rgb(0 0 0 / 0.1), rgb(0 0 0 / 0.2))",
				"--color-card":
					"light-dark(color-mix(in oklab, var(--neutral-50) 50%, var(--neutral-100)), color-mix(in oklab, var(--neutral-50) 75%, var(--neutral-100)))",
				"--color-popover":
					"light-dark(var(--neutral-50), color-mix(in oklab, var(--neutral-50) 50%, var(--neutral-100)))",
				"--focus-ring-width": "3px",
				"--focus-input-width": "0px",
				"--focus-input-color": "var(--color-border-focus)",
				"--focus-invalid-color": "var(--color-border-danger)",
				"--focus-input-edge": "1px",
				"--cursor-disabled": "default",
				"--studio-button-state-ease":
					"linear(0, 0.015 2%, 0.079 5%, 0.17 8%, 0.466 17%, 0.578 21%, 0.65 24%, 0.712 27%, 0.78 31%, 0.866 38%, 0.931 47%, 0.972 59%, 0.992 75%, 1)",
				"--studio-input-state-ease":
					"linear(0, 0.015 2%, 0.079 5%, 0.17 8%, 0.466 17%, 0.578 21%, 0.65 24%, 0.712 27%, 0.78 31%, 0.866 38%, 0.931 47%, 0.972 59%, 0.992 75%, 1)",
				"--studio-checkbox-state-ease":
					"linear(0, 0.015 2%, 0.079 5%, 0.17 8%, 0.466 17%, 0.578 21%, 0.65 24%, 0.712 27%, 0.78 31%, 0.866 38%, 0.931 47%, 0.972 59%, 0.992 75%, 1)",
				"--studio-slider-state-ease":
					"linear(0, 0.015 2%, 0.079 5%, 0.17 8%, 0.466 17%, 0.578 21%, 0.65 24%, 0.712 27%, 0.78 31%, 0.866 38%, 0.931 47%, 0.972 59%, 0.992 75%, 1)",
				"--studio-link-state-ease":
					"linear(0, 0.015 2%, 0.079 5%, 0.17 8%, 0.466 17%, 0.578 21%, 0.65 24%, 0.712 27%, 0.78 31%, 0.866 38%, 0.931 47%, 0.972 59%, 0.992 75%, 1)",
				"--studio-breadcrumbs-state-ease":
					"linear(0, 0.015 2%, 0.079 5%, 0.17 8%, 0.466 17%, 0.578 21%, 0.65 24%, 0.712 27%, 0.78 31%, 0.866 38%, 0.931 47%, 0.972 59%, 0.992 75%, 1)",
				"--studio-tag-state-ease":
					"linear(0, 0.015 2%, 0.079 5%, 0.17 8%, 0.466 17%, 0.578 21%, 0.65 24%, 0.712 27%, 0.78 31%, 0.866 38%, 0.931 47%, 0.972 59%, 0.992 75%, 1)",
				"--studio-table-state-ease":
					"linear(0, 0.015 2%, 0.079 5%, 0.17 8%, 0.466 17%, 0.578 21%, 0.65 24%, 0.712 27%, 0.78 31%, 0.866 38%, 0.931 47%, 0.972 59%, 0.992 75%, 1)",
				"--studio-calendar-state-ease":
					"linear(0, 0.015 2%, 0.079 5%, 0.17 8%, 0.466 17%, 0.578 21%, 0.65 24%, 0.712 27%, 0.78 31%, 0.866 38%, 0.931 47%, 0.972 59%, 0.992 75%, 1)",
				"--studio-time-picker-state-ease":
					"linear(0, 0.015 2%, 0.079 5%, 0.17 8%, 0.466 17%, 0.578 21%, 0.65 24%, 0.712 27%, 0.78 31%, 0.866 38%, 0.931 47%, 0.972 59%, 0.992 75%, 1)",
				"--studio-color-swatch-picker-state-ease":
					"linear(0, 0.015 2%, 0.079 5%, 0.17 8%, 0.466 17%, 0.578 21%, 0.65 24%, 0.712 27%, 0.78 31%, 0.866 38%, 0.931 47%, 0.972 59%, 0.992 75%, 1)",
				"--studio-questionnaire-state-ease":
					"linear(0, 0.015 2%, 0.079 5%, 0.17 8%, 0.466 17%, 0.578 21%, 0.65 24%, 0.712 27%, 0.78 31%, 0.866 38%, 0.931 47%, 0.972 59%, 0.992 75%, 1)",
				"--studio-switch-state-duration": "360ms",
				"--studio-switch-state-ease":
					"linear(0, 0.005 1%, 0.041 3%, 0.07 4%, 0.144 6%, 0.233 8%, 0.533 14%, 0.674 17%, 0.797 20%, 0.866 22%, 0.926 24%, 0.996 27%, 1.031 29%, 1.068 32%, 1.091 36%, 1.092 41%, 1.018 59%, 0.994 70%, 1)",
				"--studio-segmented-control-state-duration": "360ms",
				"--studio-segmented-control-state-ease":
					"linear(0, 0.005 1%, 0.041 3%, 0.07 4%, 0.144 6%, 0.233 8%, 0.533 14%, 0.674 17%, 0.797 20%, 0.866 22%, 0.926 24%, 0.996 27%, 1.031 29%, 1.068 32%, 1.091 36%, 1.092 41%, 1.018 59%, 0.994 70%, 1)",
				"--studio-tabs-state-duration": "360ms",
				"--studio-tabs-state-ease":
					"linear(0, 0.005 1%, 0.041 3%, 0.07 4%, 0.144 6%, 0.233 8%, 0.533 14%, 0.674 17%, 0.797 20%, 0.866 22%, 0.926 24%, 0.996 27%, 1.031 29%, 1.068 32%, 1.091 36%, 1.092 41%, 1.018 59%, 0.994 70%, 1)",
				"--studio-progress-state-duration": "360ms",
				"--studio-progress-state-ease":
					"linear(0, 0.005 1%, 0.041 3%, 0.07 4%, 0.144 6%, 0.233 8%, 0.533 14%, 0.674 17%, 0.797 20%, 0.866 22%, 0.926 24%, 0.996 27%, 1.031 29%, 1.068 32%, 1.091 36%, 1.092 41%, 1.018 59%, 0.994 70%, 1)",
				"--studio-sidebar-state-duration": "440ms",
				"--studio-sidebar-state-ease":
					"linear(0, 0.004 1%, 0.029 3%, 0.1 6%, 0.196 9%, 0.548 19%, 0.639 22%, 0.719 25%, 0.787 28%, 0.844 31%, 0.89 34%, 0.937 38%, 0.969 42%, 0.991 46%, 1.012 55%, 1)",
				"--studio-toast-swipe-state-ease": "cubic-bezier(0.05, 0.7, 0.1, 1)",
				"--studio-switch-color-ease":
					"linear(0, 0.015 2%, 0.079 5%, 0.17 8%, 0.466 17%, 0.578 21%, 0.65 24%, 0.712 27%, 0.78 31%, 0.866 38%, 0.931 47%, 0.972 59%, 0.992 75%, 1)",
				"--studio-segmented-control-color-ease":
					"linear(0, 0.015 2%, 0.079 5%, 0.17 8%, 0.466 17%, 0.578 21%, 0.65 24%, 0.712 27%, 0.78 31%, 0.866 38%, 0.931 47%, 0.972 59%, 0.992 75%, 1)",
				"--studio-tabs-color-ease":
					"linear(0, 0.015 2%, 0.079 5%, 0.17 8%, 0.466 17%, 0.578 21%, 0.65 24%, 0.712 27%, 0.78 31%, 0.866 38%, 0.931 47%, 0.972 59%, 0.992 75%, 1)",
				"--studio-popover-enter-duration": "440ms",
				"--studio-popover-ease":
					"linear(0, 0.004 1%, 0.029 3%, 0.1 6%, 0.196 9%, 0.548 19%, 0.639 22%, 0.719 25%, 0.787 28%, 0.844 31%, 0.89 34%, 0.937 38%, 0.969 42%, 0.991 46%, 1.012 55%, 1)",
				"--studio-popover-exit-duration": "200ms",
				"--studio-popover-exit-ease": "cubic-bezier(0.3, 0, 0.8, 0.15)",
				"--studio-tooltip-enter-duration": "440ms",
				"--studio-tooltip-ease":
					"linear(0, 0.004 1%, 0.029 3%, 0.1 6%, 0.196 9%, 0.548 19%, 0.639 22%, 0.719 25%, 0.787 28%, 0.844 31%, 0.89 34%, 0.937 38%, 0.969 42%, 0.991 46%, 1.012 55%, 1)",
				"--studio-tooltip-exit-duration": "200ms",
				"--studio-tooltip-exit-ease": "cubic-bezier(0.3, 0, 0.8, 0.15)",
				"--studio-modal-enter-duration": "440ms",
				"--studio-modal-ease":
					"linear(0, 0.004 1%, 0.029 3%, 0.1 6%, 0.196 9%, 0.548 19%, 0.639 22%, 0.719 25%, 0.787 28%, 0.844 31%, 0.89 34%, 0.937 38%, 0.969 42%, 0.991 46%, 1.012 55%, 1)",
				"--studio-modal-exit-duration": "200ms",
				"--studio-modal-exit-ease": "cubic-bezier(0.3, 0, 0.8, 0.15)",
				"--studio-drawer-enter-duration": "600ms",
				"--studio-drawer-ease":
					"linear(0, 0.003 1%, 0.028 3%, 0.099 6%, 0.193 9%, 0.541 19%, 0.633 22%, 0.713 25%, 0.781 28%, 0.838 31%, 0.885 34%, 0.932 38%, 0.966 42%, 0.989 46%, 1.012 55%, 1.015 64%, 1)",
				"--studio-drawer-exit-duration": "200ms",
				"--studio-drawer-exit-ease": "cubic-bezier(0.3, 0, 0.8, 0.15)",
				"--studio-accordion-enter-duration": "240ms",
				"--studio-accordion-ease":
					"linear(0, 0.016 2%, 0.084 5%, 0.18 8%, 0.454 16%, 0.572 20%, 0.647 23%, 0.712 26%, 0.782 30%, 0.87 37%, 0.904 41%, 0.935 46%, 0.975 58%, 0.993 74%, 1)",
				"--studio-toast-enter-duration": "440ms",
				"--studio-toast-ease":
					"linear(0, 0.004 1%, 0.029 3%, 0.1 6%, 0.196 9%, 0.548 19%, 0.639 22%, 0.719 25%, 0.787 28%, 0.844 31%, 0.89 34%, 0.937 38%, 0.969 42%, 0.991 46%, 1.012 55%, 1)",
				"--studio-toast-exit-duration": "200ms",
				"--studio-toast-exit-ease": "cubic-bezier(0.3, 0, 0.8, 0.15)",
				"--studio-message-scroller-enter-duration": "440ms",
				"--studio-message-scroller-ease":
					"linear(0, 0.004 1%, 0.029 3%, 0.1 6%, 0.196 9%, 0.548 19%, 0.639 22%, 0.719 25%, 0.787 28%, 0.844 31%, 0.89 34%, 0.937 38%, 0.969 42%, 0.991 46%, 1.012 55%, 1)",
				"--studio-message-scroller-exit-duration": "200ms",
				"--studio-message-scroller-exit-ease": "cubic-bezier(0.3, 0, 0.8, 0.15)",
				"--studio-btn-radius": "var(--radius-full)",
				"--studio-btn-xs-radius": "var(--radius-full)",
				"--studio-checkbox-radius": "2px",
				"--color-scrim": "color-mix(in oklab, var(--color-overlay) 10%, transparent)",
				"--studio-scrim-blur": "0",
				"--studio-badge-radius": "var(--studio-radius-detail)",
			},
			density: "comfortable",
			color: {
				v: 2,
				seeds: { accent: "#6750a4", danger: "#b3261e" },
				background: { light: 98, dark: 6 },
				neutralTint: 2,
				neutralHue: 305,
				preserveSeed: true,
				primary: "accent",
			},
			icons: "remix",
		},
	},
];
