// AUTO-GENERATED - DO NOT EDIT
// Run "tsx scripts/registry-build.ts" to regenerate
import type { PresetMeta } from "../preset";
import type { DesignSystem } from "@/modules/studio/preset/types";

export const PRESET_CATALOG: Array<PresetMeta & { designSystem: DesignSystem }> = [
	{
		id: "origin",
		name: "Origin",
		description: "dotUI blue, the starting point.",
		swatch: "#0072f5",
		designSystem: {
			componentParams: {
				accordion: { container: "divided", marker: "chevron", markerPosition: "trailing" },
				avatar: { fallback: "neutral" },
				badge: { style: "solid" },
				breadcrumbs: { separator: "chevron", tone: "muted" },
				button: { style: "flat", hover: "dim", press: "dim" },
				calendar: { dayShape: "rounded", today: "none", weekdays: "single" },
				card: { style: "default" },
				chart: { grid: "solid" },
				checkbox: { "card-selected": "tint", "card-control": "start" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { header: "title" },
				drawer: { backdrop: "dim" },
				field: { error: "border" },
				group: { separator: "auto" },
				input: { style: "outline", hover: "none", addon: "inside" },
				kbd: { treatment: "chip" },
				link: { underline: "never", color: "accent" },
				"list-box": { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				modal: { backdrop: "dim", position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right" },
				"otp-field": { cells: "group" },
				pagination: { current: "outline" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", indeterminate: "slide", gap: "none" },
				"qr-code": { style: "squares" },
				"radio-group": { "card-selected": "tint", "card-control": "start" },
				"segmented-control": { selected: "flat", track: "filled" },
				select: { caret: "chevron" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "circle", track: "thin" },
				switch: { "card-selected": "tint" },
				table: { separation: "lines", header: "plain" },
				tabs: { style: "segmented", color: "neutral" },
				"tag-group": { style: "solid" },
				"toggle-button": { style: "flat", hover: "dim", press: "dim", selected: "fill" },
				"toggle-button-group": { separator: "auto" },
				tooltip: { style: "inverted", motion: "scale" },
			},
			tokens: {},
			density: "default",
			color: { v: 2, seeds: { accent: "#0072f5", selection: "#0072f5" }, background: { dark: 2 }, primary: "accent" },
		},
	},
	{
		id: "claude",
		name: "Claude",
		description: "Ink actions, clay highlights.",
		swatch: "#d97757",
		inspiredBy: "Claude",
		designSystem: {
			componentParams: {
				accordion: { container: "divided", marker: "chevron", markerPosition: "trailing" },
				avatar: { fallback: "neutral" },
				badge: { style: "soft" },
				breadcrumbs: { separator: "chevron", tone: "muted" },
				button: { style: "flat", hover: "dim", press: "scale" },
				calendar: { dayShape: "rounded", today: "none", weekdays: "single" },
				card: { style: "default" },
				chart: { grid: "solid" },
				checkbox: { "card-selected": "tint", "card-control": "start" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { header: "title" },
				drawer: { backdrop: "dim" },
				field: { error: "border" },
				group: { separator: "auto" },
				input: { style: "outline", hover: "none", addon: "inside" },
				kbd: { treatment: "chip" },
				link: { underline: "always", color: "neutral" },
				"list-box": { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				modal: { backdrop: "dim", position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right" },
				"otp-field": { cells: "group" },
				pagination: { current: "outline" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", indeterminate: "slide", gap: "none" },
				"qr-code": { style: "squares" },
				"radio-group": { "card-selected": "tint", "card-control": "start" },
				"segmented-control": { selected: "flat", track: "filled" },
				select: { caret: "chevron" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "circle", track: "thin" },
				switch: { "card-selected": "tint" },
				table: { separation: "lines", header: "plain" },
				tabs: { style: "line", color: "accent" },
				"tag-group": { style: "soft" },
				"toggle-button": { style: "flat", hover: "dim", press: "scale", selected: "fill" },
				"toggle-button-group": { separator: "auto" },
				tooltip: { style: "inverted", motion: "scale" },
			},
			tokens: {
				"--font-sans": "'Inter', ui-sans-serif, system-ui, sans-serif",
				"--font-heading": "'Source Serif 4', ui-serif, Georgia, serif",
				"--radius": "0.666875rem",
				"--card-border": "light-dark(var(--neutral-300), var(--neutral-200))",
				"--overlay-border": "light-dark(var(--neutral-300), var(--neutral-200))",
				"--shadow-card": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
				"--shadow-popover": "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
				"--shadow-modal": "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
				"--color-popover": "light-dark(var(--neutral-50), var(--neutral-100))",
				"--focus-ring-width": "1px",
				"--focus-ring-inner": "1px",
				"--focus-ring-offset": "0px",
				"--focus-input-width": "var(--focus-ring-width)",
				"--focus-input-offset": "var(--focus-ring-offset)",
				"--focus-input-inner": "var(--focus-ring-inner)",
				"--focus-input-color": "var(--focus-ring-color)",
				"--default-transition-duration": "100ms",
			},
			density: "default",
			color: {
				v: 2,
				seeds: { accent: "#d97757", warning: "#fab219", danger: "#d03b3b", selection: "#2a78d6" },
				background: { dark: 7 },
				neutralHue: 96,
			},
			icons: "phosphor",
		},
	},
	{
		id: "supabase",
		name: "Supabase",
		description: "Emerald on neutral graphite.",
		swatch: "#34b27b",
		inspiredBy: "Supabase",
		designSystem: {
			componentParams: {
				accordion: { container: "divided", marker: "chevron", markerPosition: "trailing" },
				avatar: { fallback: "neutral" },
				badge: { style: "soft-outline" },
				breadcrumbs: { separator: "chevron", tone: "muted" },
				button: { style: "outline", hover: "dim", press: "scale" },
				calendar: { dayShape: "rounded", today: "none", weekdays: "single" },
				card: { style: "default" },
				chart: { grid: "solid" },
				checkbox: { "card-selected": "tint", "card-control": "start" },
				"color-editor": { style: "default" },
				command: { search: "bar", inset: "inset", scale: "large" },
				dialog: { header: "title" },
				drawer: { backdrop: "blur" },
				field: { error: "border" },
				group: { separator: "auto" },
				input: { style: "outline", hover: "border", addon: "inside" },
				kbd: { treatment: "chip" },
				link: { underline: "always", color: "neutral" },
				"list-box": { indicator: "check-start", highlight: "neutral", inset: "inset", labels: "caps" },
				loader: { style: "ring" },
				menu: { indicator: "check-start", highlight: "neutral", inset: "inset", labels: "caps" },
				modal: { backdrop: "blur", position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right" },
				"otp-field": { cells: "group" },
				pagination: { current: "outline" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", indeterminate: "slide", gap: "none" },
				"qr-code": { style: "squares" },
				"radio-group": { "card-selected": "tint", "card-control": "start" },
				"segmented-control": { selected: "flat", track: "filled" },
				select: { caret: "chevron" },
				skeleton: { animation: "pulse" },
				slider: { thumb: "circle", track: "thin" },
				switch: { "card-selected": "tint" },
				table: { separation: "lines", header: "filled" },
				tabs: { style: "line", color: "neutral" },
				"tag-group": { style: "soft-outline" },
				"toggle-button": { style: "outline", hover: "dim", press: "scale", selected: "fill" },
				"toggle-button-group": { separator: "auto" },
				tooltip: { style: "surface", motion: "scale" },
			},
			tokens: {
				"--font-sans": "'Inter', ui-sans-serif, system-ui, sans-serif",
				"--font-heading": "'Manrope', ui-sans-serif, system-ui, sans-serif",
				"--font-mono": "'Source Code Pro', ui-monospace, 'SF Mono', monospace",
				"--radius": "0.65625rem",
				"--studio-radius-panel": "var(--radius-lg)",
				"--studio-radius-surface": "var(--radius-md)",
				"--studio-radius-item": "var(--radius-xs)",
				"--focus-input-width": "var(--focus-ring-width)",
				"--focus-input-offset": "var(--focus-ring-offset)",
				"--focus-input-inner": "var(--focus-ring-inner)",
				"--focus-input-color": "var(--focus-ring-color)",
				"--disabled-bg": "initial",
				"--disabled-fg": "initial",
				"--disabled-border": "initial",
				"--disabled-selected-bg": "initial",
				"--disabled-selected-fg": "initial",
				"--disabled-unselected-bg": "initial",
				"--color-primary-disabled": "initial",
				"--disabled-opacity": "0.5",
				"--studio-slider-fill-color": "var(--color-inverse)",
			},
			density: "default",
			color: {
				v: 2,
				seeds: { accent: "#3ecf8e" },
				background: { dark: 6 },
				neutralTint: 0.3,
				neutralHue: 160,
				preserveSeed: true,
				primary: "accent",
				selection: "neutral",
				scopes: { switch: "accent", radio: "accent" },
			},
		},
	},
	{
		id: "stripe",
		name: "Stripe",
		description: "Blurple fills, cool slate hairlines.",
		swatch: "#675dff",
		inspiredBy: "Stripe",
		designSystem: {
			componentParams: {
				accordion: { container: "divided", marker: "chevron", markerPosition: "trailing" },
				avatar: { fallback: "neutral" },
				badge: { style: "soft-outline" },
				breadcrumbs: { separator: "chevron", tone: "muted" },
				button: { style: "flat", hover: "dim", press: "dim" },
				calendar: { dayShape: "rounded", today: "none", weekdays: "single" },
				card: { style: "default" },
				chart: { grid: "solid" },
				checkbox: { "card-selected": "tint", "card-control": "start" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { header: "title" },
				drawer: { backdrop: "dim" },
				field: { error: "border" },
				group: { separator: "auto" },
				input: { style: "outline", hover: "none", addon: "inside" },
				kbd: { treatment: "chip" },
				link: { underline: "never", color: "accent" },
				"list-box": { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				modal: { backdrop: "dim", position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right" },
				"otp-field": { cells: "group" },
				pagination: { current: "outline" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", indeterminate: "slide", gap: "none" },
				"qr-code": { style: "squares" },
				"radio-group": { "card-selected": "tint", "card-control": "start" },
				"segmented-control": { selected: "flat", track: "filled" },
				select: { caret: "double" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "circle", track: "thin" },
				switch: { "card-selected": "tint" },
				table: { separation: "lines", header: "plain" },
				tabs: { style: "line", color: "accent" },
				"tag-group": { style: "soft-outline" },
				"toggle-button": { style: "flat", hover: "dim", press: "dim", selected: "fill" },
				"toggle-button-group": { separator: "auto" },
				tooltip: { style: "inverted", motion: "scale" },
			},
			tokens: {
				"--font-sans": "'Inter', ui-sans-serif, system-ui, sans-serif",
				"--font-mono": "'Source Code Pro', ui-monospace, 'SF Mono', monospace",
				"--radius": "0.5rem",
				"--studio-radius-control": "var(--radius-lg)",
				"--studio-radius-item": "var(--radius-sm)",
				"--studio-radius-control-sm": "var(--radius-md)",
				"--card-border": "light-dark(var(--neutral-300), var(--neutral-200))",
				"--overlay-border": "light-dark(var(--neutral-300), var(--neutral-200))",
				"--shadow-card": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
				"--shadow-popover": "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
				"--shadow-modal": "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
				"--color-popover": "light-dark(var(--neutral-50), var(--neutral-100))",
				"--focus-ring-inner": "1px",
				"--focus-ring-offset": "0px",
				"--focus-input-width": "4px",
				"--focus-input-color": "color-mix(in oklab, var(--color-border-focus) 35%, transparent)",
				"--studio-badge-radius": "var(--radius-sm)",
				"--studio-tag-radius": "var(--radius-sm)",
			},
			density: "default",
			color: {
				v: 2,
				seeds: { accent: "#533afd", success: "#228403", danger: "#df1b41" },
				background: { light: 100, dark: 2 },
				neutralTint: 2,
				neutralHue: 260,
				primary: "accent",
			},
		},
	},
	{
		id: "linear",
		name: "Linear",
		description: "Indigo on near-black, pill actions.",
		swatch: "#828fff",
		inspiredBy: "Linear",
		designSystem: {
			componentParams: {
				accordion: { container: "divided", marker: "chevron", markerPosition: "trailing" },
				avatar: { fallback: "neutral" },
				badge: { style: "outline" },
				breadcrumbs: { separator: "chevron", tone: "muted" },
				button: { style: "flat", hover: "lighten", press: "none" },
				calendar: { dayShape: "rounded", today: "none", weekdays: "single" },
				card: { style: "default" },
				chart: { grid: "solid" },
				checkbox: { "card-selected": "tint", "card-control": "start" },
				"color-editor": { style: "default" },
				command: { search: "prompt", inset: "inset", scale: "default" },
				dialog: { header: "title" },
				drawer: { backdrop: "dim" },
				field: { error: "border" },
				group: { separator: "auto" },
				input: { style: "outline", hover: "border", addon: "inside" },
				kbd: { treatment: "chip" },
				link: { underline: "never", color: "accent" },
				"list-box": { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				modal: { backdrop: "dim", position: "top", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right" },
				"otp-field": { cells: "group" },
				pagination: { current: "outline" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", indeterminate: "slide", gap: "none" },
				"qr-code": { style: "squares" },
				"radio-group": { "card-selected": "tint", "card-control": "start" },
				"segmented-control": { selected: "flat", track: "filled" },
				select: { caret: "chevron" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "circle", track: "thin" },
				switch: { "card-selected": "tint" },
				table: { separation: "lines", header: "plain" },
				tabs: { style: "pill", color: "neutral" },
				"tag-group": { style: "outline" },
				"toggle-button": { style: "flat", hover: "lighten", press: "none", selected: "fill" },
				"toggle-button-group": { separator: "auto" },
				tooltip: { style: "surface", motion: "scale" },
			},
			tokens: {
				"--font-sans": "'Inter', ui-sans-serif, system-ui, sans-serif",
				"--radius": "0.5rem",
				"--card-border": "light-dark(var(--neutral-300), var(--neutral-200))",
				"--overlay-border": "light-dark(var(--neutral-300), var(--neutral-200))",
				"--shadow-card": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
				"--shadow-popover": "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
				"--shadow-modal": "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)",
				"--color-popover": "light-dark(var(--neutral-50), var(--neutral-100))",
				"--focus-ring-width": "1px",
				"--focus-input-inset": "inset",
				"--focus-input-offset": "0px",
				"--focus-input-width": "0px",
				"--focus-input-color": "var(--color-border-focus)",
				"--cursor-interactive": "default",
				"--cursor-disabled": "default",
				"--scrollbar-width": "thin",
				"--scrollbar-color": "var(--color-border) transparent",
				"--disabled-bg": "initial",
				"--disabled-fg": "initial",
				"--disabled-border": "initial",
				"--disabled-selected-bg": "initial",
				"--disabled-selected-fg": "initial",
				"--disabled-unselected-bg": "initial",
				"--color-primary-disabled": "initial",
				"--disabled-opacity": "0.5",
				"--transition-duration-enter": "120ms",
				"--transition-duration-exit": "90ms",
				"--default-transition-duration": "0ms",
				"--studio-btn-radius": "var(--radius-full)",
			},
			density: "default",
			color: {
				v: 2,
				seeds: { accent: "#5e6ad2", success: "#27a644", danger: "#eb5757" },
				background: { dark: 2 },
				neutralHue: 262,
				primary: "accent",
			},
		},
	},
	{
		id: "vercel",
		name: "Vercel",
		description: "Monochrome ink, Geist blue accents.",
		swatch: "#8f8f8f",
		inspiredBy: "Vercel",
		designSystem: {
			componentParams: {
				accordion: { container: "divided", marker: "chevron", markerPosition: "trailing" },
				avatar: { fallback: "neutral" },
				badge: { style: "solid" },
				breadcrumbs: { separator: "chevron", tone: "muted" },
				button: { style: "flat", hover: "dim", press: "none" },
				calendar: { dayShape: "rounded", today: "none", weekdays: "single" },
				card: { style: "default" },
				chart: { grid: "solid" },
				checkbox: { "card-selected": "outline-tint", "card-control": "end" },
				"color-editor": { style: "default" },
				command: { search: "prompt", inset: "inset", scale: "default" },
				dialog: { header: "title" },
				drawer: { backdrop: "dim" },
				field: { error: "border" },
				group: { separator: "auto" },
				input: { style: "outline", hover: "border", addon: "inside" },
				kbd: { treatment: "chip" },
				link: { underline: "never", color: "accent" },
				"list-box": { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				loader: { style: "blades" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				modal: { backdrop: "dim", position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right" },
				"otp-field": { cells: "group" },
				pagination: { current: "outline" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", indeterminate: "slide", gap: "none" },
				"qr-code": { style: "squares" },
				"radio-group": { "card-selected": "outline-tint", "card-control": "end" },
				"segmented-control": { selected: "flat", track: "outline" },
				select: { caret: "chevron" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "circle", track: "thin" },
				switch: { "card-selected": "outline-tint" },
				table: { separation: "lines", header: "plain" },
				tabs: { style: "line", color: "neutral" },
				"tag-group": { style: "solid" },
				"toggle-button": { style: "flat", hover: "dim", press: "none", selected: "fill" },
				"toggle-button-group": { separator: "auto" },
				tooltip: { style: "inverted", motion: "scale" },
			},
			tokens: {
				"--icon-stroke-width": "2.25",
				"--radius": "0.5rem",
				"--studio-radius-surface": "var(--radius-xl)",
				"--focus-input-width": "3px",
			},
			density: "comfortable",
			color: {
				v: 2,
				seeds: { accent: "#0072f5", success: "#45a557", warning: "#ffb224", danger: "#e5484d" },
				background: { light: 100, dark: "oled" },
				neutralTint: 0,
				scopes: { switch: "accent" },
			},
		},
	},
	{
		id: "airbnb",
		name: "Airbnb",
		description: "Rausch accents, ink actions.",
		swatch: "#ff385c",
		inspiredBy: "Airbnb",
		designSystem: {
			componentParams: {
				accordion: { container: "divided", marker: "chevron", markerPosition: "trailing" },
				avatar: { fallback: "neutral" },
				badge: { style: "soft" },
				breadcrumbs: { separator: "chevron", tone: "muted" },
				button: { style: "flat", hover: "dim", press: "scale" },
				calendar: { dayShape: "circle", today: "none", weekdays: "double" },
				card: { style: "default" },
				chart: { grid: "solid" },
				checkbox: { "card-selected": "outline-tint", "card-control": "hidden" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "full-bleed", scale: "default" },
				dialog: { header: "title" },
				drawer: { backdrop: "dim" },
				field: { error: "border" },
				group: { separator: "auto" },
				input: { style: "outline", hover: "border", addon: "inside" },
				kbd: { treatment: "chip" },
				link: { underline: "always", color: "neutral" },
				"list-box": { indicator: "check-end", highlight: "neutral", inset: "full-bleed", labels: "sentence" },
				loader: { style: "dots" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "full-bleed", labels: "sentence" },
				modal: { backdrop: "dim", position: "center", motion: "slide", mobile: "sheet" },
				"number-field": { steppers: "split" },
				"otp-field": { cells: "group" },
				pagination: { current: "filled" },
				popover: { motion: "slide", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", indeterminate: "slide", gap: "none" },
				"qr-code": { style: "squares" },
				"radio-group": { "card-selected": "outline-tint", "card-control": "hidden" },
				"segmented-control": { selected: "raised", track: "outline" },
				select: { caret: "chevron" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "outline", track: "thin" },
				switch: { "card-selected": "outline-tint" },
				table: { separation: "lines", header: "plain" },
				tabs: { style: "line", color: "neutral" },
				"tag-group": { style: "soft" },
				"toggle-button": { style: "flat", hover: "dim", press: "scale", selected: "fill" },
				"toggle-button-group": { separator: "auto" },
				tooltip: { style: "inverted", motion: "slide" },
			},
			tokens: {
				"--font-sans": "'Plus Jakarta Sans', ui-sans-serif, system-ui, sans-serif",
				"--radius": "1rem",
				"--studio-radius-surface": "var(--radius-md)",
				"--studio-radius-item": "var(--radius-sm)",
				"--spacing": "0.28125rem",
				"--card-border": "light-dark(transparent, var(--neutral-200))",
				"--overlay-border": "light-dark(transparent, var(--neutral-200))",
				"--shadow-card":
					"0 1px 3px 0 light-dark(rgb(0 0 0 / 0.1), transparent), 0 1px 2px -1px light-dark(rgb(0 0 0 / 0.1), transparent)",
				"--shadow-popover":
					"0 10px 15px -3px light-dark(rgb(0 0 0 / 0.1), transparent), 0 4px 6px -4px light-dark(rgb(0 0 0 / 0.1), transparent)",
				"--shadow-modal":
					"0 20px 25px -5px light-dark(rgb(0 0 0 / 0.1), transparent), 0 8px 10px -6px light-dark(rgb(0 0 0 / 0.1), transparent)",
				"--color-popover": "light-dark(var(--neutral-50), var(--neutral-100))",
				"--focus-input-inset": "inset",
				"--focus-input-offset": "0px",
				"--focus-input-width": "1px",
				"--focus-input-color": "var(--color-border-focus)",
				"--color-text-selection": "Highlight",
				"--color-fg-on-text-selection": "HighlightText",
				"--ease-enter": "cubic-bezier(0.05, 0.7, 0.1, 1)",
				"--transition-duration-enter": "280ms",
				"--transition-duration-exit": "200ms",
				"--studio-checkbox-radius": "var(--radius-xs)",
				"--studio-badge-radius": "var(--radius-sm)",
				"--studio-tag-radius": "var(--radius-sm)",
			},
			density: "comfortable",
			color: {
				v: 2,
				seeds: { accent: "#ff385c", success: "#038026", warning: "#eb6100", danger: "#d7251c" },
				background: { light: 100, dark: 5 },
				neutralTint: 0,
				preserveSeed: true,
				overrides: {
					"color-border-focus": { palette: "neutral", job: "solid" },
					"color-border-focus-muted": { palette: "neutral", job: "ui-active" },
				},
			},
		},
	},
	{
		id: "github",
		name: "GitHub",
		description: "Green actions, blue selection.",
		swatch: "#1f883d",
		inspiredBy: "GitHub",
		designSystem: {
			componentParams: {
				accordion: { container: "divided", marker: "chevron", markerPosition: "trailing" },
				avatar: { fallback: "neutral" },
				badge: { style: "outline" },
				breadcrumbs: { separator: "slash", tone: "muted" },
				button: { style: "outline", hover: "dim", press: "dim" },
				calendar: { dayShape: "rounded", today: "none", weekdays: "single" },
				card: { style: "default" },
				chart: { grid: "solid" },
				checkbox: { "card-selected": "tint", "card-control": "start" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { header: "title" },
				drawer: { backdrop: "dim" },
				field: { error: "border" },
				group: { separator: "auto" },
				input: { style: "outline", hover: "none", addon: "inside" },
				kbd: { treatment: "keycap" },
				link: { underline: "always", color: "neutral" },
				"list-box": { indicator: "check-start", highlight: "neutral", inset: "inset", labels: "sentence" },
				loader: { style: "ring" },
				menu: { indicator: "check-start", highlight: "neutral", inset: "inset", labels: "sentence" },
				modal: { backdrop: "dim", position: "center", motion: "fade", mobile: "center" },
				"number-field": { steppers: "right" },
				"otp-field": { cells: "group" },
				pagination: { current: "outline" },
				popover: { motion: "fade", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thick", indeterminate: "slide", gap: "none" },
				"qr-code": { style: "squares" },
				"radio-group": { "card-selected": "tint", "card-control": "start" },
				"segmented-control": { selected: "raised", track: "filled" },
				select: { caret: "double" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "circle", track: "thin" },
				switch: { "card-selected": "tint" },
				table: { separation: "lines", header: "filled" },
				tabs: { style: "line", color: "neutral" },
				"tag-group": { style: "outline" },
				"toggle-button": { style: "outline", hover: "dim", press: "dim", selected: "fill" },
				"toggle-button-group": { separator: "auto" },
				tooltip: { style: "inverted", motion: "fade" },
			},
			tokens: {
				"--font-sans": "'Mona Sans', ui-sans-serif, system-ui, sans-serif",
				"--radius": "0.5rem",
				"--studio-radius-surface": "var(--radius-xl)",
				"--focus-ring-inner": "1px",
				"--focus-ring-offset": "0px",
				"--focus-input-inset": "inset",
				"--focus-input-offset": "0px",
				"--focus-input-width": "1px",
				"--focus-input-color": "var(--color-border-focus)",
				"--color-text-selection": "Highlight",
				"--color-fg-on-text-selection": "HighlightText",
				"--default-transition-duration": "100ms",
			},
			density: "default",
			color: {
				v: 2,
				seeds: { accent: "#1f883d", success: "#1f883d", warning: "#9a6700", danger: "#cf222e", selection: "#0969da" },
				background: { light: 100, dark: 5 },
				neutralTint: 1.4,
				neutralHue: 251,
				preserveSeed: true,
				primary: "accent",
			},
		},
	},
	{
		id: "notion",
		name: "Notion",
		description: "Warm ink, quiet blue.",
		swatch: "#8e8b86",
		inspiredBy: "Notion",
		designSystem: {
			componentParams: {
				accordion: { container: "divided", marker: "chevron", markerPosition: "leading" },
				avatar: { fallback: "neutral" },
				badge: { style: "soft" },
				breadcrumbs: { separator: "slash", tone: "muted" },
				button: { style: "flat", hover: "dim", press: "dim" },
				calendar: { dayShape: "rounded", today: "none", weekdays: "single" },
				card: { style: "default" },
				chart: { grid: "solid" },
				checkbox: { "card-selected": "tint", "card-control": "start" },
				"color-editor": { style: "default" },
				command: { search: "bar", inset: "inset", scale: "default" },
				dialog: { header: "title" },
				drawer: { backdrop: "dim" },
				field: { error: "border" },
				group: { separator: "auto" },
				input: { style: "outline", hover: "none", addon: "inside" },
				kbd: { treatment: "text" },
				link: { underline: "always", color: "neutral" },
				"list-box": { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				modal: { backdrop: "dim", position: "center", motion: "scale", mobile: "center" },
				"number-field": { steppers: "right" },
				"otp-field": { cells: "group" },
				pagination: { current: "outline" },
				popover: { motion: "scale", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", indeterminate: "slide", gap: "none" },
				"qr-code": { style: "squares" },
				"radio-group": { "card-selected": "tint", "card-control": "start" },
				"segmented-control": { selected: "flat", track: "filled" },
				select: { caret: "chevron" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "circle", track: "thin" },
				switch: { "card-selected": "tint" },
				table: { separation: "lines", header: "plain" },
				tabs: { style: "pill", color: "neutral" },
				"tag-group": { style: "soft" },
				"toggle-button": { style: "flat", hover: "dim", press: "dim", selected: "fill" },
				"toggle-button-group": { separator: "auto" },
				tooltip: { style: "inverted", motion: "scale" },
			},
			tokens: {
				"--font-sans": "'Inter', ui-sans-serif, system-ui, sans-serif",
				"--radius": "0.5rem",
				"--spacing": "0.21875rem",
				"--focus-input-inset": "inset",
				"--focus-input-offset": "0px",
				"--focus-input-width": "1px",
				"--focus-input-color": "var(--color-border-focus)",
				"--cursor-disabled": "default",
				"--cursor-drag": "grab",
				"--cursor-dragging": "grabbing",
				"--disabled-bg": "initial",
				"--disabled-fg": "initial",
				"--disabled-border": "initial",
				"--disabled-selected-bg": "initial",
				"--disabled-selected-fg": "initial",
				"--disabled-unselected-bg": "initial",
				"--color-primary-disabled": "initial",
				"--disabled-opacity": "0.5",
				"--default-transition-duration": "100ms",
				"--studio-badge-radius": "var(--radius-sm)",
				"--studio-tag-radius": "var(--radius-sm)",
			},
			density: "default",
			color: {
				v: 2,
				seeds: { accent: "#2783de" },
				background: { light: 100, dark: 8.8 },
				neutralTint: 0.5,
				neutralHue: 81,
				primary: "accent",
			},
		},
	},
	{
		id: "spotify",
		name: "Spotify",
		description: "Vivid green on near-black.",
		swatch: "#1ed760",
		inspiredBy: "Spotify",
		designSystem: {
			componentParams: {
				accordion: { container: "divided", marker: "chevron", markerPosition: "trailing" },
				avatar: { fallback: "neutral" },
				badge: { style: "soft" },
				breadcrumbs: { separator: "chevron", tone: "muted" },
				button: { style: "flat", hover: "lighten", press: "dim" },
				calendar: { dayShape: "rounded", today: "none", weekdays: "single" },
				card: { style: "default" },
				chart: { grid: "solid" },
				checkbox: { "card-selected": "tint", "card-control": "start" },
				"color-editor": { style: "default" },
				command: { search: "field", inset: "inset", scale: "default" },
				dialog: { header: "title" },
				drawer: { backdrop: "dim" },
				field: { error: "border" },
				group: { separator: "auto" },
				input: { style: "filled", hover: "tint", addon: "inside" },
				kbd: { treatment: "chip" },
				link: { underline: "hover", color: "neutral" },
				"list-box": { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				loader: { style: "ring" },
				menu: { indicator: "check-end", highlight: "neutral", inset: "inset", labels: "sentence" },
				modal: { backdrop: "dim", position: "center", motion: "slide", mobile: "center" },
				"number-field": { steppers: "right" },
				"otp-field": { cells: "group" },
				pagination: { current: "outline" },
				popover: { motion: "slide", mobile: "drawer", tip: "none" },
				"progress-bar": { track: "thin", indeterminate: "slide", gap: "none" },
				"qr-code": { style: "squares" },
				"radio-group": { "card-selected": "tint", "card-control": "start" },
				"segmented-control": { selected: "flat", track: "filled" },
				select: { caret: "chevron" },
				skeleton: { animation: "shimmer" },
				slider: { thumb: "circle", track: "thin" },
				switch: { "card-selected": "tint" },
				table: { separation: "lines", header: "plain" },
				tabs: { style: "line", color: "neutral" },
				"tag-group": { style: "soft" },
				"toggle-button": { style: "flat", hover: "lighten", press: "dim", selected: "inverse" },
				"toggle-button-group": { separator: "auto" },
				tooltip: { style: "surface", motion: "slide" },
			},
			tokens: {
				"--font-sans": "'Figtree', ui-sans-serif, system-ui, sans-serif",
				"--radius": "0.5rem",
				"--studio-radius-panel": "var(--radius-lg)",
				"--studio-radius-control": "var(--radius-full)",
				"--studio-radius-control-sm": "var(--radius-3xl)",
				"--card-border": "transparent",
				"--overlay-border": "transparent",
				"--shadow-popover": "0 1px 3px 0 rgb(0 0 0 / 0.08), 0 1px 2px -1px rgb(0 0 0 / 0.08)",
				"--shadow-modal": "0 4px 6px -1px rgb(0 0 0 / 0.08), 0 2px 4px -2px rgb(0 0 0 / 0.08)",
				"--color-card": "color-mix(in oklab, var(--neutral-50) 65%, var(--neutral-100))",
				"--color-popover": "color-mix(in oklab, var(--neutral-50) 30%, var(--neutral-100))",
				"--focus-ring-inner": "1px",
				"--focus-ring-offset": "0px",
				"--focus-input-width": "var(--focus-ring-width)",
				"--focus-input-offset": "var(--focus-ring-offset)",
				"--focus-input-inner": "var(--focus-ring-inner)",
				"--focus-input-color": "var(--focus-ring-color)",
				"--color-text-selection": "Highlight",
				"--color-fg-on-text-selection": "HighlightText",
				"--scrollbar-width": "thin",
				"--scrollbar-color": "transparent transparent",
				"--scrollbar-color-hover": "var(--color-border) transparent",
				"--disabled-bg": "initial",
				"--disabled-fg": "initial",
				"--disabled-border": "initial",
				"--disabled-selected-bg": "initial",
				"--disabled-selected-fg": "initial",
				"--disabled-unselected-bg": "initial",
				"--color-primary-disabled": "initial",
				"--disabled-opacity": "0.5",
				"--transition-duration-enter": "250ms",
				"--transition-duration-exit": "188ms",
				"--default-transition-duration": "188ms",
				"--studio-btn-radius": "var(--radius-full)",
				"--studio-slider-fill-color": "var(--color-inverse)",
				"--studio-badge-radius": "var(--radius-sm)",
				"--studio-tag-radius": "var(--radius-sm)",
			},
			density: "comfortable",
			color: {
				v: 2,
				seeds: { accent: "#1ed760", success: "#1ed760", warning: "#ffa42b", danger: "#e91429" },
				background: { light: 100, dark: 5.5 },
				neutralTint: 0,
				preserveSeed: true,
				primary: "accent",
				overrides: {
					"color-border-focus": { palette: "neutral", job: "solid" },
					"color-border-focus-muted": { palette: "neutral", job: "ui-active" },
				},
			},
		},
	},
];
