import { existsSync, promises as fs } from "node:fs";
import path from "node:path";
import { rimraf } from "rimraf";

const INTERNAL_REGISTRY_PATH = path.join(process.cwd(), "src/__registry__");

// ----------------------------------------------------------------------------
//
// ----------------------------------------------------------------------------
async function setup() {
  const targetPath = INTERNAL_REGISTRY_PATH;
  rimraf.sync(targetPath);
  if (!existsSync(targetPath)) {
    await fs.mkdir(targetPath, { recursive: true });
  }
  const autogeneratedFilePath = path.join(targetPath, ".autogenerated");
  await fs.writeFile(
    autogeneratedFilePath,
    "This directory is autogenerated. Do not edit its contents directly.",
    "utf8"
  );
}

// ----------------------------------------------------------------------------
//
// ----------------------------------------------------------------------------
async function buildDemos() {
  const targetPath = INTERNAL_REGISTRY_PATH;

  let index = `// This file is autogenerated by scripts/build-internal-registry.ts
  // Do not edit this file directly.
  import * as React from "react"
  
  export const Index: Record<
    string,
    {
      files: string[];
      component: React.LazyExoticComponent<React.ComponentType<object>>;
    }
  > = {
  `;

  const sourcePath = path.join(process.cwd(), "src/modules/docs/demos");
  const folders = await fs.readdir(sourcePath);
  for (const folder of folders) {
    const folderPath = path.join(sourcePath, folder);
    // replace tsx with empty string
    const primitiveName = folder.replace(".tsx", "");
    const demos = await fs.readdir(folderPath);
    for (const demo of demos) {
      const demoName = `${primitiveName}/${demo.replace(".tsx", "")}`;
      const demoPath = `@/modules/docs/demos/${primitiveName}/${demo.replace(".tsx", "")}`;
      index += `
      "${demoName}": {
        files: ["modules/docs/demos/${primitiveName}/${demo}"],
        component: React.lazy(() => import("${demoPath}")),
      },`;
    }
  }

  index += `
}
`;
  rimraf.sync(path.join(targetPath, "demos.tsx"));
  await fs.writeFile(path.join(targetPath, "demos.tsx"), index, "utf8");
}

// get all files in src/modules/registry/ui and place them in __registry__/ui and transform all the imports starting with @/modules/registry/ui/ to @/components/dynamic-ui/
async function buildDynamicComponents() {
  const targetPath = path.join(INTERNAL_REGISTRY_PATH, "ui");
  const sourcePath = path.join(process.cwd(), "src/modules/registry/ui");
  const files = await fs.readdir(sourcePath);

  for (const file of files) {
    const filePath = path.join(sourcePath, file);
    const content = await fs.readFile(filePath, "utf8");
    const newContent = content.replace(/@\/modules\/registry\/ui\//g, "@/components/dynamic-ui/");
    await fs.writeFile(path.join(targetPath, file), newContent, "utf8");
  }
}

async function run() {
  try {
    await setup();
    await buildDemos();
    await buildDynamicComponents();
    console.log("✅ Done!");
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
}

run();
