// This file is synced from @dotui/registry
// Do not edit this file directly - it will be overwritten

"use client";

import type { FieldProps } from "@/components/field";
import type { ListBoxItemProps } from "@/components/list-box";
import type { ComboBoxProps as AriaComboboxProps } from "react-aria-components";
import * as React from "react";
import { Button } from "@/components/button";
import { HelpText, Label } from "@/components/field";
import { Input, InputRoot } from "@/components/input";
import { ListBox, ListBoxItem } from "@/components/list-box";
import { Overlay } from "@/components/overlay";
import { ChevronDownIcon } from "lucide-react";
import { ComboBox as AriaCombobox } from "react-aria-components";
import { tv } from "tailwind-variants";

const comboboxStyles = tv({
  slots: {
    root: "flex w-48 flex-col items-start gap-2",
  },
});

interface ComboboxProps<T extends object>
  extends Omit<ComboboxRootProps<T>, "children">,
    Omit<FieldProps, "children"> {
  isLoading?: boolean;
  children: React.ReactNode | ((item: T) => React.ReactNode);
  items?: Iterable<T>;
}
const Combobox = <T extends object>({
  label,
  description,
  errorMessage,
  children,
  items,
  isLoading,
  ...props
}: ComboboxProps<T>) => {
  return (
    <ComboboxRoot {...props}>
      {label && <Label>{label}</Label>}
      <ComboboxInput />
      <HelpText description={description} errorMessage={errorMessage} />
      <Overlay type="popover">
        <ListBox items={items} isLoading={isLoading}>
          {children}
        </ListBox>
      </Overlay>
    </ComboboxRoot>
  );
};

const ComboboxInput = () => {
  return (
    <InputRoot className="px-0">
      <Input className="pl-2" />
      <Button variant="default" shape="square" className="my-1 mr-1 size-7">
        <ChevronDownIcon />
      </Button>
    </InputRoot>
  );
};

interface ComboboxRootProps<T extends object>
  extends Omit<AriaComboboxProps<T>, "className"> {
  className?: string;
}
const ComboboxRoot = <T extends object>({
  className,
  ...props
}: ComboboxRootProps<T>) => {
  const { root } = comboboxStyles();
  return <AriaCombobox className={root({ className })} {...props} />;
};

interface ComboboxItemProps<T> extends ListBoxItemProps<T> {}
const ComboboxItem = ListBoxItem;

export type { ComboboxProps, ComboboxRootProps, ComboboxItemProps };
export { Combobox, ComboboxRoot, ComboboxInput, ComboboxItem };
