export const serifFonts = [
  "Playfair Display",
  "Merriweather",
  "Roboto Slab",
  "Lora",
  "PT Serif",
  "Noto Serif",
  "Libre Baskerville",
  "EB Garamond",
  "Noto Serif JP",
  "Bitter",
  "Crimson Text",
  "Slabo 27px",
  "Arvo",
  "Cormorant Garamond",
  "Zilla Slab",
  "Nanum Myeongjo",
  "DM Serif Display",
  "IBM Plex Serif",
  "Source Serif 4",
  "Frank Ruhl Libre",
  "Cinzel",
  "Marcellus",
  "Domine",
  "Vollkorn",
  "Cormorant",
  "Bree Serif",
  "Spectral",
  "Alegreya",
  "Bodoni Moda",
  "Tinos",
  "Prata",
  "Cardo",
  "Noto Serif KR",
  "Amiri",
  "Antic Slab",
  "Martel",
  "Noto Serif TC",
  "Sawarabi Mincho",
  "Roboto Serif",
  "Noticia Text",
  "Crimson Pro",
  "Crete Round",
  "Old Standard TT",
  "Eczar",
  "DM Serif Text",
  "Rokkitt",
  "Libre Caslon Text",
  "Sanchez",
  "Quattrocento",
  "Josefin Slab",
  "Shippori Mincho",
  "Unna",
  "Aleo",
  "Baskervville",
  "Noto Naskh Arabic",
  "Taviraj",
  "Literata",
  "Neuton",
  "Gelasio",
  "Sorts Mill Goudy",
  "Playfair Display SC",
  "Fraunces",
  "Alice",
  "Gilda Display",
  "Libre Bodoni",
  "Vidaloka",
  "STIX Two Text",
  "Faustina",
  "Abhaya Libre",
  "Pridi",
  "Newsreader",
  "Noto Serif Bengali",
  "Playfair",
  "Noto Serif SC",
  "Ultra",
  "Volkhov",
  "Zen Old Mincho",
  "Lusitana",
  "Cormorant Infant",
  "Mate",
  "Holtwood One SC",
  "Arapey",
  "Rufina",
  "Noto Nastaliq Urdu",
  "Judson",
  "Petrona",
  "Adamina",
  "Yrsa",
  "Young Serif",
  "Kameron",
  "Kaisei Decol",
  "Noto Serif Display",
  "Karma",
  "Bevan",
  "Shippori Mincho B1",
  "Kreon",
  "Gupter",
  "Suez One",
  "PT Serif Caption",
  "Glegoo",
  "Podkova",
  "Kiwi Maru",
  "Rozha One",
  "Marcellus SC",
  "Cantata One",
  "Graduate",
  "Enriqueta",
  "Italiana",
  "Noto Serif Devanagari",
  "Ovo",
  "BioRhyme",
  "Yuji Mai",
  "Brygada 1918",
  "Lateef",
  "Caudex",
  "Andada Pro",
  "Trirong",
  "Ibarra Real Nova",
  "Lustria",
  "Oranienbaum",
  "Castoro",
  "Inria Serif",
  "Zilla Slab Highlight",
  "Bellefair",
  "Maitree",
  "Hepta Slab",
  "Halant",
  "Caladea",
  "Besley",
  "Cormorant Upright",
  "Solway",
  "Gowun Batang",
  "Goudy Bookletter 1911",
  "Kurale",
  "Arbutus Slab",
  "Alegreya SC",
  "Hahmlet",
  "David Libre",
  "Poly",
  "Average",
  "Cormorant SC",
  "Markazi Text",
  "Gurajada",
  "Rasa",
  "Spectral SC",
  "Kadwa",
  "Fjord One",
  "Vesper Libre",
  "Radley",
  "Copse",
  "Bentham",
  "IM Fell English",
  "Coustard",
  "Gabriela",
  "Fauna One",
  "Antic Didone",
  "Cormorant Unicase",
  "Fanwood Text",
  "Alike",
  "Gloock",
  "Trocchi",
  "Bona Nova SC",
  "Tiro Bangla",
  "Instrument Serif",
  "IM Fell English SC",
  "Montagu Slab",
  "Cambo",
  "Quando",
  "Kalnia",
  "Libre Caslon Display",
  "Aref Ruqaa",
  "Suranna",
  "Della Respira",
  "Imbue",
  "IM Fell DW Pica",
  "Buenard",
  "Hanuman",
  "Esteban",
  "Tienne",
  "Kaisei Opti",
  "Brawler",
  "Alkalami",
  "Hina Mincho",
  "Noto Serif HK",
  "Cutive",
  "Inknut Antiqua",
  "Noto Serif Thai",
  "Amethysta",
  "Sura",
  "Vollkorn SC",
  "BIZ UDPMincho",
  "IM Fell Double Pica",
  "Alike Angular",
  "Slabo 13px",
  "Vast Shadow",
  "Yuji Syuku",
  "Almendra",
  "Noto Serif Malayalam",
  "Headland One",
  "Charis SIL",
  "Montaga",
  "Sumana",
  "Artifika",
  "Fenix",
  "Zen Antique Soft",
  "Prociono",
  "Manuale",
  "Noto Serif Hentaigana",
  "Piazzolla",
  "Mirza",
  "Balthazar",
  "Kaisei Tokumin",
  "BhuTuka Expanded One",
  "Platypi",
  "Noto Serif Georgian",
  "IM Fell French Canon",
  "Peralta",
  "Rhodium Libre",
  "Asar",
  "Zen Antique",
  "Ledger",
  "Scope One",
  "Belgrano",
  "Tiro Devanagari Hindi",
  "Bona Nova",
  "Mate SC",
  "Abyssinica SIL",
  "Noto Serif Telugu",
  "IM Fell DW Pica SC",
  "Gentium Book Plus",
  "IM Fell Great Primer",
  "Maiden Orange",
  "Scheherazade New",
  "Rosarivo",
  "IM Fell Double Pica SC",
  "Trykker",
  "Habibi",
  "Poltawski Nowy",
  "Ramaraja",
  "IM Fell Great Primer SC",
  "Texturina",
  "IM Fell French Canon SC",
  "Sree Krushnadevaraya",
  "Baskervville SC",
  "Junge",
  "Port Lligat Slab",
  "Jomolhari",
  "Bodoni Moda SC",
  "Suwannaphum",
  "Kaisei HarunoUmi",
  "Stoke",
  "Gulzar",
  "Gentium Plus",
  "Benne",
  "BIZ UDMincho",
  "Grenze",
  "Koh Santepheap",
  "Stint Ultra Condensed",
  "Almendra SC",
  "Stint Ultra Expanded",
  "Noto Serif Kannada",
  "Inika",
  "Donegal One",
  "Linden Hill",
  "Aoboshi One",
  "Marko One",
  "Noto Serif Ahom",
  "Sedan SC",
  "Jacques Francois",
  "New Tegomin",
  "Kotta One",
  "Peddana",
  "Joan",
  "Tiro Devanagari Sanskrit",
  "Bacasime Antique",
  "Sahitya",
  "Wellfleet",
  "Arbutus",
  "Hedvig Letters Serif",
  "Noto Serif Khmer",
  "Odor Mean Chey",
  "Noto Serif Tamil",
  "Noto Serif Hebrew",
  "Uchen",
  "Danfo",
  "Noto Serif Armenian",
  "Amiri Quran",
  "Tiro Devanagari Marathi",
  "Ruwudu",
  "Yuji Boku",
  "Labrada",
  "Noto Serif Sinhala",
  "Noto Serif Gujarati",
  "Noto Serif Vithkuqi",
  "Wittgenstein",
  "Diphylleia",
  "Tiro Tamil",
  "Noto Serif Tibetan",
  "BioRhyme Expanded",
  "Tiro Telugu",
  "Grandiflora One",
  "Cactus Classical Serif",
  "Noto Serif Lao",
  "Aref Ruqaa Ink",
  "Noto Serif Khojki",
  "Noto Serif Balinese",
  "Tiro Gurmukhi",
  "Noto Serif Todhri",
  "Sedan",
  "Tai Heritage Pro",
  "Suravaram",
  "Noto Rashi Hebrew",
  "Dai Banna SIL",
  "Tiro Kannada",
  "Noto Serif Ethiopic",
  "Noto Serif Oriya",
  "Annapurna SIL",
  "Noto Serif Tangut",
  "Noto Serif NP Hmong",
  "Namdhinggo",
  "Noto Serif Dogra",
  "Noto Serif Toto",
  "Noto Serif Khitan Small Script",
  "Noto Serif Yezidi",
  "Noto Serif Old Uyghur",
  "Noto Serif Ottoman Siyaq",
  "Kay Pho Du",
  "Noto Serif Gurmukhi",
  "Lisu Bosa",
  "Padyakke Expanded One",
  "Maname",
  "Narnoor",
  "Noto Serif Grantha",
  "Noto Serif Makasar",
];

export const monoFonts = [
  "Material Icons",
  "Roboto Mono",
  "Inconsolata",
  "Material Symbols Outlined",
  "Material Icons Outlined",
  "Material Symbols Rounded",
  "Source Code Pro",
  "Material Icons Round",
  "IBM Plex Mono",
  "Material Icons Sharp",
  "Material Icons Two Tone",
  "JetBrains Mono",
  "Space Mono",
  "Courier Prime",
  "DM Mono",
  "VT323",
  "Ubuntu Mono",
  "Material Symbols Sharp",
  "PT Mono",
  "Fira Code",
  "Fira Mono",
  "Cousine",
  "Share Tech Mono",
  "Anonymous Pro",
  "Major Mono Display",
  "Cutive Mono",
  "Overpass Mono",
  "Oxygen Mono",
  "Azeret Mono",
  "B612 Mono",
  "Reddit Mono",
  "Lekton",
  "Syne Mono",
  "Nova Mono",
  "Xanh Mono",
  "Fragment Mono",
  "Chivo Mono",
  "Martian Mono",
  "Geist Mono",
  "Monofett",
  "Red Hat Mono",
  "M PLUS 1 Code",
  "Kode Mono",
  "Sixtyfour Convergence",
  "Spline Sans Mono",
  "Sometype Mono",
  "Victor Mono",
  "Workbench",
  "Sixtyfour",
  "LXGW WenKai Mono TC",
  "Ubuntu Sans Mono",
];

export const handwritingFonts = [
  "Dancing Script",
  "Pacifico",
  "Caveat",
  "Nanum Gothic Coding",
  "Shadows Into Light",
  "Satisfy",
  "Indie Flower",
  "Permanent Marker",
  "Great Vibes",
  "Amatic SC",
  "Kalam",
  "Yellowtail",
  "Courgette",
  "Merienda",
  "Kaushan Script",
  "Gloria Hallelujah",
  "Zeyada",
  "Sacramento",
  "Allura",
  "Patrick Hand",
  "Sofia",
  "Tangerine",
  "Comic Neue",
  "Neucha",
  "Cookie",
  "Architects Daughter",
  "Berkshire Swash",
  "Parisienne",
  "Rochester",
  "Itim",
  "Alex Brush",
  "Handlee",
  "Homemade Apple",
  "Reenie Beanie",
  "Sriracha",
  "Mr Dafoe",
  "Bad Script",
  "Nothing You Could Do",
  "Nanum Pen Script",
  "Italianno",
  "Marck Script",
  "Pinyon Script",
  "Rock Salt",
  "Pangolin",
  "Damion",
  "Amita",
  "Caveat Brush",
  "Covered By Your Grace",
  "Charm",
  "Mrs Saint Delafield",
  "Leckerli One",
  "Gochi Hand",
  "La Belle Aurore",
  "Delius",
  "Just Another Hand",
  "Herr Von Muellerhoff",
  "Julee",
  "Cedarville Cursive",
  "Mali",
  "Shadows Into Light Two",
  "Hachi Maru Pop",
  "Norican",
  "Nanum Brush Script",
  "Schoolbell",
  "Ms Madi",
  "Allison",
  "Dawning of a New Day",
  "Arizonia",
  "Rancho",
  "Klee One",
  "Kristi",
  "Niconne",
  "Yesteryear",
  "Annie Use Your Telescope",
  "Coming Soon",
  "Oooh Baby",
  "Grand Hotel",
  "Short Stack",
  "Quintessential",
  "Waiting for the Sunrise",
  "Calligraffitti",
  "Petit Formal Script",
  "Style Script",
  "Monsieur La Doulaise",
  "Mansalva",
  "Qwigley",
  "Ma Shan Zheng",
  "Meddon",
  "Aguafina Script",
  "Qwitcher Grypen",
  "Over the Rainbow",
  "Mr De Haviland",
  "Loved by the King",
  "Delicious Handrawn",
  "Hurricane",
  "Sedgwick Ave",
  "Fuggles",
  "League Script",
  "Hi Melody",
  "Sue Ellen Francisco",
  "Rouge Script",
  "Give You Glory",
  "Fondamento",
  "Vibur",
  "Euphoria Script",
  "Walter Turncoat",
  "Meow Script",
  "Whisper",
  "Crafty Girls",
  "Ephesis",
  "Corinthia",
  "Birthstone",
  "Grape Nuts",
  "Montez",
  "Just Me Again Down Here",
  "Charmonman",
  "Bilbo Swash Caps",
  "Gamja Flower",
  "Clicker Script",
  "Delius Unicase",
  "Nerko One",
  "The Girl Next Door",
  "Comforter Brush",
  "Redressed",
  "Square Peg",
  "Dekko",
  "Patrick Hand SC",
  "East Sea Dokdo",
  "Gaegu",
  "Fuzzy Bubbles",
  "Borel",
  "Eagle Lake",
  "Vujahday Script",
  "Delius Swash Caps",
  "Swanky and Moo Moo",
  "Ruthie",
  "WindSong",
  "Kavivanar",
  "Licorice",
  "Sunshiney",
  "Edu SA Beginner",
  "Carattere",
  "MonteCarlo",
  "Sedgwick Ave Display",
  "Lovers Quarrel",
  "Playpen Sans",
  "Moon Dance",
  "The Nautigal",
  "Stalemate",
  "Birthstone Bounce",
  "Meie Script",
  "Beth Ellen",
  "Zhi Mang Xing",
  "Liu Jian Mao Cao",
  "Smooch",
  "Yomogi",
  "Waterfall",
  "Long Cang",
  "Playwrite DE Grund",
  "Passions Conflict",
  "Comforter",
  "Bilbo",
  "Edu NSW ACT Foundation",
  "Lavishly Yours",
  "Edu TAS Beginner",
  "Engagement",
  "Imperial Script",
  "Beau Rivage",
  "Playwrite GB S",
  "Shalimar",
  "Send Flowers",
  "Solitreo",
  "Condiment",
  "Playwrite US Trad",
  "Chilanka",
  "Mynerve",
  "Festive",
  "Bonheur Royale",
  "Gwendolyn",
  "Edu VIC WA NT Beginner",
  "Luxurious Script",
  "Edu AU VIC WA NT Hand",
  "Devonshire",
  "Lugrasimo",
  "Mea Culpa",
  "Water Brush",
  "Mrs Sheppards",
  "Grey Qo",
  "Ballet",
  "Playwrite IS",
  "Felipa",
  "Playwrite CU",
  "Butterfly Kids",
  "Lakki Reddy",
  "Dr Sugiyama",
  "Romanesco",
  "Praise",
  "Updock",
  "Princess Sofia",
  "Grechen Fuemen",
  "Miss Fajardose",
  "Playwrite AU SA",
  "Caramel",
  "Bonbon",
  "Mr Bedfort",
  "Edu AU VIC WA NT Pre",
  "Explora",
  "Neonderthaw",
  "Fleur De Leah",
  "Babylonica",
  "Jim Nightshade",
  "Lumanosimo",
  "LXGW WenKai TC",
  "Inspiration",
  "Love Light",
  "Playwrite IN",
  "Ruge Boogie",
  "Edu AU VIC WA NT Dots",
  "Twinkle Star",
  "My Soul",
  "Sassy Frass",
  "Island Moments",
  "Playwrite AR",
  "Playwrite HR Lijeva",
  "Kings",
  "Kolker Brush",
  "Playwrite HR",
  "Playwrite IT Moderna",
  "Splash",
  "Petemoss",
  "Ingrid Darling",
  "Cherish",
  "Edu AU VIC WA NT Guides",
  "Tapestry",
  "Slackside One",
  "Playwrite VN",
  "Edu QLD Beginner",
  "Are You Serious",
  "Playwrite ES",
  "Playwrite MX",
  "Playwrite NL",
  "Estonia",
  "Ole",
  "Puppies Play",
  "Playwrite FR Moderne",
  "Playwrite BE VLG",
  "Playwrite GB J",
  "Playwrite AU NSW",
  "Edu AU VIC WA NT Arrows",
  "Yuji Hentaigana Akari",
  "Playwrite AT",
  "Playwrite ES Guides",
  "Playwrite CZ Guides",
  "Playwrite BE WAL",
  "Playwrite SK",
  "Playwrite AU QLD",
  "Playwrite IS Guides",
  "Playwrite PE",
  "Playwrite US Modern",
  "Playwrite ZA",
  "Playwrite ID Guides",
  "Playwrite PL",
  "Playwrite PT",
  "Playwrite IE Guides",
  "Playwrite ES Deco",
  "Playwrite HR Guides",
  "Playwrite MX Guides",
  "Playwrite CA Guides",
  "Playwrite DK Loopet",
  "Playwrite CO Guides",
  "Playwrite NZ",
  "Playwrite PL Guides",
  "Playwrite HR Lijeva Guides",
  "Playwrite RO Guides",
  "Playwrite AU TAS Guides",
  "Playwrite PT Guides",
  "Playwrite AU TAS",
  "Playwrite PE Guides",
  "Playwrite TZ Guides",
  "Playwrite CL",
  "Playwrite DK Uloopet",
  "Playwrite AU VIC",
  "Playwrite AU VIC Guides",
  "Playwrite DE Grund Guides",
  "Playwrite GB S Guides",
  "Playwrite US Trad Guides",
  "Playwrite CO",
  "Playwrite ES Deco Guides",
  "Playwrite CU Guides",
  "Playwrite NG Modern",
  "Playwrite DK Loopet Guides",
  "Playwrite ZA Guides",
  "Playwrite NG Modern Guides",
  "Playwrite BE WAL Guides",
  "Playwrite NL Guides",
  "Playwrite VN Guides",
  "Playwrite US Modern Guides",
  "Playwrite AU SA Guides",
  "Playwrite DE LA Guides",
  "Playwrite CL Guides",
  "Playwrite DK Uloopet Guides",
  "Playwrite DE VA Guides",
  "Playwrite AU QLD Guides",
  "Playwrite FR Trad Guides",
  "Playwrite CZ",
  "Playwrite SK Guides",
  "Playwrite HU",
  "Playwrite GB J Guides",
  "Playwrite IN Guides",
  "Playwrite NO",
  "Playwrite NZ Guides",
  "Playwrite AR Guides",
  "Playwrite IT Moderna Guides",
  "Playwrite IT Trad Guides",
  "Playwrite AU NSW Guides",
  "Playwrite RO",
  "Playwrite AT Guides",
  "Playwrite FR Moderne Guides",
  "Playwrite IE",
  "Playwrite ID",
  "Playwrite BR Guides",
  "Playwrite DE SAS Guides",
  "Playwrite BE VLG Guides",
  "Playwrite BR",
  "Playwrite HU Guides",
  "Playwrite FR Trad",
  "Playwrite NO Guides",
  "Playwrite DE LA",
  "Playwrite CA",
  "Playwrite DE VA",
  "Playwrite DE SAS",
  "Playwrite TZ",
  "Playwrite IT Trad",
  "Yuji Hentaigana Akebono",
];

export const displayFonts = [
  "Comfortaa",
  "Lobster",
  "Lilita One",
  "Abril Fatface",
  "Rowdies",
  "Alfa Slab One",
  "Oleo Script",
  "Passion One",
  "Righteous",
  "Concert One",
  "Luckiest Guy",
  "Press Start 2P",
  "Patua One",
  "Lobster Two",
  "Creepster",
  "Silkscreen",
  "Titan One",
  "Yatra One",
  "Bangers",
  "Poiret One",
  "Baloo Bhaijaan 2",
  "Libre Barcode 39",
  "Special Elite",
  "Staatliches",
  "Fugaz One",
  "Yeseva One",
  "Macondo",
  "Bungee",
  "Baloo 2",
  "Rubik Bubbles",
  "Oxanium",
  "Audiowide",
  "Dela Gothic One",
  "Changa One",
  "Forum",
  "Lalezar",
  "Monoton",
  "Carter One",
  "Rammetto One",
  "Playball",
  "Unica One",
  "Black Ops One",
  "Big Shoulders Display",
  "Londrina Solid",
  "Calistoga",
  "Gabarito",
  "Cinzel Decorative",
  "Shrikhand",
  "Lemonada",
  "Averia Serif Libre",
  "Fredericka the Great",
  "Cabin Sketch",
  "Agbalumo",
  "Chewy",
  "Coda",
  "Grandstander",
  "Racing Sans One",
  "Boogaloo",
  "Potta One",
  "Seaweed Script",
  "Balsamiq Sans",
  "Pirata One",
  "Chonburi",
  "Corben",
  "Squada One",
  "Salsa",
  "Lemon",
  "Eater",
  "Averia Libre",
  "Chango",
  "Nixie One",
  "Black And White Picture",
  "Bowlby One",
  "Odibee Sans",
  "Bowlby One SC",
  "Gravitas One",
  "Limelight",
  "Overlock",
  "Barriecito",
  "Rye",
  "Rakkas",
  "Big Shoulders Text",
  "Knewave",
  "Love Ya Like A Sister",
  "Baloo Da 2",
  "McLaren",
  "Aboreto",
  "Koulen",
  "Darumadrop One",
  "Wallpoet",
  "UnifrakturMaguntia",
  "Sigmar One",
  "Skranji",
  "Kelly Slab",
  "Bubblegum Sans",
  "Irish Grover",
  "Grenze Gotisch",
  "Caprasimo",
  "Tilt Neon",
  "Sniglet",
  "Jomhuria",
  "Bellota Text",
  "Bungee Inline",
  "Poetsen One",
  "Contrail One",
  "Libre Barcode 39 Text",
  "Baloo Paaji 2",
  "Stardos Stencil",
  "MuseoModerno",
  "Faster One",
  "Turret Road",
  "Libre Barcode 128",
  "Pompiere",
  "Bungee Shade",
  "Vina Sans",
  "Red Rose",
  "Gluten",
  "Baloo Thambi 2",
  "Megrim",
  "Baloo Chettan 2",
  "Mountains of Christmas",
  "Happy Monkey",
  "Ruslan Display",
  "Battambang",
  "Prosto One",
  "Anybody",
  "Aladin",
  "Chelsea Market",
  "Protest Revolution",
  "Shantell Sans",
  "Nova Square",
  "Baloo Tamma 2",
  "Rampart One",
  "Sansita Swashed",
  "Croissant One",
  "Finger Paint",
  "Iceberg",
  "Sarina",
  "Expletus Sans",
  "Allan",
  "Atma",
  "Supermercado One",
  "Oregano",
  "Goldman",
  "Spicy Rice",
  "Coiny",
  "Goblin One",
  "Lacquer",
  "Kumar One",
  "Gugi",
  "Amarante",
  "ADLaM Display",
  "Cherry Cream Soda",
  "Bellota",
  "Sofadi One",
  "Zen Dots",
  "Kranky",
  "Shojumaru",
  "Codystar",
  "Averia Sans Libre",
  "Libre Barcode 39 Extended Text",
  "Oleo Script Swash Caps",
  "Tilt Warp",
  "Pixelify Sans",
  "Mogra",
  "Dynalight",
  "Germania One",
  "Bigshot One",
  "Slackey",
  "Baloo Bhai 2",
  "Fontdiner Swanky",
  "Libre Barcode 128 Text",
  "Flow Circular",
  "Saira Stencil One",
  "Bokor",
  "Unkempt",
  "Elsie",
  "Sevillana",
  "Orelega One",
  "Ga Maamli",
  "Bakbak One",
  "Nova Round",
  "Road Rage",
  "Modak",
  "Phudu",
  "Metamorphous",
  "Dokdo",
  "Henny Penny",
  "Lily Script One",
  "Freehand",
  "Galada",
  "Baloo Tammudu 2",
  "Rubik Dirt",
  "DynaPuff",
  "Overlock SC",
  "Ranchers",
  "Viaoda Libre",
  "MedievalSharp",
  "Rubik Moonrocks",
  "Triodion",
  "Raleway Dots",
  "Modern Antiqua",
  "Reggae One",
  "Arima",
  "Medula One",
  "Tektur",
  "Flamenco",
  "Poller One",
  "Crushed",
  "Baumans",
  "Akaya Kanadaka",
  "Life Savers",
  "Akronim",
  "Original Surfer",
  "Trade Winds",
  "Frijole",
  "Kablammo",
  "Sail",
  "Cute Font",
  "Jersey 15",
  "Nova Flat",
  "Nova Slim",
  "Nosifer",
  "Macondo Swash Caps",
  "Margarine",
  "Cherry Swash",
  "Rubik Scribble",
  "Uncial Antiqua",
  "Iceland",
  "Vampiro One",
  "Miniver",
  "Moul",
  "Ceviche One",
  "Sonsie One",
  "Katibeh",
  "Protest Riot",
  "Rubik Vinyl",
  "Protest Strike",
  "Asset",
  "Freckle Face",
  "Emilys Candy",
  "Akaya Telivigala",
  "Unlock",
  "Barrio",
  "Redacted",
  "Baloo Bhaina 2",
  "Miltonian Tattoo",
  "Bungee Spice",
  "Ribeye",
  "Kavoon",
  "Kenia",
  "Smythe",
  "Astloch",
  "Jersey 10",
  "Sancreek",
  "Fascinate Inline",
  "Caesar Dressing",
  "Tillana",
  "Farsan",
  "Ewert",
  "Keania One",
  "Atomic Age",
  "Nova Script",
  "Gorditas",
  "Erica One",
  "Angkor",
  "Miltonian",
  "Nova Cut",
  "Nova Oval",
  "Srisakdi",
  "Karantina",
  "Chicle",
  "Alkatra",
  "Climate Crisis",
  "Rubik Doodle Shadow",
  "Londrina Outline",
  "Ribeye Marrow",
  "Underdog",
  "Metal Mania",
  "Jolly Lodger",
  "Honk",
  "Libre Barcode 39 Extended",
  "Bruno Ace SC",
  "Paprika",
  "Zen Tokyo Zoo",
  "Train One",
  "Jacques Francois Shadow",
  "Pochaevsk",
  "Dangrek",
  "Mystery Quest",
  "Simonetta",
  "New Rocker",
  "Offside",
  "Fasthand",
  "Tilt Prism",
  "Spirax",
  "Federant",
  "Girassol",
  "Cherry Bomb One",
  "Autour One",
  "Bungee Hairline",
  "Risque",
  "Big Shoulders Stencil Text",
  "Londrina Shadow",
  "Yeon Sung",
  "Tulpen One",
  "Milonga",
  "Galindo",
  "Poor Story",
  "Funnel Display",
  "Flow Rounded",
  "Big Shoulders Stencil Display",
  "Handjet",
  "Londrina Sketch",
  "Agu Display",
  "Jacquard 12",
  "Piedra",
  "Joti One",
  "Ranga",
  "Bigelow Rules",
  "Tourney",
  "Elsie Swash Caps",
  "Lancelot",
  "Metal",
  "Glass Antiqua",
  "Fascinate",
  "Passero One",
  "Castoro Titling",
  "Rubik Glitch",
  "Smokum",
  "Chela One",
  "Griffy",
  "Marhey",
  "Big Shoulders Inline Text",
  "Bagel Fat One",
  "Averia Gruesa Libre",
  "Bungee Outline",
  "Oi",
  "Alumni Sans Inline One",
  "Rubik Wet Paint",
  "Rubik Iso",
  "Diplomata SC",
  "Blaka",
  "Hanalei Fill",
  "Micro 5",
  "Rubik Glitch Pop",
  "Kumar One Outline",
  "Ravi Prakash",
  "Luxurious Roman",
  "Stalinist One",
  "Bruno Ace",
  "Foldit",
  "Trochut",
  "Revalia",
  "Plaster",
  "Bahiana",
  "Sirin Stencil",
  "Rubik Distressed",
  "Kirang Haerang",
  "Fruktur",
  "Almendra Display",
  "Flavors",
  "Gideon Roman",
  "Freeman",
  "Libre Barcode EAN13 Text",
  "Diplomata",
  "Butcherman",
  "Purple Purse",
  "Jacquarda Bastarda 9",
  "Nabla",
  "Oldenburg",
  "Jacquard 24",
  "Emblema One",
  "Aubrey",
  "Redacted Script",
  "Kalnia Glaze",
  "Bahianita",
  "Konkhmer Sleokchher",
  "Langar",
  "Combo",
  "Sigmar",
  "Zen Loop",
  "Rubik Beastly",
  "Palette Mosaic",
  "Big Shoulders Inline Display",
  "Vibes",
  "Flow Block",
  "Rubik Puddles",
  "Rubik Spray Paint",
  "Rock 3D",
  "Geostar Fill",
  "Jersey 20",
  "Taprom",
  "Geostar",
  "Protest Guerrilla",
  "Jersey 25",
  "Moirai One",
  "Snowburst One",
  "Rubik 80s Fade",
  "Rubik Microbe",
  "Moo Lah Lah",
  "Shizuru",
  "Rubik Gemstones",
  "Hanalei",
  "Bungee Tint",
  "Badeen Display",
  "Yarndings 12",
  "Jacquard 12 Charted",
  "Blaka Hollow",
  "Rubik Burned",
  "Rubik Pixels",
  "Warnes",
  "Rubik Doodle Triangles",
  "Blaka Ink",
  "Syne Tactile",
  "Rubik Marker Hatch",
  "Rubik Maps",
  "Jaini",
  "Chokokutai",
  "Gajraj One",
  "Jersey 20 Charted",
  "Rubik Broken Fax",
  "Rubik Storm",
  "Rubik Lines",
  "Rubik Maze",
  "Linefont",
  "Ponnala",
  "Jersey 15 Charted",
  "Jaini Purva",
  "Jersey 10 Charted",
  "Wavefont",
  "Yarndings 20",
  "Yarndings 12 Charted",
  "Yarndings 20 Charted",
  "Jacquard 24 Charted",
  "Jersey 25 Charted",
  "Micro 5 Charted",
  "Jacquarda Bastarda 9 Charted",
];

export const sansSerifFonts = [
  "Roboto",
  "Open Sans",
  "Noto Sans JP",
  "Montserrat",
  "Poppins",
  "Inter",
  "Lato",
  "Roboto Condensed",
  "Oswald",
  "Noto Sans",
  "Raleway",
  "Nunito Sans",
  "Nunito",
  "Ubuntu",
  "Rubik",
  "Noto Sans KR",
  "PT Sans",
  "Kanit",
  "Work Sans",
  "DM Sans",
  "Mulish",
  "Noto Sans TC",
  "Quicksand",
  "Fira Sans",
  "Manrope",
  "Barlow",
  "IBM Plex Sans",
  "Heebo",
  "Titillium Web",
  "Hind Siliguri",
  "Bebas Neue",
  "Karla",
  "Nanum Gothic",
  "Libre Franklin",
  "Outfit",
  "Schibsted Grotesk",
  "Josefin Sans",
  "Jost",
  "Mukta",
  "Figtree",
  "Source Sans 3",
  "Prompt",
  "Noto Sans SC",
  "Anton",
  "Cabin",
  "Space Grotesk",
  "Dosis",
  "Arimo",
  "Archivo",
  "Cairo",
  "Exo 2",
  "PT Sans Narrow",
  "Oxygen",
  "Barlow Condensed",
  "Assistant",
  "Plus Jakarta Sans",
  "Hind",
  "Teko",
  "Public Sans",
  "Overpass",
  "Signika Negative",
  "Lexend",
  "Abel",
  "Red Hat Display",
  "M PLUS Rounded 1c",
  "Rajdhani",
  "Roboto Flex",
  "Fjalla One",
  "Tajawal",
  "IBM Plex Sans Arabic",
  "Varela Round",
  "Barlow Semi Condensed",
  "Sora",
  "Asap",
  "Maven Pro",
  "Noto Sans HK",
  "Fira Sans Condensed",
  "Archivo Black",
  "Play",
  "Merriweather Sans",
  "Signika",
  "Saira Condensed",
  "Almarai",
  "Urbanist",
  "Questrial",
  "Inter Tight",
  "M PLUS 1p",
  "Chakra Petch",
  "Be Vietnam Pro",
  "Noto Sans Thai",
  "Exo",
  "Catamaran",
  "Smooch Sans",
  "Lexend Deca",
  "Sarabun",
  "Archivo Narrow",
  "Orbitron",
  "Rubik Mono One",
  "Noto Kufi Arabic",
  "Acme",
  "ABeeZee",
  "Readex Pro",
  "Alegreya Sans",
  "Hind Madurai",
  "Montserrat Alternates",
  "Saira",
  "Albert Sans",
  "Yanone Kaffeesatz",
  "Noto Sans Display",
  "League Spartan",
  "Changa",
  "Chivo",
  "Encode Sans",
  "Sofia Sans",
  "Zen Kaku Gothic New",
  "Red Hat Text",
  "PT Sans Caption",
  "Russo One",
  "Sen",
  "Cantarell",
  "Didact Gothic",
  "Ubuntu Condensed",
  "Philosopher",
  "Yantramanav",
  "Vazirmatn",
  "IBM Plex Sans Condensed",
  "News Cycle",
  "Advent Pro",
  "Alata",
  "Atkinson Hyperlegible",
  "Paytone One",
  "Francois One",
  "Zen Maru Gothic",
  "Noto Sans Bengali",
  "Encode Sans Condensed",
  "Sawarabi Gothic",
  "Gruppo",
  "Gothic A1",
  "Jura",
  "Unbounded",
  "Noto Sans Devanagari",
  "Tenor Sans",
  "Bricolage Grotesque",
  "Khand",
  "Geologica",
  "Kumbh Sans",
  "Quattrocento Sans",
  "Onest",
  "Asap Condensed",
  "El Messiri",
  "Commissioner",
  "Noto Sans Mono",
  "Noto Sans Tamil",
  "Krub",
  "Fira Sans Extra Condensed",
  "Hanken Grotesk",
  "Pathway Gothic One",
  "Hammersmith One",
  "Cuprum",
  "Bai Jamjuree",
  "Viga",
  "Fredoka",
  "Kosugi Maru",
  "Mukta Malar",
  "Instrument Sans",
  "Antonio",
  "Mitr",
  "League Gothic",
  "Epilogue",
  "Syne",
  "Amaranth",
  "Blinker",
  "Sofia Sans Condensed",
  "Actor",
  "Radio Canada",
  "Arsenal",
  "BIZ UDPGothic",
  "Saira Semi Condensed",
  "Istok Web",
  "Mada",
  "Andika",
  "Hind Vadodara",
  "Gudea",
  "Black Han Sans",
  "Monda",
  "Ropa Sans",
  "Golos Text",
  "Quantico",
  "Cabin Condensed",
  "Alexandria",
  "Wix Madefor Text",
  "Six Caps",
  "Niramit",
  "Ruda",
  "Alef",
  "Alegreya Sans SC",
  "Mandali",
  "Noto Sans Malayalam",
  "Secular One",
  "Varela",
  "Sarala",
  "Pontano Sans",
  "Julius Sans One",
  "Pragati Narrow",
  "Economica",
  "Reem Kufi",
  "BenchNine",
  "Ramabhadra",
  "Ysabeau SC",
  "Khula",
  "Anton SC",
  "Electrolize",
  "Aclonica",
  "Sansita",
  "Syncopate",
  "Noto Sans Hebrew",
  "Sintony",
  "Lexend Giga",
  "Martel Sans",
  "Days One",
  "Akshar",
  "Anuphan",
  "Do Hyeon",
  "Athiti",
  "Darker Grotesque",
  "Laila",
  "Belleza",
  "Armata",
  "Basic",
  "IBM Plex Sans Thai",
  "Palanquin",
  "M PLUS 1",
  "Livvic",
  "Alatsi",
  "Jaldi",
  "Noto Sans Symbols",
  "Saira Extra Condensed",
  "Hind Guntur",
  "Michroma",
  "Jua",
  "Georama",
  "Scada",
  "Palanquin Dark",
  "Tomorrow",
  "Zen Kaku Gothic Antique",
  "Allerta Stencil",
  "Candal",
  "Spinnaker",
  "K2D",
  "Nobile",
  "Sofia Sans Extra Condensed",
  "Alumni Sans",
  "Pattaya",
  "Proza Libre",
  "Aldrich",
  "Telex",
  "Krona One",
  "Lexend Exa",
  "REM",
  "M PLUS 2",
  "Anek Malayalam",
  "Marmelad",
  "Geist",
  "Metrophobic",
  "Antic",
  "Fahkwang",
  "Monomaniac One",
  "Rethink Sans",
  "Kosugi",
  "Rambla",
  "Encode Sans Semi Condensed",
  "Allerta",
  "Glory",
  "Encode Sans Expanded",
  "Magra",
  "Reddit Sans",
  "Gantari",
  "Belanosima",
  "Dongle",
  "Wix Madefor Display",
  "Afacad",
  "Farro",
  "Montserrat Subrayada",
  "Noto Sans Armenian",
  "Mochiy Pop One",
  "Pathway Extreme",
  "Average Sans",
  "Share",
  "Anek Devanagari",
  "Cambay",
  "Amiko",
  "Fresca",
  "BIZ UDGothic",
  "Familjen Grotesk",
  "B612",
  "Arya",
  "Spline Sans",
  "Rosario",
  "Biryani",
  "Manjari",
  "Mouse Memoirs",
  "Miriam Libre",
  "IBM Plex Sans KR",
  "Anek Latin",
  "Noto Sans Meetei Mayek",
  "Geo",
  "RocknRoll One",
  "Jockey One",
  "IBM Plex Sans JP",
  "Murecho",
  "Carrois Gothic",
  "Gayathri",
  "Noto Sans Lao Looped",
  "Lexend Peta",
  "KoHo",
  "Sofia Sans Semi Condensed",
  "Noto Sans Sinhala",
  "Capriola",
  "DotGothic16",
  "Encode Sans Semi Expanded",
  "Yusei Magic",
  "Gotu",
  "Marvel",
  "Thasadith",
  "Lexend Zetta",
  "Inder",
  "Noto Sans Kannada",
  "ZCOOL XiaoWei",
  "Voltaire",
  "Mukta Vaani",
  "Noto Sans Georgian",
  "Federo",
  "SUSE",
  "Molengo",
  "ZCOOL QingKe HuangYou",
  "Noto Sans Telugu",
  "Kodchasan",
  "Mukta Mahee",
  "Tenali Ramakrishna",
  "NTR",
  "Mallanna",
  "Padauk",
  "Asul",
  "Host Grotesk",
  "Noto Sans Khmer",
  "Noto Sans Gujarati",
  "Zen Kurenaido",
  "Carme",
  "Puritan",
  "Wendy One",
  "Recursive",
  "Kufam",
  "Duru Sans",
  "Numans",
  "Mingzat",
  "Shippori Antique",
  "Agdasima",
  "Gowun Dodum",
  "Notable",
  "Sarpanch",
  "Anek Bangla",
  "Kdam Thmor Pro",
  "Bayon",
  "Kantumruy Pro",
  "IBM Plex Sans Hebrew",
  "AR One Sans",
  "Mako",
  "Share Tech",
  "Tiny5",
  "Bubbler One",
  "Harmattan",
  "Wire One",
  "Carlito",
  "Shanti",
  "42dot Sans",
  "Afacad Flux",
  "ZCOOL KuaiLe",
  "Mochiy Pop P One",
  "Ubuntu Sans",
  "Anaheim",
  "Doppio One",
  "Sulphur Point",
  "Imprima",
  "Inria Sans",
  "Noto Sans Anatolian Hieroglyphs",
  "Noto Sans Samaritan",
  "Nokora",
  "Convergence",
  "Liter",
  "Orienta",
  "Fustat",
  "Noto Sans Lao",
  "Mona Sans",
  "Anek Gujarati",
  "Homenaje",
  "Varta",
  "Noto Sans Mongolian",
  "Chau Philomene One",
  "Genos",
  "Noto Sans Oriya",
  "Strait",
  "Parkinsans",
  "Rum Raisin",
  "Akatab",
  "Gemunu Libre",
  "Madimi One",
  "Radio Canada Big",
  "Denk One",
  "Tauri",
  "Stick",
  "Lexend Mega",
  "Cairo Play",
  "Cantora One",
  "Rationale",
  "Noto Sans Thai Looped",
  "Noto Sans Gurmukhi",
  "Mooli",
  "Voces",
  "Gafata",
  "Meera Inimai",
  "Stick No Bills",
  "Zain",
  "Mohave",
  "Mina",
  "Anek Tamil",
  "Pavanam",
  "Noto Sans Buhid",
  "Ysabeau Office",
  "Cagliostro",
  "Timmana",
  "Kite One",
  "Anek Telugu",
  "Preahvihear",
  "Jaro",
  "Carrois Gothic SC",
  "Chocolate Classical Sans",
  "Noto Sans Ethiopic",
  "Text Me One",
  "Chathura",
  "Anek Kannada",
  "Kulim Park",
  "Port Lligat Sans",
  "Anta",
  "Noto Sans Symbols 2",
  "Qahiri",
  "Englebert",
  "IBM Plex Sans Thai Looped",
  "Braah One",
  "Dorsa",
  "Shippori Antique B1",
  "Trispace",
  "Tac One",
  "Finlandica",
  "Ruluko",
  "Lexend Tera",
  "Inclusive Sans",
  "Seymour One",
  "Sono",
  "Noto Sans Gothic",
  "Yaldevi",
  "Ysabeau",
  "Faculty Glyphic",
  "IBM Plex Sans Devanagari",
  "Ysabeau Infant",
  "Galdeano",
  "Alumni Sans Pinstripe",
  "Encode Sans SC",
  "Reddit Sans Condensed",
  "Sour Gummy",
  "Gasoek One",
  "Noto Sans Syriac Eastern",
  "Anek Gurmukhi",
  "Noto Sans Glagolitic",
  "Hind Mysuru",
  "Gidugu",
  "Reem Kufi Ink",
  "New Amsterdam",
  "Noto Sans Tai Viet",
  "Hubballi",
  "Truculenta",
  "Beiruti",
  "Teachers",
  "Moderustic",
  "Reem Kufi Fun",
  "Hedvig Letters Sans",
  "Dhurjati",
  "Moulpali",
  "Funnel Sans",
  "Snippet",
  "Comme",
  "Lunasima",
  "Noto Sans Coptic",
  "Ojuju",
  "Doto",
  "Alumni Sans Collegiate One",
  "Tsukimi Rounded",
  "Orbit",
  "Anek Odia",
  "Noto Music",
  "Nuosu SIL",
  "Arsenal SC",
  "Noto Sans Adlam",
  "Noto Sans Nandinagari",
  "Noto Sans Javanese",
  "Noto Sans Sora Sompeng",
  "Noto Sans Osmanya",
  "Noto Sans Cypro Minoan",
  "Noto Sans Tangsa",
  "Noto Sans Syloti Nagri",
  "M PLUS Code Latin",
  "Hubot Sans",
  "Noto Sans Old Hungarian",
  "Noto Sans Tagalog",
  "Noto Sans NKo Unjoined",
  "Noto Sans Hanunoo",
  "Noto Sans Carian",
  "Matemasie",
  "Sankofa Display",
  "Noto Sans PhagsPa",
  "Montserrat Underline",
  "Noto Sans Nag Mundari",
  "Noto Sans Canadian Aboriginal",
  "Noto Sans Avestan",
  "Noto Sans Batak",
  "Noto Sans Warang Citi",
  "Noto Sans New Tai Lue",
  "Noto Sans Thaana",
  "Noto Sans Balinese",
  "Noto Sans Imperial Aramaic",
  "Noto Znamenny Musical Notation",
  "Noto Sans Indic Siyaq Numbers",
  "Noto Sans Vithkuqi",
  "Noto Sans Old North Arabian",
  "Noto Sans Wancho",
  "Noto Sans Adlam Unjoined",
  "Noto Sans Old Italic",
  "Noto Sans Khojki",
  "Noto Sans Miao",
  "Noto Sans Tifinagh",
  "Noto Sans Sharada",
  "Noto Sans Sundanese",
  "Noto Traditional Nushu",
  "Noto Sans Egyptian Hieroglyphs",
  "Noto Sans Bamum",
  "Noto Sans Cherokee",
  "Noto Sans Tai Le",
  "Noto Sans Yi",
  "Noto Sans Ol Chiki",
  "Noto Sans Linear A",
  "Noto Sans Old Persian",
  "Noto Sans Medefaidrin",
  "Noto Sans Vai",
  "Noto Sans Newa",
  "Noto Sans Old Turkic",
  "Noto Sans Multani",
  "Noto Sans Deseret",
  "Noto Sans Mro",
  "Noto Sans Cham",
  "Noto Sans Marchen",
  "Noto Sans Lisu",
  "Noto Sans Kaithi",
  "Noto Sans Limbu",
  "Noto Sans Elbasan",
  "Noto Sans Tai Tham",
  "Noto Sans Pahawh Hmong",
  "Noto Sans Bassa Vah",
  "Noto Sans Tagbanwa",
  "Noto Sans NKo",
  "Noto Sans Hatran",
  "Noto Sans Chorasmian",
  "Noto Sans Inscriptional Pahlavi",
  "Noto Sans Runic",
  "Noto Sans Chakma",
  "Noto Sans Palmyrene",
  "Noto Sans Linear B",
  "Noto Sans Old South Arabian",
  "Noto Sans Brahmi",
  "Noto Sans Osage",
  "Noto Sans Mayan Numerals",
  "Noto Sans Cuneiform",
  "Noto Sans Kawi",
  "Noto Sans Sogdian",
  "Noto Sans Syriac",
  "Noto Sans Takri",
  "Noto Sans Zanabazar Square",
  "Noto Sans Mandaic",
  "Noto Sans Elymaic",
  "Noto Sans Inscriptional Parthian",
  "Noto Sans Hanifi Rohingya",
  "Noto Sans Rejang",
  "Noto Sans Psalter Pahlavi",
  "Noto Sans Tirhuta",
  "Noto Sans Caucasian Albanian",
  "Noto Sans Duployan",
  "Noto Sans Buginese",
  "Noto Sans Grantha",
  "Noto Sans Gunjala Gondi",
  "Noto Sans Lepcha",
  "Noto Sans Masaram Gondi",
  "Noto Sans Nushu",
  "Noto Sans Mahajani",
  "Noto Sans Kayah Li",
  "Noto Sans Lydian",
  "Noto Sans Nabataean",
  "Noto Sans Cypriot",
  "Noto Sans Saurashtra",
  "Noto Sans Old Sogdian",
  "Noto Sans Soyombo",
  "Noto Sans Old Permic",
  "Noto Sans Ogham",
  "Noto Sans Tamil Supplement",
  "Noto Sans Shavian",
  "Noto Sans Manichaean",
  "Noto Sans Meroitic",
  "Noto Sans Mende Kikakui",
  "Noto Sans Phoenician",
  "Noto Sans Pau Cin Hau",
  "Noto Sans Khudawadi",
  "Noto Sans Siddham",
  "Noto Sans Bhaiksuki",
  "Noto Sans Modi",
  "Noto Sans SignWriting",
  "Noto Sans Kharoshthi",
  "Noto Sans Ugaritic",
];

export const allFonts = [
  ...sansSerifFonts,
  ...serifFonts,
  ...monoFonts,
  ...handwritingFonts,
  ...displayFonts,
];
