// AUTO-GENERATED - DO NOT EDIT
// Run "tsx scripts/registry-build.ts" to regenerate

export interface CatalogEntry {
	name: string;
	title: string;
	description: string;
	group: string;
	exports: string[];
}

/** Every documented component, for the exported agent docs. */
export const AGENT_CATALOG: CatalogEntry[] = [
	{
		name: "accordion",
		title: "Accordion",
		description: "A stack of collapsible sections, one or many open at a time.",
		group: "disclosure",
		exports: ["Accordion", "AccordionItem", "AccordionPanel", "AccordionTrigger"],
	},
	{
		name: "alert",
		title: "Alert",
		description: "Alerts display a short, important message in a way that attracts the user's attention.",
		group: "feedback",
		exports: ["Alert", "AlertAction", "AlertDescription", "AlertTitle"],
	},
	{
		name: "attachment",
		title: "Attachment",
		description: "A file attached to a message or composer — preview, metadata, actions, and upload states.",
		group: "containers",
		exports: [
			"Attachment",
			"AttachmentAction",
			"AttachmentActions",
			"AttachmentContent",
			"AttachmentDescription",
			"AttachmentGroup",
			"AttachmentMedia",
			"AttachmentTitle",
			"AttachmentTrigger",
		],
	},
	{
		name: "avatar",
		title: "Avatar",
		description: "An avatar is a visual representation of a user or entity.",
		group: "containers",
		exports: ["Avatar", "AvatarBadge", "AvatarFallback", "AvatarGroup", "AvatarGroupCount", "AvatarImage"],
	},
	{
		name: "badge",
		title: "Badge",
		description: "Badges are small status descriptors for UI elements.",
		group: "tags",
		exports: ["Badge"],
	},
	{
		name: "breadcrumbs",
		title: "Breadcrumbs",
		description: "Breadcrumbs display a hierarchy of links to the current page or resource in an application.",
		group: "navigation",
		exports: ["BreadcrumbItem", "BreadcrumbLink", "BreadcrumbSeparator", "Breadcrumbs"],
	},
	{
		name: "bubble",
		title: "Bubble",
		description: "A chat bubble — contained message content with variants, alignment, and reactions.",
		group: "containers",
		exports: ["Bubble", "BubbleContent", "BubbleGroup", "BubbleReactions"],
	},
	{
		name: "button",
		title: "Button",
		description: "Displays a button or a component that looks like a button.",
		group: "buttons",
		exports: ["Button", "LinkButton"],
	},
	{
		name: "calendar",
		title: "Calendar",
		description: "A calendar allows a user to select a single date value.",
		group: "calendar",
		exports: [
			"Calendar",
			"CalendarCell",
			"CalendarGrid",
			"CalendarGridBody",
			"CalendarGridHeader",
			"CalendarHeader",
			"CalendarHeaderCell",
			"CalendarHeading",
			"RangeCalendar",
		],
	},
	{
		name: "card",
		title: "Card",
		description: "A card groups related content and actions.",
		group: "containers",
		exports: ["Card", "CardAction", "CardContent", "CardDescription", "CardFooter", "CardHeader", "CardTitle"],
	},
	{
		name: "chart-area",
		title: "Area Chart",
		description: "A filled line chart for values that accumulate, compose, or are read against a baseline.",
		group: "charts",
		exports: ["AreaChart"],
	},
	{
		name: "chart-bar",
		title: "Bar Chart",
		description: "Compares categories with bars — grouped, stacked, horizontal, or labelled.",
		group: "charts",
		exports: ["BarChart"],
	},
	{
		name: "chart-heatmap",
		title: "Heatmap",
		description: "Show one value per pair of categories, with color carrying the magnitude.",
		group: "charts",
		exports: ["HeatmapChart"],
	},
	{
		name: "chart-line",
		title: "Line Chart",
		description: "Draws one line per series across an ordered domain, themed by your design system.",
		group: "charts",
		exports: ["LineChart"],
	},
	{
		name: "chart-pie",
		title: "Pie Chart",
		description: "A circle divided into slices, for parts of a single whole.",
		group: "charts",
		exports: ["PieChart"],
	},
	{
		name: "chart-radar",
		title: "Radar Chart",
		description: "Plots a handful of categories around a circle, so a series reads as one recognisable shape.",
		group: "charts",
		exports: ["RadarChart"],
	},
	{
		name: "chart-radial",
		title: "Radial Chart",
		description: "Bars bent around a circle — progress against a target, or a few categories compared at a glance.",
		group: "charts",
		exports: ["RadialBarChart"],
	},
	{
		name: "checkbox",
		title: "Checkbox",
		description:
			"Checkboxes allow users to select multiple items from a list of individual items, or to mark one individual item as selected.",
		group: "selection-controls",
		exports: ["Checkbox", "CheckboxControl", "CheckboxIndicator"],
	},
	{
		name: "checkbox-group",
		title: "Checkbox Group",
		description: "A checkbox group allows a user to select multiple items from a list of options.",
		group: "selection-controls",
		exports: ["CheckboxGroup"],
	},
	{
		name: "collapsible",
		title: "Collapsible",
		description: "Shows and hides a section of content from a trigger.",
		group: "disclosure",
		exports: ["Collapsible", "CollapsiblePanel", "CollapsibleTrigger"],
	},
	{
		name: "color-area",
		title: "Color Area",
		description: "A color area allows users to select a color from a two-dimensional gradient.",
		group: "sliders",
		exports: ["ColorArea"],
	},
	{
		name: "color-editor",
		title: "Color Editor",
		description:
			"A color editor allows users to adjust a color value using a color area, channel sliders, and field inputs in multiple color formats.",
		group: "color-swatches",
		exports: ["ColorEditor", "ColorEditorArea", "ColorEditorFields"],
	},
	{
		name: "color-field",
		title: "Color Field",
		description: "A color field allows users to edit a color value using a text field.",
		group: "inputs",
		exports: ["ColorField"],
	},
	{
		name: "color-picker",
		title: "Color Picker",
		description: "A color picker allows users to select a color from a palette or input a custom color value.",
		group: "pickers",
		exports: ["ColorPicker"],
	},
	{
		name: "color-slider",
		title: "Color Slider",
		description: "A color slider allows users to adjust an individual channel of a color value.",
		group: "sliders",
		exports: ["ColorSlider", "ColorSliderControl", "ColorSliderOutput"],
	},
	{
		name: "color-swatch",
		title: "Color Swatch",
		description: "A color swatch displays a color sample.",
		group: "color-swatches",
		exports: ["ColorSwatch"],
	},
	{
		name: "color-swatch-picker",
		title: "Color Swatch Picker",
		description: "A color swatch picker allows users to select a color from a list of swatches.",
		group: "color-swatches",
		exports: ["ColorSwatchPickerItem", "ColorSwatchPicker"],
	},
	{
		name: "combobox",
		title: "Combobox",
		description:
			"Combobox combines a text input with a listbox, allowing users to filter a list of options to items matching a query.",
		group: "pickers",
		exports: ["Combobox", "ComboboxValue"],
	},
	{
		name: "command",
		title: "Command",
		description: "A command menu lets users search a list of commands and run one.",
		group: "menus-lists",
		exports: ["Command", "CommandContent", "CommandItem", "CommandSection", "CommandSectionHeader", "CommandInput"],
	},
	{
		name: "date-field",
		title: "Date Field",
		description: "A date field allows users to enter and edit date values using a keyboard.",
		group: "inputs",
		exports: ["DateField"],
	},
	{
		name: "date-picker",
		title: "Date Picker",
		description: "A date picker combines a date field and a calendar popover to allow users to select a date.",
		group: "pickers",
		exports: ["DatePicker", "DateRangePicker"],
	},
	{
		name: "dialog",
		title: "Dialog",
		description: "A dialog is an overlay shown above other content in an application.",
		group: "overlays",
		exports: [
			"Dialog",
			"DialogBody",
			"DialogContent",
			"DialogDescription",
			"DialogFooter",
			"DialogHeader",
			"DialogInset",
			"DialogTitle",
		],
	},
	{
		name: "drawer",
		title: "Drawer",
		description: "A drawer slides in from the edge of the screen to display content.",
		group: "overlays",
		exports: ["Drawer", "DrawerHandle", "DrawerIndent", "DrawerIndentBackground", "DrawerProvider", "DrawerSwipeArea"],
	},
	{
		name: "drop-zone",
		title: "Drop Zone",
		description: "A drop zone is an area into which one or more objects can be dragged and dropped.",
		group: "drop-zone",
		exports: ["DropZone", "DropZoneLabel"],
	},
	{
		name: "empty",
		title: "Empty",
		description: "An empty state placeholder for when there's no content to display.",
		group: "feedback",
		exports: ["Empty", "EmptyContent", "EmptyDescription", "EmptyHeader", "EmptyMedia", "EmptyTitle"],
	},
	{
		name: "field",
		title: "Field",
		description: "A field wraps form inputs with labels, descriptions, and error messages.",
		group: "inputs",
		exports: ["Description", "Field", "FieldContent", "FieldError", "FieldGroup", "Fieldset", "Label", "Legend"],
	},
	{
		name: "file-trigger",
		title: "File Trigger",
		description: "A file trigger allows a user to access the file system with any pressable element.",
		group: "buttons",
		exports: ["FileTrigger"],
	},
	{
		name: "group",
		title: "Group",
		description: "A group visually groups related UI elements together.",
		group: "containers",
		exports: ["Group", "GroupText"],
	},
	{
		name: "input",
		title: "Input",
		description: "A basic input component for text entry.",
		group: "inputs",
		exports: ["DateInput", "DateSegment", "Input", "InputGroup", "InputGroupAddon", "TextArea"],
	},
	{
		name: "kbd",
		title: "Kbd",
		description: "A keyboard key indicator displays keyboard shortcuts.",
		group: "tags",
		exports: ["Kbd", "KbdGroup"],
	},
	{
		name: "link",
		title: "Link",
		description: "A link allows a user to navigate to another page or resource.",
		group: "buttons",
		exports: ["Link"],
	},
	{
		name: "list-box",
		title: "List Box",
		description: "A listbox displays a list of options and allows a user to select one or more of them.",
		group: "menus-lists",
		exports: [
			"ListBox",
			"ListBoxItem",
			"ListBoxItemDescription",
			"ListBoxItemLabel",
			"ListBoxSection",
			"ListBoxSectionHeader",
			"ListBoxVirtualizer",
		],
	},
	{
		name: "loader",
		title: "Loader",
		description: "A loader indicates that content is being loaded.",
		group: "progress",
		exports: ["Loader"],
	},
	{
		name: "marker",
		title: "Marker",
		description: "A labeled divider row — a date in a message list, a section label in a feed.",
		group: "containers",
		exports: ["Marker", "MarkerContent", "MarkerIcon"],
	},
	{
		name: "mention",
		title: "Mention",
		description:
			"Mention lets users type a trigger character to insert people, commands, or other tokens inline as they write.",
		group: "pickers",
		exports: ["Mention"],
	},
	{
		name: "menu",
		title: "Menu",
		description: "A menu displays a list of actions or options that a user can choose.",
		group: "menus-lists",
		exports: [
			"Menu",
			"MenuContent",
			"MenuItem",
			"MenuItemDescription",
			"MenuItemLabel",
			"MenuSection",
			"MenuSectionHeader",
			"MenuSub",
		],
	},
	{
		name: "message",
		title: "Message",
		description: "One turn in a conversation — avatar, header, content, and footer, aligned to a side of the thread.",
		group: "containers",
		exports: ["Message", "MessageAvatar", "MessageContent", "MessageFooter", "MessageGroup", "MessageHeader"],
	},
	{
		name: "message-scroller",
		title: "MessageScroller",
		description:
			"A message list that sticks to the newest message, with a scroll-to-bottom button and lazy-rendered items.",
		group: "containers",
		exports: [
			"MessageScroller",
			"MessageScrollerButton",
			"MessageScrollerContent",
			"MessageScrollerItem",
			"MessageScrollerProvider",
			"MessageScrollerViewport",
		],
	},
	{
		name: "modal",
		title: "Modal",
		description: "A modal displays content in a layer that overlays the page content.",
		group: "overlays",
		exports: ["Modal", "ModalBackdrop", "ModalOverlay", "ModalPanel", "ModalViewport"],
	},
	{
		name: "number-field",
		title: "Number Field",
		description:
			"A number field allows a user to enter a number value with a keyboard or increment/decrement with step buttons.",
		group: "inputs",
		exports: ["NumberField", "NumberFieldDecrement", "NumberFieldGroup", "NumberFieldIncrement"],
	},
	{
		name: "otp-field",
		title: "OTP Field",
		description: "An OTP field lets users enter a one-time passcode across multiple single-character inputs.",
		group: "inputs",
		exports: ["OTPField", "OTPFieldGroup", "OTPFieldSeparator"],
	},
	{
		name: "pagination",
		title: "Pagination",
		description: "Pagination lets users navigate through content split across multiple pages.",
		group: "navigation",
		exports: [
			"Pagination",
			"PaginationEllipsis",
			"PaginationItem",
			"PaginationLink",
			"PaginationList",
			"PaginationNext",
			"PaginationPrevious",
		],
	},
	{
		name: "popover",
		title: "Popover",
		description: "A popover displays content in a floating container that appears above other content.",
		group: "overlays",
		exports: ["Popover"],
	},
	{
		name: "progress-bar",
		title: "Progress Bar",
		description: "A progress bar shows the progression of a task.",
		group: "progress",
		exports: ["ProgressBar", "ProgressBarControl", "ProgressBarFill", "ProgressBarOutput", "ProgressBarTrack"],
	},
	{
		name: "qr-code",
		title: "QR Code",
		description: "A QR code encodes a value, such as a URL, as a scannable matrix barcode.",
		group: "containers",
		exports: ["QRCode"],
	},
	{
		name: "questionnaire",
		title: "Questionnaire",
		description: "A multi-step survey — one question at a time, with progress, keyboard shortcuts, and navigation.",
		group: "containers",
		exports: [
			"Questionnaire",
			"QuestionnaireActions",
			"QuestionnaireChoice",
			"QuestionnaireChoiceDescription",
			"QuestionnaireChoices",
			"QuestionnaireDescription",
			"QuestionnaireError",
			"QuestionnaireInput",
			"QuestionnaireItem",
			"QuestionnaireNext",
			"QuestionnairePrevious",
			"QuestionnaireProgress",
			"QuestionnaireSkip",
			"QuestionnaireSubmit",
			"QuestionnaireTitle",
		],
	},
	{
		name: "radio-group",
		title: "Radio Group",
		description: "A radio group allows a user to select a single item from a list of mutually exclusive options.",
		group: "selection-controls",
		exports: ["Radio", "RadioControl", "RadioGroup", "RadioIndicator"],
	},
	{
		name: "search-field",
		title: "Search Field",
		description: "A search field allows a user to enter and clear a search query.",
		group: "inputs",
		exports: ["SearchField"],
	},
	{
		name: "segmented-control",
		title: "Segmented Control",
		description:
			"A segmented control lets users pick one option from a small set, with a pill indicator that slides to the selection.",
		group: "buttons",
		exports: ["SegmentedControl", "SegmentedControlItem"],
	},
	{
		name: "select",
		title: "Select",
		description: "Select displays a collapsible list of options and allows a user to select one of them.",
		group: "pickers",
		exports: [
			"SelectItem",
			"SelectSection",
			"SelectSectionHeader",
			"Select",
			"SelectContent",
			"SelectTrigger",
			"SelectValue",
		],
	},
	{
		name: "separator",
		title: "Separator",
		description: "A separator visually divides content in lists, menus, or other places.",
		group: "containers",
		exports: ["Separator"],
	},
	{
		name: "sidebar",
		title: "Sidebar",
		description:
			"A composable, collapsible sidebar for application shells — with a mobile drawer, icon mode, and keyboard toggle.",
		group: "navigation",
		exports: [
			"Sidebar",
			"SidebarContent",
			"SidebarFooter",
			"SidebarGroup",
			"SidebarGroupAction",
			"SidebarGroupContent",
			"SidebarGroupLabel",
			"SidebarHeader",
			"SidebarInset",
			"SidebarMenu",
			"SidebarMenuAction",
			"SidebarMenuBadge",
			"SidebarMenuButton",
			"SidebarMenuItem",
			"SidebarMenuSkeleton",
			"SidebarMenuSub",
			"SidebarMenuSubButton",
			"SidebarMenuSubItem",
			"SidebarProvider",
			"SidebarRail",
			"SidebarSeparator",
			"SidebarTrigger",
		],
	},
	{
		name: "skeleton",
		title: "Skeleton",
		description: "Skeleton is a placeholder component that displays while content is loading.",
		group: "progress",
		exports: ["Skeleton"],
	},
	{
		name: "slider",
		title: "Slider",
		description: "An input where the user selects a value from within a given range.",
		group: "sliders",
		exports: ["Slider", "SliderControl", "SliderFill", "SliderOutput", "SliderThumb", "SliderTrack"],
	},
	{
		name: "switch",
		title: "Switch",
		description: "Switches allow users to turn an individual option on or off.",
		group: "selection-controls",
		exports: ["Switch", "SwitchControl", "SwitchIndicator", "SwitchThumb"],
	},
	{
		name: "table",
		title: "Table",
		description: "A table displays data in rows and columns and enables a user to navigate and select its contents.",
		group: "containers",
		exports: [
			"Table",
			"TableBody",
			"TableCell",
			"TableColumn",
			"TableContainer",
			"TableDropIndicator",
			"TableFooter",
			"TableHeader",
			"TableLayout",
			"TableLoadMore",
			"TableRow",
			"TableVirtualizer",
		],
	},
	{
		name: "tabs",
		title: "Tabs",
		description: "Tabs organize content into multiple sections and allow users to navigate between them.",
		group: "navigation",
		exports: ["Tab", "TabIndicator", "TabList", "TabPanel", "Tabs"],
	},
	{
		name: "tag-group",
		title: "Tag Group",
		description: "A tag group displays a collection of tags.",
		group: "tags",
		exports: ["Tag", "TagGroup", "TagList"],
	},
	{
		name: "text-field",
		title: "TextField",
		description: "TextField allows a user to enter a plain text value with a keyboard.",
		group: "inputs",
		exports: ["TextField"],
	},
	{
		name: "time-field",
		title: "Time Field",
		description: "A time field allows users to enter and edit time values using a keyboard.",
		group: "inputs",
		exports: ["TimeField"],
	},
	{
		name: "time-picker",
		title: "Time Picker",
		description: "A time picker combines a time field and a scrollable column popover to allow users to select a time.",
		group: "pickers",
		exports: ["TimePicker", "TimePickerColumns"],
	},
	{
		name: "toast",
		title: "Toast",
		description: "A toast displays a brief, temporary notification.",
		group: "feedback",
		exports: ["Toaster", "ToastPrimitive", "ToastProvider"],
	},
	{
		name: "toggle-button",
		title: "Toggle Button",
		description: "A toggle button allows a user to toggle a selection on or off.",
		group: "buttons",
		exports: ["ToggleButton", "ToggleButtonProvider"],
	},
	{
		name: "toggle-button-group",
		title: "Toggle Button Group",
		description: "A toggle button group allows users to select one or more options from a set.",
		group: "buttons",
		exports: ["ToggleButtonGroup"],
	},
	{
		name: "token-field",
		title: "Token Field",
		description: "Token field lets users enter text with inline tokens such as mentions, tags, or object references.",
		group: "inputs",
		exports: ["Token", "TokenField", "TokenInput"],
	},
	{
		name: "tooltip",
		title: "Tooltip",
		description: "A tooltip displays a description of an element on hover or focus.",
		group: "overlays",
		exports: ["Tooltip", "TooltipContent"],
	},
	{
		name: "tree",
		title: "Tree",
		description:
			"A tree provides users with a way to navigate nested hierarchical information, with support for keyboard navigation and selection.",
		group: "menus-lists",
		exports: ["Tree", "TreeItem", "TreeItemContent"],
	},
];
