// AUTO-GENERATED - DO NOT EDIT
// Run "tsx scripts/registry-build.ts" to regenerate

/** Settings row labels per chapter id, for the panel search. */
export const SEARCH_INDEX: Record<string, string[]> = {
	color: ["Brand", "Keep exact", "Vividness", "Neutral", "Semantics", "Primary", "Primary › Primary"],
	typography: ["Heading", "Body", "Mono"],
	icons: ["Library", "Stroke", "Weight"],
	shape: ["Character", "Radius"],
	space: ["Density", "Unit"],
	surfaces: ["Style", "Depth", "Page", "Glass", "Control borders"],
	browser: ["Cursor", "Selectable", "Highlight", "Scrollbars", "Cursors"],
	states: [
		"Control focus",
		"Width",
		"Strength",
		"Offset",
		"Gap",
		"Field focus",
		"Focus",
		"Disabled",
		"Invalid",
		"Controls",
		"Fields",
	],
	motion: ["Character", "Speed", "Overlays", "State changes"],
	mobile: ["Pickers", "Dialogs"],
	components: [
		"Accordion",
		"Accordion › Container",
		"Accordion › Marker",
		"Accordion › Position",
		"Avatars",
		"Avatars › Shape",
		"Avatars › Fallback",
		"Badges",
		"Badges › Style",
		"Badges › Shape",
		"Badges › Kbd",
		"Buttons",
		"Buttons › Style",
		"Buttons › Radius",
		"Buttons › Hover",
		"Buttons › Press",
		"Buttons › Toggles",
		"Buttons › Groups",
		"Buttons › Segmented",
		"Buttons › Selected",
		"Buttons › Track",
		"Charts",
		"Charts › Palette",
		"Charts › Grid",
		"Dialogs",
		"Dialogs › Backdrop",
		"Dialogs › Position",
		"Inputs",
		"Inputs › Style",
		"Inputs › Hover",
		"Inputs › Addons",
		"Inputs › Number field",
		"Inputs › OTP field",
		"Loading",
		"Loading › Skeleton",
		"Loading › Spinner",
		"Loading › Progress",
		"Loading › Track",
		"Loading › Indeterminate",
		"Loading › Track gap",
		"Menus",
		"Menus › Indicator",
		"Menus › Highlight",
		"Menus › Items",
		"Menus › Labels",
		"Menus › Command palette",
		"Menus › Search",
		"Menus › Scale",
		"Navigation",
		"Navigation › Links",
		"Navigation › Tabs",
		"Navigation › Breadcrumbs",
		"Navigation › Separator",
		"Navigation › Crumbs",
		"Navigation › Pagination",
		"Pickers",
		"Pickers › Caret",
		"Pickers › Calendar",
		"Pickers › Day shape",
		"Pickers › Today",
		"Pickers › Weekdays",
		"Popovers",
		"Popovers › Arrow",
		"Popovers › Header",
		"Popovers › Tooltip",
		"Selection controls",
		"Selection controls › Checkbox",
		"Selection controls › Choice cards",
		"Selection controls › Selected",
		"Selection controls › Control",
		"Sliders",
		"Sliders › Thumb",
		"Sliders › Track",
		"Tables",
		"Tables › Rows",
		"Tables › Header",
	],
};
