// AUTO-GENERATED - DO NOT EDIT
// Run "tsx scripts/registry-build.ts" to regenerate

/** Settings row labels per chapter id, for the panel search. */
export const SEARCH_INDEX: Record<string, string[]> = {
	color: [
		"Brand",
		"Keep exact",
		"Neutral",
		"Semantics",
		"Vividness",
		"Contrast",
		"Background",
		"High contrast",
		"Hue shift",
		"Custom borders",
	],
	typography: ["Heading", "Body", "Mono"],
	icons: ["Library", "Stroke", "Weight"],
	shape: ["Radius", "Character"],
	space: ["Density", "Unit"],
	surfaces: ["Style", "Depth", "Glass", "Page", "Shadow"],
	focus: ["Color", "Style", "Geometry", "Width", "Strength", "Offset", "Gap", "Halo", "Border", "Controls", "Inputs"],
	cursor: ["Controls", "Pending", "Dragging", "Disabled"],
	selection: ["UI text", "Highlight"],
	scrollbars: ["Style"],
	disabled: ["Treatment"],
	invalid: ["Treatment"],
	charts: ["Palette", "Grid"],
	motion: ["Character", "Speed", "Overlays", "State changes"],
	mobile: ["Adapt for touch", "Pickers & menus", "Dialogs"],
	links: ["Underline", "Color"],
	alert: [],
	toast: [],
	skeleton: ["Animation"],
	spinner: ["Style"],
	progress: ["Track", "Indeterminate", "Track gap"],
	buttons: ["Style", "Radius", "Hover", "Press"],
	"button-groups": ["Separator"],
	toggles: ["Selected"],
	"segmented-control": ["Selected", "Track"],
	switch: [],
	checkbox: ["Color", "Corner"],
	radio: [],
	"choice-cards": ["Selected", "Control"],
	inputs: ["Style", "Hover"],
	"input-groups": ["Layout", "Divider"],
	"number-field": ["Steppers"],
	"otp-field": ["Cells"],
	pickers: ["Caret"],
	calendar: ["Day shape", "Today", "Weekdays"],
	sliders: ["Thumb", "Track", "Color"],
	menus: ["Indicator", "Highlight", "Items", "Details", "Labels", "Search", "Scale"],
	dialogs: ["Backdrop", "Position"],
	popovers: ["Tip", "Header"],
	tooltips: ["Style"],
	tabs: ["Style", "Color"],
	accordion: ["Container", "Marker", "Position"],
	breadcrumbs: ["Separator", "Crumbs"],
	pagination: ["Current page"],
	badges: ["Style", "Shape"],
	kbd: ["Treatment"],
	avatars: ["Shape", "Fallback"],
	tables: ["Separation", "Header"],
};
