// This file is autogenerated by scripts/build-preview-imports.ts
// Do not edit this file directly.
import type { DocsConfig } from "@/types/docs";

export const docsConfig: DocsConfig = {
  sidebarNav: [
    {
      title: "Getting Started",
      items: [{ title: "Introduction", href: "/getting-started" }],
    },
    {
      title: "Components",
      items: [
        { title: "All components", href: "/components" },
        {
          title: "Core",
          items: [
            { title: "Accordion", href: "/components/core/accordion" },
            { title: "Alert Dialog", href: "/components/core/alert-dialog" },
            { title: "Alert", href: "/components/core/alert" },
            { title: "Aspect Ratio", href: "/components/core/aspect-ratio" },
            { title: "Avatar", href: "/components/core/avatar" },
            { title: "Badge", href: "/components/core/badge" },
            { title: "Button", href: "/components/core/button" },
            { title: "Calendar", href: "/components/core/calendar" },
            { title: "Card", href: "/components/core/card" },
            { title: "Carousel", href: "/components/core/carousel" },
            { title: "Checkbox", href: "/components/core/checkbox" },
            { title: "Collapsible", href: "/components/core/collapsible" },
            { title: "Combobox", href: "/components/core/combobox" },
            { title: "Command", href: "/components/core/command" },
            { title: "Context Menu", href: "/components/core/context-menu" },
            { title: "Data Table", href: "/components/core/data-table" },
            { title: "Date Picker", href: "/components/core/date-picker" },
            { title: "Dialog", href: "/components/core/dialog" },
            { title: "Drawer", href: "/components/core/drawer" },
            { title: "Dropdown Menu", href: "/components/core/dropdown-menu" },
            { title: "React Hook Form", href: "/components/core/form" },
            { title: "Hover Card", href: "/components/core/hover-card" },
            { title: "Input", href: "/components/core/input" },
            { title: "Label", href: "/components/core/label" },
            { title: "Menubar", href: "/components/core/menubar" },
            { title: "Navigation Menu", href: "/components/core/navigation-menu" },
            { title: "Pagination", href: "/components/core/pagination" },
            { title: "Popover", href: "/components/core/popover" },
            { title: "Progress", href: "/components/core/progress" },
            { title: "Radio Group", href: "/components/core/radio-group" },
            { title: "Resizable", href: "/components/core/resizable" },
            { title: "Scroll-area", href: "/components/core/scroll-area" },
            { title: "Select", href: "/components/core/select" },
            { title: "Separator", href: "/components/core/separator" },
            { title: "Sheet", href: "/components/core/sheet" },
            { title: "Skeleton", href: "/components/core/skeleton" },
            { title: "Slider", href: "/components/core/slider" },
            { title: "Sonner", href: "/components/core/sonner" },
            { title: "Switch", href: "/components/core/switch" },
            { title: "Table", href: "/components/core/table" },
            { title: "Tabs", href: "/components/core/tabs" },
            { title: "Textarea", href: "/components/core/textarea" },
            { title: "Toast", href: "/components/core/toast" },
            { title: "Toggle Group", href: "/components/core/toggle-group" },
            { title: "Toggle", href: "/components/core/toggle" },
            { title: "Tooltip", href: "/components/core/tooltip" },
          ],
        },
        {
          title: "Animations",
          items: [
            { title: "Sparkle button", href: "/components/animations/sparkle-button" },
          ],
        },
      ],
    },
    {
      title: "Blocks",
      items: [
        { title: "All blocks", href: "/blocks" },
        {
          title: "Marketing",
          items: [{ title: "Pricing page", href: "/blocks/marketing/pages/pricing" }],
        },
        { title: "Application UI", items: [] },
        { title: "E-commerce", items: [] },
      ],
    },
    {
      title: "Hooks",
      items: [
        { title: "All hooks", href: "/hooks" },
        { title: "useBattery", href: "/hooks/use-battery" },
        { title: "useDebounce", href: "/hooks/use-debounce" },
      ],
    },
    { title: "Icons", items: [{ title: "All icons", href: "/icons" }] },
    { title: "Templates", items: [{ title: "All templates", href: "/templates" }] },
  ],
};
