// This file is autogenerated by scripts/build-preview-imports.ts
// Do not edit this file directly.
import type { DocsConfig } from "@/types/docs";

export const docsConfig: DocsConfig = {
  nav: [
    {
      title: "Getting Started",
      slug: "docs",
      items: [
        { title: "Introduction", href: "/docs" },
        { title: "Installation", href: "/docs/installation" },
        { title: "Styles", href: "/docs/styles" },
        { title: "Changelog", href: "/docs/changelog" },
      ],
    },
    {
      title: "Components",
      slug: "components",
      items: [
        { title: "Overview", href: "/components" },
        {
          title: "Inputs",
          items: [
            { title: "Button", href: "/components/inputs/button" },
            { title: "Checkbox", href: "/components/inputs/checkbox" },
            { title: "Combobox", href: "/components/inputs/combobox" },
            { title: "Date Picker", href: "/components/inputs/date-picker" },
            { title: "Form", href: "/components/inputs/form" },
            { title: "Input OTP", href: "/components/inputs/input-otp" },
            { title: "Input", href: "/components/inputs/input" },
            { title: "Label", href: "/components/inputs/label" },
            { title: "Menubar", href: "/components/inputs/menu-bar" },
            { title: "Radio Group", href: "/components/inputs/radio-group" },
            { title: "Select", href: "/components/inputs/select" },
            { title: "Slider", href: "/components/inputs/slider" },
            { title: "Switch", href: "/components/inputs/switch" },
            { title: "Tabs", href: "/components/inputs/tabs" },
            { title: "Textarea", href: "/components/inputs/textarea" },
            { title: "Toggle Group", href: "/components/inputs/toggle-group" },
            { title: "Toggle", href: "/components/inputs/toggle" },
          ],
        },
        {
          title: "Feedback",
          items: [
            { title: "Alert", href: "/components/feedback/alert" },
            { title: "Progress", href: "/components/feedback/progress" },
            { title: "Skeleton", href: "/components/feedback/skeleton" },
            { title: "Sonner", href: "/components/feedback/sonner" },
            { title: "Toast", href: "/components/feedback/toast" },
          ],
        },
        {
          title: "Layout",
          items: [
            { title: "Aspect Ratio", href: "/components/layout/aspect-ratio" },
            { title: "Resizable", href: "/components/layout/resizable" },
            { title: "Scroll-area", href: "/components/layout/scroll-area" },
          ],
        },
        {
          title: "Data display",
          items: [
            { title: "Accordion", href: "/components/data-display/accordion" },
            {
              title: "AvatarGroup",
              href: "/components/data-display/avatar-group",
              label: "New",
            },
            { title: "Avatar", href: "/components/data-display/avatar" },
            { title: "Badge", href: "/components/data-display/badge" },
            { title: "Calendar", href: "/components/data-display/calendar" },
            { title: "Card", href: "/components/data-display/card" },
            { title: "Carousel", href: "/components/data-display/carousel" },
            { title: "Data Table", href: "/components/data-display/data-table" },
            { title: "Separator", href: "/components/data-display/separator" },
            { title: "Table", href: "/components/data-display/table" },
          ],
        },
        {
          title: "Navigation",
          items: [
            { title: "Breadcrumbs", href: "/components/navigation/breadcrumbs" },
            { title: "Collapsible", href: "/components/navigation/collapsible" },
            { title: "Command", href: "/components/navigation/command" },
            { title: "Navigation Menu", href: "/components/navigation/navigation-menu" },
            { title: "Pagination", href: "/components/navigation/pagination" },
          ],
        },
        {
          title: "Overlay",
          items: [
            { title: "Alert Dialog", href: "/components/overlay/alert-dialog" },
            { title: "Context Menu", href: "/components/overlay/context-menu" },
            { title: "Dialog", href: "/components/overlay/dialog" },
            { title: "Drawer", href: "/components/overlay/drawer" },
            { title: "Dropdown Menu", href: "/components/overlay/dropdown-menu" },
            { title: "Hover Card", href: "/components/overlay/hover-card" },
            { title: "Popover", href: "/components/overlay/popover" },
            { title: "Sheet", href: "/components/overlay/sheet" },
            { title: "Tooltip", href: "/components/overlay/tooltip" },
          ],
        },
        {
          title: "Utils",
          items: [{ title: "Client only", href: "/components/utils/client-only" }],
        },
        {
          title: "Animations",
          items: [
            {
              title: "Sparkle button",
              href: "/components/animations/sparkle-button",
              label: "New",
            },
          ],
        },
      ],
    },
    {
      title: "Blocks",
      slug: "blocks",
      items: [
        { title: "Overview", href: "/blocks" },
        {
          title: "Marketing",
          items: [{ title: "Pricing page", href: "/blocks/marketing/pages/pricing" }],
        },
        { title: "Application UI", items: [] },
        { title: "E-commerce", items: [] },
      ],
    },
    {
      title: "Hooks",
      slug: "hooks",
      items: [
        { title: "Overview", href: "/hooks" },
        {
          title: "Browser",
          items: [{ title: "useMediaQuery", href: "/hooks/browser/use-media-query" }],
        },
        {
          title: "Elements",
          items: [
            { title: "useInView", href: "/hooks/elements/use-in-view" },
            {
              title: "useIntersectionObserver",
              href: "/hooks/elements/use-intersection-observer",
            },
            { title: "useWindowSize", href: "/hooks/elements/use-window-size" },
          ],
        },
        {
          title: "Sensors",
          items: [
            { title: "useBattery", href: "/hooks/sensors/use-battery" },
            { title: "useMouse", href: "/hooks/sensors/use-mouse" },
            { title: "useOrientation", href: "/hooks/sensors/use-orientation" },
          ],
        },
        {
          title: "State",
          items: [{ title: "useLocalStorage", href: "/hooks/state/use-local-storage" }],
        },
        {
          title: "Utilities",
          items: [
            { title: "useCounter", href: "/hooks/utils/use-counter" },
            { title: "useDebounce", href: "/hooks/utils/use-debounce" },
            { title: "useIsClient", href: "/hooks/utils/use-is-client" },
            { title: "useList", href: "/hooks/utils/use-list" },
            { title: "useMounted", href: "/hooks/utils/use-mounted" },
            { title: "usePrevious", href: "/hooks/utils/use-previous" },
          ],
        },
      ],
    },
    { title: "Icons", slug: "icons", items: [{ title: "Overview", href: "/icons" }] },
    {
      title: "Templates",
      slug: "templates",
      items: [{ title: "Overview", href: "/templates" }],
    },
  ],
};
