interface IconLibrary {
  name: string
  label: string
  package: string
  import: string
}

export const iconLibraries = [
  {
    name: "lucide",
    label: "Lucide icons",
    package: "lucide-react",
    import: "lucide-react",
  },
  {
    name: "remix",
    label: "Remix icons",
    package: "@remixicon/react",
    import: "@remixicon/react",
  },
  {
    name: "tabler",
    label: "Tabler icons",
    package: "@tabler/icons-react",
    import: "@tabler/icons-react",
  },
  {
    name: "hugeicons",
    label: "Huge icons",
    package: "@hugeicons/react",
    import: "@hugeicons/react",
  },
  {
    name: "phosphor",
    label: "Phosphor icons",
    package: "@phosphor-icons/react",
    import: "@phosphor-icons/react",
  },
  {
    name: "material-symbols",
    label: "Material Symbols",
    package: "@nine-thirty-five/material-symbols-react",
    import: "@nine-thirty-five/material-symbols-react/outlined",
  },
  {
    name: "octicons",
    label: "Octicons",
    package: "@primer/octicons-react",
    import: "@primer/octicons-react",
  },
] as const satisfies IconLibrary[]

/** Phosphor's `weight` prop values — the icon weight axis (phosphor-only). */
export const phosphorWeights = [
  "thin",
  "light",
  "regular",
  "bold",
  "fill",
  "duotone",
] as const

export type PhosphorWeight = (typeof phosphorWeights)[number]

export type IconLibraryName = (typeof iconLibraries)[number]["name"]

export const registryIcons: Record<
  string,
  Partial<Record<IconLibraryName, string>>
> = {
  PlusIcon: {
    lucide: "PlusIcon",
    remix: "RiAddLine",
    tabler: "IconPlus",
    hugeicons: "PlusSignIcon",
    phosphor: "PlusIcon",
    "material-symbols": "Add",
    octicons: "PlusIcon",
  },
  PaperclipIcon: {
    lucide: "PaperclipIcon",
    remix: "RiAttachmentLine",
    tabler: "IconPaperclip",
    hugeicons: "AttachmentIcon",
    phosphor: "PaperclipIcon",
    "material-symbols": "AttachFile",
    octicons: "PaperclipIcon",
  },
  SparklesIcon: {
    lucide: "SparklesIcon",
    remix: "RiSparklingLine",
    tabler: "IconSparkles",
    hugeicons: "SparklesIcon",
    phosphor: "SparkleIcon",
    "material-symbols": "StarShine",
    octicons: "SparkleIcon",
  },
  ShoppingBagIcon: {
    lucide: "ShoppingBagIcon",
    remix: "RiShoppingBagLine",
    tabler: "IconShoppingBag",
    hugeicons: "ShoppingBag01Icon",
    phosphor: "ShoppingBagIcon",
    "material-symbols": "ShoppingBag",
    octicons: "PackageIcon",
  },
  WandIcon: {
    lucide: "WandIcon",
    remix: "RiMagicLine",
    tabler: "IconWand",
    hugeicons: "MagicWand01Icon",
    phosphor: "MagicWandIcon",
    "material-symbols": "WandStars",
    octicons: "SparkleIcon",
  },
  MousePointerIcon: {
    lucide: "MousePointerIcon",
    remix: "RiCursorLine",
    tabler: "IconPointer",
    hugeicons: "Cursor01Icon",
    phosphor: "CursorIcon",
    "material-symbols": "ArrowSelectorTool",
    octicons: "CursorIcon",
  },
  MoreHorizontalIcon: {
    lucide: "MoreHorizontalIcon",
    remix: "RiMoreLine",
    tabler: "IconDots",
    hugeicons: "MoreHorizontalCircle01Icon",
    phosphor: "DotsThreeIcon",
    "material-symbols": "MoreHoriz",
    octicons: "KebabHorizontalIcon",
  },
  ShareIcon: {
    lucide: "ShareIcon",
    remix: "RiShareLine",
    tabler: "IconShare",
    hugeicons: "Share03Icon",
    phosphor: "ShareIcon",
    "material-symbols": "Share",
    octicons: "ShareIcon",
  },
  BookOpenIcon: {
    lucide: "BookOpenIcon",
    remix: "RiBookOpenLine",
    tabler: "IconBook",
    hugeicons: "BookOpen01Icon",
    phosphor: "BookOpenIcon",
    "material-symbols": "MenuBook",
    octicons: "BookIcon",
  },
  GlobeIcon: {
    lucide: "GlobeIcon",
    remix: "RiGlobalLine",
    tabler: "IconWorld",
    hugeicons: "GlobalIcon",
    phosphor: "GlobeIcon",
    "material-symbols": "Language",
    octicons: "GlobeIcon",
  },
  PenToolIcon: {
    lucide: "PenToolIcon",
    remix: "RiPenNibLine",
    tabler: "IconPencil",
    hugeicons: "QuillWrite01Icon",
    phosphor: "PenNibIcon",
    "material-symbols": "InkPen",
    octicons: "PencilIcon",
  },
  AudioLinesIcon: {
    lucide: "AudioLinesIcon",
    remix: "RiSoundModuleLine",
    tabler: "IconMicrophone",
    hugeicons: "Mic01Icon",
    phosphor: "WaveformIcon",
    "material-symbols": "GraphicEq",
    octicons: "UnmuteIcon",
  },
  ArrowUpIcon: {
    lucide: "ArrowUpIcon",
    remix: "RiArrowUpLine",
    tabler: "IconArrowUp",
    hugeicons: "ArrowUp01Icon",
    phosphor: "ArrowUpIcon",
    "material-symbols": "ArrowUpward",
    octicons: "ArrowUpIcon",
  },
  ChevronDownIcon: {
    lucide: "ChevronDownIcon",
    remix: "RiArrowDownSLine",
    tabler: "IconChevronDown",
    hugeicons: "ArrowDown01Icon",
    phosphor: "CaretDownIcon",
    "material-symbols": "KeyboardArrowDown",
    octicons: "ChevronDownIcon",
  },
  SettingsIcon: {
    lucide: "SettingsIcon",
    remix: "RiSettings3Line",
    tabler: "IconSettings",
    hugeicons: "Settings01Icon",
    phosphor: "GearIcon",
    "material-symbols": "Settings",
    octicons: "GearIcon",
  },
  FolderIcon: {
    lucide: "FolderIcon",
    remix: "RiFolderLine",
    tabler: "IconFolder",
    hugeicons: "Folder01Icon",
    phosphor: "FolderIcon",
    "material-symbols": "Folder",
    octicons: "FileDirectoryIcon",
  },
  CircleCheckIcon: {
    lucide: "CircleCheckIcon",
    remix: "RiCheckboxCircleLine",
    tabler: "IconCircleCheck",
    hugeicons: "CheckmarkCircle02Icon",
    phosphor: "CheckCircleIcon",
    "material-symbols": "CheckCircle",
    octicons: "CheckCircleIcon",
  },
  LightbulbIcon: {
    lucide: "LightbulbIcon",
    remix: "RiLightbulbLine",
    tabler: "IconBulb",
    hugeicons: "BulbIcon",
    phosphor: "LightbulbIcon",
    "material-symbols": "Lightbulb",
    octicons: "LightBulbIcon",
  },
  ContainerIcon: {
    lucide: "ContainerIcon",
    remix: "RiBox3Line",
    tabler: "IconBox",
    hugeicons: "CubeIcon",
    phosphor: "CubeIcon",
    "material-symbols": "DeployedCode",
    octicons: "ContainerIcon",
  },
  ZapIcon: {
    lucide: "ZapIcon",
    remix: "RiFlashlightLine",
    tabler: "IconBolt",
    hugeicons: "ZapIcon",
    phosphor: "LightningIcon",
    "material-symbols": "Bolt",
    octicons: "ZapIcon",
  },
  ServerIcon: {
    lucide: "ServerIcon",
    remix: "RiServerLine",
    tabler: "IconServer",
    hugeicons: "DatabaseIcon",
    phosphor: "HardDrivesIcon",
    "material-symbols": "Dns",
    octicons: "ServerIcon",
  },
  InfoIcon: {
    lucide: "InfoIcon",
    remix: "RiInformationLine",
    tabler: "IconInfoCircle",
    hugeicons: "InformationCircleIcon",
    phosphor: "InfoIcon",
    "material-symbols": "Info",
    octicons: "InfoIcon",
  },
  TerminalIcon: {
    lucide: "TerminalIcon",
    remix: "RiTerminalBoxLine",
    tabler: "IconTerminal",
    hugeicons: "SourceCodeIcon",
    phosphor: "TerminalIcon",
    "material-symbols": "Terminal",
    octicons: "TerminalIcon",
  },
  CopyIcon: {
    lucide: "CopyIcon",
    remix: "RiFileCopyLine",
    tabler: "IconCopy",
    hugeicons: "Copy01Icon",
    phosphor: "CopyIcon",
    "material-symbols": "ContentCopy",
    octicons: "CopyIcon",
  },
  MonitorIcon: {
    lucide: "MonitorIcon",
    remix: "RiComputerLine",
    tabler: "IconDeviceDesktop",
    hugeicons: "ComputerIcon",
    phosphor: "MonitorIcon",
    "material-symbols": "DesktopWindows",
    octicons: "DeviceDesktopIcon",
  },
  DownloadIcon: {
    lucide: "DownloadIcon",
    remix: "RiDownloadLine",
    tabler: "IconDownload",
    hugeicons: "Download01Icon",
    phosphor: "DownloadSimpleIcon",
    "material-symbols": "Download",
    octicons: "DownloadIcon",
  },
  SearchIcon: {
    lucide: "SearchIcon",
    remix: "RiSearchLine",
    tabler: "IconSearch",
    hugeicons: "Search01Icon",
    phosphor: "MagnifyingGlassIcon",
    "material-symbols": "Search",
    octicons: "SearchIcon",
  },
  UploadIcon: {
    lucide: "UploadIcon",
    remix: "RiUpload2Line",
    tabler: "IconUpload",
    hugeicons: "Upload01Icon",
    phosphor: "UploadSimpleIcon",
    "material-symbols": "Upload",
    octicons: "UploadIcon",
  },
  CloudCogIcon: {
    lucide: "CloudCogIcon",
    remix: "RiCloudLine",
    tabler: "IconCloudCog",
    hugeicons: "AiCloud01Icon",
    phosphor: "CloudIcon",
    "material-symbols": "Cloud",
    octicons: "CloudIcon",
  },
  GitBranchIcon: {
    lucide: "GitBranchIcon",
    remix: "RiGitBranchLine",
    tabler: "IconGitBranch",
    hugeicons: "GitBranchIcon",
    phosphor: "GitBranchIcon",
    "material-symbols": "ForkRight",
    octicons: "GitBranchIcon",
  },
  BotIcon: {
    lucide: "BotIcon",
    remix: "RiRobotLine",
    tabler: "IconRobot",
    hugeicons: "RoboticIcon",
    phosphor: "RobotIcon",
    "material-symbols": "SmartToy",
    octicons: "HubotIcon",
  },
  SendIcon: {
    lucide: "SendIcon",
    remix: "RiSendPlaneLine",
    tabler: "IconSend",
    hugeicons: "SentIcon",
    phosphor: "PaperPlaneRightIcon",
    "material-symbols": "Send",
    octicons: "PaperAirplaneIcon",
  },
  MenuIcon: {
    lucide: "MenuIcon",
    remix: "RiMenuLine",
    tabler: "IconMenu",
    hugeicons: "Menu09Icon",
    phosphor: "ListIcon",
    "material-symbols": "Menu",
    octicons: "ThreeBarsIcon",
  },
  XIcon: {
    lucide: "XIcon",
    remix: "RiCloseLine",
    tabler: "IconX",
    hugeicons: "Cancel01Icon",
    phosphor: "XIcon",
    "material-symbols": "Close",
    octicons: "XIcon",
  },
  HomeIcon: {
    lucide: "HomeIcon",
    remix: "RiHomeLine",
    tabler: "IconHome",
    hugeicons: "Home01Icon",
    phosphor: "HouseIcon",
    "material-symbols": "Home",
    octicons: "HomeIcon",
  },
  CircleIcon: {
    lucide: "CircleIcon",
    remix: "RiCircleLine",
    tabler: "IconCircle",
    hugeicons: "CircleIcon",
    phosphor: "CircleIcon",
    "material-symbols": "Circle",
    octicons: "CircleIcon",
  },
  LayoutGridIcon: {
    lucide: "LayoutGridIcon",
    remix: "RiLayoutGridLine",
    tabler: "IconLayoutGrid",
    hugeicons: "GridIcon",
    phosphor: "SquaresFourIcon",
    "material-symbols": "GridView",
    octicons: "AppsIcon",
  },
  MailIcon: {
    lucide: "MailIcon",
    remix: "RiMailLine",
    tabler: "IconMail",
    hugeicons: "Mail01Icon",
    phosphor: "EnvelopeIcon",
    "material-symbols": "Mail",
    octicons: "MailIcon",
  },
  LinkIcon: {
    lucide: "LinkIcon",
    remix: "RiLinkM",
    tabler: "IconLink",
    hugeicons: "Link01Icon",
    phosphor: "LinkIcon",
    "material-symbols": "Link",
    octicons: "LinkIcon",
  },
  SmileIcon: {
    lucide: "SmileIcon",
    remix: "RiEmotionLine",
    tabler: "IconMoodSmile",
    hugeicons: "SmileIcon",
    phosphor: "SmileyIcon",
    "material-symbols": "SentimentSatisfied",
    octicons: "SmileyIcon",
  },
  CircleAlertIcon: {
    lucide: "CircleAlertIcon",
    remix: "RiErrorWarningLine",
    tabler: "IconExclamationCircle",
    hugeicons: "Alert01Icon",
    phosphor: "WarningCircleIcon",
    "material-symbols": "Error",
    octicons: "AlertIcon",
  },
  UserIcon: {
    lucide: "UserIcon",
    remix: "RiUserLine",
    tabler: "IconUser",
    hugeicons: "UserIcon",
    phosphor: "UserIcon",
    "material-symbols": "Person",
    octicons: "PersonIcon",
  },
  StarIcon: {
    lucide: "StarIcon",
    remix: "RiStarLine",
    tabler: "IconStar",
    hugeicons: "StarIcon",
    phosphor: "StarIcon",
    "material-symbols": "Star",
    octicons: "StarIcon",
  },
  CodeIcon: {
    lucide: "CodeIcon",
    remix: "RiCodeLine",
    tabler: "IconCode",
    hugeicons: "CodeIcon",
    phosphor: "CodeIcon",
    "material-symbols": "Code",
    octicons: "CodeIcon",
  },
  HeartIcon: {
    lucide: "HeartIcon",
    remix: "RiHeartLine",
    tabler: "IconHeart",
    hugeicons: "FavouriteIcon",
    phosphor: "HeartIcon",
    "material-symbols": "Favorite",
    octicons: "HeartIcon",
  },
  LogOutIcon: {
    lucide: "LogOutIcon",
    remix: "RiLogoutBoxLine",
    tabler: "IconLogout",
    hugeicons: "Logout01Icon",
    phosphor: "SignOutIcon",
    "material-symbols": "Logout",
    octicons: "SignOutIcon",
  },
  MinusIcon: {
    lucide: "MinusIcon",
    remix: "RiSubtractLine",
    tabler: "IconMinus",
    hugeicons: "MinusSignIcon",
    phosphor: "MinusIcon",
    "material-symbols": "Remove",
    octicons: "DashIcon",
  },
  ArrowLeftIcon: {
    lucide: "ArrowLeftIcon",
    remix: "RiArrowLeftLine",
    tabler: "IconArrowLeft",
    hugeicons: "ArrowLeft01Icon",
    phosphor: "ArrowLeftIcon",
    "material-symbols": "ArrowBack",
    octicons: "ArrowLeftIcon",
  },
  MailCheckIcon: {
    lucide: "MailCheckIcon",
    remix: "RiMailCheckLine",
    tabler: "IconMailCheck",
    hugeicons: "MailValidation01Icon",
    phosphor: "EnvelopeOpenIcon",
    "material-symbols": "MarkEmailRead",
    octicons: "ReadIcon",
  },
  ArchiveIcon: {
    lucide: "ArchiveIcon",
    remix: "RiArchiveLine",
    tabler: "IconArchive",
    hugeicons: "Archive02Icon",
    phosphor: "ArchiveIcon",
    "material-symbols": "Archive",
    octicons: "ArchiveIcon",
  },
  ClockIcon: {
    lucide: "ClockIcon",
    remix: "RiTimeLine",
    tabler: "IconClock",
    hugeicons: "Clock01Icon",
    phosphor: "ClockIcon",
    "material-symbols": "Schedule",
    octicons: "ClockIcon",
  },
  CalendarPlusIcon: {
    lucide: "CalendarPlusIcon",
    remix: "RiCalendarEventLine",
    tabler: "IconCalendarPlus",
    hugeicons: "CalendarAdd01Icon",
    phosphor: "CalendarPlusIcon",
    "material-symbols": "CalendarAddOn",
    octicons: "CalendarIcon",
  },
  ListFilterIcon: {
    lucide: "ListFilterIcon",
    remix: "RiFilterLine",
    tabler: "IconFilterPlus",
    hugeicons: "FilterIcon",
    phosphor: "FunnelIcon",
    "material-symbols": "FilterList",
    octicons: "FilterIcon",
  },
  TagIcon: {
    lucide: "TagIcon",
    remix: "RiPriceTag3Line",
    tabler: "IconTag",
    hugeicons: "Tag01Icon",
    phosphor: "TagIcon",
    "material-symbols": "Sell",
    octicons: "TagIcon",
  },
  Trash2Icon: {
    lucide: "Trash2Icon",
    remix: "RiDeleteBin6Line",
    tabler: "IconTrash",
    hugeicons: "Delete02Icon",
    phosphor: "TrashSimpleIcon",
    "material-symbols": "Delete",
    octicons: "TrashIcon",
  },
  ArrowRightIcon: {
    lucide: "ArrowRightIcon",
    remix: "RiArrowRightLine",
    tabler: "IconArrowRight",
    hugeicons: "ArrowRight02Icon",
    phosphor: "ArrowRightIcon",
    "material-symbols": "ArrowForward",
    octicons: "ArrowRightIcon",
  },
  VolumeX: {
    lucide: "VolumeX",
    remix: "RiVolumeMuteLine",
    tabler: "IconVolume",
    hugeicons: "VolumeOffIcon",
    phosphor: "SpeakerXIcon",
    "material-symbols": "VolumeOff",
    octicons: "MuteIcon",
  },
  CheckIcon: {
    lucide: "CheckIcon",
    remix: "RiCheckLine",
    tabler: "IconCheck",
    hugeicons: "Tick02Icon",
    phosphor: "CheckIcon",
    "material-symbols": "Check",
    octicons: "CheckIcon",
  },
  UserRoundXIcon: {
    lucide: "UserRoundXIcon",
    remix: "RiUserUnfollowLine",
    tabler: "IconUserX",
    hugeicons: "UserRemove01Icon",
    phosphor: "UserMinusIcon",
    "material-symbols": "PersonRemove",
    octicons: "PersonIcon",
  },
  AlertTriangleIcon: {
    lucide: "AlertTriangleIcon",
    remix: "RiAlertLine",
    tabler: "IconAlertTriangle",
    hugeicons: "Alert02Icon",
    phosphor: "WarningIcon",
    "material-symbols": "Warning",
    octicons: "AlertIcon",
  },
  TrashIcon: {
    lucide: "TrashIcon",
    remix: "RiDeleteBinLine",
    tabler: "IconTrash",
    hugeicons: "Delete01Icon",
    phosphor: "TrashIcon",
    "material-symbols": "Delete",
    octicons: "TrashIcon",
  },
  BluetoothIcon: {
    lucide: "BluetoothIcon",
    remix: "RiBluetoothLine",
    tabler: "IconBluetooth",
    hugeicons: "BluetoothIcon",
    phosphor: "BluetoothIcon",
    "material-symbols": "Bluetooth",
    octicons: "BroadcastIcon",
  },
  MoreVerticalIcon: {
    lucide: "MoreVerticalIcon",
    remix: "RiMore2Line",
    tabler: "IconDotsVertical",
    hugeicons: "MoreVerticalCircle01Icon",
    phosphor: "DotsThreeVerticalIcon",
    "material-symbols": "MoreVert",
    octicons: "KebabHorizontalIcon",
  },
  FileIcon: {
    lucide: "FileIcon",
    remix: "RiFileLine",
    tabler: "IconFile",
    hugeicons: "File01Icon",
    phosphor: "FileIcon",
    "material-symbols": "Draft",
    octicons: "FileIcon",
  },
  FolderOpenIcon: {
    lucide: "FolderOpenIcon",
    remix: "RiFolderOpenLine",
    tabler: "IconFolderOpen",
    hugeicons: "FolderOpenIcon",
    phosphor: "FolderOpenIcon",
    "material-symbols": "FolderOpen",
    octicons: "FileDirectoryIcon",
  },
  FileCodeIcon: {
    lucide: "FileCodeIcon",
    remix: "RiFileCodeLine",
    tabler: "IconFileCode",
    hugeicons: "CodeIcon",
    phosphor: "FileCodeIcon",
    "material-symbols": "CodeBlocks",
    octicons: "FileCodeIcon",
  },
  FolderSearchIcon: {
    lucide: "FolderSearchIcon",
    remix: "RiFileSearchLine",
    tabler: "IconFolderSearch",
    hugeicons: "Search01Icon",
    phosphor: "FolderOpenIcon",
    "material-symbols": "FolderOpen",
    octicons: "FileDirectoryIcon",
  },
  SaveIcon: {
    lucide: "SaveIcon",
    remix: "RiSaveLine",
    tabler: "IconDeviceFloppy",
    hugeicons: "FloppyDiskIcon",
    phosphor: "FloppyDiskIcon",
    "material-symbols": "Save",
    octicons: "DownloadIcon",
  },
  EyeIcon: {
    lucide: "EyeIcon",
    remix: "RiEyeLine",
    tabler: "IconEye",
    hugeicons: "EyeIcon",
    phosphor: "EyeIcon",
    "material-symbols": "Visibility",
    octicons: "EyeIcon",
  },
  LayoutIcon: {
    lucide: "LayoutIcon",
    remix: "RiLayoutLine",
    tabler: "IconLayout",
    hugeicons: "Layout01Icon",
    phosphor: "LayoutIcon",
    "material-symbols": "SpaceDashboard",
    octicons: "ColumnsIcon",
  },
  PaletteIcon: {
    lucide: "PaletteIcon",
    remix: "RiPaletteLine",
    tabler: "IconPalette",
    hugeicons: "PaintBoardIcon",
    phosphor: "PaletteIcon",
    "material-symbols": "Palette",
    octicons: "PaintbrushIcon",
  },
  SunIcon: {
    lucide: "SunIcon",
    remix: "RiSunLine",
    tabler: "IconSun",
    hugeicons: "Sun01Icon",
    phosphor: "SunIcon",
    "material-symbols": "LightMode",
    octicons: "SunIcon",
  },
  MoonIcon: {
    lucide: "MoonIcon",
    remix: "RiMoonLine",
    tabler: "IconMoon",
    hugeicons: "MoonIcon",
    phosphor: "MoonIcon",
    "material-symbols": "DarkMode",
    octicons: "MoonIcon",
  },
  HelpCircleIcon: {
    lucide: "HelpCircleIcon",
    remix: "RiQuestionLine",
    tabler: "IconHelpCircle",
    hugeicons: "HelpCircleIcon",
    phosphor: "QuestionIcon",
    "material-symbols": "Help",
    octicons: "QuestionIcon",
  },
  FileTextIcon: {
    lucide: "FileTextIcon",
    remix: "RiFileTextLine",
    tabler: "IconFileText",
    hugeicons: "File01Icon",
    phosphor: "FileTextIcon",
    "material-symbols": "Description",
    octicons: "FileIcon",
  },
  CalendarIcon: {
    lucide: "CalendarIcon",
    remix: "RiCalendarLine",
    tabler: "IconCalendar",
    hugeicons: "Calendar01Icon",
    phosphor: "CalendarIcon",
    "material-symbols": "CalendarToday",
    octicons: "CalendarIcon",
  },
  Search: {
    lucide: "Search",
    remix: "RiSearchLine",
    tabler: "IconSearch",
    hugeicons: "Search01Icon",
    phosphor: "MagnifyingGlassIcon",
    "material-symbols": "Search",
    octicons: "SearchIcon",
  },
  CheckCircle2Icon: {
    lucide: "CheckCircle2Icon",
    remix: "RiCheckboxCircleLine",
    tabler: "IconCircleCheckFilled",
    hugeicons: "CheckmarkCircle02Icon",
    phosphor: "CheckCircleIcon",
    "material-symbols": "CheckCircle",
    octicons: "CheckCircleIcon",
  },
  CircleDollarSignIcon: {
    lucide: "CircleDollarSignIcon",
    remix: "RiMoneyDollarCircleLine",
    tabler: "IconCoin",
    hugeicons: "DollarCircleIcon",
    phosphor: "CurrencyCircleDollarIcon",
    "material-symbols": "Paid",
    octicons: "CreditCardIcon",
  },
  ArrowUpRightIcon: {
    lucide: "ArrowUpRightIcon",
    remix: "RiArrowRightUpLine",
    tabler: "IconArrowUpRight",
    hugeicons: "ArrowUpRight01Icon",
    phosphor: "ArrowUpRightIcon",
    "material-symbols": "ArrowOutward",
    octicons: "ArrowUpRightIcon",
  },
  BadgeCheck: {
    lucide: "BadgeCheck",
    remix: "RiVerifiedBadgeLine",
    tabler: "IconRosetteDiscountCheck",
    hugeicons: "CheckmarkBadge02Icon",
    phosphor: "SealCheckIcon",
    "material-symbols": "Verified",
    octicons: "VerifiedIcon",
  },
  ArrowLeftCircleIcon: {
    lucide: "ArrowLeftCircleIcon",
    remix: "RiArrowLeftCircleLine",
    tabler: "IconCircleArrowLeft",
    hugeicons: "CircleArrowLeft02Icon",
    phosphor: "ArrowCircleLeftIcon",
    "material-symbols": "ArrowCircleLeft",
    octicons: "ArrowLeftIcon",
  },
  FlipHorizontalIcon: {
    lucide: "FlipHorizontalIcon",
    remix: "RiFlipHorizontalLine",
    tabler: "IconFlipHorizontal",
    hugeicons: "FlipHorizontalIcon",
    phosphor: "FlipHorizontalIcon",
    "material-symbols": "Flip",
    octicons: "MirrorIcon",
  },
  FlipVerticalIcon: {
    lucide: "FlipVerticalIcon",
    remix: "RiFlipVerticalLine",
    tabler: "IconFlipVertical",
    hugeicons: "FlipVerticalIcon",
    phosphor: "FlipVerticalIcon",
    "material-symbols": "Flip",
    octicons: "MirrorIcon",
  },
  RotateCwIcon: {
    lucide: "RotateCwIcon",
    remix: "RiRestartLine",
    tabler: "IconRotateClockwise2",
    hugeicons: "Rotate01Icon",
    phosphor: "ArrowClockwiseIcon",
    "material-symbols": "RotateRight",
    octicons: "RedoIcon",
  },
  Clock2Icon: {
    lucide: "Clock2Icon",
    remix: "RiTimeLine",
    tabler: "IconClockHour2",
    hugeicons: "Clock03Icon",
    phosphor: "ClockIcon",
    "material-symbols": "Schedule",
    octicons: "ClockIcon",
  },
  CaptionsIcon: {
    lucide: "CaptionsIcon",
    remix: "RiClosedCaptioningLine",
    tabler: "IconTextCaption",
    hugeicons: "ClosedCaptionIcon",
    phosphor: "ClosedCaptioningIcon",
    "material-symbols": "ClosedCaption",
    octicons: "TypographyIcon",
  },
  TrendingUpIcon: {
    lucide: "TrendingUpIcon",
    remix: "RiArrowRightUpLine",
    tabler: "IconTrendingUp",
    hugeicons: "Analytics01Icon",
    phosphor: "TrendUpIcon",
    "material-symbols": "TrendingUp",
    octicons: "GraphIcon",
  },
  ChevronRightIcon: {
    lucide: "ChevronRightIcon",
    remix: "RiArrowRightSLine",
    tabler: "IconChevronRight",
    hugeicons: "ArrowRight01Icon",
    phosphor: "CaretRightIcon",
    "material-symbols": "ChevronRight",
    octicons: "ChevronRightIcon",
  },
  MinimizeIcon: {
    lucide: "MinimizeIcon",
    remix: "RiContractLeftRightLine",
    tabler: "IconMinimize",
    hugeicons: "MinusSignIcon",
    phosphor: "ArrowsInSimpleIcon",
    "material-symbols": "CloseFullscreen",
    octicons: "ScreenNormalIcon",
  },
  MaximizeIcon: {
    lucide: "MaximizeIcon",
    remix: "RiExpandLeftRightLine",
    tabler: "IconMaximize",
    hugeicons: "PlusSignIcon",
    phosphor: "ArrowsOutSimpleIcon",
    "material-symbols": "OpenInFull",
    octicons: "ScreenFullIcon",
  },
  CreditCardIcon: {
    lucide: "CreditCardIcon",
    remix: "RiBankCardLine",
    tabler: "IconCreditCard",
    hugeicons: "CreditCardIcon",
    phosphor: "CreditCardIcon",
    "material-symbols": "CreditCard",
    octicons: "CreditCardIcon",
  },
  CalculatorIcon: {
    lucide: "CalculatorIcon",
    remix: "RiCalculatorLine",
    tabler: "IconCalculator",
    hugeicons: "CalculatorIcon",
    phosphor: "CalculatorIcon",
    "material-symbols": "Calculate",
    octicons: "NumberIcon",
  },
  InboxIcon: {
    lucide: "InboxIcon",
    remix: "RiInboxLine",
    tabler: "IconArchive",
    hugeicons: "Archive02Icon",
    phosphor: "TrayIcon",
    "material-symbols": "Inbox",
    octicons: "InboxIcon",
  },
  FolderPlusIcon: {
    lucide: "FolderPlusIcon",
    remix: "RiFolderAddLine",
    tabler: "IconFolderPlus",
    hugeicons: "FolderAddIcon",
    phosphor: "FolderPlusIcon",
    "material-symbols": "CreateNewFolder",
    octicons: "FileDirectoryIcon",
  },
  ScissorsIcon: {
    lucide: "ScissorsIcon",
    remix: "RiScissorsLine",
    tabler: "IconCut",
    hugeicons: "ScissorIcon",
    phosphor: "ScissorsIcon",
    "material-symbols": "ContentCut",
    octicons: "UnlinkIcon",
  },
  ClipboardPasteIcon: {
    lucide: "ClipboardPasteIcon",
    remix: "RiClipboardLine",
    tabler: "IconClipboard",
    hugeicons: "ClipboardIcon",
    phosphor: "ClipboardIcon",
    "material-symbols": "ContentPaste",
    octicons: "PasteIcon",
  },
  ListIcon: {
    lucide: "ListIcon",
    remix: "RiListUnordered",
    tabler: "IconList",
    hugeicons: "Menu05Icon",
    phosphor: "ListIcon",
    "material-symbols": "List",
    octicons: "ListUnorderedIcon",
  },
  ZoomInIcon: {
    lucide: "ZoomInIcon",
    remix: "RiZoomInLine",
    tabler: "IconZoomIn",
    hugeicons: "ZoomInAreaIcon",
    phosphor: "MagnifyingGlassPlusIcon",
    "material-symbols": "ZoomIn",
    octicons: "ZoomInIcon",
  },
  ZoomOutIcon: {
    lucide: "ZoomOutIcon",
    remix: "RiZoomOutLine",
    tabler: "IconZoomOut",
    hugeicons: "ZoomOutAreaIcon",
    phosphor: "MagnifyingGlassMinusIcon",
    "material-symbols": "ZoomOut",
    octicons: "ZoomOutIcon",
  },
  BellIcon: {
    lucide: "BellIcon",
    remix: "RiNotification3Line",
    tabler: "IconBell",
    hugeicons: "Notification01Icon",
    phosphor: "BellIcon",
    "material-symbols": "Notifications",
    octicons: "BellIcon",
  },
  ImageIcon: {
    lucide: "ImageIcon",
    remix: "RiImageLine",
    tabler: "IconPhoto",
    hugeicons: "Image01Icon",
    phosphor: "ImageIcon",
    "material-symbols": "Image",
    octicons: "ImageIcon",
  },
  KeyboardIcon: {
    lucide: "KeyboardIcon",
    remix: "RiKeyboardLine",
    tabler: "IconKeyboard",
    hugeicons: "KeyboardIcon",
    phosphor: "KeyboardIcon",
    "material-symbols": "Keyboard",
    octicons: "CommandPaletteIcon",
  },
  LanguagesIcon: {
    lucide: "LanguagesIcon",
    remix: "RiTranslate",
    tabler: "IconLanguage",
    hugeicons: "LanguageCircleIcon",
    phosphor: "TranslateIcon",
    "material-symbols": "Translate",
    octicons: "GlobeIcon",
  },
  ShieldIcon: {
    lucide: "ShieldIcon",
    remix: "RiShieldLine",
    tabler: "IconShield",
    hugeicons: "SecurityIcon",
    phosphor: "ShieldIcon",
    "material-symbols": "Shield",
    octicons: "ShieldIcon",
  },
  PencilIcon: {
    lucide: "PencilIcon",
    remix: "RiPencilLine",
    tabler: "IconPencil",
    hugeicons: "Edit01Icon",
    phosphor: "PencilSimpleIcon",
    "material-symbols": "Edit",
    octicons: "PencilIcon",
  },
  ActivityIcon: {
    lucide: "ActivityIcon",
    remix: "RiPulseLine",
    tabler: "IconActivity",
    hugeicons: "Cardiogram01Icon",
    phosphor: "PulseIcon",
    "material-symbols": "VitalSigns",
    octicons: "PulseIcon",
  },
  PanelLeftIcon: {
    lucide: "PanelLeftIcon",
    remix: "RiLayoutLeftLine",
    tabler: "IconLayoutSidebar",
    hugeicons: "LayoutLeftIcon",
    phosphor: "SidebarSimpleIcon",
    "material-symbols": "SideNavigation",
    octicons: "SidebarExpandIcon",
  },
  ArrowDownIcon: {
    lucide: "ArrowDownIcon",
    remix: "RiArrowDownLine",
    tabler: "IconArrowDown",
    hugeicons: "ArrowDown01Icon",
    phosphor: "ArrowDownIcon",
    "material-symbols": "ArrowDownward",
    octicons: "ArrowDownIcon",
  },
  MessageSquareIcon: {
    lucide: "MessageSquareIcon",
    remix: "RiChat1Line",
    tabler: "IconMessage",
    hugeicons: "Message01Icon",
    phosphor: "ChatIcon",
    "material-symbols": "ChatBubble",
    octicons: "CommentIcon",
  },
  WalletIcon: {
    lucide: "WalletIcon",
    remix: "RiWalletLine",
    tabler: "IconWallet",
    hugeicons: "Wallet01Icon",
    phosphor: "WalletIcon",
    "material-symbols": "Wallet",
    octicons: "CreditCardIcon",
  },
  Building2Icon: {
    lucide: "Building2Icon",
    remix: "RiBankLine",
    tabler: "IconBuildingBank",
    hugeicons: "BankIcon",
    phosphor: "BuildingsIcon",
    "material-symbols": "Apartment",
    octicons: "OrganizationIcon",
  },
  BadgeCheckIcon: {
    lucide: "BadgeCheckIcon",
    remix: "RiVerifiedBadgeLine",
    tabler: "IconRosetteDiscountCheck",
    hugeicons: "CheckmarkBadge01Icon",
    phosphor: "SealCheckIcon",
    "material-symbols": "Verified",
    octicons: "VerifiedIcon",
  },
  ChevronsUpDownIcon: {
    lucide: "ChevronsUpDownIcon",
    remix: "RiExpandUpDownLine",
    tabler: "IconSelector",
    hugeicons: "UnfoldMoreIcon",
    phosphor: "CaretUpDownIcon",
    "material-symbols": "UnfoldMore",
    octicons: "UnfoldIcon",
  },
  CircleDashedIcon: {
    lucide: "CircleDashedIcon",
    remix: "RiLoader3Line",
    tabler: "IconCircleDashed",
    hugeicons: "Loading01Icon",
    phosphor: "CircleDashedIcon",
    "material-symbols": "RadioButtonUnchecked",
    octicons: "IssueDraftIcon",
  },
  EyeOffIcon: {
    lucide: "EyeOffIcon",
    remix: "RiEyeOffLine",
    tabler: "IconEyeClosed",
    hugeicons: "ViewOffIcon",
    phosphor: "EyeSlashIcon",
    "material-symbols": "VisibilityOff",
    octicons: "EyeClosedIcon",
  },
  MicIcon: {
    lucide: "MicIcon",
    remix: "RiMicLine",
    tabler: "IconMicrophone",
    hugeicons: "VoiceIcon",
    phosphor: "MicrophoneIcon",
    "material-symbols": "Mic",
    octicons: "UnmuteIcon",
  },
  RadioIcon: {
    lucide: "RadioIcon",
    remix: "RiRadioButtonLine",
    tabler: "IconPlayerRecordFilled",
    hugeicons: "RecordIcon",
    phosphor: "RadioIcon",
    "material-symbols": "Sensors",
    octicons: "BroadcastIcon",
  },
  ExternalLinkIcon: {
    lucide: "ExternalLinkIcon",
    remix: "RiExternalLinkLine",
    tabler: "IconExternalLink",
    hugeicons: "LinkSquare02Icon",
    phosphor: "ArrowSquareOutIcon",
    "material-symbols": "OpenInNew",
    octicons: "LinkExternalIcon",
  },
  RefreshCwIcon: {
    lucide: "RefreshCwIcon",
    remix: "RiRefreshLine",
    tabler: "IconRefresh",
    hugeicons: "RefreshIcon",
    phosphor: "ArrowsClockwiseIcon",
    "material-symbols": "Refresh",
    octicons: "SyncIcon",
  },
  BoldIcon: {
    lucide: "BoldIcon",
    remix: "RiBold",
    tabler: "IconBold",
    hugeicons: "TextBoldIcon",
    phosphor: "TextBIcon",
    "material-symbols": "FormatBold",
    octicons: "BoldIcon",
  },
  ItalicIcon: {
    lucide: "ItalicIcon",
    remix: "RiItalic",
    tabler: "IconItalic",
    hugeicons: "TextItalicIcon",
    phosphor: "TextItalicIcon",
    "material-symbols": "FormatItalic",
    octicons: "ItalicIcon",
  },
  UnderlineIcon: {
    lucide: "UnderlineIcon",
    remix: "RiUnderline",
    tabler: "IconUnderline",
    hugeicons: "TextUnderlineIcon",
    phosphor: "TextUnderlineIcon",
    "material-symbols": "FormatUnderlined",
    octicons: "TypographyIcon",
  },
  TableIcon: {
    lucide: "TableIcon",
    remix: "RiTable2",
    tabler: "IconTable",
    hugeicons: "Table01Icon",
    phosphor: "TableIcon",
    "material-symbols": "Table",
    octicons: "TableIcon",
  },
  ChartLineIcon: {
    lucide: "ChartLineIcon",
    remix: "RiLineChartLine",
    tabler: "IconChartLine",
    hugeicons: "ChartLineData01Icon",
    phosphor: "ChartLineIcon",
    "material-symbols": "ShowChart",
    octicons: "GraphIcon",
  },
  ChartBarIcon: {
    lucide: "ChartBarIcon",
    remix: "RiBarChartLine",
    tabler: "IconChartBar",
    hugeicons: "ChartColumnIcon",
    phosphor: "ChartBarIcon",
    "material-symbols": "BarChart",
    octicons: "GraphBarVerticalIcon",
  },
  ChartPieIcon: {
    lucide: "ChartPieIcon",
    remix: "RiPieChartLine",
    tabler: "IconChartPie",
    hugeicons: "PieChartIcon",
    phosphor: "ChartPieIcon",
    "material-symbols": "PieChart",
    octicons: "MeterIcon",
  },
  TerminalSquareIcon: {
    lucide: "TerminalSquareIcon",
    remix: "RiTerminalLine",
    tabler: "IconTerminal2",
    hugeicons: "SourceCodeSquareIcon",
    phosphor: "TerminalWindowIcon",
    "material-symbols": "Terminal",
    octicons: "TerminalIcon",
  },
  BookOpen: {
    lucide: "BookOpen",
    remix: "RiBookOpenLine",
    tabler: "IconBook",
    hugeicons: "BookOpen02Icon",
    phosphor: "BookOpenIcon",
    "material-symbols": "MenuBook",
    octicons: "BookIcon",
  },
  Settings2Icon: {
    lucide: "Settings2Icon",
    remix: "RiSettings4Line",
    tabler: "IconSettings",
    hugeicons: "Settings05Icon",
    phosphor: "SlidersHorizontalIcon",
    "material-symbols": "Tune",
    octicons: "SlidersIcon",
  },
  FrameIcon: {
    lucide: "FrameIcon",
    remix: "RiCropLine",
    tabler: "IconFrame",
    hugeicons: "CropIcon",
    phosphor: "FrameCornersIcon",
    "material-symbols": "CropFree",
    octicons: "HashIcon",
  },
  PieChartIcon: {
    lucide: "PieChartIcon",
    remix: "RiPieChartLine",
    tabler: "IconChartPie",
    hugeicons: "PieChartIcon",
    phosphor: "ChartPieSliceIcon",
    "material-symbols": "PieChart",
    octicons: "MeterIcon",
  },
  MapIcon: {
    lucide: "MapIcon",
    remix: "RiMapLine",
    tabler: "IconMap",
    hugeicons: "MapsIcon",
    phosphor: "MapTrifoldIcon",
    "material-symbols": "Map",
    octicons: "LocationIcon",
  },
  ShoppingCartIcon: {
    lucide: "ShoppingCartIcon",
    remix: "RiShoppingCartLine",
    tabler: "IconShoppingCart",
    hugeicons: "ShoppingCart01Icon",
    phosphor: "ShoppingCartIcon",
    "material-symbols": "ShoppingCart",
    octicons: "PackageIcon",
  },
  LifeBuoy: {
    lucide: "LifeBuoy",
    remix: "RiLifebuoyLine",
    tabler: "IconLifebuoy",
    hugeicons: "ChartRingIcon",
    phosphor: "LifebuoyIcon",
    "material-symbols": "Support",
    octicons: "QuestionIcon",
  },
  Send: {
    lucide: "Send",
    remix: "RiSendPlaneLine",
    tabler: "IconSend",
    hugeicons: "SentIcon",
    phosphor: "PaperPlaneTiltIcon",
    "material-symbols": "Send",
    octicons: "PaperAirplaneIcon",
  },
  AppWindowIcon: {
    lucide: "AppWindowIcon",
    remix: "RiWindowLine",
    tabler: "IconAppWindow",
    hugeicons: "CursorInWindowIcon",
    phosphor: "AppWindowIcon",
    "material-symbols": "WebAsset",
    octicons: "BrowserIcon",
  },
  BookmarkIcon: {
    lucide: "BookmarkIcon",
    remix: "RiBookmarkLine",
    tabler: "IconBookmark",
    hugeicons: "Bookmark01Icon",
    phosphor: "BookmarkIcon",
    "material-symbols": "Bookmark",
    octicons: "BookmarkIcon",
  },
  ChevronUpIcon: {
    lucide: "ChevronUpIcon",
    remix: "RiArrowUpSLine",
    tabler: "IconChevronUp",
    hugeicons: "ArrowUp01Icon",
    phosphor: "CaretUpIcon",
    "material-symbols": "KeyboardArrowUp",
    octicons: "ChevronUpIcon",
  },
  ChevronLeftIcon: {
    lucide: "ChevronLeftIcon",
    remix: "RiArrowLeftSLine",
    tabler: "IconChevronLeft",
    hugeicons: "ArrowLeft01Icon",
    phosphor: "CaretLeftIcon",
    "material-symbols": "ChevronLeft",
    octicons: "ChevronLeftIcon",
  },
  TriangleAlertIcon: {
    lucide: "TriangleAlertIcon",
    remix: "RiAlertLine",
    tabler: "IconAlertTriangle",
    hugeicons: "Alert02Icon",
    phosphor: "WarningIcon",
    "material-symbols": "Warning",
    octicons: "AlertIcon",
  },
  OctagonXIcon: {
    lucide: "OctagonXIcon",
    remix: "RiCloseCircleLine",
    tabler: "IconAlertOctagon",
    hugeicons: "MultiplicationSignCircleIcon",
    phosphor: "WarningOctagonIcon",
    "material-symbols": "Dangerous",
    octicons: "StopIcon",
  },
  Loader2Icon: {
    lucide: "Loader2Icon",
    remix: "RiLoader4Line",
    tabler: "IconLoader",
    hugeicons: "Loading03Icon",
    phosphor: "CircleNotchIcon",
    "material-symbols": "ProgressActivity",
    octicons: "SyncIcon",
  },
  VolumeOffIcon: {
    lucide: "VolumeOffIcon",
    remix: "RiVolumeMuteLine",
    tabler: "IconVolume",
    hugeicons: "VolumeOffIcon",
    phosphor: "SpeakerXIcon",
    "material-symbols": "VolumeOff",
    octicons: "MuteIcon",
  },
  AlertCircleIcon: {
    lucide: "AlertCircleIcon",
    remix: "RiAlertLine",
    tabler: "IconAlertCircle",
    hugeicons: "Alert01Icon",
    phosphor: "WarningCircleIcon",
    "material-symbols": "Error",
    octicons: "AlertIcon",
  },
  User2Icon: {
    lucide: "User2Icon",
    remix: "RiUserLine",
    tabler: "IconUser",
    hugeicons: "UserIcon",
    phosphor: "UserIcon",
    "material-symbols": "Person",
    octicons: "PersonIcon",
  },
  ArrowRightCircleIcon: {
    lucide: "ArrowRightCircleIcon",
    remix: "RiArrowRightCircleLine",
    tabler: "IconCircleArrowRight",
    hugeicons: "CircleArrowRight02Icon",
    phosphor: "ArrowCircleRightIcon",
    "material-symbols": "ArrowCircleRight",
    octicons: "ArrowRightIcon",
  },
  LogInIcon: {
    lucide: "LogInIcon",
    remix: "RiLoginBoxLine",
    tabler: "IconLogin",
    hugeicons: "Login01Icon",
    phosphor: "SignInIcon",
    "material-symbols": "Login",
    octicons: "SignInIcon",
  },
  PenSquareIcon: {
    lucide: "PenSquareIcon",
    remix: "RiEditLine",
    tabler: "IconEdit",
    hugeicons: "Edit02Icon",
    phosphor: "NotePencilIcon",
    "material-symbols": "EditSquare",
    octicons: "PencilIcon",
  },
  CameraIcon: {
    lucide: "CameraIcon",
    remix: "RiCameraLine",
    tabler: "IconCamera",
    hugeicons: "Camera01Icon",
    phosphor: "CameraIcon",
    "material-symbols": "PhotoCamera",
    octicons: "DeviceCameraIcon",
  },
  PlusSquareIcon: {
    lucide: "PlusSquareIcon",
    remix: "RiAddBoxLine",
    tabler: "IconSquarePlus",
    hugeicons: "PlusSignSquareIcon",
    phosphor: "PlusSquareIcon",
    "material-symbols": "AddBox",
    octicons: "DiffAddedIcon",
  },
  SquarePenIcon: {
    lucide: "SquarePenIcon",
    remix: "RiEdit2Line",
    tabler: "IconEdit",
    hugeicons: "Edit02Icon",
    phosphor: "NotePencilIcon",
    "material-symbols": "EditSquare",
    octicons: "PencilIcon",
  },
  Volume1Icon: {
    lucide: "Volume1Icon",
    remix: "RiVolumeDownLine",
    tabler: "IconVolume2",
    hugeicons: "VolumeLowIcon",
    phosphor: "SpeakerLowIcon",
    "material-symbols": "VolumeDown",
    octicons: "UnmuteIcon",
  },
  Volume2Icon: {
    lucide: "Volume2Icon",
    remix: "RiVolumeUpLine",
    tabler: "IconVolume",
    hugeicons: "VolumeHighIcon",
    phosphor: "SpeakerHighIcon",
    "material-symbols": "VolumeUp",
    octicons: "UnmuteIcon",
  },
  XCircleIcon: {
    lucide: "XCircleIcon",
    remix: "RiCloseCircleLine",
    tabler: "IconCircleX",
    hugeicons: "Cancel01Icon",
    phosphor: "XCircleIcon",
    "material-symbols": "Cancel",
    octicons: "XCircleIcon",
  },
  TimerIcon: {
    lucide: "TimerIcon",
    remix: "RiTimerLine",
    tabler: "IconAlarm",
    hugeicons: "Time01Icon",
    phosphor: "TimerIcon",
    "material-symbols": "Timer",
    octicons: "StopwatchIcon",
  },
  PinIcon: {
    lucide: "PinIcon",
    remix: "RiPushpinLine",
    tabler: "IconPinned",
    hugeicons: "PinIcon",
    phosphor: "PushPinIcon",
    "material-symbols": "Keep",
    octicons: "PinIcon",
  },
  GripVerticalIcon: {
    lucide: "GripVerticalIcon",
    remix: "RiDraggable",
    tabler: "IconGripVertical",
    hugeicons: "DragDropVerticalIcon",
    phosphor: "DotsSixVerticalIcon",
    "material-symbols": "DragIndicator",
    octicons: "GrabberIcon",
  },
  LoaderCircleIcon: {
    lucide: "LoaderCircleIcon",
    remix: "RiLoader4Line",
    tabler: "IconLoader2",
    hugeicons: "Loading03Icon",
    phosphor: "CircleNotchIcon",
    "material-symbols": "ProgressActivity",
    octicons: "SyncIcon",
  },
  ShieldCheckIcon: {
    lucide: "ShieldCheckIcon",
    remix: "RiShieldCheckLine",
    tabler: "IconShieldCheck",
    hugeicons: "SecurityCheckIcon",
    phosphor: "ShieldCheckIcon",
    "material-symbols": "VerifiedUser",
    octicons: "ShieldCheckIcon",
  },
  BlocksIcon: {
    lucide: "BlocksIcon",
    remix: "RiApps2Line",
    tabler: "IconBlocks",
    hugeicons: "DashboardSquare01Icon",
    phosphor: "SquaresFourIcon",
    "material-symbols": "Widgets",
    octicons: "AppsIcon",
  },
  BoxesIcon: {
    lucide: "BoxesIcon",
    remix: "RiStackLine",
    tabler: "IconBoxMultiple",
    hugeicons: "DeliveryBox01Icon",
    phosphor: "PackageIcon",
    "material-symbols": "InventoryTwo",
    octicons: "PackageIcon",
  },
  HandIcon: {
    lucide: "HandIcon",
    remix: "RiHand",
    tabler: "IconHandStop",
    hugeicons: "WavingHand01Icon",
    phosphor: "HandIcon",
    "material-symbols": "PanTool",
    octicons: "BlockedIcon",
  },
  PlugIcon: {
    lucide: "PlugIcon",
    remix: "RiPlugLine",
    tabler: "IconPlug",
    hugeicons: "Plug01Icon",
    phosphor: "PlugIcon",
    "material-symbols": "Power",
    octicons: "PlugIcon",
  },
  SlashSquareIcon: {
    lucide: "SlashSquareIcon",
    remix: "RiSlashCommands2",
    tabler: "IconSlashes",
    hugeicons: "CommandIcon",
    phosphor: "CommandIcon",
    "material-symbols": "KeyboardCommandKey",
    octicons: "CommandPaletteIcon",
  },
  TelescopeIcon: {
    lucide: "TelescopeIcon",
    remix: "RiSearchEyeLine",
    tabler: "IconTelescope",
    hugeicons: "Telescope01Icon",
    phosphor: "BinocularsIcon",
    "material-symbols": "Explore",
    octicons: "TelescopeIcon",
  },
  ImageUpIcon: {
    lucide: "ImageUpIcon",
    remix: "RiImageAddLine",
    tabler: "IconPhotoUp",
    hugeicons: "ImageUpload01Icon",
    phosphor: "ImageIcon",
    "material-symbols": "AddPhotoAlternate",
    octicons: "ImageIcon",
  },
  BitcoinIcon: {
    lucide: "BitcoinIcon",
    remix: "RiBitCoinLine",
    tabler: "IconCurrencyBitcoin",
    hugeicons: "Bitcoin01Icon",
    phosphor: "CurrencyBtcIcon",
    "material-symbols": "CurrencyBitcoin",
    octicons: "CreditCardIcon",
  },
  MoonStarIcon: {
    lucide: "MoonStarIcon",
    remix: "RiMoonClearLine",
    tabler: "IconMoonStars",
    hugeicons: "Moon02Icon",
    phosphor: "MoonStarsIcon",
    "material-symbols": "Bedtime",
    octicons: "MoonIcon",
  },
  TrendingDownIcon: {
    lucide: "TrendingDownIcon",
    remix: "RiArrowRightDownLine",
    tabler: "IconTrendingDown",
    hugeicons: "TradeDownIcon",
    phosphor: "TrendDownIcon",
    "material-symbols": "TrendingDown",
    octicons: "GraphIcon",
  },
  PlusCircleIcon: {
    lucide: "PlusCircleIcon",
    remix: "RiAddCircleLine",
    tabler: "IconCirclePlus",
    hugeicons: "PlusSignCircleIcon",
    phosphor: "PlusCircleIcon",
    "material-symbols": "AddCircle",
    octicons: "PlusCircleIcon",
  },
  BoxIcon: {
    lucide: "BoxIcon",
    remix: "RiBox3Line",
    tabler: "IconBox",
    hugeicons: "CubeIcon",
    phosphor: "CubeIcon",
    "material-symbols": "DeployedCode",
    octicons: "PackageIcon",
  },
  CircleDotIcon: {
    lucide: "CircleDotIcon",
    remix: "RiRecordCircleLine",
    tabler: "IconCircleDot",
    hugeicons: "RecordIcon",
    phosphor: "RadioButtonIcon",
    "material-symbols": "RadioButtonChecked",
    octicons: "IssueOpenedIcon",
  },
  SignalHighIcon: {
    lucide: "SignalHighIcon",
    remix: "RiSignalTowerLine",
    tabler: "IconAntennaBars4",
    hugeicons: "SignalFull01Icon",
    phosphor: "CellSignalHighIcon",
    "material-symbols": "SignalCellularAlt",
    octicons: "GraphBarVerticalIcon",
  },
  BookIcon: {
    lucide: "BookIcon",
    remix: "RiBookLine",
    tabler: "IconBook2",
    hugeicons: "Book02Icon",
    phosphor: "BookIcon",
    "material-symbols": "Book",
    octicons: "BookIcon",
  },
  ContrastIcon: {
    lucide: "ContrastIcon",
    remix: "RiContrastLine",
    tabler: "IconContrast",
    hugeicons: "BlendIcon",
    phosphor: "CircleHalfIcon",
    "material-symbols": "Contrast",
    octicons: "MoonIcon",
  },
  Users2Icon: {
    lucide: "Users2Icon",
    remix: "RiGroupLine",
    tabler: "IconUsers",
    hugeicons: "UserGroupIcon",
    phosphor: "UsersIcon",
    "material-symbols": "Group",
    octicons: "PeopleIcon",
  },
  LayersIcon: {
    lucide: "LayersIcon",
    remix: "RiStackLine",
    tabler: "IconStack2",
    hugeicons: "Layers01Icon",
    phosphor: "StackIcon",
    "material-symbols": "Layers",
    octicons: "StackIcon",
  },
  MousePointer2Icon: {
    lucide: "MousePointer2Icon",
    remix: "RiCursorLine",
    tabler: "IconPointer",
    hugeicons: "Cursor01Icon",
    phosphor: "CursorIcon",
    "material-symbols": "ArrowSelectorTool",
    octicons: "CursorIcon",
  },
  RulerIcon: {
    lucide: "RulerIcon",
    remix: "RiRulerLine",
    tabler: "IconRuler",
    hugeicons: "RulerIcon",
    phosphor: "RulerIcon",
    "material-symbols": "Straighten",
    octicons: "SpacingMediumIcon",
  },
  ShapesIcon: {
    lucide: "ShapesIcon",
    remix: "RiShapesLine",
    tabler: "IconTriangleSquareCircle",
    hugeicons: "ShapesIcon",
    phosphor: "ShapesIcon",
    "material-symbols": "Category",
    octicons: "SquareCircleIcon",
  },
  TypeIcon: {
    lucide: "TypeIcon",
    remix: "RiFontSize",
    tabler: "IconTypography",
    hugeicons: "TextIcon",
    phosphor: "TextTIcon",
    "material-symbols": "Title",
    octicons: "TypographyIcon",
  },
}
