interface IconLibrary {
  name: string
  label: string
  package: string
  import: string
}

export const iconLibraries = [
  {
    name: 'lucide',
    label: 'Lucide icons',
    package: 'lucide-react',
    import: 'lucide-react',
  },
  {
    name: 'remix',
    label: 'Remix icons',
    package: '@remixicon/react',
    import: '@remixicon/react',
  },
  {
    name: 'tabler',
    label: 'Tabler icons',
    package: '@tabler/icons-react',
    import: '@tabler/icons-react',
  },
  {
    name: 'hugeicons',
    label: 'Huge icons',
    package: '@hugeicons/react',
    import: '@hugeicons/react',
  },
  {
    name: 'phosphor',
    label: 'Phosphor icons',
    package: '@phosphor-icons/react',
    import: '@phosphor-icons/react',
  },
] as const satisfies IconLibrary[]

/** Phosphor's `weight` prop values — the icon weight axis (phosphor-only). */
export const phosphorWeights = [
  'thin',
  'light',
  'regular',
  'bold',
  'fill',
  'duotone',
] as const

export type PhosphorWeight = (typeof phosphorWeights)[number]

export type IconLibraryName = (typeof iconLibraries)[number]['name']

export const registryIcons: Record<
  string,
  Partial<Record<IconLibraryName, string>>
> = {
  PlusIcon: {
    lucide: 'PlusIcon',
    remix: 'RiAddLine',
    tabler: 'IconPlus',
    hugeicons: 'PlusSignIcon',
    phosphor: 'PlusIcon',
  },
  PaperclipIcon: {
    lucide: 'PaperclipIcon',
    remix: 'RiAttachmentLine',
    tabler: 'IconPaperclip',
    hugeicons: 'AttachmentIcon',
    phosphor: 'PaperclipIcon',
  },
  SparklesIcon: {
    lucide: 'SparklesIcon',
    remix: 'RiSparklingLine',
    tabler: 'IconSparkles',
    hugeicons: 'SparklesIcon',
    phosphor: 'SparkleIcon',
  },
  ShoppingBagIcon: {
    lucide: 'ShoppingBagIcon',
    remix: 'RiShoppingBagLine',
    tabler: 'IconShoppingBag',
    hugeicons: 'ShoppingBag01Icon',
    phosphor: 'ShoppingBagIcon',
  },
  WandIcon: {
    lucide: 'WandIcon',
    remix: 'RiMagicLine',
    tabler: 'IconWand',
    hugeicons: 'MagicWand01Icon',
    phosphor: 'MagicWandIcon',
  },
  MousePointerIcon: {
    lucide: 'MousePointerIcon',
    remix: 'RiCursorLine',
    tabler: 'IconPointer',
    hugeicons: 'Cursor01Icon',
    phosphor: 'CursorIcon',
  },
  MoreHorizontalIcon: {
    lucide: 'MoreHorizontalIcon',
    remix: 'RiMoreLine',
    tabler: 'IconDots',
    hugeicons: 'MoreHorizontalCircle01Icon',
    phosphor: 'DotsThreeIcon',
  },
  ShareIcon: {
    lucide: 'ShareIcon',
    remix: 'RiShareLine',
    tabler: 'IconShare',
    hugeicons: 'Share03Icon',
    phosphor: 'ShareIcon',
  },
  BookOpenIcon: {
    lucide: 'BookOpenIcon',
    remix: 'RiBookOpenLine',
    tabler: 'IconBook',
    hugeicons: 'BookOpen01Icon',
    phosphor: 'BookOpenIcon',
  },
  GlobeIcon: {
    lucide: 'GlobeIcon',
    remix: 'RiGlobalLine',
    tabler: 'IconWorld',
    hugeicons: 'GlobalIcon',
    phosphor: 'GlobeIcon',
  },
  PenToolIcon: {
    lucide: 'PenToolIcon',
    remix: 'RiPenNibLine',
    tabler: 'IconPencil',
    hugeicons: 'QuillWrite01Icon',
    phosphor: 'PenNibIcon',
  },
  AudioLinesIcon: {
    lucide: 'AudioLinesIcon',
    remix: 'RiSoundModuleLine',
    tabler: 'IconMicrophone',
    hugeicons: 'Mic01Icon',
    phosphor: 'WaveformIcon',
  },
  ArrowUpIcon: {
    lucide: 'ArrowUpIcon',
    remix: 'RiArrowUpLine',
    tabler: 'IconArrowUp',
    hugeicons: 'ArrowUp01Icon',
    phosphor: 'ArrowUpIcon',
  },
  ChevronDownIcon: {
    lucide: 'ChevronDownIcon',
    remix: 'RiArrowDownSLine',
    tabler: 'IconChevronDown',
    hugeicons: 'ArrowDown01Icon',
    phosphor: 'CaretDownIcon',
  },
  SettingsIcon: {
    lucide: 'SettingsIcon',
    remix: 'RiSettings3Line',
    tabler: 'IconSettings',
    hugeicons: 'Settings01Icon',
    phosphor: 'GearIcon',
  },
  FolderIcon: {
    lucide: 'FolderIcon',
    remix: 'RiFolderLine',
    tabler: 'IconFolder',
    hugeicons: 'Folder01Icon',
    phosphor: 'FolderIcon',
  },
  CircleCheckIcon: {
    lucide: 'CircleCheckIcon',
    remix: 'RiCheckboxCircleLine',
    tabler: 'IconCircleCheck',
    hugeicons: 'CheckmarkCircle02Icon',
    phosphor: 'CheckCircleIcon',
  },
  LightbulbIcon: {
    lucide: 'LightbulbIcon',
    remix: 'RiLightbulbLine',
    tabler: 'IconBulb',
    hugeicons: 'BulbIcon',
    phosphor: 'LightbulbIcon',
  },
  ContainerIcon: {
    lucide: 'ContainerIcon',
    remix: 'RiBox3Line',
    tabler: 'IconBox',
    hugeicons: 'CubeIcon',
    phosphor: 'CubeIcon',
  },
  ZapIcon: {
    lucide: 'ZapIcon',
    remix: 'RiFlashlightLine',
    tabler: 'IconBolt',
    hugeicons: 'ZapIcon',
    phosphor: 'LightningIcon',
  },
  ServerIcon: {
    lucide: 'ServerIcon',
    remix: 'RiServerLine',
    tabler: 'IconServer',
    hugeicons: 'DatabaseIcon',
    phosphor: 'HardDrivesIcon',
  },
  InfoIcon: {
    lucide: 'InfoIcon',
    remix: 'RiInformationLine',
    tabler: 'IconInfoCircle',
    hugeicons: 'InformationCircleIcon',
    phosphor: 'InfoIcon',
  },
  TerminalIcon: {
    lucide: 'TerminalIcon',
    remix: 'RiTerminalBoxLine',
    tabler: 'IconTerminal',
    hugeicons: 'SourceCodeIcon',
    phosphor: 'TerminalIcon',
  },
  CopyIcon: {
    lucide: 'CopyIcon',
    remix: 'RiFileCopyLine',
    tabler: 'IconCopy',
    hugeicons: 'Copy01Icon',
    phosphor: 'CopyIcon',
  },
  MonitorIcon: {
    lucide: 'MonitorIcon',
    remix: 'RiComputerLine',
    tabler: 'IconDeviceDesktop',
    hugeicons: 'ComputerIcon',
    phosphor: 'MonitorIcon',
  },
  DownloadIcon: {
    lucide: 'DownloadIcon',
    remix: 'RiDownloadLine',
    tabler: 'IconDownload',
    hugeicons: 'Download01Icon',
    phosphor: 'DownloadSimpleIcon',
  },
  SearchIcon: {
    lucide: 'SearchIcon',
    remix: 'RiSearchLine',
    tabler: 'IconSearch',
    hugeicons: 'Search01Icon',
    phosphor: 'MagnifyingGlassIcon',
  },
  UploadIcon: {
    lucide: 'UploadIcon',
    remix: 'RiUpload2Line',
    tabler: 'IconUpload',
    hugeicons: 'Upload01Icon',
    phosphor: 'UploadSimpleIcon',
  },
  CloudCogIcon: {
    lucide: 'CloudCogIcon',
    remix: 'RiCloudLine',
    tabler: 'IconCloudCog',
    hugeicons: 'AiCloud01Icon',
    phosphor: 'CloudIcon',
  },
  GitBranchIcon: {
    lucide: 'GitBranchIcon',
    remix: 'RiGitBranchLine',
    tabler: 'IconGitBranch',
    hugeicons: 'GitBranchIcon',
    phosphor: 'GitBranchIcon',
  },
  BotIcon: {
    lucide: 'BotIcon',
    remix: 'RiRobotLine',
    tabler: 'IconRobot',
    hugeicons: 'RoboticIcon',
    phosphor: 'RobotIcon',
  },
  SendIcon: {
    lucide: 'SendIcon',
    remix: 'RiSendPlaneLine',
    tabler: 'IconSend',
    hugeicons: 'SentIcon',
    phosphor: 'PaperPlaneRightIcon',
  },
  MenuIcon: {
    lucide: 'MenuIcon',
    remix: 'RiMenuLine',
    tabler: 'IconMenu',
    hugeicons: 'Menu09Icon',
    phosphor: 'ListIcon',
  },
  XIcon: {
    lucide: 'XIcon',
    remix: 'RiCloseLine',
    tabler: 'IconX',
    hugeicons: 'Cancel01Icon',
    phosphor: 'XIcon',
  },
  HomeIcon: {
    lucide: 'HomeIcon',
    remix: 'RiHomeLine',
    tabler: 'IconHome',
    hugeicons: 'Home01Icon',
    phosphor: 'HouseIcon',
  },
  CircleIcon: {
    lucide: 'CircleIcon',
    remix: 'RiCircleLine',
    tabler: 'IconCircle',
    hugeicons: 'CircleIcon',
    phosphor: 'CircleIcon',
  },
  LayoutGridIcon: {
    lucide: 'LayoutGridIcon',
    remix: 'RiLayoutGridLine',
    tabler: 'IconLayoutGrid',
    hugeicons: 'GridIcon',
    phosphor: 'SquaresFourIcon',
  },
  MailIcon: {
    lucide: 'MailIcon',
    remix: 'RiMailLine',
    tabler: 'IconMail',
    hugeicons: 'Mail01Icon',
    phosphor: 'EnvelopeIcon',
  },
  LinkIcon: {
    lucide: 'LinkIcon',
    remix: 'RiLinkM',
    tabler: 'IconLink',
    hugeicons: 'Link01Icon',
    phosphor: 'LinkIcon',
  },
  SmileIcon: {
    lucide: 'SmileIcon',
    remix: 'RiEmotionLine',
    tabler: 'IconMoodSmile',
    hugeicons: 'SmileIcon',
    phosphor: 'SmileyIcon',
  },
  CircleAlertIcon: {
    lucide: 'CircleAlertIcon',
    remix: 'RiErrorWarningLine',
    tabler: 'IconExclamationCircle',
    hugeicons: 'Alert01Icon',
    phosphor: 'WarningCircleIcon',
  },
  UserIcon: {
    lucide: 'UserIcon',
    remix: 'RiUserLine',
    tabler: 'IconUser',
    hugeicons: 'UserIcon',
    phosphor: 'UserIcon',
  },
  StarIcon: {
    lucide: 'StarIcon',
    remix: 'RiStarLine',
    tabler: 'IconStar',
    hugeicons: 'StarIcon',
    phosphor: 'StarIcon',
  },
  CodeIcon: {
    lucide: 'CodeIcon',
    remix: 'RiCodeLine',
    tabler: 'IconCode',
    hugeicons: 'CodeIcon',
    phosphor: 'CodeIcon',
  },
  HeartIcon: {
    lucide: 'HeartIcon',
    remix: 'RiHeartLine',
    tabler: 'IconHeart',
    hugeicons: 'FavouriteIcon',
    phosphor: 'HeartIcon',
  },
  LogOutIcon: {
    lucide: 'LogOutIcon',
    remix: 'RiLogoutBoxLine',
    tabler: 'IconLogout',
    hugeicons: 'Logout01Icon',
    phosphor: 'SignOutIcon',
  },
  MinusIcon: {
    lucide: 'MinusIcon',
    remix: 'RiSubtractLine',
    tabler: 'IconMinus',
    hugeicons: 'MinusSignIcon',
    phosphor: 'MinusIcon',
  },
  ArrowLeftIcon: {
    lucide: 'ArrowLeftIcon',
    remix: 'RiArrowLeftLine',
    tabler: 'IconArrowLeft',
    hugeicons: 'ArrowLeft01Icon',
    phosphor: 'ArrowLeftIcon',
  },
  MailCheckIcon: {
    lucide: 'MailCheckIcon',
    remix: 'RiMailCheckLine',
    tabler: 'IconMailCheck',
    hugeicons: 'MailValidation01Icon',
    phosphor: 'EnvelopeOpenIcon',
  },
  ArchiveIcon: {
    lucide: 'ArchiveIcon',
    remix: 'RiArchiveLine',
    tabler: 'IconArchive',
    hugeicons: 'Archive02Icon',
    phosphor: 'ArchiveIcon',
  },
  ClockIcon: {
    lucide: 'ClockIcon',
    remix: 'RiTimeLine',
    tabler: 'IconClock',
    hugeicons: 'Clock01Icon',
    phosphor: 'ClockIcon',
  },
  CalendarPlusIcon: {
    lucide: 'CalendarPlusIcon',
    remix: 'RiCalendarEventLine',
    tabler: 'IconCalendarPlus',
    hugeicons: 'CalendarAdd01Icon',
    phosphor: 'CalendarPlusIcon',
  },
  ListFilterIcon: {
    lucide: 'ListFilterIcon',
    remix: 'RiFilterLine',
    tabler: 'IconFilterPlus',
    hugeicons: 'FilterIcon',
    phosphor: 'FunnelIcon',
  },
  TagIcon: {
    lucide: 'TagIcon',
    remix: 'RiPriceTag3Line',
    tabler: 'IconTag',
    hugeicons: 'Tag01Icon',
    phosphor: 'TagIcon',
  },
  Trash2Icon: {
    lucide: 'Trash2Icon',
    remix: 'RiDeleteBin6Line',
    tabler: 'IconTrash',
    hugeicons: 'Delete02Icon',
    phosphor: 'TrashSimpleIcon',
  },
  ArrowRightIcon: {
    lucide: 'ArrowRightIcon',
    remix: 'RiArrowRightLine',
    tabler: 'IconArrowRight',
    hugeicons: 'ArrowRight02Icon',
    phosphor: 'ArrowRightIcon',
  },
  VolumeX: {
    lucide: 'VolumeX',
    remix: 'RiVolumeMuteLine',
    tabler: 'IconVolume',
    hugeicons: 'VolumeOffIcon',
    phosphor: 'SpeakerXIcon',
  },
  CheckIcon: {
    lucide: 'CheckIcon',
    remix: 'RiCheckLine',
    tabler: 'IconCheck',
    hugeicons: 'Tick02Icon',
    phosphor: 'CheckIcon',
  },
  UserRoundXIcon: {
    lucide: 'UserRoundXIcon',
    remix: 'RiUserUnfollowLine',
    tabler: 'IconUserX',
    hugeicons: 'UserRemove01Icon',
    phosphor: 'UserMinusIcon',
  },
  AlertTriangleIcon: {
    lucide: 'AlertTriangleIcon',
    remix: 'RiAlertLine',
    tabler: 'IconAlertTriangle',
    hugeicons: 'Alert02Icon',
    phosphor: 'WarningIcon',
  },
  TrashIcon: {
    lucide: 'TrashIcon',
    remix: 'RiDeleteBinLine',
    tabler: 'IconTrash',
    hugeicons: 'Delete01Icon',
    phosphor: 'TrashIcon',
  },
  BluetoothIcon: {
    lucide: 'BluetoothIcon',
    remix: 'RiBluetoothLine',
    tabler: 'IconBluetooth',
    hugeicons: 'BluetoothIcon',
    phosphor: 'BluetoothIcon',
  },
  MoreVerticalIcon: {
    lucide: 'MoreVerticalIcon',
    remix: 'RiMore2Line',
    tabler: 'IconDotsVertical',
    hugeicons: 'MoreVerticalCircle01Icon',
    phosphor: 'DotsThreeVerticalIcon',
  },
  FileIcon: {
    lucide: 'FileIcon',
    remix: 'RiFileLine',
    tabler: 'IconFile',
    hugeicons: 'File01Icon',
    phosphor: 'FileIcon',
  },
  FolderOpenIcon: {
    lucide: 'FolderOpenIcon',
    remix: 'RiFolderOpenLine',
    tabler: 'IconFolderOpen',
    hugeicons: 'FolderOpenIcon',
    phosphor: 'FolderOpenIcon',
  },
  FileCodeIcon: {
    lucide: 'FileCodeIcon',
    remix: 'RiFileCodeLine',
    tabler: 'IconFileCode',
    hugeicons: 'CodeIcon',
    phosphor: 'FileCodeIcon',
  },
  FolderSearchIcon: {
    lucide: 'FolderSearchIcon',
    remix: 'RiFileSearchLine',
    tabler: 'IconFolderSearch',
    hugeicons: 'Search01Icon',
    phosphor: 'FolderOpenIcon',
  },
  SaveIcon: {
    lucide: 'SaveIcon',
    remix: 'RiSaveLine',
    tabler: 'IconDeviceFloppy',
    hugeicons: 'FloppyDiskIcon',
    phosphor: 'FloppyDiskIcon',
  },
  EyeIcon: {
    lucide: 'EyeIcon',
    remix: 'RiEyeLine',
    tabler: 'IconEye',
    hugeicons: 'EyeIcon',
    phosphor: 'EyeIcon',
  },
  LayoutIcon: {
    lucide: 'LayoutIcon',
    remix: 'RiLayoutLine',
    tabler: 'IconLayout',
    hugeicons: 'Layout01Icon',
    phosphor: 'LayoutIcon',
  },
  PaletteIcon: {
    lucide: 'PaletteIcon',
    remix: 'RiPaletteLine',
    tabler: 'IconPalette',
    hugeicons: 'PaintBoardIcon',
    phosphor: 'PaletteIcon',
  },
  SunIcon: {
    lucide: 'SunIcon',
    remix: 'RiSunLine',
    tabler: 'IconSun',
    hugeicons: 'Sun01Icon',
    phosphor: 'SunIcon',
  },
  MoonIcon: {
    lucide: 'MoonIcon',
    remix: 'RiMoonLine',
    tabler: 'IconMoon',
    hugeicons: 'MoonIcon',
    phosphor: 'MoonIcon',
  },
  HelpCircleIcon: {
    lucide: 'HelpCircleIcon',
    remix: 'RiQuestionLine',
    tabler: 'IconHelpCircle',
    hugeicons: 'HelpCircleIcon',
    phosphor: 'QuestionIcon',
  },
  FileTextIcon: {
    lucide: 'FileTextIcon',
    remix: 'RiFileTextLine',
    tabler: 'IconFileText',
    hugeicons: 'File01Icon',
    phosphor: 'FileTextIcon',
  },
  CalendarIcon: {
    lucide: 'CalendarIcon',
    remix: 'RiCalendarLine',
    tabler: 'IconCalendar',
    hugeicons: 'Calendar01Icon',
    phosphor: 'CalendarIcon',
  },
  Search: {
    lucide: 'Search',
    remix: 'RiSearchLine',
    tabler: 'IconSearch',
    hugeicons: 'Search01Icon',
    phosphor: 'MagnifyingGlassIcon',
  },
  CheckCircle2Icon: {
    lucide: 'CheckCircle2Icon',
    remix: 'RiCheckboxCircleLine',
    tabler: 'IconCircleCheckFilled',
    hugeicons: 'CheckmarkCircle02Icon',
    phosphor: 'CheckCircleIcon',
  },
  CircleDollarSignIcon: {
    lucide: 'CircleDollarSignIcon',
    remix: 'RiMoneyDollarCircleLine',
    tabler: 'IconCoin',
    hugeicons: 'DollarCircleIcon',
    phosphor: 'CurrencyCircleDollarIcon',
  },
  ArrowUpRightIcon: {
    lucide: 'ArrowUpRightIcon',
    remix: 'RiArrowRightUpLine',
    tabler: 'IconArrowUpRight',
    hugeicons: 'ArrowUpRight01Icon',
    phosphor: 'ArrowUpRightIcon',
  },
  BadgeCheck: {
    lucide: 'BadgeCheck',
    remix: 'RiVerifiedBadgeLine',
    tabler: 'IconRosetteDiscountCheck',
    hugeicons: 'CheckmarkBadge02Icon',
    phosphor: 'SealCheckIcon',
  },
  ArrowLeftCircleIcon: {
    lucide: 'ArrowLeftCircleIcon',
    remix: 'RiArrowLeftCircleLine',
    tabler: 'IconCircleArrowLeft',
    hugeicons: 'CircleArrowLeft02Icon',
    phosphor: 'ArrowCircleLeftIcon',
  },
  FlipHorizontalIcon: {
    lucide: 'FlipHorizontalIcon',
    remix: 'RiFlipHorizontalLine',
    tabler: 'IconFlipHorizontal',
    hugeicons: 'FlipHorizontalIcon',
    phosphor: 'FlipHorizontalIcon',
  },
  FlipVerticalIcon: {
    lucide: 'FlipVerticalIcon',
    remix: 'RiFlipVerticalLine',
    tabler: 'IconFlipVertical',
    hugeicons: 'FlipVerticalIcon',
    phosphor: 'FlipVerticalIcon',
  },
  RotateCwIcon: {
    lucide: 'RotateCwIcon',
    remix: 'RiRestartLine',
    tabler: 'IconRotateClockwise2',
    hugeicons: 'Rotate01Icon',
    phosphor: 'ArrowClockwiseIcon',
  },
  Clock2Icon: {
    lucide: 'Clock2Icon',
    remix: 'RiTimeLine',
    tabler: 'IconClockHour2',
    hugeicons: 'Clock03Icon',
    phosphor: 'ClockIcon',
  },
  CaptionsIcon: {
    lucide: 'CaptionsIcon',
    remix: 'RiClosedCaptioningLine',
    tabler: 'IconTextCaption',
    hugeicons: 'ClosedCaptionIcon',
    phosphor: 'ClosedCaptioningIcon',
  },
  TrendingUpIcon: {
    lucide: 'TrendingUpIcon',
    remix: 'RiArrowRightUpLine',
    tabler: 'IconTrendingUp',
    hugeicons: 'Analytics01Icon',
    phosphor: 'TrendUpIcon',
  },
  ChevronRightIcon: {
    lucide: 'ChevronRightIcon',
    remix: 'RiArrowRightSLine',
    tabler: 'IconChevronRight',
    hugeicons: 'ArrowRight01Icon',
    phosphor: 'CaretRightIcon',
  },
  MinimizeIcon: {
    lucide: 'MinimizeIcon',
    remix: 'RiContractLeftRightLine',
    tabler: 'IconMinimize',
    hugeicons: 'MinusSignIcon',
    phosphor: 'ArrowsInSimpleIcon',
  },
  MaximizeIcon: {
    lucide: 'MaximizeIcon',
    remix: 'RiExpandLeftRightLine',
    tabler: 'IconMaximize',
    hugeicons: 'PlusSignIcon',
    phosphor: 'ArrowsOutSimpleIcon',
  },
  CreditCardIcon: {
    lucide: 'CreditCardIcon',
    remix: 'RiBankCardLine',
    tabler: 'IconCreditCard',
    hugeicons: 'CreditCardIcon',
    phosphor: 'CreditCardIcon',
  },
  CalculatorIcon: {
    lucide: 'CalculatorIcon',
    remix: 'RiCalculatorLine',
    tabler: 'IconCalculator',
    hugeicons: 'CalculatorIcon',
    phosphor: 'CalculatorIcon',
  },
  InboxIcon: {
    lucide: 'InboxIcon',
    remix: 'RiInboxLine',
    tabler: 'IconArchive',
    hugeicons: 'Archive02Icon',
    phosphor: 'TrayIcon',
  },
  FolderPlusIcon: {
    lucide: 'FolderPlusIcon',
    remix: 'RiFolderAddLine',
    tabler: 'IconFolderPlus',
    hugeicons: 'FolderAddIcon',
    phosphor: 'FolderPlusIcon',
  },
  ScissorsIcon: {
    lucide: 'ScissorsIcon',
    remix: 'RiScissorsLine',
    tabler: 'IconCut',
    hugeicons: 'ScissorIcon',
    phosphor: 'ScissorsIcon',
  },
  ClipboardPasteIcon: {
    lucide: 'ClipboardPasteIcon',
    remix: 'RiClipboardLine',
    tabler: 'IconClipboard',
    hugeicons: 'ClipboardIcon',
    phosphor: 'ClipboardIcon',
  },
  ListIcon: {
    lucide: 'ListIcon',
    remix: 'RiListUnordered',
    tabler: 'IconList',
    hugeicons: 'Menu05Icon',
    phosphor: 'ListIcon',
  },
  ZoomInIcon: {
    lucide: 'ZoomInIcon',
    remix: 'RiZoomInLine',
    tabler: 'IconZoomIn',
    hugeicons: 'ZoomInAreaIcon',
    phosphor: 'MagnifyingGlassPlusIcon',
  },
  ZoomOutIcon: {
    lucide: 'ZoomOutIcon',
    remix: 'RiZoomOutLine',
    tabler: 'IconZoomOut',
    hugeicons: 'ZoomOutAreaIcon',
    phosphor: 'MagnifyingGlassMinusIcon',
  },
  BellIcon: {
    lucide: 'BellIcon',
    remix: 'RiNotification3Line',
    tabler: 'IconBell',
    hugeicons: 'Notification01Icon',
    phosphor: 'BellIcon',
  },
  ImageIcon: {
    lucide: 'ImageIcon',
    remix: 'RiImageLine',
    tabler: 'IconPhoto',
    hugeicons: 'Image01Icon',
    phosphor: 'ImageIcon',
  },
  KeyboardIcon: {
    lucide: 'KeyboardIcon',
    remix: 'RiKeyboardLine',
    tabler: 'IconKeyboard',
    hugeicons: 'KeyboardIcon',
    phosphor: 'KeyboardIcon',
  },
  LanguagesIcon: {
    lucide: 'LanguagesIcon',
    remix: 'RiTranslate',
    tabler: 'IconLanguage',
    hugeicons: 'LanguageCircleIcon',
    phosphor: 'TranslateIcon',
  },
  ShieldIcon: {
    lucide: 'ShieldIcon',
    remix: 'RiShieldLine',
    tabler: 'IconShield',
    hugeicons: 'SecurityIcon',
    phosphor: 'ShieldIcon',
  },
  PencilIcon: {
    lucide: 'PencilIcon',
    remix: 'RiPencilLine',
    tabler: 'IconPencil',
    hugeicons: 'Edit01Icon',
    phosphor: 'PencilSimpleIcon',
  },
  ActivityIcon: {
    lucide: 'ActivityIcon',
    remix: 'RiPulseLine',
    tabler: 'IconActivity',
    hugeicons: 'Cardiogram01Icon',
    phosphor: 'PulseIcon',
  },
  PanelLeftIcon: {
    lucide: 'PanelLeftIcon',
    remix: 'RiLayoutLeftLine',
    tabler: 'IconLayoutSidebar',
    hugeicons: 'LayoutLeftIcon',
    phosphor: 'SidebarSimpleIcon',
  },
  ArrowDownIcon: {
    lucide: 'ArrowDownIcon',
    remix: 'RiArrowDownLine',
    tabler: 'IconArrowDown',
    hugeicons: 'ArrowDown01Icon',
    phosphor: 'ArrowDownIcon',
  },
  MessageSquareIcon: {
    lucide: 'MessageSquareIcon',
    remix: 'RiChat1Line',
    tabler: 'IconMessage',
    hugeicons: 'Message01Icon',
    phosphor: 'ChatIcon',
  },
  WalletIcon: {
    lucide: 'WalletIcon',
    remix: 'RiWalletLine',
    tabler: 'IconWallet',
    hugeicons: 'Wallet01Icon',
    phosphor: 'WalletIcon',
  },
  Building2Icon: {
    lucide: 'Building2Icon',
    remix: 'RiBankLine',
    tabler: 'IconBuildingBank',
    hugeicons: 'BankIcon',
    phosphor: 'BuildingsIcon',
  },
  BadgeCheckIcon: {
    lucide: 'BadgeCheckIcon',
    remix: 'RiVerifiedBadgeLine',
    tabler: 'IconRosetteDiscountCheck',
    hugeicons: 'CheckmarkBadge01Icon',
    phosphor: 'SealCheckIcon',
  },
  ChevronsUpDownIcon: {
    lucide: 'ChevronsUpDownIcon',
    remix: 'RiExpandUpDownLine',
    tabler: 'IconSelector',
    hugeicons: 'UnfoldMoreIcon',
    phosphor: 'CaretUpDownIcon',
  },
  CircleDashedIcon: {
    lucide: 'CircleDashedIcon',
    remix: 'RiLoader3Line',
    tabler: 'IconCircleDashed',
    hugeicons: 'Loading01Icon',
    phosphor: 'CircleDashedIcon',
  },
  EyeOffIcon: {
    lucide: 'EyeOffIcon',
    remix: 'RiEyeOffLine',
    tabler: 'IconEyeClosed',
    hugeicons: 'ViewOffIcon',
    phosphor: 'EyeSlashIcon',
  },
  MicIcon: {
    lucide: 'MicIcon',
    remix: 'RiMicLine',
    tabler: 'IconMicrophone',
    hugeicons: 'VoiceIcon',
    phosphor: 'MicrophoneIcon',
  },
  RadioIcon: {
    lucide: 'RadioIcon',
    remix: 'RiRadioButtonLine',
    tabler: 'IconPlayerRecordFilled',
    hugeicons: 'RecordIcon',
    phosphor: 'RadioIcon',
  },
  ExternalLinkIcon: {
    lucide: 'ExternalLinkIcon',
    remix: 'RiExternalLinkLine',
    tabler: 'IconExternalLink',
    hugeicons: 'LinkSquare02Icon',
    phosphor: 'ArrowSquareOutIcon',
  },
  RefreshCwIcon: {
    lucide: 'RefreshCwIcon',
    remix: 'RiRefreshLine',
    tabler: 'IconRefresh',
    hugeicons: 'RefreshIcon',
    phosphor: 'ArrowsClockwiseIcon',
  },
  BoldIcon: {
    lucide: 'BoldIcon',
    remix: 'RiBold',
    tabler: 'IconBold',
    hugeicons: 'TextBoldIcon',
    phosphor: 'TextBIcon',
  },
  ItalicIcon: {
    lucide: 'ItalicIcon',
    remix: 'RiItalic',
    tabler: 'IconItalic',
    hugeicons: 'TextItalicIcon',
    phosphor: 'TextItalicIcon',
  },
  UnderlineIcon: {
    lucide: 'UnderlineIcon',
    remix: 'RiUnderline',
    tabler: 'IconUnderline',
    hugeicons: 'TextUnderlineIcon',
    phosphor: 'TextUnderlineIcon',
  },
  TableIcon: {
    lucide: 'TableIcon',
    remix: 'RiTable2',
    tabler: 'IconTable',
    hugeicons: 'Table01Icon',
    phosphor: 'TableIcon',
  },
  ChartLineIcon: {
    lucide: 'ChartLineIcon',
    remix: 'RiLineChartLine',
    tabler: 'IconChartLine',
    hugeicons: 'ChartLineData01Icon',
    phosphor: 'ChartLineIcon',
  },
  ChartBarIcon: {
    lucide: 'ChartBarIcon',
    remix: 'RiBarChartLine',
    tabler: 'IconChartBar',
    hugeicons: 'ChartColumnIcon',
    phosphor: 'ChartBarIcon',
  },
  ChartPieIcon: {
    lucide: 'ChartPieIcon',
    remix: 'RiPieChartLine',
    tabler: 'IconChartPie',
    hugeicons: 'PieChartIcon',
    phosphor: 'ChartPieIcon',
  },
  TerminalSquareIcon: {
    lucide: 'TerminalSquareIcon',
    remix: 'RiTerminalLine',
    tabler: 'IconTerminal2',
    hugeicons: 'SourceCodeSquareIcon',
    phosphor: 'TerminalWindowIcon',
  },
  BookOpen: {
    lucide: 'BookOpen',
    remix: 'RiBookOpenLine',
    tabler: 'IconBook',
    hugeicons: 'BookOpen02Icon',
    phosphor: 'BookOpenIcon',
  },
  Settings2Icon: {
    lucide: 'Settings2Icon',
    remix: 'RiSettings4Line',
    tabler: 'IconSettings',
    hugeicons: 'Settings05Icon',
    phosphor: 'SlidersHorizontalIcon',
  },
  FrameIcon: {
    lucide: 'FrameIcon',
    remix: 'RiCropLine',
    tabler: 'IconFrame',
    hugeicons: 'CropIcon',
    phosphor: 'FrameCornersIcon',
  },
  PieChartIcon: {
    lucide: 'PieChartIcon',
    remix: 'RiPieChartLine',
    tabler: 'IconChartPie',
    hugeicons: 'PieChartIcon',
    phosphor: 'ChartPieSliceIcon',
  },
  MapIcon: {
    lucide: 'MapIcon',
    remix: 'RiMapLine',
    tabler: 'IconMap',
    hugeicons: 'MapsIcon',
    phosphor: 'MapTrifoldIcon',
  },
  ShoppingCartIcon: {
    lucide: 'ShoppingCartIcon',
    remix: 'RiShoppingCartLine',
    tabler: 'IconShoppingCart',
    hugeicons: 'ShoppingCart01Icon',
    phosphor: 'ShoppingCartIcon',
  },
  LifeBuoy: {
    lucide: 'LifeBuoy',
    remix: 'RiLifebuoyLine',
    tabler: 'IconLifebuoy',
    hugeicons: 'ChartRingIcon',
    phosphor: 'LifebuoyIcon',
  },
  Send: {
    lucide: 'Send',
    remix: 'RiSendPlaneLine',
    tabler: 'IconSend',
    hugeicons: 'SentIcon',
    phosphor: 'PaperPlaneTiltIcon',
  },
  AppWindowIcon: {
    lucide: 'AppWindowIcon',
    remix: 'RiWindowLine',
    tabler: 'IconAppWindow',
    hugeicons: 'CursorInWindowIcon',
    phosphor: 'AppWindowIcon',
  },
  BookmarkIcon: {
    lucide: 'BookmarkIcon',
    remix: 'RiBookmarkLine',
    tabler: 'IconBookmark',
    hugeicons: 'Bookmark01Icon',
    phosphor: 'BookmarkIcon',
  },
  ChevronUpIcon: {
    lucide: 'ChevronUpIcon',
    remix: 'RiArrowUpSLine',
    tabler: 'IconChevronUp',
    hugeicons: 'ArrowUp01Icon',
    phosphor: 'CaretUpIcon',
  },
  ChevronLeftIcon: {
    lucide: 'ChevronLeftIcon',
    remix: 'RiArrowLeftSLine',
    tabler: 'IconChevronLeft',
    hugeicons: 'ArrowLeft01Icon',
    phosphor: 'CaretLeftIcon',
  },
  TriangleAlertIcon: {
    lucide: 'TriangleAlertIcon',
    remix: 'RiAlertLine',
    tabler: 'IconAlertTriangle',
    hugeicons: 'Alert02Icon',
    phosphor: 'WarningIcon',
  },
  OctagonXIcon: {
    lucide: 'OctagonXIcon',
    remix: 'RiCloseCircleLine',
    tabler: 'IconAlertOctagon',
    hugeicons: 'MultiplicationSignCircleIcon',
    phosphor: 'WarningOctagonIcon',
  },
  Loader2Icon: {
    lucide: 'Loader2Icon',
    remix: 'RiLoader4Line',
    tabler: 'IconLoader',
    hugeicons: 'Loading03Icon',
    phosphor: 'CircleNotchIcon',
  },
  VolumeOffIcon: {
    lucide: 'VolumeOffIcon',
    remix: 'RiVolumeMuteLine',
    tabler: 'IconVolume',
    hugeicons: 'VolumeOffIcon',
    phosphor: 'SpeakerXIcon',
  },
  AlertCircleIcon: {
    lucide: 'AlertCircleIcon',
    remix: 'RiAlertLine',
    tabler: 'IconAlertCircle',
    hugeicons: 'Alert01Icon',
    phosphor: 'WarningCircleIcon',
  },
  User2Icon: {
    lucide: 'User2Icon',
    remix: 'RiUserLine',
    tabler: 'IconUser',
    hugeicons: 'UserIcon',
    phosphor: 'UserIcon',
  },
  ArrowRightCircleIcon: {
    lucide: 'ArrowRightCircleIcon',
    remix: 'RiArrowRightCircleLine',
    tabler: 'IconCircleArrowRight',
    hugeicons: 'CircleArrowRight02Icon',
    phosphor: 'ArrowCircleRightIcon',
  },
  LogInIcon: {
    lucide: 'LogInIcon',
    remix: 'RiLoginBoxLine',
    tabler: 'IconLogin',
    hugeicons: 'Login01Icon',
    phosphor: 'SignInIcon',
  },
  PenSquareIcon: {
    lucide: 'PenSquareIcon',
    remix: 'RiEditLine',
    tabler: 'IconEdit',
    hugeicons: 'Edit02Icon',
    phosphor: 'NotePencilIcon',
  },
  CameraIcon: {
    lucide: 'CameraIcon',
    remix: 'RiCameraLine',
    tabler: 'IconCamera',
    hugeicons: 'Camera01Icon',
    phosphor: 'CameraIcon',
  },
  PlusSquareIcon: {
    lucide: 'PlusSquareIcon',
    remix: 'RiAddBoxLine',
    tabler: 'IconSquarePlus',
    hugeicons: 'PlusSignSquareIcon',
    phosphor: 'PlusSquareIcon',
  },
  SquarePenIcon: {
    lucide: 'SquarePenIcon',
    remix: 'RiEdit2Line',
    tabler: 'IconEdit',
    hugeicons: 'Edit02Icon',
    phosphor: 'NotePencilIcon',
  },
  Volume1Icon: {
    lucide: 'Volume1Icon',
    remix: 'RiVolumeDownLine',
    tabler: 'IconVolume2',
    hugeicons: 'VolumeLowIcon',
    phosphor: 'SpeakerLowIcon',
  },
  Volume2Icon: {
    lucide: 'Volume2Icon',
    remix: 'RiVolumeUpLine',
    tabler: 'IconVolume',
    hugeicons: 'VolumeHighIcon',
    phosphor: 'SpeakerHighIcon',
  },
  XCircleIcon: {
    lucide: 'XCircleIcon',
    remix: 'RiCloseCircleLine',
    tabler: 'IconCircleX',
    hugeicons: 'Cancel01Icon',
    phosphor: 'XCircleIcon',
  },
  TimerIcon: {
    lucide: 'TimerIcon',
    remix: 'RiTimerLine',
    tabler: 'IconAlarm',
    hugeicons: 'Time01Icon',
    phosphor: 'TimerIcon',
  },
  PinIcon: {
    lucide: 'PinIcon',
    remix: 'RiPushpinLine',
    tabler: 'IconPinned',
    hugeicons: 'PinIcon',
    phosphor: 'PushPinIcon',
  },
  GripVerticalIcon: {
    lucide: 'GripVerticalIcon',
    remix: 'RiDraggable',
    tabler: 'IconGripVertical',
    hugeicons: 'DragDropVerticalIcon',
    phosphor: 'DotsSixVerticalIcon',
  },
  LoaderCircleIcon: {
    lucide: 'LoaderCircleIcon',
    remix: 'RiLoader4Line',
    tabler: 'IconLoader2',
    hugeicons: 'Loading03Icon',
    phosphor: 'CircleNotchIcon',
  },
  ShieldCheckIcon: {
    lucide: 'ShieldCheckIcon',
    remix: 'RiShieldCheckLine',
    tabler: 'IconShieldCheck',
    hugeicons: 'SecurityCheckIcon',
    phosphor: 'ShieldCheckIcon',
  },
  BlocksIcon: {
    lucide: 'BlocksIcon',
    remix: 'RiApps2Line',
    tabler: 'IconBlocks',
    hugeicons: 'DashboardSquare01Icon',
    phosphor: 'SquaresFourIcon',
  },
  BoxesIcon: {
    lucide: 'BoxesIcon',
    remix: 'RiStackLine',
    tabler: 'IconBoxMultiple',
    hugeicons: 'DeliveryBox01Icon',
    phosphor: 'PackageIcon',
  },
  HandIcon: {
    lucide: 'HandIcon',
    remix: 'RiHand',
    tabler: 'IconHandStop',
    hugeicons: 'WavingHand01Icon',
    phosphor: 'HandIcon',
  },
  PlugIcon: {
    lucide: 'PlugIcon',
    remix: 'RiPlugLine',
    tabler: 'IconPlug',
    hugeicons: 'Plug01Icon',
    phosphor: 'PlugIcon',
  },
  SlashSquareIcon: {
    lucide: 'SlashSquareIcon',
    remix: 'RiSlashCommands2',
    tabler: 'IconSlashes',
    hugeicons: 'CommandIcon',
    phosphor: 'CommandIcon',
  },
  TelescopeIcon: {
    lucide: 'TelescopeIcon',
    remix: 'RiSearchEyeLine',
    tabler: 'IconTelescope',
    hugeicons: 'Telescope01Icon',
    phosphor: 'BinocularsIcon',
  },
  ImageUpIcon: {
    lucide: 'ImageUpIcon',
    remix: 'RiImageAddLine',
    tabler: 'IconPhotoUp',
    hugeicons: 'ImageUpload01Icon',
    phosphor: 'ImageIcon',
  },
  BitcoinIcon: {
    lucide: 'BitcoinIcon',
    remix: 'RiBitCoinLine',
    tabler: 'IconCurrencyBitcoin',
    hugeicons: 'Bitcoin01Icon',
    phosphor: 'CurrencyBtcIcon',
  },
  MoonStarIcon: {
    lucide: 'MoonStarIcon',
    remix: 'RiMoonClearLine',
    tabler: 'IconMoonStars',
    hugeicons: 'Moon02Icon',
    phosphor: 'MoonStarsIcon',
  },
  TrendingDownIcon: {
    lucide: 'TrendingDownIcon',
    remix: 'RiArrowRightDownLine',
    tabler: 'IconTrendingDown',
    hugeicons: 'TradeDownIcon',
    phosphor: 'TrendDownIcon',
  },
  PlusCircleIcon: {
    lucide: 'PlusCircleIcon',
    remix: 'RiAddCircleLine',
    tabler: 'IconCirclePlus',
    hugeicons: 'PlusSignCircleIcon',
    phosphor: 'PlusCircleIcon',
  },
  BoxIcon: {
    lucide: 'BoxIcon',
    remix: 'RiBox3Line',
    tabler: 'IconBox',
    hugeicons: 'CubeIcon',
    phosphor: 'CubeIcon',
  },
  CircleDotIcon: {
    lucide: 'CircleDotIcon',
    remix: 'RiRecordCircleLine',
    tabler: 'IconCircleDot',
    hugeicons: 'RecordIcon',
    phosphor: 'RadioButtonIcon',
  },
  SignalHighIcon: {
    lucide: 'SignalHighIcon',
    remix: 'RiSignalTowerLine',
    tabler: 'IconAntennaBars4',
    hugeicons: 'SignalFull01Icon',
    phosphor: 'CellSignalHighIcon',
  },
  BookIcon: {
    lucide: 'BookIcon',
    remix: 'RiBookLine',
    tabler: 'IconBook2',
    hugeicons: 'Book02Icon',
    phosphor: 'BookIcon',
  },
  ContrastIcon: {
    lucide: 'ContrastIcon',
    remix: 'RiContrastLine',
    tabler: 'IconContrast',
    hugeicons: 'BlendIcon',
    phosphor: 'CircleHalfIcon',
  },
  Users2Icon: {
    lucide: 'Users2Icon',
    remix: 'RiGroupLine',
    tabler: 'IconUsers',
    hugeicons: 'UserGroupIcon',
    phosphor: 'UsersIcon',
  },
  LayersIcon: {
    lucide: 'LayersIcon',
    remix: 'RiStackLine',
    tabler: 'IconStack2',
    hugeicons: 'Layers01Icon',
    phosphor: 'StackIcon',
  },
  MousePointer2Icon: {
    lucide: 'MousePointer2Icon',
    remix: 'RiCursorLine',
    tabler: 'IconPointer',
    hugeicons: 'Cursor01Icon',
    phosphor: 'CursorIcon',
  },
  RulerIcon: {
    lucide: 'RulerIcon',
    remix: 'RiRulerLine',
    tabler: 'IconRuler',
    hugeicons: 'RulerIcon',
    phosphor: 'RulerIcon',
  },
  ShapesIcon: {
    lucide: 'ShapesIcon',
    remix: 'RiShapesLine',
    tabler: 'IconTriangleSquareCircle',
    hugeicons: 'ShapesIcon',
    phosphor: 'ShapesIcon',
  },
  TypeIcon: {
    lucide: 'TypeIcon',
    remix: 'RiFontSize',
    tabler: 'IconTypography',
    hugeicons: 'TextIcon',
    phosphor: 'TextTIcon',
  },
}
