import type { RegistryItem } from "@/registry/types";

const sliderMeta = {
	name: "slider",
	type: "registry:ui",
	group: "sliders",
	files: [
		{
			type: "registry:ui",
			path: "ui/slider/base.tsx",
			target: "ui/slider.tsx",
		},
	],
	registryDependencies: ["field", "focus-styles"],
	dependencies: ["react-aria"],
	params: {
		"thumb-style": {
			kind: "enum",
			default: "solid",
			values: [
				"solid",
				"outline",
				"bar",
				"dots-vertical",
				"dots-horizontal",
				"arrows",
				"ticks",
				"faceted",
			] as const,
			// description: "Visual style of the slider thumb.",
		},
		"thumb-shadow": {
			kind: "enum",
			default: "auto",
			values: ["auto", "none", "sm", "lg"] as const,
			// description: "Elevation shadow of the slider thumb.",
		},
		"fill-color": {
			kind: "scalar",
			type: "color",
			cssVar: "--slider-fill-color",
			default: "--color-primary",
			// description: "Color of the slider fill.",
		},
		"track-radius": {
			kind: "scalar",
			type: "radius",
			cssVar: "--slider-track-radius",
			default: "--radius-full",
			// description: "Radius of the slider track.",
		},
		"thumb-radius": {
			kind: "scalar",
			type: "radius",
			cssVar: "--slider-thumb-radius",
			default: "--radius-full",
			// description: "Radius of the slider thumb.",
		},
		"thumb-size": {
			kind: "scalar",
			type: "spacing",
			cssVar: "--slider-thumb-size",
			default: "1.25rem",
			minValue: 3,
			maxValue: 8,
			step: 0.25,
			// description: "Size of the slider thumb.",
		},
		"thumb-track-gap": {
			kind: "scalar",
			type: "spacing",
			cssVar: "--slider-thumb-track-gap",
			default: "0.25rem",
			minValue: 0,
			maxValue: 4,
			step: 0.25,
			// description: "Invisible gap between the slider thumb and track.",
		},
		"default-cursor": {
			kind: "scalar",
			type: "cursor",
			cssVar: "--slider-cursor",
			default: "--cursor-interactive",
			// description: "Default cursor used by the slider.",
		},
		"cursor-while-dragging": {
			kind: "scalar",
			type: "cursor",
			cssVar: "--slider-dragging-cursor",
			default: "--cursor-interactive",
			// description: "Cursor used while dragging the slider thumb.",
		},
		size: {
			kind: "scalar",
			type: "spacing",
			cssVar: "--slider-size",
			default: "0.25rem",
			minValue: 1,
			maxValue: 7,
			step: 0.25,
			// description: "Thickness of the slider track.",
		},
	},
} satisfies RegistryItem;

export default sliderMeta;
