// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import React from "react";

export const allPreviews = {
  "hooks/use-continuous-retry": {
    component: React.lazy<React.FC>(() => import("~/content/hooks/use-continuous-retry")),
  },
  "hooks/use-debounce": {
    component: React.lazy<React.FC>(() => import("~/content/hooks/use-debounce")),
  },
  "hooks/use-fetch": {
    component: React.lazy<React.FC>(() => import("~/content/hooks/use-fetch")),
  },
  "hooks/use-intersection-observer": {
    component: React.lazy<React.FC>(
      () => import("~/content/hooks/use-intersection-observer")
    ),
  },
  "hooks/use-local-storage": {
    component: React.lazy<React.FC>(() => import("~/content/hooks/use-local-storage")),
  },
  "hooks/use-media-query": {
    component: React.lazy<React.FC>(() => import("~/content/hooks/use-media-query")),
  },
  "hooks/use-network-state": {
    component: React.lazy<React.FC>(() => import("~/content/hooks/use-network-state")),
  },
  "hooks/use-orientation": {
    component: React.lazy<React.FC>(() => import("~/content/hooks/use-orientation")),
  },
  "hooks/use-prefeerred-language": {
    component: React.lazy<React.FC>(
      () => import("~/content/hooks/use-prefeerred-language")
    ),
  },
  "hooks/use-previous": {
    component: React.lazy<React.FC>(() => import("~/content/hooks/use-previous")),
  },
  "hooks/use-session-storage": {
    component: React.lazy<React.FC>(() => import("~/content/hooks/use-session-storage")),
  },
  "hooks/use-visibility-change": {
    component: React.lazy<React.FC>(
      () => import("~/content/hooks/use-visibility-change")
    ),
  },
  "hooks/use-window-size": {
    component: React.lazy<React.FC>(() => import("~/content/hooks/use-window-size")),
  },
};
