// This file is autogenerated by scripts/build-preview-imports.ts
// Do not edit this file directly.
import React from "react";

export const allPreviews = {
  "hooks/use-continuous-retry": {
    component: React.lazy<React.FC>(() => import("~/content/hooks/use-continuous-retry")),
    code: `export default function Demo() {
  return <div>demo</div>;
}
`,
  },
  "hooks/use-debounce": {
    component: React.lazy<React.FC>(() => import("~/content/hooks/use-debounce")),
    code: `"use client";

import * as React from "react";
import { Loader2Icon, SearchIcon } from "lucide-react";
import { Input } from "@/components/ui/input";
import { useDebounce } from "@/hooks/use-debounce";

export default function UseDebounceDemo() {
  const [isLoading, setIsLoading] = React.useState<boolean>(false);
  const [searchInput, setSearchInput] = React.useState<string>("");
  const debouncedValue = useDebounce<string>(searchInput, 1000);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setIsLoading(false);
    setSearchInput(e.target.value);
  };

  const handleSubmit = () => {
    setIsLoading(true);
    // fetch here
    setTimeout(() => {
      setIsLoading(false);
    }, 1000);
  };

  React.useEffect(() => {
    handleSubmit();
  }, [debouncedValue]);

  return (
    <div className="relative w-52">
      {isLoading ? (
        <div className="absolute left-2 flex h-full items-center">
          <Loader2Icon
            size={18}
            className="pointer-events-none animate-spin text-muted-foreground"
          />
        </div>
      ) : (
        <SearchIcon
          size={18}
          className="pointer-events-none absolute left-2 top-1/2 -translate-y-1/2 transform text-muted-foreground"
        />
      )}
      <Input
        value={searchInput}
        onChange={handleChange}
        placeholder="Search items"
        className="full-w pl-8"
      />
    </div>
  );
}
`,
  },
  "hooks/use-fetch": {
    component: React.lazy<React.FC>(() => import("~/content/hooks/use-fetch")),
    code: `export default function Demo() {
  return <div>demo</div>;
}
`,
  },
  "hooks/use-intersection-observer": {
    component: React.lazy<React.FC>(
      () => import("~/content/hooks/use-intersection-observer")
    ),
    code: `export default function Demo() {
  return <div>demo</div>;
}
`,
  },
  "hooks/use-local-storage": {
    component: React.lazy<React.FC>(() => import("~/content/hooks/use-local-storage")),
    code: `export default function Demo() {
  return <div>demo</div>;
}
`,
  },
  "hooks/use-media-query": {
    component: React.lazy<React.FC>(() => import("~/content/hooks/use-media-query")),
    code: `export default function Demo() {
  return <div>demo</div>;
}
`,
  },
  "hooks/use-network-state": {
    component: React.lazy<React.FC>(() => import("~/content/hooks/use-network-state")),
    code: `export default function Demo() {
  return <div>demo</div>;
}
`,
  },
  "hooks/use-orientation": {
    component: React.lazy<React.FC>(() => import("~/content/hooks/use-orientation")),
    code: `export default function Demo() {
  return <div>demo</div>;
}
`,
  },
  "hooks/use-prefeerred-language": {
    component: React.lazy<React.FC>(
      () => import("~/content/hooks/use-prefeerred-language")
    ),
    code: `export default function Demo() {
  return <div>demo</div>;
}
`,
  },
  "hooks/use-previous": {
    component: React.lazy<React.FC>(() => import("~/content/hooks/use-previous")),
    code: `export default function Demo() {
  return <div>demo</div>;
}
`,
  },
  "hooks/use-session-storage": {
    component: React.lazy<React.FC>(() => import("~/content/hooks/use-session-storage")),
    code: `export default function Demo() {
  return <div>demo</div>;
}
`,
  },
  "hooks/use-visibility-change": {
    component: React.lazy<React.FC>(
      () => import("~/content/hooks/use-visibility-change")
    ),
    code: `export default function Demo() {
  return <div>demo</div>;
}
`,
  },
  "hooks/use-window-size": {
    component: React.lazy<React.FC>(() => import("~/content/hooks/use-window-size")),
    code: `export default function Demo() {
  return <div>demo</div>;
}
`,
  },
};
