import React from "react";
import { Loader2Icon } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { allPreviews } from "./autogenerated";

type AllPreviewsKeys = keyof typeof allPreviews;

export const ComponentPreview = ({ name }: { name: AllPreviewsKeys }) => {
  const Preview = React.useMemo(() => {
    const Component = allPreviews[name]?.component;

    if (!Component) {
      return (
        <p className="text-sm text-muted-foreground">
          Component
          <code className="relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-sm">
            {name}
          </code>
          not found in registry.
        </p>
      );
    }

    return <Component />;
  }, [name]);

  return (
    <div>
      <Tabs defaultValue="preview">
        <TabsList className="grid w-[400px] grid-cols-2">
          <TabsTrigger value="preview">Preview</TabsTrigger>
          <TabsTrigger value="code">Code</TabsTrigger>
        </TabsList>
        <TabsContent value="preview" className="rounded-md border">
          <React.Suspense
            fallback={
              <div className="flex items-center text-sm text-muted-foreground">
                <Loader2Icon className="mr-2 h-4 w-4 animate-spin" />
                <span>Loading...</span>
              </div>
            }
          >
            <div className="flex min-h-[350px] w-full items-center justify-center p-8">
              {Preview}
            </div>
          </React.Suspense>
        </TabsContent>
        <TabsContent value="code" className="rounded-md border">
          <div className="min-h-[350px] px-6 py-4">
            {`import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion""`}
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
};
