import React from "react";
import { CodeBlock } from "@/components/code-block";
import { ThemeWrapper } from "@/components/theme-wrapper";
import { ScrollArea } from "@/lib/components/core/default/scroll-area";
import { Skeleton } from "@/lib/components/core/default/skeleton";
import { cn } from "@/lib/utils/classes";
import { previews } from "@/autogenerated/previews";
import { ThemeCustomizer } from "./theme-customizer";

type PreviewsKeys = keyof typeof previews;

export interface ComponentPreviewProps {
  name: PreviewsKeys;
  className?: string;
  containerClassName?: string;
  aspect?: "default" | "page";
  defaultExpanded?: boolean;
  preview?: string;
  expandable?: boolean;
}

export const ComponentPreview = ({
  name,
  className,
  containerClassName,
  aspect = "default",
  preview,
  expandable,
}: ComponentPreviewProps) => {
  // make it server component
  const component = React.useMemo(() => {
    const Component = previews[name]?.component;

    if (!Component) {
      return <p className="text-sm text-fg-muted">Component not found.</p>;
    }

    return <Component />;
  }, [name]);

  const code = React.useMemo(() => {
    const allCodeFiles = previews[name]?.code ?? [];

    if (allCodeFiles.length === 0) {
      return [];
    }

    return allCodeFiles.map((file) => ({
      ...file,
      code: file.code.replace("export default function", "function"),
    }));
  }, [name]);

  return (
    <div className={cn("overflow-hidden rounded-md border", containerClassName)}>
      <div className="relative">
        <ThemeWrapper fallback={<Skeleton className="h-40" />}>
          <ScrollArea
            className={cn("flex items-center justify-center bg-bg text-fg", {
              "max-h-[800px]": aspect === "default",
            })}
          >
            <div className="flex min-h-40 items-center justify-center px-4 py-8">
              <div className={cn("flex w-full items-center justify-center", className)}>
                {component}
              </div>
            </div>
          </ScrollArea>
          <ThemeCustomizer />
        </ThemeWrapper>
      </div>
      <CodeBlock
        files={code.map((file) => ({ fileName: file.title, code: file.code, lang: "tsx" }))}
        preview={preview}
        className={"w-full rounded-t-none border-x-0 border-b-0"}
        expandable={expandable}
      />
    </div>
  );
};
