import React from "react";
import { Code } from "bright";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { allPreviews } from "./autogenerated";
import { ScrollArea } from "./ui/scroll-area";

type AllPreviewsKeys = keyof typeof allPreviews;

export const ComponentPreview = ({ name }: { name: AllPreviewsKeys }) => {
  const preview = React.useMemo(() => {
    const Component = allPreviews[name]?.component;

    if (!Component) {
      return (
        <p className="text-sm text-muted-foreground">
          Component
          <code className="relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-sm">
            {name}
          </code>
          not found.
        </p>
      );
    }

    return <Component />;
  }, [name]);

  const code = React.useMemo(() => {
    const codeString = allPreviews[name]?.code;

    if (!codeString) {
      return (
        <p className="text-sm text-muted-foreground">
          <code className="relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-sm">
            {name}
          </code>
          not found.
        </p>
      );
    }

    return codeString;
  }, [name]);

  return (
    <div>
      <Tabs defaultValue="preview">
        <TabsList className="grid w-[400px] grid-cols-2">
          <TabsTrigger value="preview">Preview</TabsTrigger>
          <TabsTrigger value="code">Code</TabsTrigger>
        </TabsList>
        <TabsContent value="preview" className="rounded-md border">
          <div className="flex w-full min-h-[350px] items-center justify-center p-8">{preview}</div>
        </TabsContent>
        <TabsContent value="code" className="rounded border">
          <div className=" p-1">
            <ScrollArea className="h-[350px]">
              <Code
                lang="tsx"
                className="relative rounded font-mono text-sm"
                style={{ marginTop: 0, marginBottom: 0 }}
                theme="github-dark"
                codeClassName="min-h-[322px]"
              >
                {code}
              </Code>
            </ScrollArea>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
};
