// AUTO-GENERATED - DO NOT EDIT
// Run "npx tsx scripts/generate-examples.ts" to regenerate

export const ExamplesIndex: Record<
  string,
  () => Promise<{ default: React.ComponentType }>
> = {
  "accordion": () => import("@dotui/registry/ui/accordion/examples"),
  "alert": () => import("@dotui/registry/ui/alert/examples"),
  "avatar": () => import("@dotui/registry/ui/avatar/examples"),
  "badge": () => import("@dotui/registry/ui/badge/examples"),
  "breadcrumbs": () => import("@dotui/registry/ui/breadcrumbs/examples"),
  "button": () => import("@dotui/registry/ui/button/examples"),
  "checkbox": () => import("@dotui/registry/ui/checkbox/examples"),
  "checkbox-group": () => import("@dotui/registry/ui/checkbox-group/examples"),
  "color-area": () => import("@dotui/registry/ui/color-area/examples"),
  "color-editor": () => import("@dotui/registry/ui/color-editor/examples"),
  "color-field": () => import("@dotui/registry/ui/color-field/examples"),
  "color-picker": () => import("@dotui/registry/ui/color-picker/examples"),
  "color-slider": () => import("@dotui/registry/ui/color-slider/examples"),
  "color-swatch": () => import("@dotui/registry/ui/color-swatch/examples"),
  "color-swatch-picker": () => import("@dotui/registry/ui/color-swatch-picker/examples"),
  "combobox": () => import("@dotui/registry/ui/combobox/examples"),
  "command": () => import("@dotui/registry/ui/command/examples"),
  "date-field": () => import("@dotui/registry/ui/date-field/examples"),
  "date-picker": () => import("@dotui/registry/ui/date-picker/examples"),
  "dialog": () => import("@dotui/registry/ui/dialog/examples"),
  "disclosure": () => import("@dotui/registry/ui/disclosure/examples"),
  "drawer": () => import("@dotui/registry/ui/drawer/examples"),
  "drop-zone": () => import("@dotui/registry/ui/drop-zone/examples"),
  "empty": () => import("@dotui/registry/ui/empty/examples"),
  "file-trigger": () => import("@dotui/registry/ui/file-trigger/examples"),
  "form": () => import("@dotui/registry/ui/form/examples"),
  "group": () => import("@dotui/registry/ui/group/examples"),
  "list-box": () => import("@dotui/registry/ui/list-box/examples"),
  "menu": () => import("@dotui/registry/ui/menu/examples"),
  "modal": () => import("@dotui/registry/ui/modal/examples"),
  "number-field": () => import("@dotui/registry/ui/number-field/examples"),
  "overlay": () => import("@dotui/registry/ui/overlay/examples"),
  "popover": () => import("@dotui/registry/ui/popover/examples"),
  "progress-bar": () => import("@dotui/registry/ui/progress-bar/examples"),
  "radio-group": () => import("@dotui/registry/ui/radio-group/examples"),
  "react-hook-form": () => import("@dotui/registry/ui/react-hook-form/examples"),
  "search-field": () => import("@dotui/registry/ui/search-field/examples"),
  "select": () => import("@dotui/registry/ui/select/examples"),
  "separator": () => import("@dotui/registry/ui/separator/examples"),
  "skeleton": () => import("@dotui/registry/ui/skeleton/examples"),
  "slider": () => import("@dotui/registry/ui/slider/examples"),
  "switch": () => import("@dotui/registry/ui/switch/examples"),
  "table": () => import("@dotui/registry/ui/table/examples"),
  "tabs": () => import("@dotui/registry/ui/tabs/examples"),
  "tag-group": () => import("@dotui/registry/ui/tag-group/examples"),
  "text-area": () => import("@dotui/registry/ui/text-area/examples"),
  "text-field": () => import("@dotui/registry/ui/text-field/examples"),
  "time-field": () => import("@dotui/registry/ui/time-field/examples"),
  "toggle-button": () => import("@dotui/registry/ui/toggle-button/examples"),
  "toggle-button-group": () => import("@dotui/registry/ui/toggle-button-group/examples"),
  "tooltip": () => import("@dotui/registry/ui/tooltip/examples"),
};
