/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as OgRouteImport } from './routes/og'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ViewBlockRouteImport } from './routes/view/$block'
import { Route as RChar123nameChar125DotjsonRouteImport } from './routes/r/{$name}[.]json'
import { Route as RInitDotjsonRouteImport } from './routes/r/init[.]json'
import { Route as PreviewSlugRouteImport } from './routes/preview/$slug'
import { Route as DemosSlugRouteImport } from './routes/demos/$slug'
import { Route as AppCreateRouteImport } from './routes/_app/create'
import { Route as AppComponentsRouteImport } from './routes/_app/components'
import { Route as AppDocsRouteRouteImport } from './routes/_app/docs/route'
import { Route as AppBlocksRouteRouteImport } from './routes/_app/blocks/route'
import { Route as AppDocsChar123Char125DotmdRouteImport } from './routes/_app/docs/{$}[.]md'
import { Route as AppDocsSplatRouteImport } from './routes/_app/docs/$'
import { Route as AppBlocksChar123CategoryChar125RouteImport } from './routes/_app/blocks/{-$category}'

const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const ViewBlockRoute = ViewBlockRouteImport.update({
  id: '/view/$block',
  path: '/view/$block',
  getParentRoute: () => rootRouteImport,
} as any)
const RChar123nameChar125DotjsonRoute =
  RChar123nameChar125DotjsonRouteImport.update({
    id: '/r/{$name}.json',
    path: '/r/{$name}.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const RInitDotjsonRoute = RInitDotjsonRouteImport.update({
  id: '/r/init.json',
  path: '/r/init.json',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewSlugRoute = PreviewSlugRouteImport.update({
  id: '/preview/$slug',
  path: '/preview/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosSlugRoute = DemosSlugRouteImport.update({
  id: '/demos/$slug',
  path: '/demos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComponentsRoute = AppComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocsRouteRoute = AppDocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBlocksRouteRoute = AppBlocksRouteRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocsChar123Char125DotmdRoute =
  AppDocsChar123Char125DotmdRouteImport.update({
    id: '/{$}.md',
    path: '/{$}.md',
    getParentRoute: () => AppDocsRouteRoute,
  } as any)
const AppDocsSplatRoute = AppDocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppDocsRouteRoute,
} as any)
const AppBlocksChar123CategoryChar125Route =
  AppBlocksChar123CategoryChar125RouteImport.update({
    id: '/{-$category}',
    path: '/{-$category}',
    getParentRoute: () => AppBlocksRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/og': typeof OgRoute
  '/playground': typeof PlaygroundRoute
  '/blocks': typeof AppBlocksRouteRouteWithChildren
  '/docs': typeof AppDocsRouteRouteWithChildren
  '/components': typeof AppComponentsRoute
  '/create': typeof AppCreateRoute
  '/demos/$slug': typeof DemosSlugRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/r/init.json': typeof RInitDotjsonRoute
  '/r/{$name}.json': typeof RChar123nameChar125DotjsonRoute
  '/view/$block': typeof ViewBlockRoute
  '/blocks/{-$category}': typeof AppBlocksChar123CategoryChar125Route
  '/docs/$': typeof AppDocsSplatRoute
  '/docs/{$}.md': typeof AppDocsChar123Char125DotmdRoute
}
export interface FileRoutesByTo {
  '/og': typeof OgRoute
  '/playground': typeof PlaygroundRoute
  '/blocks': typeof AppBlocksRouteRouteWithChildren
  '/docs': typeof AppDocsRouteRouteWithChildren
  '/components': typeof AppComponentsRoute
  '/create': typeof AppCreateRoute
  '/demos/$slug': typeof DemosSlugRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/r/init.json': typeof RInitDotjsonRoute
  '/r/{$name}.json': typeof RChar123nameChar125DotjsonRoute
  '/view/$block': typeof ViewBlockRoute
  '/': typeof AppIndexRoute
  '/blocks/{-$category}': typeof AppBlocksChar123CategoryChar125Route
  '/docs/$': typeof AppDocsSplatRoute
  '/docs/{$}.md': typeof AppDocsChar123Char125DotmdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/og': typeof OgRoute
  '/playground': typeof PlaygroundRoute
  '/_app/blocks': typeof AppBlocksRouteRouteWithChildren
  '/_app/docs': typeof AppDocsRouteRouteWithChildren
  '/_app/components': typeof AppComponentsRoute
  '/_app/create': typeof AppCreateRoute
  '/demos/$slug': typeof DemosSlugRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/r/init.json': typeof RInitDotjsonRoute
  '/r/{$name}.json': typeof RChar123nameChar125DotjsonRoute
  '/view/$block': typeof ViewBlockRoute
  '/_app/': typeof AppIndexRoute
  '/_app/blocks/{-$category}': typeof AppBlocksChar123CategoryChar125Route
  '/_app/docs/$': typeof AppDocsSplatRoute
  '/_app/docs/{$}.md': typeof AppDocsChar123Char125DotmdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/og'
    | '/playground'
    | '/blocks'
    | '/docs'
    | '/components'
    | '/create'
    | '/demos/$slug'
    | '/preview/$slug'
    | '/r/init.json'
    | '/r/{$name}.json'
    | '/view/$block'
    | '/blocks/{-$category}'
    | '/docs/$'
    | '/docs/{$}.md'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/og'
    | '/playground'
    | '/blocks'
    | '/docs'
    | '/components'
    | '/create'
    | '/demos/$slug'
    | '/preview/$slug'
    | '/r/init.json'
    | '/r/{$name}.json'
    | '/view/$block'
    | '/'
    | '/blocks/{-$category}'
    | '/docs/$'
    | '/docs/{$}.md'
  id:
    | '__root__'
    | '/_app'
    | '/og'
    | '/playground'
    | '/_app/blocks'
    | '/_app/docs'
    | '/_app/components'
    | '/_app/create'
    | '/demos/$slug'
    | '/preview/$slug'
    | '/r/init.json'
    | '/r/{$name}.json'
    | '/view/$block'
    | '/_app/'
    | '/_app/blocks/{-$category}'
    | '/_app/docs/$'
    | '/_app/docs/{$}.md'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  OgRoute: typeof OgRoute
  PlaygroundRoute: typeof PlaygroundRoute
  DemosSlugRoute: typeof DemosSlugRoute
  PreviewSlugRoute: typeof PreviewSlugRoute
  RInitDotjsonRoute: typeof RInitDotjsonRoute
  RChar123nameChar125DotjsonRoute: typeof RChar123nameChar125DotjsonRoute
  ViewBlockRoute: typeof ViewBlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/view/$block': {
      id: '/view/$block'
      path: '/view/$block'
      fullPath: '/view/$block'
      preLoaderRoute: typeof ViewBlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/{$name}.json': {
      id: '/r/{$name}.json'
      path: '/r/{$name}.json'
      fullPath: '/r/{$name}.json'
      preLoaderRoute: typeof RChar123nameChar125DotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/init.json': {
      id: '/r/init.json'
      path: '/r/init.json'
      fullPath: '/r/init.json'
      preLoaderRoute: typeof RInitDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$slug': {
      id: '/preview/$slug'
      path: '/preview/$slug'
      fullPath: '/preview/$slug'
      preLoaderRoute: typeof PreviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/$slug': {
      id: '/demos/$slug'
      path: '/demos/$slug'
      fullPath: '/demos/$slug'
      preLoaderRoute: typeof DemosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/create': {
      id: '/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/components': {
      id: '/_app/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof AppComponentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/docs': {
      id: '/_app/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AppDocsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/blocks': {
      id: '/_app/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof AppBlocksRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/docs/{$}.md': {
      id: '/_app/docs/{$}.md'
      path: '/{$}.md'
      fullPath: '/docs/{$}.md'
      preLoaderRoute: typeof AppDocsChar123Char125DotmdRouteImport
      parentRoute: typeof AppDocsRouteRoute
    }
    '/_app/docs/$': {
      id: '/_app/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof AppDocsSplatRouteImport
      parentRoute: typeof AppDocsRouteRoute
    }
    '/_app/blocks/{-$category}': {
      id: '/_app/blocks/{-$category}'
      path: '/{-$category}'
      fullPath: '/blocks/{-$category}'
      preLoaderRoute: typeof AppBlocksChar123CategoryChar125RouteImport
      parentRoute: typeof AppBlocksRouteRoute
    }
  }
}

interface AppBlocksRouteRouteChildren {
  AppBlocksChar123CategoryChar125Route: typeof AppBlocksChar123CategoryChar125Route
}

const AppBlocksRouteRouteChildren: AppBlocksRouteRouteChildren = {
  AppBlocksChar123CategoryChar125Route: AppBlocksChar123CategoryChar125Route,
}

const AppBlocksRouteRouteWithChildren = AppBlocksRouteRoute._addFileChildren(
  AppBlocksRouteRouteChildren,
)

interface AppDocsRouteRouteChildren {
  AppDocsSplatRoute: typeof AppDocsSplatRoute
  AppDocsChar123Char125DotmdRoute: typeof AppDocsChar123Char125DotmdRoute
}

const AppDocsRouteRouteChildren: AppDocsRouteRouteChildren = {
  AppDocsSplatRoute: AppDocsSplatRoute,
  AppDocsChar123Char125DotmdRoute: AppDocsChar123Char125DotmdRoute,
}

const AppDocsRouteRouteWithChildren = AppDocsRouteRoute._addFileChildren(
  AppDocsRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppBlocksRouteRoute: typeof AppBlocksRouteRouteWithChildren
  AppDocsRouteRoute: typeof AppDocsRouteRouteWithChildren
  AppComponentsRoute: typeof AppComponentsRoute
  AppCreateRoute: typeof AppCreateRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBlocksRouteRoute: AppBlocksRouteRouteWithChildren,
  AppDocsRouteRoute: AppDocsRouteRouteWithChildren,
  AppComponentsRoute: AppComponentsRoute,
  AppCreateRoute: AppCreateRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  OgRoute: OgRoute,
  PlaygroundRoute: PlaygroundRoute,
  DemosSlugRoute: DemosSlugRoute,
  PreviewSlugRoute: PreviewSlugRoute,
  RInitDotjsonRoute: RInitDotjsonRoute,
  RChar123nameChar125DotjsonRoute: RChar123nameChar125DotjsonRoute,
  ViewBlockRoute: ViewBlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
