/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as OgRouteImport } from './routes/og'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as HomeDotmdRouteImport } from './routes/home[.]md'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as RV0RouteImport } from './routes/r/v0'
import { Route as RRegistryDotjsonRouteImport } from './routes/r/registry[.]json'
import { Route as RInitRouteImport } from './routes/r/init'
import { Route as RNameRouteImport } from './routes/r/$name'
import { Route as PreviewSlugRouteImport } from './routes/preview/$slug'
import { Route as InternalColorsRouteImport } from './routes/internal.colors'
import { Route as InternalColorLabRouteImport } from './routes/internal.color-lab'
import { Route as DemosSlugRouteImport } from './routes/demos/$slug'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as AppPresetsRouteImport } from './routes/_app/presets'
import { Route as AppCreateRouteImport } from './routes/_app/create'
import { Route as AppComponentsRouteImport } from './routes/_app/components'
import { Route as AppChartsRouteImport } from './routes/_app/charts'
import { Route as DotwellKnownApiCatalogRouteImport } from './routes/[.]well-known/api-catalog'
import { Route as AppDocsRouteRouteImport } from './routes/_app/docs/route'
import { Route as AppDocsChar123Char125DotmdRouteImport } from './routes/_app/docs/{$}[.]md'
import { Route as AppDocsSplatRouteImport } from './routes/_app/docs/$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeDotmdRoute = HomeDotmdRouteImport.update({
  id: '/home.md',
  path: '/home.md',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const RV0Route = RV0RouteImport.update({
  id: '/r/v0',
  path: '/r/v0',
  getParentRoute: () => rootRouteImport,
} as any)
const RRegistryDotjsonRoute = RRegistryDotjsonRouteImport.update({
  id: '/r/registry.json',
  path: '/r/registry.json',
  getParentRoute: () => rootRouteImport,
} as any)
const RInitRoute = RInitRouteImport.update({
  id: '/r/init',
  path: '/r/init',
  getParentRoute: () => rootRouteImport,
} as any)
const RNameRoute = RNameRouteImport.update({
  id: '/r/$name',
  path: '/r/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewSlugRoute = PreviewSlugRouteImport.update({
  id: '/preview/$slug',
  path: '/preview/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalColorsRoute = InternalColorsRouteImport.update({
  id: '/internal/colors',
  path: '/internal/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalColorLabRoute = InternalColorLabRouteImport.update({
  id: '/internal/color-lab',
  path: '/internal/color-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosSlugRoute = DemosSlugRouteImport.update({
  id: '/demos/$slug',
  path: '/demos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPresetsRoute = AppPresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppComponentsRoute = AppComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChartsRoute = AppChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => AppRouteRoute,
} as any)
const DotwellKnownApiCatalogRoute = DotwellKnownApiCatalogRouteImport.update({
  id: '/.well-known/api-catalog',
  path: '/.well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDocsRouteRoute = AppDocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocsChar123Char125DotmdRoute =
  AppDocsChar123Char125DotmdRouteImport.update({
    id: '/{$}.md',
    path: '/{$}.md',
    getParentRoute: () => AppDocsRouteRoute,
  } as any)
const AppDocsSplatRoute = AppDocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppDocsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/home.md': typeof HomeDotmdRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og': typeof OgRoute
  '/playground': typeof PlaygroundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs': typeof AppDocsRouteRouteWithChildren
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/charts': typeof AppChartsRoute
  '/components': typeof AppComponentsRoute
  '/create': typeof AppCreateRoute
  '/presets': typeof AppPresetsRoute
  '/api/search': typeof ApiSearchRoute
  '/demos/$slug': typeof DemosSlugRoute
  '/internal/color-lab': typeof InternalColorLabRoute
  '/internal/colors': typeof InternalColorsRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/r/$name': typeof RNameRoute
  '/r/init': typeof RInitRoute
  '/r/registry.json': typeof RRegistryDotjsonRoute
  '/r/v0': typeof RV0Route
  '/docs/$': typeof AppDocsSplatRoute
  '/docs/{$}.md': typeof AppDocsChar123Char125DotmdRoute
}
export interface FileRoutesByTo {
  '/home.md': typeof HomeDotmdRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og': typeof OgRoute
  '/playground': typeof PlaygroundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs': typeof AppDocsRouteRouteWithChildren
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/charts': typeof AppChartsRoute
  '/components': typeof AppComponentsRoute
  '/create': typeof AppCreateRoute
  '/presets': typeof AppPresetsRoute
  '/api/search': typeof ApiSearchRoute
  '/demos/$slug': typeof DemosSlugRoute
  '/internal/color-lab': typeof InternalColorLabRoute
  '/internal/colors': typeof InternalColorsRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/r/$name': typeof RNameRoute
  '/r/init': typeof RInitRoute
  '/r/registry.json': typeof RRegistryDotjsonRoute
  '/r/v0': typeof RV0Route
  '/': typeof AppIndexRoute
  '/docs/$': typeof AppDocsSplatRoute
  '/docs/{$}.md': typeof AppDocsChar123Char125DotmdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/home.md': typeof HomeDotmdRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/og': typeof OgRoute
  '/playground': typeof PlaygroundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/docs': typeof AppDocsRouteRouteWithChildren
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/_app/charts': typeof AppChartsRoute
  '/_app/components': typeof AppComponentsRoute
  '/_app/create': typeof AppCreateRoute
  '/_app/presets': typeof AppPresetsRoute
  '/api/search': typeof ApiSearchRoute
  '/demos/$slug': typeof DemosSlugRoute
  '/internal/color-lab': typeof InternalColorLabRoute
  '/internal/colors': typeof InternalColorsRoute
  '/preview/$slug': typeof PreviewSlugRoute
  '/r/$name': typeof RNameRoute
  '/r/init': typeof RInitRoute
  '/r/registry.json': typeof RRegistryDotjsonRoute
  '/r/v0': typeof RV0Route
  '/_app/': typeof AppIndexRoute
  '/_app/docs/$': typeof AppDocsSplatRoute
  '/_app/docs/{$}.md': typeof AppDocsChar123Char125DotmdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home.md'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/og'
    | '/playground'
    | '/sitemap.xml'
    | '/docs'
    | '/.well-known/api-catalog'
    | '/charts'
    | '/components'
    | '/create'
    | '/presets'
    | '/api/search'
    | '/demos/$slug'
    | '/internal/color-lab'
    | '/internal/colors'
    | '/preview/$slug'
    | '/r/$name'
    | '/r/init'
    | '/r/registry.json'
    | '/r/v0'
    | '/docs/$'
    | '/docs/{$}.md'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/home.md'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/og'
    | '/playground'
    | '/sitemap.xml'
    | '/docs'
    | '/.well-known/api-catalog'
    | '/charts'
    | '/components'
    | '/create'
    | '/presets'
    | '/api/search'
    | '/demos/$slug'
    | '/internal/color-lab'
    | '/internal/colors'
    | '/preview/$slug'
    | '/r/$name'
    | '/r/init'
    | '/r/registry.json'
    | '/r/v0'
    | '/'
    | '/docs/$'
    | '/docs/{$}.md'
  id:
    | '__root__'
    | '/_app'
    | '/home.md'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/og'
    | '/playground'
    | '/sitemap.xml'
    | '/_app/docs'
    | '/.well-known/api-catalog'
    | '/_app/charts'
    | '/_app/components'
    | '/_app/create'
    | '/_app/presets'
    | '/api/search'
    | '/demos/$slug'
    | '/internal/color-lab'
    | '/internal/colors'
    | '/preview/$slug'
    | '/r/$name'
    | '/r/init'
    | '/r/registry.json'
    | '/r/v0'
    | '/_app/'
    | '/_app/docs/$'
    | '/_app/docs/{$}.md'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  HomeDotmdRoute: typeof HomeDotmdRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OgRoute: typeof OgRoute
  PlaygroundRoute: typeof PlaygroundRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownApiCatalogRoute: typeof DotwellKnownApiCatalogRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DemosSlugRoute: typeof DemosSlugRoute
  InternalColorLabRoute: typeof InternalColorLabRoute
  InternalColorsRoute: typeof InternalColorsRoute
  PreviewSlugRoute: typeof PreviewSlugRoute
  RNameRoute: typeof RNameRoute
  RInitRoute: typeof RInitRoute
  RRegistryDotjsonRoute: typeof RRegistryDotjsonRoute
  RV0Route: typeof RV0Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home.md': {
      id: '/home.md'
      path: '/home.md'
      fullPath: '/home.md'
      preLoaderRoute: typeof HomeDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/r/v0': {
      id: '/r/v0'
      path: '/r/v0'
      fullPath: '/r/v0'
      preLoaderRoute: typeof RV0RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/registry.json': {
      id: '/r/registry.json'
      path: '/r/registry.json'
      fullPath: '/r/registry.json'
      preLoaderRoute: typeof RRegistryDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/init': {
      id: '/r/init'
      path: '/r/init'
      fullPath: '/r/init'
      preLoaderRoute: typeof RInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$name': {
      id: '/r/$name'
      path: '/r/$name'
      fullPath: '/r/$name'
      preLoaderRoute: typeof RNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$slug': {
      id: '/preview/$slug'
      path: '/preview/$slug'
      fullPath: '/preview/$slug'
      preLoaderRoute: typeof PreviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/colors': {
      id: '/internal/colors'
      path: '/internal/colors'
      fullPath: '/internal/colors'
      preLoaderRoute: typeof InternalColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/color-lab': {
      id: '/internal/color-lab'
      path: '/internal/color-lab'
      fullPath: '/internal/color-lab'
      preLoaderRoute: typeof InternalColorLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/$slug': {
      id: '/demos/$slug'
      path: '/demos/$slug'
      fullPath: '/demos/$slug'
      preLoaderRoute: typeof DemosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/presets': {
      id: '/_app/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof AppPresetsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/create': {
      id: '/_app/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/components': {
      id: '/_app/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof AppComponentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/charts': {
      id: '/_app/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof AppChartsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof DotwellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/docs': {
      id: '/_app/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AppDocsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/docs/{$}.md': {
      id: '/_app/docs/{$}.md'
      path: '/{$}.md'
      fullPath: '/docs/{$}.md'
      preLoaderRoute: typeof AppDocsChar123Char125DotmdRouteImport
      parentRoute: typeof AppDocsRouteRoute
    }
    '/_app/docs/$': {
      id: '/_app/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof AppDocsSplatRouteImport
      parentRoute: typeof AppDocsRouteRoute
    }
  }
}

interface AppDocsRouteRouteChildren {
  AppDocsSplatRoute: typeof AppDocsSplatRoute
  AppDocsChar123Char125DotmdRoute: typeof AppDocsChar123Char125DotmdRoute
}

const AppDocsRouteRouteChildren: AppDocsRouteRouteChildren = {
  AppDocsSplatRoute: AppDocsSplatRoute,
  AppDocsChar123Char125DotmdRoute: AppDocsChar123Char125DotmdRoute,
}

const AppDocsRouteRouteWithChildren = AppDocsRouteRoute._addFileChildren(
  AppDocsRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppDocsRouteRoute: typeof AppDocsRouteRouteWithChildren
  AppChartsRoute: typeof AppChartsRoute
  AppComponentsRoute: typeof AppComponentsRoute
  AppCreateRoute: typeof AppCreateRoute
  AppPresetsRoute: typeof AppPresetsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDocsRouteRoute: AppDocsRouteRouteWithChildren,
  AppChartsRoute: AppChartsRoute,
  AppComponentsRoute: AppComponentsRoute,
  AppCreateRoute: AppCreateRoute,
  AppPresetsRoute: AppPresetsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  HomeDotmdRoute: HomeDotmdRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OgRoute: OgRoute,
  PlaygroundRoute: PlaygroundRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownApiCatalogRoute: DotwellKnownApiCatalogRoute,
  ApiSearchRoute: ApiSearchRoute,
  DemosSlugRoute: DemosSlugRoute,
  InternalColorLabRoute: InternalColorLabRoute,
  InternalColorsRoute: InternalColorsRoute,
  PreviewSlugRoute: PreviewSlugRoute,
  RNameRoute: RNameRoute,
  RInitRoute: RInitRoute,
  RRegistryDotjsonRoute: RRegistryDotjsonRoute,
  RV0Route: RV0Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
