type RegistryDemoItem = {
  name: string;
  files: string[];
};

type RegistryDemos = RegistryDemoItem[];

const buildDemos = (registryItem: string, demos: string[]): RegistryDemos => {
  return demos.map((demo) => {
    return {
      name: `${registryItem}-${demo}`,
      files: [`demos/${registryItem}/${demo}.tsx`],
    };
  });
};

export const demos: RegistryDemos = [
  ...buildDemos("alert", [
    "action",
    "composition",
    "content",
    "custom-icon",
    "default",
    "title",
    "variants",
  ]),
  ...buildDemos("avatar", ["composition", "default", "shape", "sizes"]),
  ...buildDemos("badge", ["default", "icon", "sizes", "variants"]),
  ...buildDemos("breadcrumbs", [
    "basic",
    "composition",
    "disabled",
    "icon",
    "router-integration",
  ]),
  ...buildDemos("button", [
    "default",
    "disabled",
    "link-button",
    "loading",
    "prefix-and-suffix",
    "shapes",
    "sizes",
    "variants",
  ]),
  ...buildDemos("calendar", [
    "composition",
    "controlled",
    "default",
    "disabled",
    "error-message",
    "page-behaviour",
    "read-only",
    "uncontrolled",
    "unvailable-dates",
    "validation",
    "visible-months",
    "variant",
  ]),
  ...buildDemos("checkbox-group", [
    "cards",
    "composition",
    "controlled",
    "default",
    "description",
    "disabled",
    "error-message",
    "label",
    "read-only",
    "required",
    "uncontrolled",
  ]),
  ...buildDemos("checkbox", [
    "card",
    "controlled",
    "default",
    "disabled",
    "indeterminate",
    "read-only",
    "uncontrolled",
    "composition",
  ]),
  ...buildDemos("color-area", [
    "channels",
    "composition",
    "controlled",
    "default",
    "disabled",
    "uncontrolled",
  ]),
  ...buildDemos("color-field", [
    "color-channel",
    "composition",
    "controlled",
    "default",
    "description",
    "disabled",
    "error-message",
    "form",
    "label",
    "prefix-and-suffix",
    "read-only",
    "required",
    "sizes",
    "uncontrolled",
  ]),
  ...buildDemos("color-picker", [
    "composition",
    "controlled",
    "default",
    "options",
    "uncontrolled",
  ]),
  ...buildDemos("color-slider", [
    "channel",
    "composition",
    "controlled",
    "default",
    "disabled",
    "label",
    "uncontrolled",
    "vertical",
  ]),
  ...buildDemos("color-swatch", ["default"]),
  ...buildDemos("color-thumb", []),
  ...buildDemos("combobox", [
    "async-loading",
    "basic",
    "composition",
    "controlled",
    "custom-value",
    "description",
    "disabled",
    "label",
    "loading",
    "required",
    "sections",
    "uncontrolled",
    "validation",
  ]),
  ...buildDemos("date-field", [
    "composition",
    "controlled",
    "default",
    "description",
    "disabled",
    "error-message",
    "granularity",
    "hide-time-zone",
    "hour-cycle",
    "label",
    "placeholder",
    "prefix-and-suffix",
    "read-only",
    "required",
    "sizes",
    "time-zones",
    "uncontrolled",
  ]),
  ...buildDemos("date-picker", [
    "composition",
    "controlled",
    "default",
    "description",
    "disabled",
    "error-message",
    "granularity",
    "hide-time-zone",
    "hour-cycle",
    "label",
    "placeholder",
    "prefix",
    "read-only",
    "required",
    "sizes",
    "time-zones",
    "uncontrolled",
  ]),
  ...buildDemos("date-range-picker", [
    "composition",
    "controlled",
    "default",
    "description",
    "disabled",
    "error-message",
    "granularity",
    "hide-time-zone",
    "hour-cycle",
    "label",
    "placeholder",
    "prefix",
    "read-only",
    "required",
    "sizes",
    "time-zones",
    "uncontrolled",
  ]),
  ...buildDemos("dialog", [
    "alert-dialog",
    "async-form-submission",
    "basic",
    "composition",
    "controlled",
    "description",
    "dismissable",
    "drawer",
    "inset-content",
    "nested",
    "popover",
    "title",
    "types",
  ]),
  ...buildDemos("drawer", ["basic", "placement"]),
  ...buildDemos("drop-zone", [
    "basic",
    "disabled",
    "file-trigger",
    "label",
    "visual-feedback",
    "events",
  ]),
  ...buildDemos("file-trigger", [
    "default",
    "directory-selection",
    "file-types",
    "media-capture",
    "multiple-files",
  ]),
  ...buildDemos("link", ["default", "disabled", "icon", "variants"]),
  ...buildDemos("list-box", [
    "async-loading",
    "basic",
    "composition",
    "contact-list",
    "controlled",
    "disabled-items",
    "empty-state",
    "grid",
    "horizontal",
    "image-grid",
    "item-variant",
    "label-and-description",
    "links",
    "loading",
    "prefix-and-suffix",
    "sections",
    "selection-behavior",
    "selection-mode",
    "separator",
    "uncontrolled",
  ]),
  ...buildDemos("menu", [
    "basic",
    "composition",
    "controlled",
    "disabled-items",
    "item-variant",
    "label-and-description",
    "link-items",
    "long-press",
    "multiple-selection",
    "overlay-type",
    "placement",
    "prefix-and-suffix",
    "section",
    "separator",
    "shortcut",
    "single-selection",
    "submenus",
  ]),
  ...buildDemos("modal", ["basic"]),
  ...buildDemos("number-field", [
    "composition",
    "controlled",
    "default",
    "description",
    "disabled",
    "error-message",
    "format-options",
    "label",
    "read-only",
    "required",
    "sizes",
    "uncontrolled",
  ]),
  ...buildDemos("popover", ["basic"]),
  ...buildDemos("progress", [
    "composition",
    "custom-color",
    "custom-value-label",
    "default",
    "duration",
    "format-options",
    "indeterminate",
    "label",
    "min-max-values",
    "shape",
    "sizes",
    "toolbar",
    "value-label",
    "variants",
  ]),
  ...buildDemos("radio-group", [
    "cards",
    "composition",
    "controlled",
    "default",
    "description",
    "disabled",
    "error-message",
    "label",
    "orientation",
    "read-only",
    "required",
    "uncontrolled",
  ]),
  ...buildDemos("range-calendar", [
    "composition",
    "controlled",
    "default",
    "disabled",
    "error-message",
    "non-contiguous-ranges",
    "page-behaviour",
    "read-only",
    "uncontrolled",
    "unvailable-dates",
    "validation",
    "visible-months",
    "variant",
  ]),
  ...buildDemos("search-field", [
    "composition",
    "controlled",
    "default",
    "description",
    "disabled",
    "error-message",
    "form",
    "label",
    "prefix-and-suffix",
    "read-only",
    "required",
    "sizes",
    "uncontrolled",
  ]),
  ...buildDemos("select", [
    "async-loading",
    "basic",
    "composition",
    "controlled",
    "description",
    "disabled",
    "label",
    "links",
    "loading",
    "placeholder",
    "required",
    "sections",
    "uncontrolled",
    "validation",
  ]),
  ...buildDemos("separator", ["card", "orientation"]),
  ...buildDemos("skeleton", [
    "api-simulation",
    "card",
    "children",
    "fixed-size-children",
    "show",
  ]),
  ...buildDemos("slider", [
    "composition",
    "controlled",
    "default",
    "description",
    "disabled",
    "format-options",
    "label",
    "range",
    "sizes",
    "step",
    "uncontrolled",
    "value-label",
    "value-scale",
    "vertical",
  ]),
  ...buildDemos("switch", [
    "controlled",
    "default",
    "disabled",
    "label",
    "sizes",
    "uncontrolled",
    "card",
    "composition",
  ]),
  ...buildDemos("tabs", [
    "basic",
    "controlled",
    "disabled-item",
    "disabled",
    "keyboard-activation",
    "vertical",
  ]),
  ...buildDemos("text-area", [
    "composition",
    "controlled",
    "default",
    "description",
    "disabled",
    "error-message",
    "form",
    "label",
    "prefix-and-suffix",
    "read-only",
    "required",
    "uncontrolled",
  ]),
  ...buildDemos("text-field", [
    "composition",
    "controlled",
    "default",
    "description",
    "disabled",
    "error-message",
    "label",
    "prefix-and-suffix",
    "read-only",
    "required",
    "sizes",
    "uncontrolled",
  ]),
  ...buildDemos("time-field", [
    "composition",
    "controlled",
    "default",
    "description",
    "disabled",
    "error-message",
    "granularity",
    "hide-time-zone",
    "hour-cycle",
    "label",
    "placeholder",
    "prefix-and-suffix",
    "read-only",
    "required",
    "sizes",
    "time-zones",
    "uncontrolled",
  ]),
  ...buildDemos("toggle-button", [
    "controlled",
    "default",
    "disabled",
    "shapes",
    "sizes",
    "uncontrolled",
    "variants",
  ]),
  ...buildDemos("tooltip", [
    "variant",
    "arrow",
    "composition",
    "container-padding",
    "default",
    "delay",
    "flip",
    "offset",
    "placement",
    "with-arrow",
  ]),
  ...buildDemos("toggle-button-group", ["default"]),
  ...buildDemos("button-group", ["default"]),
  ...buildDemos("tag-group", ["default"]),
  ...buildDemos("table", ["default"]),
  ...buildDemos("form", ["basic", "react-aria", "react-hook-form"]),
  ...buildDemos("command", ["basic", "dialog"]),
  ...buildDemos("overlay", ["basic", "type"]),
];
