import fs from "fs";
import path from "path";
import { rimraf } from "rimraf";
import { getAllCategoryDocs } from "@/utils/docs";
import type { DocsConfig } from "@/types/docs";

const getCategoryItems = (category: string) => {
  return getAllCategoryDocs(category).map((category) => ({
    title: category.title,
    href: category.href,
    label: category.label,
  }));
};

const docsConfig: DocsConfig = {
  sidebarNav: [
    {
      title: "Getting Started",
      slug: "getting-started",
      items: getCategoryItems("getting-started"),
    },
    {
      title: "Components",
      slug: "components",
      items: [
        {
          title: "All components",
          href: "/components",
        },
        {
          title: "Core",
          items: getCategoryItems("components/core"),
        },
        {
          title: "Animations",
          items: getCategoryItems("components/animations"),
        },
      ],
    },
    {
      title: "Blocks",
      slug: "blocks",
      items: [
        {
          title: "All blocks",
          href: "/blocks",
        },
        {
          title: "Marketing",
          items: getCategoryItems("blocks/marketing"),
        },
        {
          title: "Application UI",
          items: getCategoryItems("blocks/application-ui"),
        },
        {
          title: "E-commerce",
          items: getCategoryItems("blocks/e-commerce"),
        },
      ],
    },
    {
      title: "Hooks",
      slug: "hooks",
      items: [
        {
          title: "All hooks",
          href: "/hooks",
        },
        ...getCategoryItems("hooks"),
      ],
    },
    {
      title: "Icons",
      slug: "icons",
      items: [
        {
          title: "All icons",
          href: "/icons",
        },
        ...getCategoryItems("icons"),
      ],
    },
    {
      title: "Templates",
      slug: "templates",
      items: [
        {
          title: "All templates",
          href: "/templates",
        },
      ],
    },
  ],
};

const index = `
// This file is autogenerated by scripts/build-preview-imports.ts
// Do not edit this file directly.
import type { DocsConfig } from "@/types/docs";

export const docsConfig: DocsConfig = ${JSON.stringify(docsConfig)};
`;

rimraf.sync(path.join(process.cwd(), "src", "config", "docs-config.ts"));
fs.writeFileSync(path.join(process.cwd(), "src", "config", "docs-config.ts"), index);
