import { existsSync, promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { rimraf } from "rimraf";

interface BuildConfig {
  sourceDir: string;
  targetDir: string;
  foldersToSync: string[];
}

interface ImportTransformation {
  pattern: RegExp;
  replacer: (match: string, ...args: any[]) => string;
}

// Content transformation rules
const IMPORT_TRANSFORMATIONS: ImportTransformation[] = [
  // Transform component imports to remove variants - @/components/button/basic → @/components/button
  {
    pattern: /from\s+["']@\/components\/([a-zA-Z-]+)\/[a-zA-Z-]+["']/g,
    replacer: (match, componentName) => {
      return `from "@/components/${componentName}"`;
    },
  },
  // Transform registry imports to UI package imports
  {
    pattern: /from\s+["']@dotui\/registry\/([^"']+?)["']/g,
    replacer: (match, importPath) => {
      return `from "@dotui/ui/__registry__/${importPath}"`;
    },
  },
  // Transform style-engine imports to maintain consistency
  {
    pattern: /from\s+["']@dotui\/style-engine\/([^"']+?)["']/g,
    replacer: (match, importPath) => {
      return `from "@dotui/style-engine/${importPath}"`;
    },
  },
  // Transform relative imports within registry
  {
    pattern: /from\s+["']\.\.\/([^"']+?)["']/g,
    replacer: (match, relativePath) => {
      const parts = relativePath.split("/");
      const fileName = parts.pop()?.split(".")[0];
      if (fileName && parts.length > 0) {
        return `from "@dotui/ui/__registry__/${[...parts, fileName].join("/")}"`;
      }
      return match;
    },
  },
];

// ----------------------------------------------------------------------------
// Setup and cleanup target directories
// ----------------------------------------------------------------------------
async function setupTargetDirectories(config: BuildConfig): Promise<void> {
  const { targetDir } = config;

  // Clean up existing registry directory
  if (existsSync(targetDir)) {
    rimraf.sync(targetDir);
    console.log(`🗑️  Cleaned existing registry`);
  }

  // Ensure target directory exists
  await fs.mkdir(targetDir, { recursive: true });

  // Create autogenerated marker
  const markerPath = path.join(targetDir, ".autogenerated");
  await fs.writeFile(
    markerPath,
    "This directory is autogenerated by packages/registry/scripts/build-registry.ts\nDo not edit its contents directly.",
    "utf8",
  );
}

// ----------------------------------------------------------------------------
// Transform file content with import path updates
// ----------------------------------------------------------------------------
function transformFileContent(content: string, filePath: string): string {
  let transformedContent = content;

  // Apply all import transformations
  for (const { pattern, replacer } of IMPORT_TRANSFORMATIONS) {
    transformedContent = transformedContent.replace(pattern, replacer);
  }

  // Add header comment for generated files
  if (filePath.endsWith(".tsx") || filePath.endsWith(".ts")) {
    const header = `// This file is autogenerated by packages/registry/scripts/build-registry.ts
// Do not edit this file directly - it will be overwritten
`;
    if (!transformedContent.startsWith("//")) {
      transformedContent = header + "\n" + transformedContent;
    }
  }

  return transformedContent;
}

// ----------------------------------------------------------------------------
// Recursively copy directory with content transformation
// ----------------------------------------------------------------------------
async function copyDirectoryWithTransform(
  sourceDir: string,
  targetDir: string,
  transformContent: (content: string, filePath: string) => string,
): Promise<void> {
  await fs.mkdir(targetDir, { recursive: true });

  const entries = await fs.readdir(sourceDir, { withFileTypes: true });

  for (const entry of entries) {
    const sourcePath = path.join(sourceDir, entry.name);
    const targetPath = path.join(targetDir, entry.name);

    if (entry.isDirectory()) {
      await copyDirectoryWithTransform(
        sourcePath,
        targetPath,
        transformContent,
      );
    } else if (entry.isFile()) {
      const content = await fs.readFile(sourcePath, "utf8");
      const transformedContent = transformContent(content, sourcePath);

      await fs.writeFile(targetPath, transformedContent, "utf8");
      console.log(`✓ Built: ${path.relative(sourceDir, sourcePath)}`);
    }
  }
}

// ----------------------------------------------------------------------------
// Main build function
// ----------------------------------------------------------------------------
async function buildRegistry(config: BuildConfig): Promise<void> {
  const { sourceDir, targetDir, foldersToSync } = config;

  console.log(`🔄 Building registry [${foldersToSync.join(", ")}]`);
  console.log(`📂 Source: ${sourceDir}`);
  console.log(`📁 Target: ${targetDir}`);

  try {
    await setupTargetDirectories(config);

    // Build each specified folder
    for (const folder of foldersToSync) {
      const sourceFolderPath = path.join(sourceDir, folder);
      const targetFolderPath = path.join(targetDir, folder);

      if (existsSync(sourceFolderPath)) {
        await copyDirectoryWithTransform(
          sourceFolderPath,
          targetFolderPath,
          transformFileContent,
        );
        console.log(`📁 Completed folder: ${folder}`);
      } else {
        console.warn(`⚠️  Source folder not found: ${sourceFolderPath}`);
      }
    }

    console.log(`✅ Successfully built registry to UI package`);
  } catch (error) {
    console.error(`❌ Build failed:`, error);
    process.exit(1);
  }
}

// ----------------------------------------------------------------------------
// Main execution
// ----------------------------------------------------------------------------
async function main(): Promise<void> {
  const scriptDir = path.dirname(fileURLToPath(import.meta.url));
  const registrySourceDir = path.resolve(scriptDir, "../src");
  const uiTargetDir = path.resolve(scriptDir, "../../ui/src/__registry__");

  const config: BuildConfig = {
    sourceDir: registrySourceDir,
    targetDir: uiTargetDir,
    foldersToSync: ["components", "hooks", "lib"],
  };

  await buildRegistry(config);
}

// ----------------------------------------------------------------------------
// Entry point
// ----------------------------------------------------------------------------
if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((error) => {
    console.error("❌ Script execution failed:", error);
    process.exit(1);
  });
}

export { buildRegistry, transformFileContent, IMPORT_TRANSFORMATIONS };
