/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<
  string,
  {
    files: string[];
    component: React.LazyExoticComponent<React.ComponentType<object>>;
  }
> = {

  "login": {
    files: ["blocks/auth/login/page.tsx","blocks/auth/login/components/login-form.tsx"],
    component: React.lazy(async () => {
      const mod = await import("@dotui/registry/blocks/auth/login/page")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    })
  },
  "cards": {
    files: ["blocks/showcase/cards/components/cards.tsx","blocks/showcase/cards/components/account-menu.tsx","blocks/showcase/cards/components/backlog.tsx","blocks/showcase/cards/components/booking.tsx","blocks/showcase/cards/components/color-editor.tsx","blocks/showcase/cards/components/filters.tsx","blocks/showcase/cards/components/invite-members.tsx","blocks/showcase/cards/components/login-form.tsx","blocks/showcase/cards/components/notifications.tsx","blocks/showcase/cards/components/team-name.tsx"],
    component: React.lazy(async () => {
      const mod = await import("@dotui/registry/blocks/showcase/cards/components/cards")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    })
  },
}
